### ISSUE TITLE
font hex file requires uppercase hex only

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#100]
If you use a hex file for font command it requires uppercase letters.
Can it accept both upper and lower case hex?

does not work

`font --font-high=24 /X11_12x24.shex`
[X11_12x24.zip](https://github.com/chenall/grub4dos/files/160296/X11_12x24.zip)

**Comment by 2012yaya2007** [comment]
Your documents are not standardized

**Comment by steve6375** [comment]
But can you easily fix to accept upper and lower case?

**Comment by 2012yaya2007** [comment]
You mean, variable word width?
The number of dot matrix is changed?

**Comment by steve6375** [comment]
no i mean, first line work, 2nd line does not work because lower case hex used.

OK
0031:0000000006000E001E007E000600060006000600060006000600060006000600060006000600060006003FC000000000

BAD
0031:0000000006000e001e007e000600060006000600060006000600060006000600060006000600060006003fc000000000

**Comment by 2012yaya2007** [comment]
Can solve.
Why lower case?

**Comment by steve6375** [comment]
because some tools which convert .bdf to .hex do not convert to uppercase (.bdf in lowercase hex).
Only solve if easy to do. Not a big problem.

**Comment by 2012yaya2007** [comment]
All right, I deal with it.

**Comment by 2012yaya2007** [comment]
test
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/160697/grldr.rar.txt)

**Comment by steve6375** [comment]
Great! thanks.
