### ISSUE TITLE
set /p pauses animation

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#101]
This is a small issue. **Only fix if easy.**
With this menu, the animation does not appear until the user presses a key to enter a word
After first key, the animation plays OK.
Is it possible for the animation to play from start?

\menu.lst

```
errorcheck off
graphicsmode -1 800
splashimage /_ISO/e2b/grub/background.bmp.gz
clear
call Fn.70 3
map --mem --read-only /_ISO/docs/Templates/Animate/E2B_GIF.ima (fd3)
map --hook
splashimage --animated=0x90=3=9=300=180 (fd3)/frame_0001.bmp
# Animation does not appear/start until user press first key
set /p ask=TYPE A WORD
set /p ask=TYPE A WORD
set /p ask=TYPE A WORD

title reboot
reboot

```

**Comment by 2012yaya2007** [comment]
"Is it possible for the animation to play from start?"
Look at my example.

**Comment by steve6375** [comment]
?? what example ??

**Comment by 2012yaya2007** [comment]
test
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/167177/grldr.rar.txt)

**Comment by 2012yaya2007** [comment]
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=369720&extra=page%3D1

**Comment by 2012yaya2007** [comment]
F2
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/168323/grldr.rar.txt)

**Comment by steve6375** [comment]
What is F2 ???
I use 2016-03-11 with above menu

Step 1 - boot  > no animation
![image](https://cloud.githubusercontent.com/assets/1469350/13697377/fb7fb17c-e764-11e5-8b64-a85c341057ed.png)

Step 2 - I type 's'   > animation starts...
![image](https://cloud.githubusercontent.com/assets/1469350/13697384/0c5d977a-e765-11e5-9b76-d4486cba782a.png)

Animation now starts. I want animation to start on boot. Is this possiblt? Animation plays during user entry OK, but does not play on first call of set /p. So /p must be using different kbd input for start of input?

**Comment by 2012yaya2007** [comment]
Still don't understand.
1.in Boot , play the animation, do not display the menu.
2.User comes, press “A” key, stop animation.
3.Entry menu.

timeout 30
default 4
graphicsmode -1 800
font  /unifont.hex.gz
splashimage --animated=0x8f=1=26=130=150 /BritneyLZMA/frame-01.bmp.........
Can achieve 1.(Time may not be long enough)

Press "F2" key,stop animation.(If infinite loop animation,again Press "F2" key,play the animation)

**Comment by steve6375** [comment]
No - please use my EXACT example code.  The splashimage statement can be omitted, it is not needed.

Your code uses type=0x8f   - my code uses type=0x90

[E2B_GIF.zip](https://github.com/chenall/grub4dos/files/169441/E2B_GIF.zip)

What I want is to have an animated bitmap playing at same time as user inputs a password. It almost works, but there seems to be a problem with code in 'set /p' and animation does not play until user types first key of input.

**Comment by steve6375** [comment]
ISSUES95-104_DEMO.zip - see ISSUE 104
Please try attached DEMO for issues
95 - exit command
96 - no large font after configfile command
101 - no animation at start of set /p
102 - goto n after errorcheck
103 - font command does not set high=16 + BIOS font
104 - bad font filespec causes bad display

**Comment by 2012yaya2007** [comment]
title E2B_GIF.ima
clear
call Fn.70 3
map --mem --read-only /E2B_GIF.ima (fd3)
map --hook
splashimage --animated=0x90=3=9=300=180 (fd3)/frame_0001.bmp

# Animation does not appear/start until user press first key

set /p ask=on: 1, off: 0
if %ask%==0 calc _0x835b=_0x835b&0xfffffffe ! calc _0x835b=_0x835b|1

**Comment by steve6375** [comment]
The issue is that animation does not start until user presses first key
Can it be solved?
It is not very important issue, but I think problem is in  set /p code and keyboard input code used for first key press?

**Comment by 2012yaya2007** [comment]
"first key press?" What is the role?
"F2"  Hotkey Play / stop.

**Comment by steve6375** [comment]
I want animation to play at start
Then prompt user for input

I want:
1. Animation plays
2. Prompts user
3. User enters a b c d [ENTER]
4. Display menu

The problem is that animation does not start

**Comment by 2012yaya2007** [comment]
set /p ask=on: a, off: b  a/b:
 if %ask%==b calc 0x835b=0x835b&0xfffffffe ! calc 0x835b=0x835b|1
Can not solve the problem?

**Comment by steve6375** [comment]
I want animation to play without user key press

**Comment by 2012yaya2007** [comment]
Since there is no keyboard, What are you going to do with "set /p" ?

**Comment by 2012yaya2007** [comment]
Batch processing can control the keyboard keys?

**Comment by steve6375** [comment]
Current issue:

in menu_issue101.lst file
1. User is prompted for input  **(no animation)**  <<<<< ISSUE
2. User presses a key - e.g. a  >>> animation starts to play

I want:
1. Animation plays
2. User is prompted for input (animation still playing)

Please make USB drive using ISSUES95-104_DEMO.zip  - you will see problem for ISSUE 101

**Comment by 2012yaya2007** [comment]
set /p ask=TYPE A WORD
 if %ask%==0 calc 0x835b=0x835b&0xfffffffe ! calc 0x835b=0x835b|1
Press "0" key does not play, the other keys are broadcast.

**Comment by steve6375** [comment]
I want animation to play before user prompt.
![image](https://cloud.githubusercontent.com/assets/1469350/13728882/93c47c32-e91e-11e5-82d4-9fdc75ea56d1.png)

Problem is user must press A key first before animation plays - press ABCD key
![image](https://cloud.githubusercontent.com/assets/1469350/13728895/d130828c-e91e-11e5-80f5-fd0d44050df2.png)

**Comment by steve6375** [comment]
I can call batch file to get what I want.
I think problem is in checkkey / get_cmdline_str.readline = 1 | wait_t;

**getline.cmd**

```
!BAT
clear
echo -n ENTER PASSWORD: 
#checkkey 0xFF if no key, 0xD if CR, ESC=27
call Fn.20  ;; set /A key=%@retval%&0xff > nul ;; if /i not "%key%"=="0xFF" call Fn.19
write 0x60000 0 > nul

# use Fn.19 to get keyboard input and allow animation to play immediately.
#get key until ESC or CR
:loop
call Fn.19 ;; set /A key=%@retval%&0xff > nul ;; call Fn.2 %key% >> (md)0x300+1
if %key%==0x27 goto :fin
if %key%==0xD goto :fin
call Fn.2 %key%
goto :loop
:fin
cat (md)0x300+1 | set input=

echo
echo USER INPUT WAS: %input%
pause
```

![image](https://cloud.githubusercontent.com/assets/1469350/13729287/3f3e2f36-e929-11e5-8fdf-543d19a3bbfa.png)

**Comment by steve6375** [comment]
I found this works OK and plays animation at same time if called in batch file!

`call password fred || configfile /menu.lst

This is what I wanted so I will close this issue, as it is not very important.
Thanks for trying to fix it.

**Comment by steve6375** [comment]
This works too from a menu.lst file

```
clear
echo
echo !BAT > (md)0x300+1
echo -e password fred \|\| configfile (md)0xa000+0x50 >> (md)0x300+1
call (md)0x300+1
```
