### ISSUE TITLE
goto n in menu does not work if errorcheck off

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#102]
re. goto command in menu, it does not work if errorcheck is off

title menu 0
pause 1111
boot

title This works
errorcheck on
goto 0
pause ggggg
boot

title This does NOT work
errorcheck off
goto 0
pause fffff
boot

**Comment by 2012yaya2007** [comment]
Yes, it must errorcheck on

**Comment by steve6375** [comment]
Can you fix please?

**Comment by 2012yaya2007** [comment]
I'm sorry, I can't.

**Comment by steve6375** [comment]
On 'goto' command in the menu, can you turn on errorcheck first?

**Comment by 2012yaya2007** [comment]
Can realize. But later on errorcheck.

**Comment by steve6375** [comment]
Can you give error message if errorcheck is off and code has goto n ? maybe

'Error: errorcheck is off!.'

??

**Comment by steve6375** [comment]
ISSUES95-104_DEMO.zip - see ISSUE 104
Please try attached DEMO for issues
95 - exit command
96 - no large font after configfile command
101 - no animation at start of set /p
102 - goto n after errorcheck
103 - font command does not set high=16 + BIOS font
104 - bad font filespec causes bad display

**Comment by steve6375** [comment]
This is fixed in 2016-03-13 - it turns on errorcheck :+1:
