### ISSUE TITLE
'font' command does not change to BIOS font

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#103]
201603-11
menu.lst 

```
splashimage /_ISO/e2b/grub/background.bmp.gz

title X2 font
echo Current font
font --font-high=24 /_ISO/e2b/grub/sft.f24
echo sft font
font
pause Should be BIOS font
errorcheck off
boot
```

![image](https://cloud.githubusercontent.com/assets/1469350/13698434/f0966880-e76b-11e5-9592-8585e8714d15.png)

font not set to BIOS and space character corrupted.

**Comment by steve6375** [comment]
ISSUES95-104_DEMO.zip - see ISSUE 104
Please try attached DEMO for issues
95 - exit command
96 - no large font after configfile command
101 - no animation at start of set /p
102 - goto n after errorcheck
103 - font command does not set high=16 + BIOS font
104 - bad font filespec causes bad display

**Comment by 2012yaya2007** [comment]
Only in the VBE font display mode can play a role.
Boot exception

**Comment by steve6375** [comment]
This works:

title font command test OK
echo Current font
font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz
echo unifont
**font**
pause Should be BIOS font
errorcheck off
boot

So why cannot 'font' work when in  24 high mode?
I don't understand.  
'font' command should set  font-high=16 and use BIOS fonts for 0000-00FF characters. 
All that is needed is for 'font' command to set  font-high=16. 
Why is this not possible?

**Comment by 2012yaya2007** [comment]
"font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz"  and  "font  /_ISO/e2b/grub/unifont.hex.gz" are the same.Load the BIOS font only.Don't believe you have a try:
title font command test OK 测试

**Comment by steve6375** [comment]
"font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz" and "font /_ISO/e2b/grub/unifont.hex.gz" are the same - yes, i agree, but that is not the problem.

ISSUES95-104_DEMO.zip
Please make USB flash drive using this download - use exact files on new flash drive.
Then try each ISSUE. I make demo of each problem for you to see.

Issue 103 -   if set  font 24 and then use 'font' command it should set  BIOS font and 16 high for characters 0000-00FF.

title font command test **OK**
echo Current font
font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz
echo unifont
**font**
pause Should be BIOS font
errorcheck off
boot

title ISSUE 103 font command test  **BUG  NOT WORK**
echo Current font
font --font-high=**24** /_ISO/e2b/grub/sft.f24
echo 24 high font
**font**
pause Should be BIOS font
errorcheck off
boot

**Comment by 2012yaya2007** [comment]
title font command test OK
 echo Current font
 font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz      Did not perform
 echo unifont
 font
 pause Should be BIOS font
 errorcheck off
 boot

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/13728352/9caf46d0-e90d-11e5-99a4-6fb6a99a3319.png)

Works for me OK

Anyway, this is not the problem.

The problem is this case:

title ISSUE 103 font command test BUG NOT WORK
echo Current font
font **--font-high=24 /_ISO/e2b/grub/sft.f24**
echo sft font
font
pause Should be BIOS font
errorcheck off
boot
![image](https://cloud.githubusercontent.com/assets/1469350/13728376/0282167c-e90e-11e5-98a1-f0fb8a26bbda.png)

**Comment by steve6375** [comment]
2016-03-16 fixed - thanks! :+1:
