### ISSUE TITLE
Internal menu.lst in grldr does not boot from (bd)/menu.lst

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#107]
If you have two grub4dos devices (e.g. two grub4dos USB drives) in a system, sometimes loads the wrong \menu.lst

USB 1: grub4dos + \menu.lst
USB 2: grub4dos + \menu.lst
HDD0: grub4dos + \menu.lst

Choose BIOS Boot option to boot USB 2 >>> grub4dos can load wrong menu.lst

Cause:
Internal grldr menu.lst does not boot from (bd)\menu.lst
missing line ??? configfile /menu.lst  ???

```
pxe detect
configfile
default 0
timeout 1

title find /menu.lst, /boot/grub/menu.lst, /grub/menu.lst
    errorcheck off
    configfile /boot/grub/menu.lst
    configfile /grub/menu.lst
    if "%@root%"=="(ud)" && calc *0x82A0=*0x82b9&0xff
    if "%@root:~1,1%"=="f" && find --set-root --devices=f /menu.lst && configfile /menu.lst
    find --set-root --ignore-floppies --ignore-cd /menu.lst && configfile /menu.lst
    find --set-root --ignore-floppies --ignore-cd /boot/grub/menu.lst && configfile /boot/grub/menu.lst
    find --set-root --ignore-floppies --ignore-cd /grub/menu.lst && configfile /grub/menu.lst
    configfile http://b.chenall.net/menu.lst
    errorcheck on
    commandline

title commandline
    commandline

title reboot
    reboot

title halt
    halt
```

**Comment by steve6375** [comment]
Not sure if this is an issue now - need to do some more testing!
Does it seem like a bug or have I missed something?

**Comment by steve6375** [comment]
cannot reproduce this now...

**Comment by 2012yaya2007** [comment]
Choose BIOS Boot option to boot USB 2.Assign a drive letter 0x00?  0x80?
If 0x00,Should not be used grldr.mbr.(mbr->grldr->/menu.lst)
Should  be used mbr->pbr(grldr.pbr)->grldr->/menu.lst

**Comment by steve6375** [comment]
Cannot reproduce. Will close and open new issue if it happens again.
