### ISSUE TITLE
How to change 0018 and 0019 character fonts?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#108]
The unifont.hex file has for character 0019
0019:AAAA00018000000180007D11C1B07D51C1107D11800000018000000180005555
which I think is down-arrow ???
`echo -e \x19`
which seems to work OK

How can I change this by loading an additional font file? e.g. (using 0011 character for test)
myfont.hex
0019:AAAA00018000000180007189CA184A09CA08719D800000018000000180005555

``````
font /unifont.gz.hex
font --font-high=16 /myfont.hex
echo -e \x19 
```   << still get old down-arrow character

How is this special characters 0000-001F encoded in hex???

Also, I want to make 24-high fonts for 0000-001F, but the format seems strange.
E.g. When I press e for edit menu, the up-arrow and down-arrow symbols are missing

![image](https://cloud.githubusercontent.com/assets/1469350/13843505/f31f854a-ec2b-11e5-981e-9d160735fa30.png)

``````

**Comment by steve6375** [comment]
This appears to be a bug (or maybe two?)
1. With 16-high fonts, characters 0000-001F always use the BIOS character set (expected behaviour?)
2. With 24-high fonts, characters 0000-001F always output as 'space' character

0010 and 0011 do work, but 0018 and 0019 do not and these are needed for grub4dos edit menu.

Are 0010 and 0011 internal fonts??

![image](https://cloud.githubusercontent.com/assets/1469350/13873033/b0d762e6-ece6-11e5-8492-7ce8d056b6d2.png)

![image](https://cloud.githubusercontent.com/assets/1469350/13873123/2b7f29d4-ece7-11e5-913b-56626345e690.png)

**Comment by 2012yaya2007** [comment]
"Are 0010 and 0011 internal fonts??" yes
With 24-high fonts, 0018 and 0019 ,Need to make their own.
Our approach: Use "2191 and 2193",transform to narrow character,rename"0018 and 0019 ".

**Comment by steve6375** [comment]
2016-03-18 fixes :+1: 
Why <=17hex ?? In 24-high font I cannot print  0-17hex
10 and 11 work, but others do not. Why not <=11 hex??

0d is CR, so maybe allow characters 000E+ to be defined??
e.g.
echo -e \x17   >> prints space and cannot define a font for it.

**Comment by steve6375** [comment]
P.S. All versions of grub4dos:  echo -e issue??
Why does
echo -e \xfc  
not print any character??   any number above 7f does not print - why?
How can I print any character - e.g. 2190 ??

**Comment by steve6375** [comment]
2016-03-20 version buggy - something is broken!

when it loads Easy2Boot, it prints chinese characters and then goes to command prompt
![image](https://cloud.githubusercontent.com/assets/1469350/13903734/5a2f99a0-ee7f-11e5-8560-65d2b3b3e344.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13903740/685e3018-ee7f-11e5-8f8f-f9f7e0c2f0e8.png)

**Comment by steve6375** [comment]
How to use new echo -e ' ??
Please give example for unicode output.

also bug:
It breaks compatibility???
![image](https://cloud.githubusercontent.com/assets/1469350/13903783/e330c0de-ee80-11e5-8d7d-772d6b133784.png)

**Comment by 2012yaya2007** [comment]
"2016-03-20 version buggy "
How to reproduce?

echo -u \x0018\x0019\x2191\x2193
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/181264/grldr.rar.txt)

**Comment by steve6375** [comment]
sorry, attached grldr in last post 
echo -e 'hello'  is OK
also works with Easy2Boot OK
:+1:

**Comment by steve6375** [comment]
Can you improve help message please?
![image](https://cloud.githubusercontent.com/assets/1469350/13905144/b8c172fc-eeae-11e5-811c-bc489302f2ae.png)

suggest
-u       \xnnnn display unicode characters

Also, this seems odd??
![image](https://cloud.githubusercontent.com/assets/1469350/13905171/8fc98758-eeaf-11e5-91bc-0e892de976f5.png)

**Comment by steve6375** [comment]
Also help message should be  [-e | -u | -h ]
??
![image](https://cloud.githubusercontent.com/assets/1469350/13905182/1798c46e-eeb0-11e5-8a97-5820d311196d.png)
Also 
A blink-
![image](https://cloud.githubusercontent.com/assets/1469350/13905204/c51f7272-eeb0-11e5-81a1-e7fc9c388933.png)

is only for text-mode, in graphics-mode A is light- background
![image](https://cloud.githubusercontent.com/assets/1469350/13905199/a9e7a060-eeb0-11e5-9ae5-212c09d38794.png)

Maybe:
A=blink- (text mode) or BG light- (graphics mode), B=FG light-, C=BG, D=FG.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/13913389/0d0c3600-ef3e-11e5-855b-82909e9fa1e8.png)

why is it printing **\**<space> for  \x0020  ????

**Comment by steve6375** [comment]
BUG! echo \x25  not working
![image](https://cloud.githubusercontent.com/assets/1469350/13913776/b9320b3c-ef41-11e5-91fe-6406a43226c1.png)

![image](https://cloud.githubusercontent.com/assets/1469350/13913845/4395fc7a-ef42-11e5-9761-78cff2184c7a.png)

![image](https://cloud.githubusercontent.com/assets/1469350/13913686/17c1e79a-ef41-11e5-977c-ae35f7e2f124.png)

**Comment by steve6375** [comment]
P.S. Please add a post if you make a new grldr, I do not get notified of new commits, but I do get emailed if you add a comment to this issue. thanks.

**Comment by steve6375** [comment]
2016-03-20 has same bug

![image](https://cloud.githubusercontent.com/assets/1469350/13915091/7124e752-ef4a-11e5-9703-484f37117533.png)

being treated as  -u unicode ???

2016-03-18 OK

**Comment by 2012yaya2007** [comment]
echo -e 12\x18\x1934\u2191\u219356
Can not upload?

**Comment by 2012yaya2007** [comment]
echo -e 12\x18\x1934\u2191\u219356
Can not upload?

**Comment by steve6375** [comment]
Is there 2016-03-22 version?

**Comment by 2012yaya2007** [comment]
Can not upload to here!

**Comment by 2012yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/184019/grldr.rar.txt)

**Comment by steve6375** [comment]
Looks good :+1:

**Comment by steve6375** [comment]
But not compatible???
![image](https://cloud.githubusercontent.com/assets/1469350/13951087/a9424dbe-f026-11e5-8c8d-423c50fc9fac.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13951097/b36d944c-f026-11e5-8fab-5ce91ba36e2c.png)

Is it a problem??

**Comment by steve6375** [comment]
Maybe check for \unnnn where nnnn=hex else print as literal ???

**Comment by 2012yaya2007** [comment]
"\unload" is what ?
Why not "unload"?

**Comment by steve6375** [comment]
It is just an example because \u is now not compatible with previous versions.

can we have

echo **-u** hello\x25\u0252fred    new -u switch
and
echo **-e** hello\x25\unload fred   <<< as before 100% compatible

**Comment by 2012yaya2007** [comment]
"\u" is an already defined? What meaning?

**Comment by steve6375** [comment]
no special meaning, it is just not same as old version.
It is a small point and maybe no-one will notice it?
It does not cause me a problem. If you think it is OK, then I am happy too.

**Comment by 2012yaya2007** [comment]
Maybe it's better this way:
\xnn
\Xnnnn

**Comment by steve6375** [comment]
maybe?? It is your choice.

Most compatible is to use new -u in place of -e

echo -u  fred\x25\X00FCHello
or
echo -u fred\x25\u00FCHello

echo -e fred\unload\x25Hello only   (unicode nnnn not  recognised, \u=u or \X=X )

But I think user will probably never use \u or \X in code anyway???

**Comment by steve6375** [comment]
Fixed. Thanks a lot, :+1:
