### ISSUE TITLE
0.4.6a 2016-03-23 Cannot move help off screen using menusetting.gz

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#110]
In previous versions and 0.4.5c
menusetting.gz n n 1 **70** 24 2 64 3
would hide the menu help text (move to line 70)
However, with recent versions of 0.4.6a, it moves to approx. line 34
setmenu --help=0=0=70 doesn't seem to work afterwards either

for 800x600  31 seems max value accepted. I thought this bug was fixed previously?

**Comment by 2012yaya2007** [comment]
There is a limit, ensure that ‘help’ can display

**Comment by steve6375** [comment]
Thanks :+1:
