### ISSUE TITLE
20160324 setmenu --keyhelp bug

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#111]
20160323 is OK for --keyhelp (but has --help bug as cannot set help off screen)
20160324 is bad - 

graphicsmode -1 800
splashimage /_ISO/e2b/grub/background.bmp.gz
clear
set rstart=8
set topstart=3
set menuw=85
set noitems=20
set tophelp=100
set wdspace=n
set lnspace=n
set bdwidth=1
/_ISO/e2b/grub/menusetting.gz   %wdspace% %lnspace% %bdwidth% %tophelp% %noitems% %topstart% %menuw% %rstart%
**setmenu --keyhelp=61=0xe**

title TEST
reboot
title E2B
reboot

20160324
![image](https://cloud.githubusercontent.com/assets/1469350/14029318/43d0c972-f1f9-11e5-9872-7ce3d2e5f093.png)

20160323
![image](https://cloud.githubusercontent.com/assets/1469350/14029351/7d5402a4-f1f9-11e5-83ce-95d830f75606.png)

**Comment by steve6375** [comment]
20160325 has same bug - graphics/menu corrupted. Can you fix please?

**Comment by 2012yaya2007** [comment]
20160323 There are limits to "tophelp", so normal.
20160324 Accept your request, let go, so wrong.

**Comment by steve6375** [comment]
Thanks!
