### ISSUE TITLE
XPM splash not working

### ISSUE THREAD

**Issue by smx-smx** [chenall/grub4dos#113]
Starting from the build 2016-03-15, i get a black screen with blinking cursor when trying to load grub.exe from syslinux via the command
KERNEL /grub.exe

Build 2016-03-10 is unaffected and works as expected (menu appears)

**Comment by 2012yaya2007** [comment]
"KERNEL /grub.exe"
I have no problem testing.
How to reproduce?

**Comment by smx-smx** [comment]
The splash image seems to be the issue. Removed it and it works again:

```
color NORMAL HIGHLIGHT HELPTEXT HEADING
splashimage=/splash.xpm.gz
foreground=FFFFFF
background=000000
```

This is the spash image:
http://expirebox.com/download/6a7f3fb2536cbe7a48e2b11baefb6655.html

An interesting thing is also that such splash doesn't show in 2016-03-10.
I know it used to show, but i would need a longer backtracking to figure out where it broke

**Comment by smx-smx** [comment]
Ok, did a longer backtrace. Works on 2015-08-07.
From 2015-08-20 onwards it doesn't.

**Comment by 2012yaya2007** [comment]
Do not support XPM format

**Comment by smx-smx** [comment]
Maybe the header check should be restored and added on top, so that a detected XPM image is skipped
https://github.com/chenall/grub4dos/blob/0.4.6a/stage2/graphics.c#L2318
