### ISSUE TITLE
splashimage --offset command causes no display if not in graphics modes

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#116]
A valid splashimage --offset command causes no display if in text mode.

e.g.

menu.lst

```
splashimage --offset=0x80=570=23 /_ISO/e2b/grub/E2BPlate.bmp
pause No text here

title TEST\n no menu visible
root ()
```

**Comment by 2012yaya2007** [comment]
Does not set the VBE graphics mode, loading the image, is the wrong approach .
G4D tries to remedy this error. Before loading the BMP image, perform the "-1 w h graphicsmode", trying to enter the w*h VBE mode.

**Comment by 2012yaya2007** [comment]
However, BIOS does not support the 570*23 VBE mode, so the failure. 
Of course, the crash is bug.

**Comment by steve6375** [comment]
Yes, crash is a bug. I know it is invalid command but should not crash.
