### ISSUE TITLE
Cannot write to small <900 byte NTFS files

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#12]
This is a long-standing bug in grub4dos and it would be really great if this could be solved.

**Comment by steve6375** [comment]
Latest version does not print 2K warning but it does not work
e.g. 700 byte file on NTFS drive with 4k clusters

echo fred > /file700.txt
dd if=()/x.txt  of=()/f700.txt
cat /f700.txt

these do not work ??

**Comment by yaya2007** [comment]
The grub4dos-0.4.6a-2015-04-28.7z version, I test no problem.
File700.txt is already established?The length of >=700 bytes?
G4d write, not allowed to exceed the original length. If needed, please fill the retention of information.

**Comment by steve6375** [comment]
f700 is a file of 700 0's

![image](https://cloud.githubusercontent.com/assets/1469350/7434325/fb197a4a-f031-11e4-961f-e45b710513b4.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7434308/d55e733c-f031-11e4-8e36-63a08f75b097.png)

**Comment by yaya2007** [comment]
"Size on disk: 0 bytes"
 in the disk Not space allocation, the sparse file? Write a sparse file is not currently supported.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7440335/deb116ea-f0a6-11e4-83b3-05dff87aa39e.png)
I think it says 0 because it is a resident file in $mft. I tried many files created using editor or fsutil, etc. and none work??
![image](https://cloud.githubusercontent.com/assets/1469350/7440348/57017090-f0a7-11e4-96c4-2553fb63561c.png)

**Comment by steve6375** [comment]
I tested same file on a 64GB NTFS Flash drive and it worked.
But it does not work on my 2TB NTFS USB HDD (1st partition).

![image](https://cloud.githubusercontent.com/assets/1469350/7440508/eaa93422-f0b1-11e4-945f-4959cbbdff34.png)

**Comment by yaya2007** [comment]
" But it does not work on my 2TB NTFS USB HDD (1st partition)."
Can the ftest.txt file of MFT screenshot?

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7441016/1f1b900a-f0cc-11e4-9382-61654fed5466.png)

**Comment by yaya2007** [comment]
Sorry, I did not speak clearly.From the start of the "FILE"  in the record.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7444529/9e910222-f17e-11e4-9b57-fe1e8c87a571.png)

**Comment by yaya2007** [comment]
cat --hex (hd0,0)24+2
cat --hex (hd0,0)95509192+2
cat --hex (hd0,0)603797200+2

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7445168/5c9e245a-f19f-11e4-932b-cbf8b5f0f799.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7445171/6c785f4e-f19f-11e4-8597-eb09b1010162.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7445175/856548aa-f19f-11e4-82df-fbd7a97b9ce7.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7445178/98e8a764-f19f-11e4-9fd6-cc4a84bb027a.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7445183/ae7f9e20-f19f-11e4-9c8a-73148a47e773.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7445186/bceaed8e-f19f-11e4-98a8-54d34a4c45a4.png)

**Comment by yaya2007** [comment]
cat --hex (hd0,0)+1

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7455914/154b2f10-f278-11e4-83c5-a85e27f1e5c8.png)

**Comment by steve6375** [comment]
NTFS
000B Bytes Per Sector = 512 (0200h)
000D Sectors Per Cluster = 8 (08h)
0015 Media Descriptor = 248 (F8h) HDD
0020 Total Log. Sectors (big) = 0 (00000000h)
0028 Total Sectors on HDD = 000000007A3BA564h
0030 Log. Cluster no. for $MFT file = 0000000000000003h
0038 Log. Cluster no. for $MFTMirr file = 0000000001095F02h
0040 Clusters per MFT Record = 246 (F6h)
0044 Clusters per Index Buffer = 64 (40h)
0048 Volume ID Serial No. = 01CF22D445188640h
Drive 2  WD My Passport 0748  F/W Rev.=1019  Serial No.=0748WX31 [ bytes = 30 37 34 38 57 58 33 31 ]
Reported size 2,000,365,289,472 bytes (1,862.9853GiB)  Last LBA 3,906,963,455
RMPrepUSB Max 2,000,363,420,160 bytes (1,862.9836GiB)  Last LBA 3,906,959,804

**Comment by steve6375** [comment]
version 2015-05-05 does not even boot on my 2TB NTFS drive now!!!
Something is broken!

**Comment by yaya2007** [comment]
(hd0,0)108100+2 Damage!
The previous test caused.. Sorry.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7515459/130679e6-f4bf-11e4-8fd3-f34e61ea52a1.png)
![image](https://cloud.githubusercontent.com/assets/1469350/7515470/24f0a992-f4bf-11e4-972b-2886b8ea4acd.png)

**Comment by yaya2007** [comment]
Have a look around the 108100 sector, can determine what file is damaged?

**Comment by steve6375** [comment]
I am not sure what you mean???

2015-05-05 \grdlr - no boot - console only
2015-04-13 \grldr - OK no problem - boots to menu OK

chkdsk OK.

No damage, no corruption - just new grldr 2015-05-05 does not boot on my NTFS drive due to bug...

**Comment by yaya2007** [comment]
grub4dos-0.4.6a-2015-04-28.7z  ok?

**Comment by steve6375** [comment]
yes. Just 2015-05-05 will not boot to menu
configfile /menu.lst    just shows console - no menu.

**Comment by steve6375** [comment]
Problem seems to be not reading menu.lst correctly
![image](https://cloud.githubusercontent.com/assets/1469350/7521743/35c236b8-f4e8-11e4-8210-65e6f6c811c0.png)

**Comment by steve6375** [comment]
Seems to work now, great :-)
