### ISSUE TITLE
Scrolling in graphics mode causes artifacts at bottom of screen

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#120]
Scrolling causes graphics junk to appear at bottom of screen on real systems.
USB boot. Switch off system - wait 2 minutes (for RAM to decay) - switch on.
I think this is because uninitialised RAM is being used which is not 00.
If test in VBox then do not get artifacts problem (RAM is 00?).
Some systems show different pattern (depends on state of uninitialised RAM).
Only happens when screen scrolls.
0.4.5c and 0.4.6a. This bug has been present for a very long time.
To reproduce, use menu.lst file attached on real system (try several).

[menu.zip](https://github.com/chenall/grub4dos/files/329771/menu.zip)
![scrollbug1](https://cloud.githubusercontent.com/assets/1469350/16301039/03ae27ca-393b-11e6-9f61-75c5d3ba6003.jpg)
![scrollbug2](https://cloud.githubusercontent.com/assets/1469350/16301042/0614f804-393b-11e6-9c78-f7e338e82fe5.jpg)

**Comment by steve6375** [comment]
Different pattern on Acer Aspire R3 - see bottom of screen.

![r3_bad_graphics](https://cloud.githubusercontent.com/assets/1469350/16314835/ab060d4e-3977-11e6-9b5a-fb5cabb09461.jpg)

**Comment by yaya2007** [comment]
I was tested on 2 computers and found no problems.

**Comment by steve6375** [comment]
Try a notebook or two

**Comment by steve6375** [comment]
On notebook, mode is 0x115

In code graphics.c

```
/* scroll the screen */
void bios_scroll_up();
static void
graphics_scroll (void)
{
    unsigned long i;
    unsigned long old_state = cursor_state;
    cursor_state &= ~1;
    if (graphics_mode <= 0xFF)
    {/* VGA */
    bios_scroll_up ();
    }
    else
    {/* VBE */

    memmove_forward_SSE ((char *)current_phys_base, (char *)current_phys_base + (current_bytes_per_scanline * (font_h + line_spacing)),
            /*((y1 - 1) << 4)*/ current_y_resolution * current_bytes_per_scanline);
    }

    for (i=0;i<current_term->chars_per_line;++i)
    graphics_putchar(' ',1);
    gotoxy(0,fonty);
    cursor_state = old_state;
    return;
}

```

```
memmove_forward_SSE ((char *)current_phys_base, (char *)current_phys_base + (current_bytes_per_scanline * (font_h + line_spacing)), current_y_resolution * current_bytes_per_scanline);
```

so destination is start of base graphics memory
Source is  start + 1 line
size is y res (=37 in 800x600) \* bytes per scanline

but display size is 37.5 lines (600/16)  not 37 or 38 ???
So it assumes that  graphics memory from 37.5 to 38 is all 0's ???
could this be the problem?

P.S. In screenshot 2, the vertical lines are 8 pixels high and at the line 37-37.5 position.

**Comment by yaya2007** [comment]
Test no problem in a notebook .

In graphics mode, text cannot account for all rows and columns. 
The problem has nothing to do with the rolling screen. May be related to the clear of the screen But to view the relevant code, did not find the problem. 
There may be some problems with the display card or the screen.

**Comment by steve6375** [comment]
The corruption definitely is to do with scrolling.
See Picture 1 above in first post - line 37.5 is blank.
As soon as I press Enter, the line 37.5 gets corrupted with bad pixels (Picture 2)
Also, if page mode is off, there is no corruption of line 37.5 until text hits bottom of screen and starts to scroll. So it IS a scroll problem.
Also, if you delete the 'clear' line so there is no clear command, then you get graphics corruption at line 37.5 at first screen (see picture below)
![line75 5](https://cloud.githubusercontent.com/assets/1469350/16341600/e702bd8e-3a25-11e6-865d-ea3c052cc5cd.jpg)

Also, if I echo 36 lines, then pause - there is no corruption at bottom of screen, but when next two lines are written then get corruption of line 37.5. So corruption happens when line is printed at bottom of screen.

Please look at code again. It copies lines 1-38 to line 0-36,  but line 38 is only half good,  line 37 to 38.5 is data=00, but line 38.5 to 38.99 is maybe not 00??? 
What if on some notebooks, memory from line 38.5 to line 38.99 is 'random' (not 0).

**Comment by steve6375** [comment]
```
graphicsmode 0x115
call Fn.05 0 35
echo 1 
pause > nul
echo 2
pause > nul
echo 3
pause >nul
```

Switch off notebook - wait 1 minute
Switch on notebook
when 1 is displayed, it pauses but no corruption
then press ENTER, 
2 is displayed but get corruption

![line38](https://cloud.githubusercontent.com/assets/1469350/16343013/d0502aa2-3a2c-11e6-9c78-c93bb755f009.jpg)

**Comment by steve6375** [comment]
I tested Acer Aspire 7741G and no problem seen (mode 0x115 not supported, so used -1 800)
Asus EeePC 904HA and Acer Aspire R3-131T show the issue.
Maybe needs Intel graphics or mode 0x115?

**Comment by yaya2007** [comment]
Perhaps current_phys_base is in conflict with some cache?

**Comment by yaya2007** [comment]
Already corrected. Upload official website

**Comment by steve6375** [comment]
Thanks. Fix seems to work. I will close this after testing a bit more. :-)
