### ISSUE TITLE
cat --replace not working correctly

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#122]
I want to replace the key TK8TP-XXXXX-XXXXX-RFFTV-B7QPF with a different key

cat --locate=TK8TP --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE /t0.xml

The first occurrence in the file is replaced correctly, but the second occurrence is not done correctly.
Happens in both 0.4.5c and 0.4.6a

This works OK (if I do it in two stages)
cat --locate=TK8TP --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE --number=1 /t0.xml
cat --locate=TK8TP --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE --number=1 /t0.xml

[t0.zip](https://github.com/chenall/grub4dos/files/380182/t0.zip)

**Comment by yaya2007** [comment]
I didn't find the problem. 

title cat
cat /t0.xml
pause
cat --locate=TK8TP --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE /t0.xml
cat /t0.xml
pause
![-20160726114104](https://cloud.githubusercontent.com/assets/8120248/17125511/a83641a6-5326-11e6-907d-c68922b58e10.jpg)

**Comment by steve6375** [comment]
It works on small files, but not on the sample that I attached.
Please use the sample file that I attached.

**Comment by steve6375** [comment]
Are you able to reproduce now?
Substitution works if use --replace=XXXX-XX     but not for --replace=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
so it seems to depend on the length of the substitution string??

**Comment by yaya2007** [comment]
Have a try 
Get rid of 'txt"

[grldr.rar.txt](https://github.com/chenall/grub4dos/files/387733/grldr.rar.txt)

**Comment by steve6375** [comment]
cat --locate=TK8TP- --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE /t0.xml
This works, but

cat --locate=TK8TP- --replace=AAAAA-BBBBB-CCCCC-DDDDD-EEEEE-FFFFF /t0.xml
does not

![image](https://cloud.githubusercontent.com/assets/1469350/17202785/636f3b90-5493-11e6-92d7-6b8c732f5f62.png)

Note: no `</Key>  `

**Comment by steve6375** [comment]
Seems to work now! Thanks! :-)

**Comment by steve6375** [comment]
I think #122 is fixed now - thanks  :-)

Could you look at Issue #119
https://github.com/chenall/grub4dos/issues/119 please?

This is a serious bug which only affect 0.4.6a and it means many people
cannot use 0.4.6a because it crashes when they run grub4dos menus or batch
files on certain systems.

Several people have spent many hours trying to reproduce the bug and at
last we have a reproducible case which you can test.

The problem occurs when you do a geometry command or find or if exist
command on the 'bad' partition - it seems to crash batch files or lose the
command stack in the console, etc. (memory corruption?).

If you cannot reproduce the problem in Virtual Box, please contact me and I
will describe how to reproduce the problem in greater detail.

Thanks
Steve

**Comment by yaya2007** [comment]
See, but there is no reproduce.

**Comment by steve6375** [comment]
Fixed in 2016-08-06 0.4.6a
