### ISSUE TITLE
0.4.6a 2016-08-06 is absorbing key presses

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#125]
When grub4dos loads, if the menu contains a hotkey entry, e.g. Ctrl+I, you could press Ctrl+I _whilst the main menu loads_ and grub4dos would switch to the Install menu (with hotkey loaded)

**menu.lst**

```
title ^Ctrl+I Install menu
configfile /install.cfg

```

0.4.5  OK
0.4.6a all versions up to 2016-07-04  OK
0.4.6a 2016-08-06   FAIL

2016-08-06 is absorbing the key press. Something has changed??? Please can you fix.

e.g. Make Easy2Boot USB drive. Boot to E2B - before Main menu loads - press ctrl+U - Utilities menu should load but it does not if using \grldr 0.4.6a 2016-08-06.

**Comment by yaya2007** [comment]
Have a try 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/416998/grldr.rar.txt)

**Comment by steve6375** [comment]
Works :+1:
