### ISSUE TITLE
'cat' issue reading files' contents

### ISSUE THREAD

**Issue by ner00** [chenall/grub4dos#130]
I'm not sure if this issue has been mentioned before, I have searched the existing issues and none seems to.
I'm facing a problem where I can't read the content of binaries inside Windows and its sub-folders.
For example, the following command gives me a small hex dump full of 00s:
`cat --hex (hd0,1)/windows/write.exe`

This will not work with any original executable inside Windows:
`cat --hex --locate=\x4D\x5A\x90 (hd0,1)/windows/write.exe`

Curiously, for example, if I create a copy of \windows\write.exe (both in WINDIR) and name it write1.exe, then both commands will work properly:
`cat --hex (hd0,1)/windows/write1.exe`
`cat --hex --locate=\x4D\x5A\x90 (hd0,1)/windows/write1.exe`

I do not understand what causes this behavior.
I have Windows 10 Pro (x64) and Grub4dos 0.4.6a (2016-11-09)

**Comment by steve6375** [comment]
What if you copy explorer.exe to the USB drive?
Is your Windows disk MBR or GPT?

**Comment by ner00** [comment]
If I copy the file anywhere it will work, even on the same disk/folder where it isn't working with the original filename. The disk is MBR. Also, I was testing this in VMWare and upon booting my laptop I don't seem to have this issue. it's really weird and I'm not sure how or why it is happening.

**Comment by steve6375** [comment]
So this problem only occurs under VMWare? What is the virtual disk file extension? How was it made?
Did you run chkdisk on the virtual disk?
I tried it on my laptop (real boot) and it is OK for me.

**Comment by steve6375** [comment]
How are you booting to grub4dos under VMWare? Are you booting from a virtual disk containing grub4dos or a real USB drive

**Comment by ner00** [comment]
Only seems to be happening on VMWare, on my laptop also no issue.
Just did a chkdsk and still the same. The disk is a typical vmdk file, it was created a few months ago when I created the VM and installed W10 on it, I had been using it without a hitch since then. I'm booting Grub4dos from the virtual disk where Windows is installed.

If I go to C:\Windows and create a copy of 'write.exe', named 'write2.exe', and go back to grub4dos, then the 'cat' command will work as expected on the copy but not on the original. But this doesn't happen to some other files like, for example, win.ini will work just fine out of the box.

I have no clue what can be the root of this.

**Comment by steve6375** [comment]
Try 
raw cat --hex (filespec)
Is VMWare VM in any special mode like snapshot or something?

**Comment by ner00** [comment]
Did `raw cat --hex (hd0,1)/windows/write.exe` and got the exact same output, whole file zeroed.
As a matter of fact I have been running out of a snapshot to which I have reverted several times.

**Comment by steve6375** [comment]
Can you try vmdk under another VM like VBox?
What if you export the vmdk and try the new vmdk?

**Comment by ner00** [comment]
Everything seems to be pointing towards a problem with my VM's disk.
I checked if there was any misalignment, it seems ok on that front, cloned the current vmdk to a new vmdk using Acronis TI but the new disk shows the same problem. Defraging and compacting the vmdk also didn't do anything. Deleting the snapshot also nothing. I probably will just install Win10 again from scratch on a new vmdk and see where it leads.

**Comment by ner00** [comment]
I deleted the VM and reinstalled Windows on a new VM, everything seems to be working now.
I'm disappointed that I wasn't able to pin-point the issue and fix it but I'm afraid that it might have taken me too much time to figure out and resolve the cause. Anyway, it was a local issue all along.
