### ISSUE TITLE
USB 2.0 boot bug on OLD motherboard

### ISSUE THREAD

**Issue by Deoptim** [chenall/grub4dos#133]
About system:
P4V800-X, Pentium 4 2.8GHz / 2GB RAM
```
xubuntu@xubuntu:~$ lspci | grep USB
00:10.0 USB controller: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev 81)
00:10.1 USB controller: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev 81)
00:10.2 USB controller: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev 81)
00:10.3 USB controller: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev 81)
00:10.4 USB controller: VIA Technologies, Inc. USB 2.0 (rev 86)
xubuntu@xubuntu:~$
```
Introduction:
In BIOS I have "USB 2.0 Configuration" => "FullSpeed" or "HiSpeed" settings.

- When i chose "FullSpeed" in BIOS - and then boot into Boot Menu, chose USB flash drive - it boot fine this drive, but very slow (feels less then USB 1.1).
- When i chose "HiSpeed" in BIOS - and boot into Boot Menu then chose USB flash drive - it stuck.

When i use USB BIOS "FullSpeed" settings, i need to use Plop Boot Manager for fast booting (faster than without this Plop loader, but not faster then USB 1.1).

What is bug:

I use GRUB4DOS 0.4.6a 2016-12-24 version.
After load flash drive (without Plop) i try initialize the USB
```
usb --init
... Scanning USB devices ...
Found 1 USB devices. Device Num: 0x80;
```
I look and see it seems to be good.
When I try to boot some kernel from flash drive, it FAST load, for example 8/25Mb of kernel and then stuck, after reading disk error, I look in the "uuid", that the flash drive (hd0,0) or (0x80,0) already is not present. Once I was able to load the kernel with no problems, it quickly load it into memory (feels full speed USB2.0).

But in general, I can not boot from flash drive (but command like "ls /" works, and if you try to "ls /folder/" it can fall off) after the USB initialization due to fall off of flash drive on grub4dos.

**Comment by yaya2007** [comment]
"for example 8/25Mb of kernel and then stuck"
Every boot ,then stuck?There are also success ?

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/725436/grldr.rar.txt)

**Comment by Deoptim** [comment]
Hello.
I replaced this grldr.
Time of the time with same problem now it reboots the computer.

```
Booting 'Try Xubuntu without installing'
Filesystem type is iso9660_Joliet, using whole disk
  [Linux-bzImage, setup=0x4200, size=0x675ec0]
Loading:/casper/initrd.lz
 [0M/25M]
Stuck here...
```
I reboot the computer and tried once again:
```
Booting 'Try Xubuntu without installing'
Filesystem type is iso9660_Joliet, using whole disk
kernel /casper/vmlinuz file=/cdrom/preseed/xubuntu.seed boot=casper quiet splash --- iso-scan/filename=/iso/xubuntu-16.04.1-desktop-i386.iso

Error 25: (http://grub4dos.chenall.net/e/25)
               Disk read error
Press any key to continue...
```
I reboot the computer and tried other menu entry(mapped in mem WinPE.iso):
```
[8M/288M]
And now automatic reboot the computer.
```
As you can see that the error occurs at different time.
But I'm sure - with grub initialize of USB, it fast loading in memory (USB 2.0), and the data was be correct, because I once got correctly load the kernel [25M/25M].

**Comment by Deoptim** [comment]
Hello again.
Now i made USB boot normal, without errors.

Problem was in SDRAM modules, it was installed the three PC3200 modules 1Gb/1Gb/256Mb (of three DIMM slots on motherboard).
In the BIOS settings where SDRAM Clock Speed is set - was selected Auto.

With this above parameters:
After boot in OS, if i look in tool like CPUZ - always set SDRAM speed to DDR333 (not maximal DDR400).

If i tried in the BIOS settings set the speed to 400 (instead Auto). Then if i tested the memory via Memtest - it was a lot of errors!

And only now i looked to Manual for this OLD motherboard and I saw this quote:
> (Note: PC3200 DDR DIMMs max to 2 DIMM slots only.)

Then i pulled out the 256Mb module and set the manual speed to 400 in BIOS.
Now Memtest looks fine and most import - no errors when i initialize and boot the USB via Grub4DOS loader.

**Comment by Deoptim** [comment]
Mapping to mem and Linux kernel loading is work as it should.

Now i have another problem with Windows boot configuration.
If i boot this configuration:
```
title Boot USB Sergei Strelec
find --set-root --ignore-floppies /SSTR/bootmgr
chainloader /SSTR/bootmgr
```

I have this error:
> File: \SSTR\BCD
> Status: 0xc000000e
> Info: The Boot Configuration Data for your PC is missing or contains errors.

But I see that this error is quite spread and there is no common solution for it.

Most interesting, when I first boot PLoP, and then this windows configuration - **I have no this error!**

This is again something with USB?

**Comment by yaya2007** [comment]
Find the root of the problem. very good.

I guess, May be BCD problem. No more help, sorry.

**Comment by steve6375** [comment]
chainloader /SSTR/bootmgr
works OK for me with Sergei Strelec extracted ISO.
No problem.

**Comment by Deoptim** [comment]
Ok. Thanks.
By the way, I forgot to mention that only works the new **grldr.rar.txt** that you have posted.
With the original bootloader there is the same error/stuck that I wrote earlier.
