### ISSUE TITLE
ls ()/ does not list files in root 2017-03-30

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#136]
In previous versions

root /_ISO
ls /  << lists files in /_ISO
ls ()/ << lists files in root

With new versions
root /_ISO
ls /  << lists files in /_ISO
ls ()/ << lists files in /_ISO   

cat command is also affected

This breaks batch files, etc, serious bug!

**Comment by yaya2007** [comment]
"root /_ISO" usage, grub4dos-0.4.5c-2016-01-18 version also can not do 
The correct approach is "root ()/_ISO"

**Comment by steve6375** [comment]
Sorry - I made typo, BUG is shown below

\menu.lst
```
root ()/_ISO/e2b/
ls /
echo
echo
ls ()/
pause
```
![image](https://cloud.githubusercontent.com/assets/1469350/24541379/14213836-15ef-11e7-90bf-18e8326c75d6.png)
![image](https://cloud.githubusercontent.com/assets/1469350/24541397/24106618-15ef-11e7-81ba-61a96ed9d735.png)

**Comment by steve6375** [comment]
Same result if
```
root ()/_ISO/e2b
ls /
echo
echo
ls ()/
pause
```

**Comment by steve6375** [comment]
P.S. re. 

> VOL_Dir is "xxxx".

Should be Volume Name and also add \n

> Volume Name is "xxxx".**\n**

and **The current working directory(i.e., relative path) is**
  should be just
**The current working directory (relative path) is**

space before ( and just (relative path)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/887291/grldr.rar.txt)

**Comment by steve6375** [comment]
That seems to work.
But current working directory text could be made better?

**Comment by yaya2007** [comment]
"But current working directory text could be made better?"
Please explain further

**Comment by steve6375** [comment]
See comment above.

The current working directory(i.e.**,** relative path) is incorrect English
should be just
The current working directory (relative path) is

space before ( and just (relative path)

![image](https://cloud.githubusercontent.com/assets/1469350/24578066/b34127d2-16d0-11e7-84d2-24f3af6880a3.png)

i.e., is incorrect.  Sentences are 'xxxxxx, i.e. yyyyyyy'  or use (i.e. relative path).  no comma after i.e.
Always use space before (

**Comment by steve6375** [comment]
FYI: Many other examples where a space should be used but is missing...
![image](https://cloud.githubusercontent.com/assets/1469350/24578111/9c53c100-16d1-11e7-9545-90a82b21fb50.png)

**Comment by steve6375** [comment]
Thanks!
