### ISSUE TITLE
USB driver in 2017-04-17 not working?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#139]
report from an Easy2Boot user...
For testing, I'm using an old Athlon 64 motherboard (GA-K8VT800) and the grub4dos USB 2.0 driver (2016-12-23) clearly speeds it up. The hardware is recognized correctly by the latest /glrdr 2017-04-17 ("Found 1 USB devices"), but everything is still slow. So it looks like the driver is not actually being used?
[http://rmprepusb.blogspot.co.uk/2017/04/e2b-v191a-released.html](http://rmprepusb.blogspot.co.uk/2017/04/e2b-v191a-released.html)  - see comments

**Comment by yaya2007** [comment]
Link cannot be accessed

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/940421/grldr.rar.txt)

**Comment by steve6375** [comment]
User reports that the new version is working OK - so problem seems to be fixed.

**Comment by Deoptim** [comment]
Hello again.
Can you do such support for my old motherboard?
In the likeness of build in [this closed ticket](https://github.com/chenall/grub4dos/issues/133) as you made in file **grldr.rar.txt**.
Thanks.

**Comment by yaya2007** [comment]
Have a try 
usb --delay=N --init
N can be 0x10, 0x11, 0x12, 0x13, 0x14....

**Comment by Deoptim** [comment]
Thanks for answer.
Yes, I was tried use this command - and was have the same problems as described in [this closed ticket](https://github.com/chenall/grub4dos/issues/133).
Only works this your file - [grldr.rar.txt](https://github.com/chenall/grub4dos/files/725436/grldr.rar.txt) (2016-12-24).

**Comment by Deoptim** [comment]
**yaya2007**
Okay, at least tell me please, what changes you made in the sources of this file? At least, I can try to patch and build the grub4dos for myself...

**Comment by yaya2007** [comment]
I don't understand what you mean.
You want to insert 3 memory, the specification does not mean no, it can not be solved .
grldr.rar.txt (2016-12-24).Temporary modification, which source code is not clear .
You seem to report that the problem has been solved. What is required now, I do not understand it at all .

**Comment by steve6375** [comment]
Closing as original issue solver.
@Deoptim - if you still have a problem, please raise a new issue.
