### ISSUE TITLE
set /p has problem with long unicode strings

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#140]
I think this has been a bug for a while in 0.4.5c and 0.4.6a

set /p ask=xxxxx
has a problem with certain unicode strings or length of string?
Please test attached menu

if you shorten the string or delete certain characters then it works OK.
ask /p does not wrap the line if it is longer than screen width but also counts UTF-8 pre-codes (e.g. E1 BB)

set 800x600 graphicsmode and load unifont
[$$TEST_VIETNAMESE.zip](https://github.com/chenall/grub4dos/files/981479/TEST_VIETNAMESE.zip)

**Comment by steve6375** [comment]
I think the problem is to do with the number of characters in the string.
In the case above it had 86 characters but 92 bytes.
This code shows same issue with 98 or more ASCII characters
**\menu.lst**

```
title TEST ASK

graphicsmode -1 800

echo -e \n96
set /p ask=012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
echo -e \n97
set /p ask=0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456
echo -e \n98
set /p ask=01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567
echo -e \n99
set /p ask=012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678
echo -e \n100
set /p ask=0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
echo
pause FINISHED TEST
errorcheck off
boot
```
![image](https://cloud.githubusercontent.com/assets/1469350/25780298/85d58ec8-331d-11e7-886c-03637536122a.png)

**Comment by steve6375** [comment]
Improved test
[K.zip](https://github.com/chenall/grub4dos/files/981540/K.zip)
![image](https://cloud.githubusercontent.com/assets/1469350/25780481/3354f35c-3320-11e7-8714-981d6b3d6fce.png)

**Comment by steve6375** [comment]
So is problem that  set /p  does not wrap lines?

**Comment by erol-y** [comment]
now, "set /p" prints string and than shows prompt "$>" at new line to catching user input
![issue140](https://user-images.githubusercontent.com/29168158/27314326-b1ff35e6-557b-11e7-814e-6c0e10ba644b.png)

![issue140_1](https://user-images.githubusercontent.com/29168158/27314087-26b2c508-557a-11e7-8a27-6d4416576319.png)

![issue140_2](https://user-images.githubusercontent.com/29168158/27314099-36d980ca-557a-11e7-8b87-cb414f154170.png)


[grldr.zip.txt](https://github.com/chenall/grub4dos/files/1086864/grldr.zip.txt)

**Comment by steve6375** [comment]
Why ??
Why have you changed it to throw new line and $> ??
This is not compatible. It is not nice.
The problem was that long lines were not printed which you have fixed, but why have you changed it so it no longer stops at the end of the prompt?
Please change it back to

set /p ask=prompt (Y/N) : 

prompt (Y/N) :

**Comment by erol-y** [comment]
Because, g4d cannot handle prompt when it is longer than line width. it needs much effort to rewrite. this is simplest way for key /p .
I will work it on.

**Comment by steve6375** [comment]
If x cursor position => display width, then throw \n$>     
???

**Comment by erol-y** [comment]
Yes, we are talking about same thing. It shows $> when prompt does not fit to the line. 
I checked screenshot from previous post. It shows always. I will check it.

**Comment by erol-y** [comment]
Latest workaround it should work.
![prompt1](https://user-images.githubusercontent.com/29168158/27460502-f4f1eba8-57bc-11e7-91be-2f3eefe05d62.png)

[grldr.zip.txt](https://github.com/chenall/grub4dos/files/1096418/grldr.zip.txt)

**Comment by steve6375** [comment]
Line wrap is OK, but character counting of UTF-8 is wrong
e.g. 2a BAD line wraps, but the line length is not exceeded.
![image](https://user-images.githubusercontent.com/1469350/27500307-d8ff0eb4-585f-11e7-8f39-96101992bd3c.png)

Is there a way to use actual cursor position rather than count bytes in the message?

**Comment by erol-y** [comment]
1=> There is a bug that Grub4Dos can not handle prompt.
	When it is longer than line limit (CMDLINE_WIDTH), g4d only shows "<".

2=> 'u' is a unicode character (2 bytes)
	'a' is ascii (1 byte)
	grub_strlen("ua") returns 3.
	So we should count how many characters there are.
	
3=> Calculating "start" is problematic with long prompt string
	if prompt's length is between:
	(CMDLINE_WIDTH - (CMDLINE_MARGIN / 2)) <= prompt < CMDLINE_WIDTH
	it acts anormal. This if() is added to check that.

![ubu1](https://user-images.githubusercontent.com/29168158/27566394-9cb68aaa-5ad4-11e7-9c21-b4d8ffee103e.png)

[grldr.zip.txt](https://github.com/chenall/grub4dos/files/1103882/grldr.zip.txt)

**Comment by steve6375** [comment]
looks better, I think 👍
