### ISSUE TITLE
Problem booting into Grub2 core.img

### ISSUE THREAD

**Issue by nguyentumine** [chenall/grub4dos#141]
I have used the latest Grub4dos version is [grub4dos-0.4.6a-2017-05-12.7z](http://grub4dos.chenall.net/downloads/grub4dos-0.4.6a-2017-05-12/)
When booting into Grub2 via **core.img**, my machine automatically restarts.

```
title Load Grub2
kernel /AIO/grub/i386-pc/core.img
```

Version 0.4.5c works fine.
grub4dos-0.4.6a-2017-05-05.7z **works**.
grub4dos-0.4.6a-2017-05-06.7z not works.

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/999166/grldr.rar.txt)
Have a try

**Comment by nguyentumine** [comment]
Thanks, it work now.
