### ISSUE TITLE
vol for OpenMandriva ISO does not show complete volume name

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#143]
```
set ISO=OpenMandrivaLx.3.0-PLASMA.x86_64.iso
map /%ISO% (0xff)
map --hook
root (0xff)
vol
pause
```

volume name is shortened to OpenMandrivaLX_3.0
ISO volume names are 32 characters padded with spaces (not 16 characters).

![image](https://cloud.githubusercontent.com/assets/1469350/26754151/e4c1b240-486c-11e7-8d51-9bc58265cd49.png)

**Comment by yaya2007** [comment]
For Joliet discs, Windows uses information of enhanced volume ,Maximum 16uni character.
If you use the main volume information, you can display 32 characters. iso9600 discs this is it .

Please see the disk 0x10,0x12 sector content.

**Comment by steve6375** [comment]
When booting linux ISOs it is often useful to use 
root=live:LABEL=%vol%

but we cannot obtain the correct label using grub4dos...

**Comment by yaya2007** [comment]
There is a limit to the number of volume characters.

No more than 16 bytes 
or
Do not use ISO of Joliet format

**Comment by steve6375** [comment]
OK
What about UUID of ISO?  
I can get ISO using
map %ISO% (0xff)
map --hook
root (0xff)
#get UUID from ISO
cat --skip=813 --length=4 (0xff)16+1 | set ID=
cat --skip=817 --length=2 (0xff)16+1 | set ID=%ID%-
cat --skip=819 --length=2 (0xff)16+1 | set ID=%ID%-
cat --skip=821 --length=2 (0xff)16+1 | set ID=%ID%-
cat --skip=823 --length=2 (0xff)16+1 | set ID=%ID%-
cat --skip=825 --length=2 (0xff)16+1 | set ID=%ID%-
cat --skip=827 --length=2 (0xff)16+1 | set ID=%ID%-
echo ISO UUID=%ID%

but grub4dos uuid does not report UUID???

**Comment by yaya2007** [comment]
I don't know the UUID of the CD

**Comment by steve6375** [comment]
Volume name can be obtained from ISO using
cat --hex --skip=0x28 --length=32 (0xff)16+1
![image](https://cloud.githubusercontent.com/assets/1469350/26763004/4e44c686-4943-11e7-9423-0ea23a00314f.png)
Here volume name is 30 characters - when using with linux and root=live:LABEL=%vol%  it needs to be full volume name (not 16 characters).
![image](https://cloud.githubusercontent.com/assets/1469350/26763135/7f55232c-4945-11e7-8076-d9c58fc736da.png)

**Comment by steve6375** [comment]
Actually, looking at https://fossies.org/linux/grub/grub-core/fs/iso9660.c
I think the UUID is taken from the modified date, so it should be from 830
```
#get UUID from ISO
cat --skip=830 --length=4 (0xff)16+1 | set ISO_UUID=
cat --skip=834 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
cat --skip=836 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
cat --skip=838 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
cat --skip=840 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
cat --skip=842 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
cat --skip=844 --length=2 (0xff)16+1 | set ISO_UUID=%ISO_UUID%-
echo ISO UUID=%ISO_UUID%

```

Here is code for volume name - which is 32 or 16
  987 static grub_err_t
  988 grub_iso9660_label (grub_device_t device, char **label)
  989 {
  990   struct grub_iso9660_data *data;
  991   data = grub_iso9660_mount (device->disk);
  992 
  993   if (data)
  994     {
  995       if (data->joliet)
  996         *label = grub_iso9660_convert_string (data->voldesc.volname, 16);
  997       else
  998         *label = grub_strndup ((char *) data->voldesc.volname, 32);
  999       if (*label)
 1000     {
 1001       char *ptr;
 1002       for (ptr = *label; *ptr;ptr++);
 1003       ptr--;
 1004       while (ptr >= *label && *ptr == ' ')
 1005         *ptr-- = 0;
 1006     }
 1007 
 1008       grub_free (data);
 1009     }
 1010   else
 1011     *label = 0;
 1012 
 1013   return grub_errno;
 1014 }

**Comment by steve6375** [comment]
I prove that Ubuntu uses offset 830=modified date for UUID  (not 813=created date)
![image](https://cloud.githubusercontent.com/assets/1469350/26766172/f96f2caa-4983-11e7-8f14-295e77dcbeff.png)
![image](https://cloud.githubusercontent.com/assets/1469350/26766177/033e3032-4984-11e7-8b51-7f350653f48b.png)

**Comment by yaya2007** [comment]
8.1.1 Volume Descriptor Type (BP 1) 
This field shall specify as an 8-bit number the Volume Descriptor Type. 
Number O shall mean that the Volume Descriptor is a Boot Record; 
Number 1 shall mean that the Volume Descriptor is a Primary Volume Descriptor; 
Number 2 shall mean that the Volume Descriptor is a Supplementary Volume Descriptor or an Enhanced Volume Descriptor; 
Number 3 shall mean that the Volume Descriptor is a Volume Partition Descriptor; 
Numbers 4 to 254 are reserved for future standardization; 
Number 255 shall mean that the Volume Descriptor is a Volume Descriptor Set Terminator. 
This field shall be recorded according to 7.1.1. 

ISO_TYPE_9660 and ISO_TYPE_RockRidge use Primary Volume Descriptor.
ISO_TYPE_Joliet use Enhanced Volume Descriptor.

Please see:
cat --hex --skip=0x28 --length=32 (0xff)18+1

**Comment by yaya2007** [comment]
Please try UUID:

[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1050951/grldr.rar.txt)

**Comment by steve6375** [comment]
Not correct.
It seems to be treating the UUID as binary numbers when in fact they are ASCII?

![image](https://cloud.githubusercontent.com/assets/1469350/26776178/0d2b3288-49d0-11e7-8c1a-da6f5fcb0a29.png)

**Comment by steve6375** [comment]
re. Volume Label. Yes, you are correct to say that the specification for the volume label for Joliet says to use the enhanced volume descriptor.

BUT OpenMandriva does not use this - it seems to use the (0xff)16+1  Volume Descriptor Set
![image](https://cloud.githubusercontent.com/assets/1469350/26776878/01ccaef0-49d3-11e7-9216-b3606635454c.png)

I tested Ubuntu
![image](https://cloud.githubusercontent.com/assets/1469350/26776990/6c513c82-49d3-11e7-8fb6-6878cb7f41f5.png)
![image](https://cloud.githubusercontent.com/assets/1469350/26777015/83e83972-49d3-11e7-9251-a8d321aedb0e.png)
![image](https://cloud.githubusercontent.com/assets/1469350/26777098/dd7ab9d8-49d3-11e7-8499-e9acb58d89cc.png)
It seems to also use sector 16. Primary
Next Fedora - which does not use the enhanced descriptor either...
![image](https://cloud.githubusercontent.com/assets/1469350/26777255/793afd74-49d4-11e7-9278-a6ccafbb468c.png)
![image](https://cloud.githubusercontent.com/assets/1469350/26777389/eb5ebd00-49d4-11e7-97f5-6c75d30722d3.png)

So in all cases, linux uses the Primary Volume Descriptor at (0xff)16.
Since getting the volume label is useful for linux booting when we need to use root=live:LABEL=%vol%
I would suggest that for ISO9660 (inc Joliet)  the vol command returns the Primary label. Maybe add a --enhanced parameter to get the Enhanced Volume Label?

**Comment by nguyentumine** [comment]
I think using 0x8028 instead of 0x9029, it is not separated by dots. ISO9660, Joliet and UDF are the same.
Great for adding a parameter to convert whitespace to **\x20**.

**Comment by yaya2007** [comment]
"I would suggest that for ISO9660 (inc Joliet) the vol command returns the Primary label. Maybe add a --enhanced parameter to get the Enhanced Volume Label?"
Set a parameter:
--linux ?

**Comment by steve6375** [comment]
Most people will want the vol command so they can use the volume label with linux cheat codes.
but --linux or --windows is OK.
Need to ensure that trailing spaces are deleted also.

**Comment by nguyentumine** [comment]
I think he will always get the full 32 characters and trim all the spaces at the end.

**Comment by steve6375** [comment]
Official MS Windows ISOs don't use Joliet so Primary vol name will be returned.
Most Joliet ISOs will be linux ISOs. So most common usage for vol command will be to use the volume label   with a linux cheat code.
So it makes sense for default  for vol command to return Primary Volume label and have a **--enhanced** or **--windows** or **--joliet** switch to return the enhanced volume label?

**Comment by yaya2007** [comment]
It's not Linux's problem. It's OpenMandriva's problem. 

Look at udf. Enter 32 characters, can you display? Do also use Primary Volume Descriptor?

**Comment by steve6375** [comment]
Sorry, I do not understand you. 

I just showed you three linux examples - OpenMandriva, Ubuntu and Fedora all use the Primary Volume Descriptor for the volume label of a Joliet ISO.

**Comment by yaya2007** [comment]
--primary
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1054284/grldr.rar.txt)

**Comment by steve6375** [comment]
Works :-)  
UUID OK and  vol --primary OK
--iso-force-Primary does not work ???

help text not clear?
![image](https://cloud.githubusercontent.com/assets/1469350/26821505/8bf39794-4a9e-11e7-8b6e-6eb2a3164420.png)
--iso-force-**P**rimary ??? What is this and why uppercase P in Primary ??

'... use only the **a** Primary Volume Descriptor'

**Comment by yaya2007** [comment]
--iso-force-Primary should be removed.

'... use only the a Primary Volume Descriptor'
How to express, please suggest.

**Comment by steve6375** [comment]
Use --primary for ISO Primary Volume Descriptor (as used by linux).

**Comment by steve6375** [comment]
Closing - thanks!
