### ISSUE TITLE
vol command on udf ISO does not trim spaces

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#145]
![image](https://user-images.githubusercontent.com/1469350/26898449-f2ed6f94-4bc3-11e7-8b27-2eb6f66b1763.png)

**Comment by steve6375** [comment]
re. code change
for (i=0; i<0x20; i++)
			{
				if (vol_found[i] == ' ' && (vol_found[i] == vol_found[i+1] || i == 0x19))
					break;

why 0x19 ???  why not 0x1f ???

what if volume label contains more than one space?? - e.g.

ABCspace space DEF

or what if ends with only one space - e.g.

1234567890123456789012345678901 space 

Should code start at i=0x1f and step -1
```
 0x1f steps of  -1  to  0
   if vol_found(i) not 0 and vol_found(i) not 0x20 then break;
   if  vol_found(i)==0x20  then vol_found(i)=0
loop
```

???

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/26948239-83dddbfa-4c8d-11e7-9b68-201311fbeb14.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/26948341-eb240fa0-4c8d-11e7-83ef-c9f5b5c0f19a.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1062842/grldr.rar.txt)

**Comment by steve6375** [comment]
OK

**Comment by steve6375** [comment]
I am not very good at C code, but I do not understand this code or why you have 0x19 ???

for (i=0; i<0x20; i++)
			{
				if (vol_found[i] == ' ' && (vol_found[i] == vol_found[i+1] || **i == 0x19**))
					break;
			}
			vol_found[i] = 0;

**Comment by yaya2007** [comment]
0x19: low-level error. It should be 0x1f.

**Comment by steve6375** [comment]
Ok, no problem ;-)

**Comment by steve6375** [comment]
If FAT32 volume name has two spaces, the vol shortens name
e.g.
'123(space)(space)456'
vol reports as '**123**'


code approx line 7160 builtins.c
```
			devread (*(unsigned long long *)(SUPERBLOCK+0x58)+(filepos>>9), filepos&0x1ff, 12, (unsigned long long)(unsigned long)vol_found, n);
			if (flags)
				return;
			vol_found[11] = 0;
			for (i=0; i<11; i++)
			{
				if (vol_found[i] == ' ' && (vol_found[i] == vol_found[i+1] || i == 10))
					break;
			}
			vol_found[i] = 0;
		}
		else

```
![image](https://user-images.githubusercontent.com/1469350/27002360-fb051d88-4dd7-11e7-9c58-35ca494bf6e8.png)
![image](https://user-images.githubusercontent.com/1469350/27002363-12d7a7be-4dd8-11e7-8933-8637223a0e51.png)

**Comment by steve6375** [comment]
Thanks
