### ISSUE TITLE
cat --hex not listing ASCII characters correctly

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#150]
![image](https://user-images.githubusercontent.com/1469350/27224587-d0ebbaf6-528d-11e7-8112-033a0e592b2f.png)

0x1e7 - 0x1F1 - Should be 'Boot error'

**Comment by steve6375** [comment]
Still some characters are not being displayed
![image](https://user-images.githubusercontent.com/1469350/27259079-c50fabd6-5402-11e7-9292-455094fbb952.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/27259229-b8d30720-5405-11e7-8e0d-caf86794a250.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/27259232-e28aaf1e-5405-11e7-82e3-4a63d70208b8.png)

**Comment by yaya2007** [comment]
According to the UTF-8 character display.

**Comment by steve6375** [comment]
How can I display bytes (not UTF-8) if in graphicsmode?

**Comment by yaya2007** [comment]
Hex, it has been shown.

**Comment by steve6375** [comment]
If displaying UTF-8 then a dot should be added so that we can tell position of character?, e.g.

`31 31 CC B8 31 31              >>>>>                11/.11`

Can this be easily done?

**Comment by yaya2007** [comment]
Is that so? 
Just show 0x20-0x7f. 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1083664/grldr.rar.txt)

**Comment by steve6375** [comment]
I think that may be best solution you agree?

**Comment by yaya2007** [comment]
Set up a switch:  --hex-en

**Comment by steve6375** [comment]
--UTF8  ???

**Comment by steve6375** [comment]
Thanks!
