### ISSUE TITLE
Kernel panic with grub4dos-0.4.6a-2017-06-18

### ISSUE THREAD

**Issue by xesarni** [chenall/grub4dos#152]
The USB 2.0 driver from Easy2Boot v1.93 (grub4dos-0.4.6a-2017-06-18) triggers "kernel panic - not syncing: VFS: unable to mount root fs on unknown block(0,0)" during boot (tested on Xubuntu 16.04.2 x64 & Lubuntu 17.04 x32) on a GA-K8VT800 motherboard. ﻿The last working version is grub4dos-0.4.6a-2017-06-11.

**Comment by yaya2007** [comment]
Using the built-in USB2.0 driver?

**Comment by yaya2007** [comment]
Please test separately, and then report. Never get mixed up. 
[grub4dos-1.rar.txt](https://github.com/chenall/grub4dos/files/1093417/grub4dos-1.rar.txt)

**Comment by yaya2007** [comment]
[grub4dos-2.rar.txt](https://github.com/chenall/grub4dos/files/1093424/grub4dos-2.rar.txt)

[grub4dos-3.rar.txt](https://github.com/chenall/grub4dos/files/1093440/grub4dos-3.rar.txt)

**Comment by xesarni** [comment]
> Using the built-in USB2.0 driver?

I'm not sure what you mean. I'm using "Install fast Grub4dos USB 2.0 driver" from Easy2Boot and I don't have any external controllers.

> grub4dos-1.rar.txt

 Tested, works fine.

> grub4dos-2.rar.txt

The file is missing: 404 Not Found

> grub4dos-3.rar.txt

 Tested, works fine.

**Comment by yaya2007** [comment]
[grub4dos-2.rar.txt](https://github.com/chenall/grub4dos/files/1094112/grub4dos-2.rar.txt)

**Comment by steve6375** [comment]
"Install fast Grub4dos USB 2.0 driver" from Easy2Boot uses the grub4dos  usb --init command.

**Comment by yaya2007** [comment]
Got it

**Comment by xesarni** [comment]
> grub4dos-2.rar.txt

Unreliable. Kernel panics happen, but not during every boot up.

**Comment by yaya2007** [comment]
2.txt is the same as 3.txt USB code. So, or both fail, or both succeed. Should not be a success, a failure.

**Comment by steve6375** [comment]
It may be that you need to power off the system before each test and wait 1 minute?
Do not reboot/restart.

**Comment by xesarni** [comment]
Yes, retested and got a kernel panic with 3.txt.

1.txt still seems to be OK.

**Comment by yaya2007** [comment]
power off the system before each test and wait 1 minute.
[4.rar.txt](https://github.com/chenall/grub4dos/files/1094735/4.rar.txt)

**Comment by yaya2007** [comment]
[5.rar.txt](https://github.com/chenall/grub4dos/files/1094794/5.rar.txt)

**Comment by xesarni** [comment]
4.rar & 5.rar behave like 2.rar & 3.rar.

**Comment by yaya2007** [comment]
power off the system before each test and wait 1 minute.
[6.rar.txt](https://github.com/chenall/grub4dos/files/1096416/6.rar.txt)

**Comment by xesarni** [comment]
Seems to be better, but I had a kernel panic once. Maybe it's not grub4dos' fault.

**Comment by steve6375** [comment]
Try repeatedly testing the older 'good' grldr...?

**Comment by xesarni** [comment]
grldr 2017-06-25 from E2B v1.94 seems to be fine. Thanks!
