### ISSUE TITLE
No error returned when invalid grub4dos batch file is called

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#155]
If a grub4dos batch file is called in a menu.lst or in another batch file, execution is not stopped if !BAT is missing from the file.

e.g.
```
errorcheck on
debug normal
call /test.g4b
echo here
```

/test.g4b
```
### !BAT is missing !!!
set t=1
```

This line works
`call /test.g4b || echo ERROR`

However, I would have expected grub4dos to report an error and stop (unless errorcheck off was used)?

**Comment by yaya2007** [comment]
Error prompt :
Error 13

**Comment by steve6375** [comment]
Yes, but not when run from a batch file or menu.lst - execution does not stop.

**Comment by yaya2007** [comment]
> e.g.
errorcheck on
debug normal
call /test.g4b
echo here


/test.g4b
### !BAT is missing !!!
set t=1

**Comment by yaya2007** [comment]
Test again ,can be terminated, normal.
Examples may be inappropriate

**Comment by steve6375** [comment]
menu.lst
```
errorcheck on
debug normal
call /test.g4b
echo here
pause
```
test.g4b
```
### !BAT is missing !!!
set t=1
pause

```
![image](https://user-images.githubusercontent.com/1469350/30525499-9616b6ae-9bff-11e7-8c47-d34e8ebd59ee.png)

No message is seen??? No indication of error ???

But if run from console...
![image](https://user-images.githubusercontent.com/1469350/30525541-4f772d54-9c00-11e7-80e7-88f20a7c68e5.png)
we see an error.

**Comment by yaya2007** [comment]
There is no termination in the preset menu.
There is termination in the menu.

**Comment by steve6375** [comment]
That is strange???. My example is using \menu.lst and it does not terminate.
I am running from VBox from a USB drive which has grub4dos installed on it.
