### ISSUE TITLE
Disk error when attempting to boot from mapped drives

### ISSUE THREAD

**Issue by ppgrainbow** [chenall/grub4dos#157]
Hello! I'm new to GitHub and I would like to report a problem with the latest version of GRUB4DOS v0.4.6a.

I've been using GRUB4DOS under Virtual PC 2007 to multiboot between MS-DOS 6.22, OS/2 Warp 4 and Windows 95.

In the latest version, revision 2017-10-05, I found that I can no longer boot OS/2 Warp or Windows 95 when using GRUB4DOS when I use the map feature.

When I select OS/2 Warp 4 to boot from the second hard disk image mapped as the first hard disk image, this is the error message that I get:

![os2_error](https://user-images.githubusercontent.com/32658796/31364897-bef3d038-ad1c-11e7-85db-f6f5f4d87005.png)

And when I try to boot Windows 95 from the third hard disk image mapped as the first hard disk image, this is the error message that I get:

![win95_error](https://user-images.githubusercontent.com/32658796/31364922-d9077df8-ad1c-11e7-92a4-0e3a9b294582.png)

Furthermore, when I try to boot from a floppy disk image to copy the system files from the second or third hard disk image that is mapped as the first hard disk image, I get a "Sector not found reading drive C" error.

Here is the current snippet of the OS/2 Warp and Windows 95 boot parameters in my MENU.LST file:

> title IBM PC-DOS 6.30 / IBM OS/2 Warp 4\n\n 
hide (hd0,0)
hide (hd0,4)
hide (hd0,5)
hide (hd0,6)
unhide (hd1,0)
unhide (hd1,4)
unhide (hd1,5)
unhide (hd1,6)
hide (hd2,0)
hide (hd2,4)
hide (hd2,5)
hide (hd2,6)
map (hd0) (hd1)
map (hd1) (hd0)
map --floppies=1
map --hook
root (hd0,0)
chainloader +1

> title Microsoft Windows 95\n\n 
hide (hd0,0)
hide (hd0,4)
hide (hd0,5)
hide (hd0,6)
hide (hd1,0)
hide (hd1,4)
hide (hd1,5)
hide (hd1,6)
unhide (hd2,0)
unhide (hd2,4)
unhide (hd2,5)
unhide (hd2,6)
map (hd0) (hd2)
map (hd2) (hd0)
find --set-root /IO.SYS
map --floppies=1
map --hook
root (hd0,0)
chainloader +1

I have followed directions to map hard disk images correctly and used the map --hook parameter to hook INT13 and it worked in rev 2017-08-30 and now, it doesn't work anymore in the rev 2017-10-05 release.

Is this a bug in the latest release of GRUB4DOS or something else that I'm missing? If there is something that I'm missing, what has changed?

**Comment by steve6375** [comment]
Can you confirm that if you simply replace \grldr with the 2017-08-30 version, then it works?

**Comment by ppgrainbow** [comment]
Steve, I can confirm that if I replace the version of GRLDR with the 2017-08-30 version, then I can boot OS/2 or Windows 95:

![win95_boot](https://user-images.githubusercontent.com/32658796/31415751-2798cca2-adda-11e7-9a6c-d784c5958f20.png)


If I use the 2017-10-05 version of GRLDR, then I end up getting disk read errors when trying to boot OS/2 or Windows 95.

![win95_error](https://user-images.githubusercontent.com/32658796/31415795-6abdd040-adda-11e7-8b62-2d7153b212e9.png)

Something has either changed with the 2017-10-05 revision and I failed to notice what was wrong with this release.

**Comment by steve6375** [comment]
OK - thanks for confirming.
Code change in asm.s has possibly caused a problem???

**Comment by ppgrainbow** [comment]
You're welcome. I got the r2017-10-04 build of GRUB4DOS v0.4.6 to work.

The problem could be the code change in the asm.s file in r2017-10-05.

**Comment by yaya2007** [comment]
Have a try

**Comment by ppgrainbow** [comment]
Yaya, I tried the 2017-10-11 version of GRLDR and I'm still getting disk IO errors when trying to boot from either OS/2 or Windows 95. :(

**Comment by yaya2007** [comment]
Have a try
[grldr2017-10-12.rar.txt](https://github.com/chenall/grub4dos/files/1377584/grldr2017-10-12.rar.txt)

**Comment by ppgrainbow** [comment]
Yay! The 2017-10-12 version of GRLDR works! I can boot OS/2 or Windows 95 again! :)

Can anyone look into the code for any reason why the 2017-10-05 version of GRLDR was buggy?

**Comment by ppgrainbow** [comment]
Thank you so much for fixing the disk I/O error issue! I'm gonna close this bug now! :)
