### ISSUE TITLE
grub.exe begin pxe scan on debug off

### ISSUE THREAD

**Issue by nguyentumine** [chenall/grub4dos#158]
I booted Grub4dos from Grub2.
```
menuentry "Test grub.exe" {
	set opt="debug off; pause Somethings"
	linux /grub.exe --config-file=$opt
}
```
Output:
`begin pxe scan... Somethings.`

Is this an unwanted thing?

![2017-10-21_071631](https://user-images.githubusercontent.com/13947826/31845872-eb1ebbac-b62f-11e7-999b-0567dd7a2f42.jpg)

**Comment by yaya2007** [comment]
Maybe the grub.exe version is too old

**Comment by nguyentumine** [comment]
The filename is grub4dos-0.4.6a-2017-10-14.7z
I downloaded it from http://grub4dos.chenall.net/categories/downloads/

**Comment by yaya2007** [comment]
attempt 
[grub.rar.txt](https://github.com/chenall/grub4dos/files/1404790/grub.rar.txt)

**Comment by nguyentumine** [comment]
This version is OK. Many thanks!

**Comment by yaya2007** [comment]
Patch has been uploaded to the official website .
