### ISSUE TITLE
Improve color help - help color text does not mention how to set 64-bit colours

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#161]
e.g.
color helptext=0x00FF00FF
color standard=0x00FFFFFF00FF00FF
also normal, highlight and border (and 'heading'?)

Also '**help echo**' does not mention 64-bit colour syntax - e.g.
echo $[0x00FFFFFF00CCCC00]Hello$[]Normal colour

Should also mention that $[] resets to original colour value.

![image](https://user-images.githubusercontent.com/1469350/33264929-73689538-d367-11e7-8b2b-0d9037269054.png)

**Comment by yaya2007** [comment]
help color
help echo
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1513560/grldr.rar.txt)

**Comment by steve6375** [comment]
re. color
![image](https://user-images.githubusercontent.com/1469350/33376568-0cddbd8e-d506-11e7-94cf-aae9e8315805.png)
use the word part not bits to avoid confusion
high **part**=      low **part**=

re. help echo
![image](https://user-images.githubusercontent.com/1469350/33376713-ada4e986-d506-11e7-8bf8-b8bcad3fdff1.png)

C and D have different meanings so suggest use 
$[0xCD] 16 or 64 bit color value for MESSAGE. C=background, D=character.

**Comment by yaya2007** [comment]
Color function correction. See help, please.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1524498/grldr.rar.txt)

**Comment by steve6375** [comment]
1. color STANDARD is not mentioned ???? Suggest add standard=0xFFFFFF to last example line?


2. in 800x600
![image](https://user-images.githubusercontent.com/1469350/33524226-46107454-d810-11e7-9f21-54c3ac261bea.png)
command `color blue/red` or `color 0x41` changes  menu text (NORMAL), **AND** console text (STANDARD) when executed from grub4dos console, BUT only the menu text is changed when executed from within menu.lst ??? Is this a bug - I don't think console color should be changed?

3. Should be 'highlight character color **is** 0xf or' ...
![image](https://user-images.githubusercontent.com/1469350/33524028-a3b985b8-d80c-11e7-9727-181cf629ef34.png)

4. Is this expected? background for Highlight is black, but help text implies background will be the same as NORMAL color?
![image](https://user-images.githubusercontent.com/1469350/33524094-f846bf5a-d80d-11e7-8ca2-25270bc88dc6.png)
graphicsmode -1 800
color normal=0x41 highlight=0xFF00FF

title TEST\nHELP
root ()
boot
title TEST\nHELP
root ()
boot
title TEST\nHELP
root ()
boot
title TEST\nHELP
root ()
boot
 
![image](https://user-images.githubusercontent.com/1469350/33524103-35d1d76a-d80e-11e7-9ac7-e2d3f0ec59b1.png)



5. Please change e,g and e.g to  e.g. 
![image](https://user-images.githubusercontent.com/1469350/33524148-233cc8f2-d80f-11e7-9515-aa41b0af1b10.png)


6. color values are 4-bit and 32-bit  (numbers are 8-bit and 64-bit)
![image](https://user-images.githubusercontent.com/1469350/33524137-cfd82d64-d80e-11e7-94e9-ead46f060ec7.png)

**Comment by steve6375** [comment]
$[0xCD] where C and D are  4-bit numbers for 16 colors, or 32-bit numbers for 24-bit colors.
![image](https://user-images.githubusercontent.com/1469350/33524254-ecdcb19e-d810-11e7-9b3b-0b12fc8da393.png)

**Comment by yaya2007** [comment]
1. Add to 
2. Change the console color on the command line.Tagging 
3. Remove
4. correct
5. correct
6. correct

help echo
correct
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1525431/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks!
