### ISSUE TITLE
吐个槽，关于在win7下安装grub4dos到MBR

### ISSUE THREAD

**Issue by nobk** [chenall/grub4dos#162]
README_GRUB4DOS_CN.txt下面的相关内容大部分都只适用于win9x 2000 xp，这份文档里面80%的内容都该归档到过时文档里面了吧，现在基本上都在用win7 8 10系统了。

我读完那164KB的文件，最后还是没找到一个明确的在windows 7下面把grub4dos安装到MBR的方法。

由于我需要远程修改默认启动项，还要支持跨平台，只有选择把grub4dos安装在MBR。grub2我实在没找到能在windows7下面远程修改默认启动项的方案。

而安装包里面的bootlace没法在win7下面执行。听说grubinst能安装，然而安装包里面不带，我又不知道具体哪个版本的grubinst适用于现在的grub4dos-0.4.6a-2017-12-05.7z版本，这个也不敢乱试。
作者你看看是不是与时俱进把安装工具以及说明文件也更新一下啊？

**Comment by yaya2007** [comment]
使用bootice
