### ISSUE TITLE
Request: Support bracketed multiple expressions in grub4dos language

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#165]
It would be nice to support bracketed multiple expressions, e.g. using {} in a single line of code.

`if X==1 { echo fred ;; if Y==2 echo doris ;; if Z==3 echo Z && echo Z1 ;; spashimage /my.jpg ;; if Z==3 echo Z2 || echo Z-2 }`

Is this possible for both menu.lst files and batch files?
If `echo {`  was required, it could be coded as `echo \{`

**Comment by yaya2007** [comment]
Alternative:
if  NOT X==1 goto :label1
echo fred ;; if Y==2 echo doris ;; if Z==3 echo Z && echo Z1 ;; spashimage /my.jpg ;; if Z==3 echo Z2 || echo Z-2
:label1

**Comment by steve6375** [comment]
Yes, but that does not work in menu.lst config files.
It would be nice to have this feature, if possible.

**Comment by yaya2007** [comment]
Now you can do the same in the menu, using goto: Label 
Example: 
title test
 echo This is a test string
 set /p os=Please Input:
 if /i %os%==1 && goto :label1
 if /i %os%==2 && goto :label2
 echo -e \nInvalid input
 goto :aaa
 :label1
 echo -e \nThis is a label1
 goto :aaa
 :label2
 echo -e \nThis is a label2
 :aaa
 set os=
 pause
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1671951/grldr.rar.txt)

**Comment by steve6375** [comment]
**\menu.lst**
clear
echo 1
goto :xx
echo 3
:xx
echo 2
if 1==2 && goto :yy
goto :zz
:yy
echo fail
:zz
echo pass
pause

![image](https://user-images.githubusercontent.com/1469350/35530706-c26415da-052c-11e8-8f6b-21e4d45ccd0a.png)

Does it have to be under a title menu entry ???

**Comment by yaya2007** [comment]
yes

**Comment by steve6375** [comment]
OK.
Q. How can I use goto for a subroutine?
Using  
```
set ret=:z1
call :z2
pause fail
:z1
echo z1
pause

:z2
echo z2
goto %ret%
```
does not work and  goto :eof and exit at the end does not work either?
I assume call will not work either...

**Comment by yaya2007** [comment]
Labels can't use variables

**Comment by yaya2007** [comment]
Please test 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1693841/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks! Labels now work.
also  `if 1==1 goto :t2`  seems to work too :-)  (no && required)

now labels must be in same 'scope' as title\iftitle

looks good!

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/35797352-633e28d6-0a57-11e8-9ed3-334fcefa743f.png)
```
iftitle [if 1==1] test me!
clear
echo 1
set RET=pp
if 1==1 goto :tl

:pp
echo LABEL pp worked
pause here
set RET=pp2
goto :t1
echo bad
:pp2
echo LABEL pp2 worked
goto :t2

:tl
echo t1 %RET%
goto :%RET%

:t2
pause t2
errorcheck off
boot
```
seem to be a problem?

**Comment by yaya2007** [comment]
goto :t1  err
goto :tl  ok

**Comment by steve6375** [comment]
doh! sorry!  the unifont 1 and l are so similar! Works OK now,

**Comment by steve6375** [comment]
Thanks!

**Comment by yaya2007** [comment]
The parenthesis function is implemented, please test.
Example:

title Test the braces 
!BAT
if "12"=="12" { 
set a0=0 
    if "34"=="12" { set b0=0 ;; set b1=1 }
    else  if "12"=="12" { set b2=2 ;; set b3=3 }
    else { set b4=4 ;; set b5=5 }
    set b9=9
    set b 
set a1=1 }
else  if "12"=="12" { set a2=2 ;; set a3=3 } 
else { set a4=4 ;; set a5=5 }
set a9=9
set a
pause

[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1958389/grldr.rar.txt)

**Comment by steve6375** [comment]
Looks good.
!BAT must be first line after title\iftitle
must be space before and after {
must use batch command syntax until next title\iftitle, e.g. echo %a%%%b%  if after !BAT.

One strange thing, if you run a menu entry that uses !BAT and it then returns to the menu, if you then press e for edit, it only lists 
`!BAT`
on the screen with no more lines showing.
![image](https://user-images.githubusercontent.com/1469350/39404700-6fcf62f2-4b90-11e8-8c79-fb418270ca1f.png)
![image](https://user-images.githubusercontent.com/1469350/39404709-a4bc4250-4b90-11e8-8b38-55fca7f2b4ba.png)

**Comment by steve6375** [comment]
if 1==2 { echo 1 } else { echo 2 }

This does not seem to work?

so else must be at start of a line ?

**Comment by steve6375** [comment]
```
if 1==2 { echo 1 ;; echo 2 ;; if 1==2 echo x || echo 3 } 
else echo 99
```

Does not seem to work?
Is only else {} and else if  valid ??

**Comment by yaya2007** [comment]
"!BAT must be first line after title\iftitle
 must be space before and after {
 must use batch command syntax until next title\iftitle, e.g. echo %a%%%b% if after !BAT."
yes

"One strange thing, if you run a menu entry that uses !BAT and it then returns to the menu, if you then press e for edit, it only lists"
Press the button 2 times ( press e for edit).  The reason is unknown. I don't want to check it out .

'{' or '}' can't be be at start of a line .
example:
if "12"=="12"
 {  set a0=0    //err
set a1=1
}                     //err

"if 1==2 { echo 1 } else { echo 2 }
This does not seem to work?
so else must be at start of a line ?"
else must be at start of a line .

"Does not seem to work?
Is only else {} and else if valid ?"
Is only else {} and else if {} valid.

**Comment by steve6375** [comment]
OK - and cannot have nested {   {  }  }  braces ?
`if 12==12 { if 34==34 echo fred && if 44==44 { echo doris ;; echo jim } }`

**Comment by yaya2007** [comment]
I try to try

**Comment by steve6375** [comment]
Its not a problem if it is too difficult.

**Comment by yaya2007** [comment]
modify : '}' can be be at start of a line .

Nesting of different levels, It  '{'  or '} ' can't be on the same line. 
title test
!BAT
if 12==12 { 
if 34==34 echo fred && if 34==44 { echo doris ;; echo jim } 
}
pause
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1959803/grldr.rar.txt)

**Comment by steve6375** [comment]
Seems good :-) thanks
