### ISSUE TITLE
goto in batch files broken by grub4dos 0.4.6a 2018-02-20

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#168]
Sorry, just tested 2018-02-20 - it seems to have broken labels in batch files?

![image](https://user-images.githubusercontent.com/1469350/36532535-de7a1e2e-17b8-11e8-9f70-f3fa9db26d6f.png)

!BAT
debug off
checkrange 20130710:-1 read 0x8278 || pause Error - Old grub4dos version: Please use grldr from the E2B download! && set badver=1
:: this batch file calls itself, so use the label as the place to jump to
goto %~x1
exit

:.automenu

:: must turn off errorcheck or FAT32 dirs give error if using cat --length=0
errorcheck off

**Comment by steve6375** [comment]
Here is older version which works 
![image](https://user-images.githubusercontent.com/1469350/36532750-7f7c9c8e-17b9-11e8-9d52-f23759a8f690.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1751501/grldr.rar.txt)

**Comment by steve6375** [comment]
debug version ???
![image](https://user-images.githubusercontent.com/1469350/36593688-aae20be6-1892-11e8-9b21-537f4661424f.png)
does not work with Easy2Boot even if press ENTER

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1751667/grldr.rar.txt)

**Comment by steve6375** [comment]
Still a problem with E2B batch files
![image](https://user-images.githubusercontent.com/1469350/36595057-ab177744-1898-11e8-94fe-1a1eb6324ff0.png)
same automn.g4b as in first post.

**Comment by steve6375** [comment]
You can make an E2B flash drive and test yourself
http://www.easy2boot.com/download/

**Comment by yaya2007** [comment]
S[1#472]:[goto loop]
It should be
S[1#472]:[goto :loop]
It's like
S[1#466]:[...................goto :loop]

Although the old version does not use ':', it can also work. That's g4d too loose. It's better to be standard. 

Now there are 2 destinations that need to be distinguished. 
See 'help goto'.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/1755626/grldr.rar.txt)

**Comment by steve6375** [comment]
OK, I have changed my batch file to say :loop now. Thanks.

![image](https://user-images.githubusercontent.com/1469350/36639656-5e43694c-1a09-11e8-8fd6-79b8d8993818.png)
Help text should say LABEL  and use in batch files or **menus**,

also goto %x% or goto %1 works without needing preceding colon

```
!BAT
#usage /test.g4b test
goto :fred
pause

:fred
echo fred
set d=doris
goto %d%
pause

:doris
echo doris
goto %~1
pause

:test
echo test
pause

```
![image](https://user-images.githubusercontent.com/1469350/36639807-2698e500-1a0c-11e8-8d22-be4e664d3628.png)
So help text could say 
e.g. goto :LABEL (must use colon) or goto %label% or goto :%label% or goto %1

Could code be made more compatible with old versions if you tested for a number?
e.g. 'if label starts with 0-9 then treat as  menu number, else treat as script label'

**Comment by yaya2007** [comment]
Specifications, label front add ":". Although not ":" it can work. However, the tag does not use the number.

**Comment by yaya2007** [comment]
"e.g. goto [+|-]NUM. use in the menu. NUM starts with 0-49.\n"
   "e.g. goto [:]LABLE. use in batch files or menus. LABLE can't use 0-49."

**Comment by steve6375** [comment]
LABEL  not LABLE


why 49?? Menu can go to 99??

**Comment by yaya2007** [comment]
can

**Comment by yaya2007** [comment]
"goto [+|-|:]DESTINATION",
   "e.g. goto [+|-]NUM. Use in menus. Jump to the specified title.\n"
   "e.g. goto [:]LABEL. Use in batch files or menus. Jump to the specified ':LABEL'.\n"
   "When there is no ':' in front of the LABEL, the LABEL can't be a number."

**Comment by steve6375** [comment]
👍

**Comment by steve6375** [comment]
2018-02-27 goto in batch files also broken.
![image](https://user-images.githubusercontent.com/1469350/36808504-290d74aa-1cbd-11e8-8e37-91dbd76a1851.png)

**Comment by steve6375** [comment]
2018-03-03 just seems to hang!
Problem seems to be in line
configfile /_ISO/e2b/grub/menu.lst

It hangs here and the /_ISO/e2b/grub/menu.lst file does not seem to be executed!

**Comment by steve6375** [comment]
Same issue in 2018-03-15 
Please fix.

To reproduce, make an Easy2Boot USB flash drive and replace \grldr
Issue seems to be at end of \_ISO\e2b\grub\menu.lst    last line

configfile (md)0x3000+0xA0

**Comment by steve6375** [comment]
2018-03-15 BUG DEMO
Please download and test on USB drive  [K.zip](https://github.com/chenall/grub4dos/files/1832894/K.zip)

![image](https://user-images.githubusercontent.com/1469350/37706111-309ed562-2cf6-11e8-8346-f165ea4c2f8d.png)
Sample to show BUG in configfile command with latest grldr
menu.lst will not run menu1.lst - it hangs!

menu1.lst has at top
echo menu.lst
pause NEVER GETS HERE!



If use good grub4dos then get
![image](https://user-images.githubusercontent.com/1469350/37706396-496b1208-2cf7-11e8-8655-788f25c9bcb9.png)

**Comment by steve6375** [comment]
The sample grldr that you provided in bug #172 works OK.
But the released version 28-03-2018 has the same bug and hangs when loading the config file.
Can you reproduce the problem?

**Comment by yaya2007** [comment]
GCC version problem. We are trying to solve it.

**Comment by steve6375** [comment]
I think this is fixed but I haven't tested it a lot. Thanks.
