### ISSUE TITLE
Joliet ISO9660:1988 not supported by 0.4.6a

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#17]
See #174 1998 spec
https://code.google.com/p/grub4dos-chenall/issues/detail?id=174
I tested 0.4.6a 19/11/2014 and fails to work (also 0.4.5c fails)

**Comment by steve6375** [comment]
This is a compatibility problem because 0.4.5c can access files inside this type of ISO (ISO 9660 Level 4) file but 0.4.6a cannot read the files inside this type of ISO. Therefore, I am reluctant to switch to using 0.4.6a because it may not work with some ISOs.

Also bitdefender iso not accessible under 0.4.6a
![image](https://cloud.githubusercontent.com/assets/1469350/5814490/eee1d734-a083-11e4-80c1-bf937b1826b2.png)
![image](https://cloud.githubusercontent.com/assets/1469350/5814513/265c9e1a-a084-11e4-8e26-00fea084d2b5.png)

**Comment by steve6375** [comment]
For level 4 ISO, only one file is listed by 0.4.5c (\grlr is missing)
![image](https://cloud.githubusercontent.com/assets/1469350/5815031/8fd00f9e-a089-11e4-8b6a-227654cf660e.png)

![image](https://cloud.githubusercontent.com/assets/1469350/5815012/5a3c93ca-a089-11e4-9cad-a73cf53d7061.png)

0.4.6a gives odd results sometimes
![image](https://cloud.githubusercontent.com/assets/1469350/5814999/2b4f2ef6-a089-11e4-95a2-cb8c5f3bb892.png)
BUT sometimes it works!
![image](https://cloud.githubusercontent.com/assets/1469350/5815205/7d6021b2-a08b-11e4-871d-aa324efc72d9.png)
Test ISO is at:
https://code.google.com/p/grub4dos-chenall/issues/detail?id=174#c2

**Comment by chenall** [comment]
Does it works on 0.4.5c?
If it can, can we force 0.4.6a to not use Joliet
using the new test version 
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-01-23.7z

map --iso-types=0

iso_types bits
0 iso9600(always use) 
1 udf
2 iso9600_Joliet
3 iso9600_RockRidge

iso9600_Joliet only(iso9600_Joliet  and iso9660)
iso_types = 5

to disalbe udf (0xf xor 2)
iso_types = 13 

disalbe joliet(0xf xor 4) 
iso_types = 11

**Comment by steve6375** [comment]
I am confused! New version just works (i.e. without using --iso-types), so I tried 2015-01-20 version of 0.4.6a and that works too now! Before I tested a NTFS USB drive and a exFAT drive and both failed as shown in the screenshot but 0.4.5c worked!
I still get the 'Error: partition 0 should not start...' message though and 0.4.5c does not give this message - can this message be suppressed as it seems to work and can only be suppressed using debug msg=0?

**Comment by steve6375** [comment]
0.4.6a 2015-02-09
'map /_ISO/MAINMENU/bitdefender-rescue-cd.iso (0xff)'

I still get the 'Error: partition 0 should not start at sector 0(the MBR sector)'

only debug msg=0 will suppress it, but it is not an error. It should be a WARNING and at  debug msg=2 level.

**Comment by steve6375** [comment]
Request change message to Warning and set to  debug 2 level?

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/7561903/c75defe0-f7c7-11e4-81a9-c9cef329065e.png)

v. 2015-05-10 still shows spurious Error message - please fix.

**Comment by steve6375** [comment]
Same error message in 46a 2015-05-18 version - please fix.

**Comment by steve6375** [comment]
fixed in 2015-06-05 0.4.6a thanks!
