### ISSUE TITLE
Improve write command help text

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#171]
![image](https://user-images.githubusercontent.com/1469350/37596081-e395e8de-2b72-11e8-8f80-3cffa1991220.png)

The syntax when using --bytes=n is not specified in the help text.

INTEGER is 32-bit value (0x01020304) if ADDR is used or hex byte string ( \x01\x02\x03\x04) if FILE is used.

P.S. Should be space before _(or device)_.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/37596936-b4b08cec-2b75-11e8-8fb0-451eccde0b2c.png)
writing hex value only seems to work if ADDR is used, does not work if FILE?

**Comment by steve6375** [comment]
write [--offset=SKIP] ADDR INTEGER32
or
write [--offset=SKIP] [--bytes=N] FILE BYTES_OR_STRING  - where N=1-8 and BYTES_OR_STRING is format \x00\x01\x02 or any string

is that more accurate?

**Comment by yaya2007** [comment]
"write [--offset=SKIP] [--bytes=N] ADDR_OR_FILE INTEGER_OR_STRING",
"Write a 32-bit INTEGER to memory ADDR or write a STRING to FILE(or device!)\n"
"To memory ADDR: default N=4, otherwise N<=8."

**Comment by steve6375** [comment]
need to explain STRING can be \xhh\xhh format if want to write bytes

**Comment by yaya2007** [comment]
1234 is a string

**Comment by steve6375** [comment]
yes, but the help text does not tell you how to write bytes to a FILE
for ADDR use 0xhhhhhhhh
for FILE use \xhh\xhh

**Comment by yaya2007** [comment]
"write [--offset=SKIP] [--bytes=N] ADDR_OR_FILE INTEGER_OR_STRING",
  "Write a 32-bit INTEGER to memory ADDR or write a STRING to FILE(or device!)\n" 
  "To memory ADDR: default N=4, otherwise N<=8. Use 0xhhhhhhhh form.\n"
  "To FILE(or device): default STRING size. UTF-8(or hex values) use \xhh form, UTF-16(big endian) use \xhhhh form."

**Comment by steve6375** [comment]
\xhhhh does not work?
![image](https://user-images.githubusercontent.com/1469350/37702602-f94f39cc-2cea-11e8-8f56-45c312360dc9.png)

**Comment by steve6375** [comment]
\X0170 works  but not \x0170
![image](https://user-images.githubusercontent.com/1469350/37703719-8b812e2e-2cee-11e8-9fe6-cbd7cf1a3a75.png)

use X and spaces, so we get...

"To FILE (or device): default STRING size. UTF-8 (or hex values) use \xhh form, UTF-16 (big endian) use \Xhhhh form."

**Comment by yaya2007** [comment]
The role of \Xhhhh: 
UTF-16 (big endian) -> UTF-8
Use the following method to view:
cat --hex (md)0x300+1
Reference 'help echo'

**Comment by steve6375** [comment]
yes I know - but what I am saying us that your help text show lowercase x  in "\xhhhh"  but it should be uppercase X as in "\Xhhhh"

i.e. the help text is not correct - it should say uppercase \Xhhhh for UTF-16

**Comment by yaya2007** [comment]
I'm sorry！ It should be the uppercase X.
