### ISSUE TITLE
kernel and initrd in label

### ISSUE THREAD

**Issue by nguyentumine** [chenall/grub4dos#174]
It looks like the **kernel** and **initrd** commands automatically load, regardless of whether it's in a label.

```
title Test1
if exist /bzImage2 goto :test

kernel	/bzImage root=/dev/ram0 vga=normal
initrd	/initrd.gz

:test
kernel	/bzImage2 root=/dev/ram0 vga=normal
initrd	/initrd2.gz
```
![2018-04-10_191324](https://user-images.githubusercontent.com/13947826/38556699-bd0775b4-3cf4-11e8-894b-391b9783eb2e.png)

Although it is possible to use variables instead, but it seems automatic execution without parsing the syntax is unreasonable.

```
title Test2
if exist /bzImage2 goto :test

set _kernel=/bzImage root=/dev/ram0 vga=normal
set _initrd=/initrd.gz
goto :boot

:test
set _kernel=/bzImage2 root=/dev/ram0 vga=normal
set _initrd=/initrd2.gz
goto :boot

:boot
kernel	%_kernel%
initrd	%_initrd%
```

**Comment by steve6375** [comment]
You need to use 'boot' to make it boot when you want.
Try this

```
title Test1
if exist /bzImage2 goto :test

kernel	/bzImage root=/dev/ram0 vga=normal
initrd	/initrd.gz
boot

:test
kernel	/bzImage2 root=/dev/ram0 vga=normal
initrd	/initrd2.gz
```

The command 'boot' is implied only at the end of a menu

**Comment by nguyentumine** [comment]
@steve6375 The kernel and initrd commands execute automatically.
![2018-04-11_054733](https://user-images.githubusercontent.com/13947826/38587531-01a21f2e-3d4c-11e8-8c99-d3141314b12c.png)
