### ISSUE TITLE
Animation stops if hold down cursor key

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#178]
2018-06-12  (e.g. E2B standard menu)
To reproduce, use E2B 

1. Play continuous splashimage animation in menu - e.g. rotating E2B logo.
2. Now hold down UP or DOWN cursor key so that menu selection highlight scrolls continuously.
After 10-300 scrolls the animation will disappear - it cannot be brought back using F2.

2017-12-23 is OK

**Comment by steve6375** [comment]
Can reproduce on real system or in VirtualBox when booting from USB using VMUB.

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2109563/grldr.rar.txt)

**Comment by steve6375** [comment]
Fixed! Thanks :-)
