### ISSUE TITLE
Request: centre menu entries

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#179]
It would be a nice feature if menu entry text could be optionally centred in the menu.
it should expand any variables and then centre the text:

```
set fred=ddddddddddddd
title 123
root ()
title menu 1234567
root ()
title %fred%
root ()
```

> 
>             123
>           1234567
>       ddddddddddddd
> 

If the menu entries are numbered, then the menu numbers should be left-aligned.
![image](https://user-images.githubusercontent.com/1469350/41819935-2dd657b8-77c1-11e8-9dfa-d44acae39655.png)

e.g. setmenu --centre-align

**Comment by yaya2007** [comment]
setmenu --title-middle
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2132725/grldr.rar.txt)

**Comment by steve6375** [comment]
great! But why  --title-middle ????

we already have --left-align and --right-align  ??? so why not --centre-align or --middle-align ?

**Comment by yaya2007** [comment]
No change of key help and project help

**Comment by steve6375** [comment]
Seems to work well.

maybe also add a **setmenu --help-middle**  option to centre the menu help text as well?

**Comment by yaya2007** [comment]
setmenu --centre-align
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2139545/grldr.rar.txt)

**Comment by steve6375** [comment]
P.S. UK spelling is 'centre' but  USA spelling is 'center'  - so if you are using American language (e.g. gray not grey) then perhaps it should be --center-align   or maybe --middle-align to avoid spelling mistakes by user?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/41959654-839ce81c-79e5-11e8-886d-7e8c6baca89d.png)
Works!

**Comment by steve6375** [comment]
On small issue
If menu is centered and use a highlight background colour and remove arrow pointer, then the left column 'spacer' is also highlighted.

```
color highlight=0x00FF0000FFFF00  ;; # yellow text + background will be 00FF00 (green)
# remove arrow pointer from left side
write 0x8308 0 > nul
setmenu --centre-align
setmenu --highlight-short
```


![image](https://user-images.githubusercontent.com/1469350/41979676-93c8ecfe-7a1c-11e8-907c-361e287aa7fa.png)

**Comment by steve6375** [comment]
P.S. I found a workaround
write 0x8308 219

**Comment by yaya2007** [comment]
setmenu   --middle-align

setmenu --box l=0
Do not display triangle and automatic numbering 

"Small cursor when using large fonts "
correct
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2143422/grldr.rar.txt)

**Comment by steve6375** [comment]
no menu entries ???
even if I don't use --middle-align
![image](https://user-images.githubusercontent.com/1469350/42012808-ef69d224-7a91-11e8-97eb-89747a3e2831.png)

also no cursor??
Is it broken?

**Comment by yaya2007** [comment]
I'm sorry 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2144271/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks! That's better. Seems OK so far :-)

**Comment by steve6375** [comment]
still looks good 👍 !

**Comment by steve6375** [comment]
sorry, just spotted these two issues:
1. left-align
if use setmenu --middle-align  and then use setmenu --left-align  it does not align on left.
however right-align aligns on right.

So must just be a problem with left-align


2. --box l=0
setmenu --box l=0
This turns off the auto-numbering. Why? We already have --auto-num-off and --auto-num-on
How can we get a left-aligned menu with no border but with numbered menu items by using setmenu?
--auto-num-on does not seem to work after using --box l=0

I don't think --box l=0 should change auto-numbering or the arrow marker. The initial problem was the highlighted space character at the left of the menu when using centred menus.
setmenu --middle-align
setmenu --auto-num-on
setmenu --highlight-short
color highlight=0xffffff00FF0000
setmenu --box x=10 y=20 w=40 h=20 l=0
(now need to remove arrow and not highlight space next to arrow)
perhaps add a new command --marker-off and --marker-on

**Comment by yaya2007** [comment]
if use setmenu --middle-align and then use setmenu --right-align it does not align on right.
Middle to its priority

**Comment by yaya2007** [comment]
Middle to its priority

**Comment by steve6375** [comment]
hmmd, I must have done something to make right-align work after middle-align. I could swap between the two from the console several times with no problem before. However, now both left-align and right-align don't work.

**Comment by yaya2007** [comment]
--side-align 
--middle-align
--triangle-on
--triangle-off

**Comment by steve6375** [comment]
what is side-align , we already have --left-align and --right-align ??

**Comment by yaya2007** [comment]
--side-align is (--left-align and --right-align)
--side-align is --middle-align-off

--left-align set menu_tab &= 0xbf
--right-align set menu_tab |= 0x40
--middle-align set menu_tab |= 0x08
You can't turn off the middle alignment on the command line 
--side-align  set menu_tab &= 0xf7

**Comment by yaya2007** [comment]
In addition, when middle alignment, triangle or automatic numbering on the left? on the right?

**Comment by steve6375** [comment]
left is OK.

**Comment by steve6375** [comment]
when user gives right-align or left-align command, why can't you also do side-align internally?

**Comment by yaya2007** [comment]
When the left is aligned, the triangle is on the left. 
When the right is right, the triangle is on the right. 
When the middleis aligned, I don't know how to deal with a triangle.

Does the Arabs like to be on the right?

**Comment by steve6375** [comment]
when middle, pointer triangle is on left (most common case). For Arabs it can be turned off.

**Comment by yaya2007** [comment]
OK ，Bye

**Comment by yaya2007** [comment]
"--left-align* --right-align --middle-align\n"
"--auto-num-off* --auto-num-on --triangle-on* --triangle-off\n"
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2151506/grldr.rar.txt)

**Comment by steve6375** [comment]
I am having problems getting --auto-num-off to work?
Could it be something I am doing by write 0x8274 0x2001  or write 0x8274 0 ??? Edit - I dont think so,

after setmenu --auto-num-off    0x8274 still reads as 0x12001

[Edit] This was my problem with menu system - please ignore!

**Comment by steve6375** [comment]
Also
--auto-num-on
--right-align
--middle-align

then the numbers are on the right hand side
![image](https://user-images.githubusercontent.com/1469350/42123253-c3990a28-7c46-11e8-95a2-22085ea7483c.png)

**Comment by steve6375** [comment]
For compatability
triangle-off   should be 0x8276 bit 0 SET     (1)
triangle-on  should be 0x8276 bit 0 RESET  (0)

i.e. opposite of what it is now.

so that 
write 0x8274 0x2001
write 0x8274 0x0
work in same way as before

**Comment by yaya2007** [comment]
0x8274 is automatic numbering 
0x8308 is a triangle 

"then the numbers are on the right hand side"
Special reservations

**Comment by steve6375** [comment]
by default  0x8274 is now  0x12001  - it used to be 0x2001
grub4dos documentation says to use write 0x8274 0x2001   or 0x0 to turn on autonumber
Please make the default value 0x2001  not 0x12001  so it is compatible with previous users code.

**Comment by yaya2007** [comment]
You understand the mistake.
0x8274 is 0x2000 (2 bytes) by default .
--auto-num-on: 0x2000 -> 0x2001

**Comment by steve6375** [comment]
0 or  0x2000  is same result.
But the problem is you are using 0x8276 now and users have already written code
write 0x8274 0x2001    will overwrite 0x8276 with 0000
so using location 0x8276 to store extra bits breaks compatibility with users code
Please can you use a different location to store extra bits in and leave 0x8276 as 0x0000 as before?

**Comment by yaya2007** [comment]
0x8276 I didn't use it. 
However, it is risky for users to use the reserved built-in data area.

**Comment by yaya2007** [comment]
When the triangle is printed, 0x8276 is used:
grub_putchar(highlight ? (### menu_num_ctrl[2] = entryno,menu_cfg[0]) : ' ', 255);

**Comment by steve6375** [comment]
so 8276 is now used. But this is not compatible

see Chenall code for menu.lst file
https://github.com/chenall/grub4dos/blob/master/menu.lst

**Comment by yaya2007** [comment]
When the triangle is printed, 0x8276 is used :
grub_putchar(highlight ? (**menu_num_ctrl[2]** = entryno,menu_cfg[0]) : ' ', 255);
It used to be this (0.4.5c)

**Comment by steve6375** [comment]
my problem with auto-num-off was due to my menu - it does work OK, sorry,

**Comment by steve6375** [comment]
OK - most of my problem were caused by my menu system using  write 0x8274 in many places.

So 2 issues are:
1. If issue right-align and then middle-align, the numbers and arrow are on right-hand side of menu (this may be a 'feature'.  If use right-align then left-align then middle-align the numbers are now on the left. So this might be useful workaround for Arabic RTL languages? - should we leave this bug\feature in?)
2. Cannot use 0x8276  WORD area - breaks compatibility

**Comment by steve6375** [comment]
write 0x8274 is used here
https://github.com/chenall/grub4dos/blob/master/menu.lst
http://www.pontikis.net/blog/easily-create-bootable-usb-with-multiple-iso-images
http://fireball-catcher.blogspot.com/2013/03/grub4dos.html
https://forum.donanimhaber.com/easy-peasy-grub4dos-menu-lst-dosyasi-yardim-cozuldu--108638700

it is often used by many people.

**Comment by yaya2007** [comment]
1. This is not what bug. is intended to do. 
2. I don't use the 0x8276. problem. Just a few years ago, you just discovered it?

**Comment by yaya2007** [comment]
write 0x8274 0x2001.
What is the effect of 0x8274 (1 bytes)? 
What is the effect of 0x8275 (1 bytes)? 
What is the effect of 0x8276 (1 bytes)? 
What is the effect of 0x8277 (1 bytes)?

**Comment by steve6375** [comment]
write --bytes=2 0x8274 0x2001   - this works with new version OK

but 

write 0x8274 0x2001  - causes many problems with new version

but user code already uses   write 0x8274 0x2001  or write 0x8274 0x2000 or  write 0x8274 0
so this causes many problems with new grub4dos version.

Solution is:  do not use  menu_num_ctrl[2] or menu_num_ctrl[3] anywhere please.
