### ISSUE TITLE
How to get current default menu number?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#181]
I thought the byte at 0x8276 was current_entry and it could be read to obtain the current menu entry, but it always seems to be 0?

**Comment by yaya2007** [comment]
In issue#179, You post request:
"Solution is: do not use menu_num_ctrl[2] or menu_num_ctrl[3] anywhere please"

So, it was closed.

**Comment by steve6375** [comment]
So my question is:
How can I get the currently selected menu entry number as a variable?
See http://reboot.pro/topic/18584-changing-screen-resolution-with-hotkeys/ which does not seem to work.

**Comment by steve6375** [comment]
Thanks
re. setmenu --auto-num-all-on

![image](https://user-images.githubusercontent.com/1469350/44633297-667acf80-a981-11e8-8c62-58314e23bdee.png)

why are some entries not numbered ? e.g. 8 and 10

![image](https://user-images.githubusercontent.com/1469350/44633306-84e0cb00-a981-11e8-8c32-9469d795072f.png)
![image](https://user-images.githubusercontent.com/1469350/44633360-354ecf00-a982-11e8-9142-cd863c358a70.png)

But this entry is numbered (5)
![image](https://user-images.githubusercontent.com/1469350/44633333-f3be2400-a981-11e8-9f2e-ecb5841df55b.png)

**Comment by steve6375** [comment]
P.S. looking at the menu files, there are two spaces after ] when it is numbered but  no spaces after title, so the entry is not numbered if there is no space after  ] or title.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/44777397-71e11d00-ab72-11e8-939e-4cca7fc0f589.png)

[menu.zip](https://github.com/chenall/grub4dos/files/2331483/menu.zip)
