### ISSUE TITLE
How to use a variable for whole title line in menu.lst?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#182]
I would like to use a variable for the title line - e.g.

```
set A=This is title\nThis is help text

title %A%
root ()
boot
```
but the help text does not display.
Is there any way to do this?

If possible, I would also like to set a hotkey to, e.g.
`set A=^F1 This is title\nThis is help text`

**Comment by steve6375** [comment]
P.S. The reason for this is so that I can have different languages, e.g.

call FRENCH.g4b

would set the menu strings A, B, C, etc. in French and then I can use
title %A%
...
title %B%
...

**Comment by yaya2007** [comment]
I tested, no problem. 

set A=This is title
set B=This is help text

title %A% \n %B%
root ()
boot

**Comment by steve6375** [comment]
Yes, but only 60 variables allowed, so if each menu has title and 3 help lines, then I can only have 14 menu entries and I also need to use other variables too for calculations, etc. So I really need single variable for each title line.

**Comment by yaya2007** [comment]
3 help lines？

**Comment by steve6375** [comment]
[menu.zip](https://github.com/chenall/grub4dos/files/2378401/menu.zip)
Here is the menu.lst file.
Although only 5-10 menu entries actually display in the menu, there are many more menu entries with multiple lines of help.

I would have to use
`title %A%\n%Ah1%\n%Ah2%\n%Ah3%
`
which means 2, 3 or 4 variables per title line.

grub4dos does not support enough variables for all of these.

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/2381639/grldr.rar.txt)

**Comment by steve6375** [comment]
Great! :-)  Many thanks.
