### ISSUE TITLE
Strange behaviour of >= or <= operator?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#188]
![image](https://user-images.githubusercontent.com/1469350/52777160-0b29c000-303b-11e9-97d3-82219307d4b1.png)

`if /i 02g>=02h echo fred`
**fred**

non-hex characters seem to cause a different result from hex characters.

**Comment by yaya2007** [comment]
Only numbers and strings can be judged .
002e is an illegal number.

**Comment by steve6375** [comment]
Why is 002f different from 002g ?

**Comment by yaya2007** [comment]
The decimal system can only contain 0,1,2,3,4,5,6,7,8,9.

**Comment by yaya2007** [comment]
String starting must be English letters.
Hexadecimal start must be 0x, follow-up can only contain 0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f.

**Comment by steve6375** [comment]
yes, but 002 is a decimal number because it does not start with 0x.
so why is 002f different from 002g?
I would expect if starts with a number then when it meets the first non-number, it would finish parse
so
002f = 2
100f = 100
99f = 99
99g = 99
etc.
but it does not work like that...
![image](https://user-images.githubusercontent.com/1469350/53080787-5c312c80-34f1-11e9-8f50-5d36575cad3f.png)

see above example

**Comment by yaya2007** [comment]
k, m, g, t are quantifiers.
It will magnify the front number.

**Comment by steve6375** [comment]
Thanks! That explains it.
![image](https://user-images.githubusercontent.com/1469350/53157317-2788a800-35b9-11e9-8ac3-ca1cc378d893.png)
