### ISSUE TITLE
$[] causing commands to be displayed

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#190]
![image](https://user-images.githubusercontent.com/1469350/52911450-d0729280-329b-11e9-856f-f2a16a6d95fc.png)

\menu.lst
```
pause hello
echo -e $[0104]a$[]
pause > nul
write (md)0x300+1 aaaaaaaaaaaa > nul
echo -e $[0104]b$[]
pause > nul
```

**Comment by steve6375** [comment]
if add a space to end of line after $[] then is OK
echo -e $[0104]a$[]    <<<< add space to end of line

**Comment by steve6375** [comment]
also occurs with
echo $[0x1f]
when no character after ]

**Comment by yaya2007** [comment]
Why can't I upload files?

**Comment by steve6375** [comment]
Thanks!
