### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by suFDHAI78fyw78q09Y98yfd** [chenall/grub4dos#192]
UUID lets us only bot that device by using the USB own UUID to identify that device alone for booting.

This in writing is great just what we need but has one major drawback. There is no way to get the true UUID from a USB device. I have tried from Linux, Debian live bootable CDs and DVDs None of the Live CDs or DVDs could with using many commands show true UUID information of any USB device on the system. Don't use Linux or Debian often more a Windows user. The Linux and Debian commands I used found from many sites using a search engine to find them.

With Grub4Dos we need a way to get and show the True UUID of all our storage devices. If we had a tool we could run on Windows OS for example XP3. That when run will show and output to a .txt the True UUID for all storage devices attached to the system that the tool is run on. We then can use this information to use with Grub4Dos.

Then will be very easy to set a UUID and target that UUID to boot a storage device that only has that same UUID. This would be very precise as Grub4Dos will always only boot the device with the same UUID.

This I know is very much needed, I have been waiting for it to happen but as yet it hasn't. Today I write here and ask you, to please make this possible.

Thanks.

**Comment by steve6375** [comment]
I do not understand. The uuid and vol commands in grub4dos can be used. Type **help uuid** and **help vol**
see also https://github.com/chenall/grub4dos/issues/143

Please explain what the problem is.

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
I'm using grub4dos like this with Win32 XP3
Need grub4dos are located in C:\ which assume is a root dir
Boot.ini modified so.
[boot loader]
timeout=30
default=multi(0)disk(0)rdisk(0)partition(1)\WINDOWS
[operating systems]
multi(0)disk(0)rdisk(0)partition(1)\WINDOWS="Microsoft Windows XP Professional" /noexecute=Alwaysoff /fastdetect
c:\grldr="grub4dos v0.4.6a"

Gives me two options each time when reboot the pc.

I am needing a tool to use with command prompt (console, cli) while on win32 XP3 to show me the UUID of each device rather than having to manipulate the same in dos. I did just try to run in a console in XP3 but the grub.exe is dos so outputs nothing of use

>C:\grub4dos-0.4.6a-2019-02-22\grub4dos-0.4.6a\grub.exe help uui
d

GRUB: Unrecognized or failed command line parameters. Usage:
        GRUB [OPTIONS]
OPTIONS: --bypass, --time-out=T, --hot-key=K, --duce, --chs-no-tune,
OPTIONS: --keep-pxe, --config-file="FILE"
The options are case-sensitive, you must use lower-case letters. Each
option can be specified only once at most.
FILE can be specified in GRUB or DOS style. If FILE is led by the pair '#@',
then a DOS filename follows.
FILE can also be some GRUB commands delimited by semi-colon, or the whole
content of a menu file(again semi-colon delimits each line of the menu file).
FILE can be double-quoted(this is recommended, especially for use as embedded
commands or menu).     Hexdump of command-line buffer in PSP:
0080:   01 20 68 65 6C 70 20 75 75 69 64 00 53 54 45 52   ☺ help uuid STER
0090:   3D 41 30 0D 64 64 72 65 73 73 2E 20 20 46 6F 72   =A0.ddress.  For
00A0:   20 65 78 61 6D 70 6C 65 3A 0D 20 6F 6E 20 4E 54    example:. on NT
00B0:   56 44 4D 2C 20 73 70 65 63 69 66 79 20 61 6E 20   VDM, specify an
00C0:   69 6E 76 61 6C 69 64 0D 20 6F 6E 6C 79 2E 0D 00   invalid. only..
00D0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00E0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00F0:   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

>

The same for other commands
--help uuid
--help
/?
-h
--h
etc

With simple tool we can get UUID quickly and able to modify menu.lst with a simple command only to boot that UUID and ignore everything else for booting.

With that done we can then with same menu.lst expand and have options for several device choose any one. Each having in menu.lst its own true UUID for only that device, then easy to choose which device or USB to boot. While also most important we don't need to hook this and that or care for any of that stuff. Just boot the chosen UUID.

Getting the correct UUID is the first step while in windows using command prompt or by any other simple tool method without need to install anything extra to do so.

If Grub.exe can be used with Win32 console I haven't figured how yet. Neither have I ever seen correctly the true UUID of any device. Windows doesn't show this it shows 16 characters GUIDs and others different but not true UUID. Reason for needing a tool in Win32 XP3 do show this information.

This is for use with PC that cannot boot normally any USB bios doesn't do that. And for a PC that can do so. It to overcome problems associated with hook remap and similar where the devices may change often different ports as with USB. This way target UUID is the only way I believe best to do this very easily. Also help when user doesn't know code or want to know all the hook and remap learning to do simple task. But USB of choice using the UUID of the USB. Hope this more explains what the problem is.


Thanks.

**Comment by steve6375** [comment]
This appears to be a Windows question?
Your question appears to be 'How can I obtain the grub4dos volume UUIDs when running under Windows'.
You will need to use a Windows utility like secinspect
Attached are two .cmd scripts, one works for FAT32 volumes and the other for NTFS volumes
e.g
GET_UUID_NTFS J:
GET_UUID_FAT32 U:
[Utils.zip](https://github.com/chenall/grub4dos/files/2999180/Utils.zip)

**Comment by steve6375** [comment]
P.S. From grub4dos, just boot to **grub4dos menu** and type c to get to the grub4dos command line and type 
`uuid`

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
Grub4dos  typed uuid got a big list of devices and see uuid for each of the drives.

Which drives are the bootable ones, maybe that info was shown didn't notice, I may have missed that if it was. Mentioned in case it wasn't maybe something to add.

Ok so I tried to pipe all uuid output on screen to a .txt file for use in windows.

Normal windows pipe didn't work
uuid >C:uui devices list.txt

neither did
hd1,# uuid devices list.txt  hd1,# (number as is shown on uuid list).

Dos or linux pipe must be different command that is used to save the uuid output to hd1,0 uuid.txt

No issue now I have your scripts and secinspect that does the same task to get all the uuid's of all the drives on this windows pc. I heve never heard mention or read anywhere of secinspect. It will be well used from now to know all drives uuid's now and future for use with grub4dos. Thanks this is what I was looking for to be able to get and copy true uuid's in windows os.

I have many bootable drives, more bootable usb's than actual bootable hdd's. Have you any examples or a link that shows a basic simple menu.lst  When booted to the menu.lst will have listed of many bootable devices all bootable by using uuid alone.

Such simple menu.lst could maybe be like this, I haven't tried this only just got the drive uuid's. Uuid's below are not actual uuid's I know of.

uuid=1234567890123456 "Boot USB Drive A"
uuid=0987654321098765 "Boot USB Drive B"

When boot the menu.lst it would show on screen something like this below. Navigate the list using keyboard up-down arrow buttons to choose a drive to boot from.

Boot USB Drive A
Boot USB Drive B


Thanks.

**Comment by steve6375** [comment]
Once in the grub4dos environment, there is no operating system.
You can redirect output into a file ONLY if the file already exists (use grub4dos 0.4.6a latest version 2018-12)
e.g.
`uuid > /myfile.txt`

using...
`uuid 000E0336000C1B8D`
you can find any partition using the uuid command
Find uuid number 000E0336000C1B8D equipment, and set it to the current device

so a menu such as

```
title Boot to xxxx
uuid 000E0336000C1B8D && chainloader +1
```

will boot to that partition (if it is bootable).

grub4dos has no way of knowing which partitions are bootable. You can use grub4dos to detect files or volume labels, etc.. Can you tell just by looking at the files on a volume if it would boot successfully or not?

Most people use tag files. For instance, if you have 7 partitions but only 5 were bootable and each one contained a bootable PBR, you could have a specific tag file on each partition and use a menu such as

```
title Boot to Windows 10 
find --set-root /Win10.tag
chainloader +1

title Boot to Ubuntu
find --set-root /Ubuntu.tag
chainloader +1
```

This relies on the PBR of each partition containing boot code, you may need to boot in other ways such as directly booting to bootmgr, e.g.

```
title Boot to Windows 10 
find --set-root /Win10.tag
chainloader /bootmgr

title Boot to Windows XP
find --set-root /WinXP.tag
chainloader /ntldr

```
There is no way for grub4dos to know how you have installed each OS on each partition, so it does not know how to boot from them! 
Also, it does not know that any partition is C: or D: because those names are given to the volumes by Windows and are controlled by Windows and the user settings in Windows.
Grub4dos is not magic, it cannot just make all partitions bootable! You have to write the correct menu for each OS or partition.
There is a grub4dos guide at https://www.rmprepusb.com/tutorials/grub4dos
a primer for all command at https://www.rmprepusb.com/tutorials/grub4dos/grub4dos-commands-primer
Example menus https://www.rmprepusb.com/tutorials/grub4dos/grub4dos_examples
Unless you have a specific issue or have a specific request relevant to grub4dos, please close this issue and ask in a suitable forum such as reboot.pro.

**Comment by suFDHAI78fyw78q09Y98yfd** [comment]
I now have all the info I need this looks like it will be the solution. Now I have all the UUIDs of all bootable drives from windows secinspect tools and your scripts. I can make easily a simple menu to be able to boot those drives.

Each USB device now has a sticker with written on it what it contains. With USB inserted easy then to select from the menu to boot that drive or any drive that is on the menu list.

Boot USB Drive A
uuid 000E0336000C1B8D && chainloader +1

Boot USB Drive B
uuid 0E000633C000D81B && chainloader +1


I like also the tag examples for multi bootable drives. Not done that yet but neither scared to now knowing I can boot those also using tags.  will look for making tags when I set up a multiple boot drive, now that drives are starting to become larger.

Thank You for al your help and this has been a major help boot any USB or device anywhere using its UUID. Thanks for the links if have any other question for this I will go their. Hope this also becomes useful for others needing simple UUID use with Grub4Dos. It has everything anyone could need even a tool and scripts to get the UUID in windows.

Command Prompt  >CD folder where secinspect and the script.cmd files are located. Type the script.cmd you need or drag and drop it to command prompt. Add the drive you need UUID for such as C:
You may need to run the same script.cmd twice to get a UUID result for the first time. After that the script.cmd will show you the UUID of drive chosen each time. I did this without system environment variable but that wouldn't hurt if need secinspect global.

Grub4Dos has just become very easy to configure with UUID will never able to lose the drive, unable to boot. When the bootable drive has been moved USB and Grub4Dos now sees a non bootable drive instead. Using UUID overcome this to target and boot always the correct drive each time using each drives own unique UUID. 


Thanks.
