### ISSUE TITLE
Hungarian keyboard not fully supported by setkey command

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#193]
https://en.wikipedia.org/wiki/QWERTZ#Hungary

Some characters on the QWERTZ Hungarian keyboard are obtained using Alt key + a letter key

e.g. Alt+v = @    (key code = 02f00 for Alt+v and AltGr+v)

![image](https://user-images.githubusercontent.com/1469350/56991720-49da0b80-6b90-11e9-97d8-3cb52cc9b487.png)
How can this be translated using setkey command?
[ ] < > # @ { } ; and * | \ are all  Alt+ codes 

Can you extend table for Alt codes for A-Z plus 0-9 ,./-=;#'[] please?

**Comment by steve6375** [comment]
Also
Key 56   (OEM102)
http://kbdlayout.info/KBDHU/scancodes
![image](https://user-images.githubusercontent.com/1469350/57019164-94559980-6c1d-11e9-9cf0-027636a57f5e.png)

is extra key. On UK kbd it produces
shift+#56 =  |  (0x567c)  
unshift #56 =  \  (0x565c)  under grub4dos
which is correct.

can you also **add 0x567c and 0x565c to table in setkey** please so we can make it produce < for Hungarian keyboard (alt+key#56 = 0000 so we cannot use that).

**Comment by steve6375** [comment]
adding support for AltGR would also help other keyboard  languages,
e.g. German keyboard - @ = AltGr+Q
http://kbdlayout.info/00000407/shiftstates+scancodes/VK_CONTROL+VK_MENU

**Comment by steve6375** [comment]
[builtins.zip](https://github.com/chenall/grub4dos/files/3145378/builtins.zip)
Modified builtins.c

Added Aa-Az and A0-A9 for Alt keys plus added oem102 and shiftoem102.
Also changed help text as was incorrect and incomplete (control and capslock are not supported, resetting a single key was not mentioned), etc.

OK to include in next build?

**Comment by steve6375** [comment]
Improved help text
```
  "setkey [NEW_KEY USA_KEY]",
  "Map default key USA_KEY to NEW_KEY."
  " Key names: 0-9, A-Z, a-z or escape, exclam, at, numbersign, dollar,"
  " percent, caret, ampersand, asterisk, parenleft, parenright, minus,"
  " underscore, equal, plus, backspace, tab, bracketleft, braceleft,"
  " bracketright, braceright, enter, semicolon, colon, quote, doublequote,"
  " backquote, tilde, shift, backslash, bar, comma, less, period,"
  " greater, slash, question, alt, space, delete, oem102, shiftoem102,"
  " [ctrl|shift]F1-10. Use A for Alt+(a-z)(0-9), e.g. 'setkey at Av'."
  " Reset: 'setkey USA_KEY USA_KEY' for one key, 'setkey' to reset all."
```

**Comment by steve6375** [comment]
[KBD_QWERTZ_HUN.zip](https://github.com/chenall/grub4dos/files/3145933/KBD_QWERTZ_HUN.zip)
This now works for Hungarian keyboard with new builtins.c code.
All standard characters can be generated.

**Comment by steve6375** [comment]
Sorry, for Latin American please add these 2 codes to the setkey table

```
  {"Aminus",		0x8200},
  {"Aequal",		0x8300},
```
see http://stanislavs.org/helppc/scan_codes.html

P.S.
these 4 keys are not detected in grub4dos so there is no point in adding them
but it would be useful if you could find out why they are not detected and add them?
  {"Abracketleft",	0x1A00},
  {"Abracketright",	0x1B00},
  {"Asemicolon",	0x2700},
  {"Abackslash",	0x2600}, #same as Alt+l

**Comment by yaya2007** [comment]
It's not grub4dos,That's bios.

**Comment by steve6375** [comment]
OK, can you just add Aminus and Aequal please?

**Comment by steve6375** [comment]
Ah - it is a Virtual Box problem! All six work if booted on a real system.
Please can you add all six table entries into the next version of grub4dos.
The help text will also need updating.

**Comment by yaya2007** [comment]
-  " greater, slash, question, alt, space, delete, oem102, shiftoem102"
+  " greater, slash, question, alt, space, delete, oem102, shiftoem102,"
+  " Aminus, Aequal, Abracketleft, Abracketright, Asemicolon, Abackslash,"

show keyboard code:
echo -k

Why can't you upload grlgr.rar.txt?

**Comment by steve6375** [comment]
[builtins.zip](https://github.com/chenall/grub4dos/files/3162133/builtins.zip)

**Comment by yaya2007** [comment]
[grldr.rar.zip](https://github.com/chenall/grub4dos/files/3164486/grldr.rar.zip)

**Comment by steve6375** [comment]
Please wait for final version before releasing a new version. A key is not working for some reason!

**Comment by steve6375** [comment]
Very sorry for all the trouble. VBox was returning missing BIOS key scan codes, also the link I had for BIOS codes was wrong! It turns out that on a real system, we can have all the keys (except for oem102) with Alt+ codes. I have modified the table and help text in builtins.c and compiled a new grldr and tested it on a real system
[builtins.zip](https://github.com/chenall/grub4dos/files/3166856/builtins.zip)

**Comment by yaya2007** [comment]
Can I submit it it?

**Comment by steve6375** [comment]
yes please submit, but builtins.c **setkey code only** - it does not include any changes for memory that you made in 2019-05-07 version

**Comment by steve6375** [comment]
All OK so far! Thanks.
why need for  echo -k  ?   I use  pause --test-key to print key code?

**Comment by yaya2007** [comment]
I didn't notice. Next cancellation.

**Comment by steve6375** [comment]
No problems reported so closing. Thanks!
