### ISSUE TITLE
20190507 fails to boot to Acronis TrueImage 2016 ISO

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#195]
See http://www.easy2boot.com/forum/   post 04/06/2019
Acronis TrueImage 2016 ISO (one specific version MD5 Checksum: 2BB62B3B2215CDF000D062C50CD2E40C) - other versions of TI 2016 work OK,
Fails to boot under QEMU 32-bit emulator or real systems if grldr 20190507 or 20190512 is used.
Boots OK with grldr 20190325 and previous versions.
Hangs at "Starting Acronis Loader" message.

I do not have the same ISO and cannot reproduce, but maybe you can check changes in 20190507 to see if something may have changed?

**Comment by steve6375** [comment]
I now have the ISO file and I can reproduce the problem under Vbox too.
![image](https://user-images.githubusercontent.com/1469350/58981681-bd43ee00-87ca-11e9-85b8-ad13c90545ac.png)
I have about 6 different versions of Acronis TrueImage 2016 and only this one specific version fails.
It works OK on 20190325 grldr

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/58982295-07799f00-87cc-11e9-8269-c5c836c8e12f.png)

both old and new versions give identical numbers after chainloader, but newer versions hang.

**Comment by yaya2007** [comment]
"only this one specific version fails"
Can you provide it?  (test.iso)
Simplified, as long as the problem is repeated.

**Comment by steve6375** [comment]
ISO is 1.1GB and I cannot edit it because all the tools I have tried prevent it from booting after re-saving it,

**Comment by steve6375** [comment]
485MB
http://www.1u.cz/2015/05/18/acronis-true-image-2015-cz-iso-download/
This version also shows the same problem.
Hangs with latest versions of grldr.

**Comment by yaya2007** [comment]
Locate the segment settings in variables.
Thank you for your detailed information.

**Comment by steve6375** [comment]
No adverse reports, so closing, thanks.
