### ISSUE TITLE
splashimage --fill-color corruption using QEMU

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#196]
OK on real system or VBox.

But corruption (lines, etc.) when using QEMU under Windows

menu.lst
```
graphicsmode -1 800
splashimage --fill-color=0xFFFFFF

title commandline
commandline
root ()

title junk
reboot
```

The corruption only appears if -vga std is NOT specified

Std VGA = OK
No Std VGA = corruption

bmp and jpgs etc. are all OK - only fill-color seems to be affected ?????

![image](https://user-images.githubusercontent.com/1469350/58980717-e2376180-87c8-11e9-90af-bf7fe5ed5e15.png)

No Std VGA...
![image](https://user-images.githubusercontent.com/1469350/58980257-ce3f3000-87c7-11e9-8610-56f8173bbafb.png)

**Comment by steve6375** [comment]
-vga std uses the vgabios-stdvga.bin file
if not specified it uses the vgabios-cirrus.bin file

**Comment by yaya2007** [comment]
"splashimage --fill-color=0xFFFFFF"
It should work in VBE mode.
graphicsmode  should be pre-set.

update:
Judge display mode, not VGA mode, exit.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3259623/grldr.rar.txt)

**Comment by steve6375** [comment]
Same issue.
The menu has
graphicsmode -1 800
splashimage --fill-color=0xFFFFFF

so it is in 800x600 24-colour mode
and the fill-color command still causes corruption
The problem is that QEMU is using the Cirrus VGA BIOS. Whatever code you use for the fill does not work for systems which have Cirrus Logic VGA BIOSes.

Please try simple menu and QEMUBootTester.exe (or RMPrepUSB - QEMU) and you will see.

**Comment by yaya2007** [comment]
Please provide QEMUBootTester.exe (or RMPrepUSB-QEMU)

**Comment by steve6375** [comment]
RMPrepusb is on www.rmprepusb.com and www.easy2boot.com.

**Comment by steve6375** [comment]
http://files.easy2boot.com/200003548-9492b9590f/Install_RMPrepUSB_Full_v2.1.742.exe.zip

**Comment by yaya2007** [comment]
Locate at current_bits_per_pixel. 
Thank you for your detailed information.

**Comment by steve6375** [comment]
Also problem when using blue on black - it makes green background and green normal menu text.

```
graphicsmode -1 800
splashimage --fill-color=0x000000
color normal=blue/black

title test
root ()
title test
root ()
title test
root ()
```



![image](https://user-images.githubusercontent.com/1469350/59159420-4e63df00-8ac1-11e9-89dc-82f3fdcea305.png)

**Comment by steve6375** [comment]
Also, text is wrong colour

```
graphicsmode -1 800
splashimage --fill-color=0x000001
color normal=blue/black

title test
root ()
title test
root ()
title test
root ()
```

menu text is green and not blue!

**Comment by steve6375** [comment]
This works better...
`color normal=0x0001FF`
but non-menu areas are still green
![image](https://user-images.githubusercontent.com/1469350/59161304-08b31080-8ad9-11e9-93fb-beeb49de64d5.png)

**Comment by steve6375** [comment]
The problem seems to be due to using blue as the 'normal' text colour on a black background???
Even without splashimage --fill-color it shows green!

```
graphicsmode -1 800
color normal=0x01	

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()
```
![image](https://user-images.githubusercontent.com/1469350/59162359-8716af00-8ae7-11e9-837e-acd3be08de5a.png)


```
graphicsmode -1 800
color normal=0x1FF	

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()
```
![image](https://user-images.githubusercontent.com/1469350/59162409-c98cbb80-8ae8-11e9-85a7-daae3f3578fb.png)




Here is menu with red on black which is OK
```

graphicsmode -1 800
color red/black green/black

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()

title test
root ()

title E2B
root ()
```

![image](https://user-images.githubusercontent.com/1469350/59162448-3c963200-8ae9-11e9-83be-9086b8ca45f3.png)




Here is same menu but blue on black - BAD

```

graphicsmode -1 800
color blue/black green/black

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()

title test
root ()

title E2B
root ()
```
![image](https://user-images.githubusercontent.com/1469350/59162457-68b1b300-8ae9-11e9-88cd-fcbb7bb449a9.png)

**Comment by yaya2007** [comment]
Use 64 bits for color 
color normal=0x1FF (Cannot use 0xff)
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3271348/grldr.rar.txt)

color normal=0x00FF0000000000FF

**Comment by steve6375** [comment]
Still fails.


```
graphicsmode -1 800
color normal=blue/black highlight=blue/dark-gray

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()

title test
root ()

title E2B
root ()
```

![image](https://user-images.githubusercontent.com/1469350/59185188-b836c400-8b67-11e9-9c27-953534e7bd78.png)

**Comment by steve6375** [comment]
This gives green background around menu area

```
graphicsmode -1 800
color normal=blue/black highlight=blue/dark-gray
color normal=0x1FF

title test reboot
chainloader /grldr
boot

title test
root ()

title test
root ()

title test
root ()

title E2B
root ()
```

![image](https://user-images.githubusercontent.com/1469350/59185821-4eb7b500-8b69-11e9-87f8-3f1d2e7044d0.png)

**Comment by yaya2007** [comment]
error:  Conversion from 8-bit color to 64-bit color .
Now, support 15 bits per pixel (5:5:5)
Have a try .
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3275633/grldr.rar.txt)

**Comment by steve6375** [comment]
Hi
Seems to work OK :-) thanks.
What do you mean 5 bits?  Does this allow more colors?? Does it affect what range we can use?
e.g. 0x1f ???
or is this just an internal change?

**Comment by yaya2007** [comment]
Direct color support 15/16/24/32 bits per pixel .
Viewing Screen Support Mode with "vbeprobe".
e.g. 0x113  800 * 600 * 15  5:5:5:1
       0x114  800 * 600 * 16  5:6:5:0
       0x115  800 * 600 * 24  8:8:8:0
       0x143  800 * 600 * 32  8:8:8:8  (RMPrepUSB does not)

e.g.  graphicsmode 0x113  (Set up )
       graphicsmode  (See)
It doesn't mean much. Add an option.

**Comment by steve6375** [comment]
Thanks.
