### ISSUE TITLE
Enhancement: Add command to slow down CPU

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#198]
Some DOS programs and games run too fast on modern CPUs.
It would be useful to be able to slow down the CPU (perhaps by turning off level 1 and level 2 cache) before booting to DOS. Is it possible to add a command into grub4dos?

e.g.
cpu [ --cache-off | --l1-off | --l2-off | --cache-on | -- l1-on | --l2-on]

where cache-off is the same as --l1-off and  --l2-off.

Maybe also add l3 but probably just disabling L3 will have little affect on DOS.

DOS slowdown tweakers such as setmul are available but these require extra drivers in config.sys, etc. and so the DOS must be modified to be able to use them and it often interferes with the memory map/free memory required for the app. or game.

https://stackoverflow.com/questions/48360238/how-can-the-l1-l2-l3-cpu-caches-be-turned-off-on-modern-x86-amd64-chips

**Comment by yaya2007** [comment]
According to the information you provide, it seems that the cache can be closed (opened), but it can not be accurate to l1, l2.

**Comment by steve6375** [comment]
setmul can (seemingly) disable or enable L1 and L2 individually. I have tried to contact the author as the information seems hard to find.

**Comment by steve6375** [comment]
Reply from setmul developer
```

> There are various reasons to not integrate SetMul in Grub4DOS
> - Highly platform specific and sometimes experimental.
> - There is no indication of what speed one will get, from the software's point of view.
> - Only vintage processors are supported. 
Already the pentium II lacks any features for slowdown. 
Later there is intel Speedstep, falcosoft has a tool for that.
problem is that it again is experimental and not nearly as effective as we would like. 
> Experimental means that can crash on certain hardware configs, among other issues.
> 
> The one thing that seems like a straightforward slowdown is L1 cache disable, 
which is standard since 486, and also very simple and quite effective. 
Snippets of the code I use for that are below.
> 
> Regards,
> Gerwin
> 
> 
> Disabling L1 Cache:
> ring0_CR0_set_address( 0x60000000, &ax, &dx,0); // set bit 30 to disable L1 Cache
> 
> Enabling L1 Cache:
> ring0_CR0_unset_address( 0x9FFFFFFF, &ax, &dx,0); 
> 
> void CR0_set(void)
> {
> asm __volatile__ (
> "CR0_set_label:\n"
> "movl %cr0,%eax\n" // get current CR0 reg
> "movl %eax,(%ebx)\n" // store original CR0 reg for output
> "or %ecx, %eax\n" // use ecx input as 'OR' mask
> "movl %eax,%cr0\n" // set CR0 reg
> "movl %eax,(%edi)\n" // store changed CR0 reg for output
> "wbinvd\n" // invalidate current cache
> "lret\n"
> );
> }
> 

```

**Comment by yaya2007** [comment]
As mentioned earlier, not only control L1, but also control the whole cache.

**Comment by steve6375** [comment]
OK, maybe add just a disable cache command? I can make a few tests if you can add it in a test version...

**Comment by yaya2007** [comment]
--cache-off  ok.
Start dos, load umbpci. sys, restart. 
Start dos, load emm386.exe, successful. 

--cache-on restart.

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3386278/grldr.rar.txt)

**Comment by steve6375** [comment]
Under VBOX - hotkeys no longer work (menu displays e.g.  ^Ctrl+D)
Under VBOX both CPU commands in console cause a hang.
Same on real system,
Is this correct file?

**Comment by yaya2007** [comment]
Things of little significance. I decided to give up. 
Without cache, the CPU accesses the memory directly. The speed does not match and there are many problems.

**Comment by steve6375** [comment]
OK - thanks for trying anyway!
