### ISSUE TITLE
Can't download binaries from dl.grub4dos.chenall.net

### ISSUE THREAD

**Issue by pbatard** [chenall/grub4dos#199]
I have tried multiple times over the last week, but it appears it is impossible from people in Europe and the US to download the http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2019-06-17.7z binaries linked from http://grub4dos.chenall.net/downloads/grub4dos-0.4.6a-2019-06-17/.

Tried 4 different browsers on 3 different computers or servers located at completely different physical locations (EU and US) and, every time, I got a 403, so I am pretty sure the problem is __not__ a user problem. e.g.:
```
$ wget http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2019-06-17.7z
--2019-07-11 16:06:16--  http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2019-06-17.7z
Resolving dl.grub4dos.chenall.net (dl.grub4dos.chenall.net)... 116.211.92.253, 116.211.92.252, 116.211.92.243, ...
Connecting to dl.grub4dos.chenall.net (dl.grub4dos.chenall.net)|116.211.92.253|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-11 16:06:18 ERROR 403: Forbidden.
```

May I suggest to use GitHub releases [as I currently do for Rufus for instance](https://github.com/pbatard/rufus/releases)? IMO, it's a lot more convenient and reliable than any custom download solution one might come up with, and it does make sense to have the releases made available on the GitHub project itself.

**Comment by yaya2007** [comment]
This is created and maintained by chenall.  Unable to contact chenall. 
I won't set it up or change it. 

After uploading patches, the system compiles and publishes automatically. 
Can you do the same? 
It also guarantees that previously released versions can also be downloaded.

**Comment by pbatard** [comment]
> This is created and maintained by chenall. Unable to contact chenall.

I logically thought since this GitHub repository was under the `chenall` name that the person maintaining this repository would have full control of both http://grub4dos.chenall.net and http://dl.grub4dos.chenall.net. If you don't, then I would really urge you to move your downloads somewhere else.

> After uploading patches, the system compiles and publishes automatically.
Can you do the same?

Sure. AppVeyor for one thing makes it fairly easy to automate the builds and then automatically publish them under GitHub Releases. For instance I recently did something like that to build and push an Arm Trusted Firmware for the Raspberry Pi 3. See https://github.com/pbatard/pitf/blob/master/appveyor.yml which automatically uploads built binaries to the [releases](https://github.com/pbatard/pitf/releases) (NB: Since we're using untouched release code from the official Arm Trusted Firmware repo, we don't actually clone the source from our repo, but instead download a release `.tgz`, but you'll find plenty of help on how to use AppVeyor to clone and build from your repo source, and, say, do it only on tagged releases).

> It also guarantees that previously released versions can also be downloaded.

And you can upload all previous binaries to GitHub releases too. I would know, since I had to manually upload all my previous Rufus releases there after I dropped the custom download server I used.

All in all, I really don't see anything in your workflow that should prevent the use of GitHub Releases (though it may of course require a bit of work to set everything up). On the contrary, I see quite a few advantages of doing so, including restoring the ability for people to download official binaries, which may be important when you are dealing with boot loaders, as well as validate precisely how the binaries were built... 

As a matter of fact, the reason I am reporting this is that, since I am including Grub4DOS downloads for Rufus, I want people to make sure that the binaries that get installed can be compared with the official ones, in case they have doubts, which is why I'd rather avoid compiling my own version of `grldr` when the official one will do.

**Comment by a1ive** [comment]
Users in China may have problem when downloading GitHub Releases.
It's too slow and s3.amazonaws.com are blocked in some province like Sinkiang.

**Comment by pbatard** [comment]
Then I guess Grub4DOS has to decide if it wants to be a Chinese project or a worldwide project.

I can assure you that, for anybody else in the world but in China, GitHub and Amazon Web Services __are__ superfast and, because the latter is pretty much serving a good chunk of the web, they are also unlikely to be censored, as opposed to any other solution you may come up with.

With China is censoring access to some servers, then, logically, the last thing you'll want is to upload Grub4DOS releases to a small server that can be easily swatted off the internet without much of anybody noticing (because clearly if Amazon Web Services is being censored as a whole in some regions of China, then no matter how remote you think you may be of attracting Chinese censorship, __no__ single host can be declared safe). In fact, I will venture that chances are that people will be more prone to devise and share means of circumventing censorship when it applies to the largest host of the internet, which may eventually leave Chinese users with the ability to access Grub4DOS content, whereas the same may not be true when a server like dl.grub4dos.chenall.net that (I would surmise) is hosted in mainland China is taken down.

At any rate, as long as Grub4DOS doesn't start to consider itself a project that is aimed mainly at Chinese people, then the Chinese censorship or slow access of GitHub and Amazon Web Services must be seen for what it is: a __minority__ issue. As a project maintainer myself, I will therefore stress out that you may want to be very careful about placing the needs of the minority over the ones of the majority, when doing so will have a negative impact on said majority (for instance, you may want to be aware that, even when accessible, grub4dos.chenall.net is quite slow for people not located in China, so moving the downloads away from there would be seen as a good thing for everyone else).

Now, that doesn't mean that you shouldn't try to look for a solution that can satisfy both minority and majority (in this case, Chinese people and the rest of the world). However, considering that we are talking about Chinese censorship here, I really don't see how you will be able to __guarantee__ that whatever server you pick is not going to end up on the new censorship black list for one reason or another and become inaccessible yet again. Therefore, I really do think that moving the releases to servers that, on the other hand, are pretty much __guaranteed__ to always be fast and accessible for the rest of the world, regardless of what the Chinese government does, is something Grub4DOS should look into. A project should try to satisfy the majority of its users first, and then its minorities. Not the other way round.

**Comment by yaya2007** [comment]
Cheall has been repaired.

**Comment by pbatard** [comment]
Works again, thanks!

And I see that you are also looking [73cd117dedc219815faa9f83b4904da4f6f00c86] into automating uploads of the Travis binaries to GitHub releases, which is great. From having done that a couple of times with AppVeyor, I know that it can be a bit tricky and frustrating to set up properly (I never seem to get it quite right on the first try either), but once it's set up, it's very nice.

Since the binaries can be downloaded again, I will close this issue. Thanks for looking into it.
