### ISSUE TITLE
Grub4dos and big-disk GPT support

### ISSUE THREAD

**Issue by suntong** [chenall/grub4dos#200]
How to install Grub4dos to the MBR or a GPT disk? 

- In `docs/README_GRUB4DOS.txt` there is only one line mentioning GPT:
> --gpt  Install the grldr.mbr to the GPT partition type device.
- In the undated doc at https://www.lightofdawn.org/wiki/wiki.cgi/BIOSBootGPT it says, _"Grub4Dos - which is a long-running fork of Grub Legacy, doesn't support it yet at the time of writing."_
- In http://reboot.pro/topic/21905-grub4dos-and-gpt-support/ there is a lengthy discussion of the issue, in which the _"test the bootlace.com --gpt command (using bootlace.com from GRUB4DOS 0.4.6a 2018-09-19)"_ doesn't seem to be successful. The discussion is so long that I stopped reading half way at the first of all three pages, and decided to ask here. 

Thus - how to install Grub4dos to the MBR of a GPT disk, with `grub4dos-0.4.6a-2019-07-16`, if my GPT disk is `/dev/sdd`?

```sh
$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$ uname -rm
4.15.0-54-generic x86_64

```

Thanks

**Comment by yaya2007** [comment]
BIOS is supported, but UEFI is not supported. 
When formatting, select: 
1. Using BOOTICE 
"Align partitions by integer multiple of this sector number"  >=32
2. Using DiskGenius
"Align an integer multiple of the number of partitions to this sector " >=32
3. Other
Reason by analogy.
That is to say, the first partition >= LBA(32)
 
bootlace.com --gpt /dev/sdd

**Comment by suntong** [comment]
Thanks a lot @yaya2007, 

That indeed is `/dev/sdd` (MBR), instead of `/dev/sddx` (PBR), right? 
Would you elaborate a bit more please? -- As I've also read that, 

- GPT disk LBA Sector 0 containing the protective MBR; while Sector 1 containing the disk GPT
- grub4dos grldr.mbr code (which is what is installed to the MBR AND to following sectors) is several sectors long and it simply won't fit without overwriting VITAL data of the GPT disk.

So how `bootlace.com --gpt /dev/sdd` is possible, giving above restrains? Only high level elaboration in a sentence or two is good enough for me. Thanks!

**Comment by yaya2007** [comment]
1. That indeed is /dev/sdd (MBR).
2. grldr.mbr code length 16 sectors.
3. grldr.mbr code  is installed after the LBA(34) sector and before the first partition.

**Comment by suntong** [comment]
Thanks a lot @yaya2007!

**Comment by suntong** [comment]
Ops, closed too soon.... 

So I gave it a try just now, and this is what I'm getting:

```
$ bootlace64.com --gpt /dev/sdd


Error: Specified gpt partition not exist.

BOOTLACE writes GRLDR BOOT RECORD to MBR or to the boot area of a file system.
Usage:  bootlace.com  [OPTIONS]  DEVICE_OR_FILE
Options: --read-only, --floppy[=N], --boot-prevmbr-first, --boot-prevmbr-last,
--no-backup-mbr, --force-backup-mbr, --mbr-enable-floppy, --mbr-disable-floppy,
--mbr-enable-osbr, --mbr-disable-osbr, --duce, --time-out=T, --hot-key=K, 
--preferred-drive=D, --preferred-partition=P, --sectors-per-track=S, --heads=H,
--start-sector=B, --total-sectors=C, --install-partition=I, --serial-number=SN,
--restore-mbr, --mbr-no-bpb, --chs-no-tune, --gpt
DEVICE_OR_FILE: Filename of the device or image. For DOS, a BIOS drive number
(in hex 0xHH or decimal DDD format)can be used to access the drive.
```

The way I created/partitioned this disk is documented at 
https://suntong.github.io/blogs/2015/12/26/creating-gpt-partitions-easily-on-the-command-line/#solution

Any remedy? Thx

**Comment by yaya2007** [comment]
Please send the contents of disk LBA (0) - LBA (80).

**Comment by suntong** [comment]
`dd if=/dev/sdd of=/tmp/sdd80.img bs=4096 count=128`

[sdd80.zip](https://github.com/chenall/grub4dos/files/3429326/sdd80.zip)

**Comment by yaya2007** [comment]
This disk is 4096 bytes per sector? Usually 512 bytes.

**Comment by yaya2007** [comment]
This disk is 4096 bytes per sector? Usually 512 bytes.

**Comment by suntong** [comment]
I think so, because this is what I got:

```
$ fdisk -l /dev/sdd
Disk /dev/sdd: 2.7 TiB, 3000558944256 bytes, 732558336 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: AF4AD361-07A7-4E6D-AF69-1D5B75077198

Device         Start       End   Sectors   Size Type
/dev/sdd1        256     51455     51200   200M BIOS boot
/dev/sdd2      51456   5294335   5242880    20G Linux filesystem
/dev/sdd3    5294336  13158655   7864320    30G Microsoft basic data
/dev/sdd4   13158656  16304383   3145728    12G Linux filesystem
/dev/sdd5   16304384  19450111   3145728    12G Linux filesystem
/dev/sdd6   19450112  21547263   2097152     8G Linux filesystem
/dev/sdd7   21547264  23644415   2097152     8G Linux filesystem
. . . 

$ sgdisk -p /dev/sdd
Disk /dev/sdd: 732558336 sectors, 2.7 TiB
Model: My Book 1230    
Sector size (logical/physical): 4096/4096 bytes
Disk identifier (GUID): AF4AD361-07A7-4E6D-AF69-1D5B75077198
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 5
First usable sector is 6, last usable sector is 732558330
Partitions will be aligned on 256-sector boundaries
Total free space is 250 sectors (1000.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1             256           51455   200.0 MiB   EF02  Boot
   2           51456         5294335   20.0 GiB    8300  Live
   3         5294336        13158655   30.0 GiB    0700  Win
   4        13158656        16304383   12.0 GiB    8300  os1
. . . 
```

**Comment by suntong** [comment]
512 bytes per sector might not be good enough for large disks that > 2TB I suppose.

**Comment by yaya2007** [comment]
In this way, the compatibility is quite poor!

**Comment by suntong** [comment]
> 这样的话，兼容性会很差

But, the only reason I use GPT is for large disks that > 2TB. Else I'd use MBR. 

Do you have > 2TB  large disks that has 512 bytes per sector? Just curious.

**Comment by suntong** [comment]
Maybe add an extra flag `--big-disk` for > 2TB large disks that has 4096 bytes per sector?

**Comment by yaya2007** [comment]
Bytes per sector has nothing to do with disk size.
Grub4dos does not currently support native 4K disks.

**Comment by suntong** [comment]
Disk size is closely related to bytes per sector, due to the size limitation of the 32-bit size of capacity field in the partition table. This is

    (2^32)-1 x 512 byte = 2 TB.

Any disk > 2TB in size needs 4096 bytes per sector.

Leaving this open and hope that Grub4dos can support native 4K disks someday...

**Comment by yaya2007** [comment]
The capacity field in GPT partition table is 64 bits!!!

**Comment by steve6375** [comment]
AFAIK Legacy BIOSes cannot boot from 4K sector disks so there is no point trying to install grub4dos to a 4K sector disk. The BIOS (int 13h) calls only support 512-byte sector hard disks.

**Comment by suntong** [comment]
Got it. Thanks for explanation.
