### ISSUE TITLE
hotkeys not working with 2019-07-16

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#202]
![image](https://user-images.githubusercontent.com/1469350/61713130-c32c6900-ad4f-11e9-9ba7-eef7f4b32ae3.png)

2019-06 was OK

**Comment by yaya2007** [comment]
Please test 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3429310/grldr.rar.txt)

**Comment by steve6375** [comment]
Seems good 👍

**Comment by steve6375** [comment]
thanks.
