### ISSUE TITLE
bootlace Error: No boot signature(55 AA)

### ISSUE THREAD

**Issue by suntong** [chenall/grub4dos#203]
BOOTLACE writes GRLDR boot record to PBR as well as MBR, right?

This is what I get:

```
% bootlace64.com /dev/sdd2

Error: No boot signature(55 AA). Must specify --floppy explicitly for floppy.
```

This is a freshly initialized disk. I.e., the PBR is all zero. 

IMO, since bootlace is overwriting PBR boot record, it should be allowed to write to the PBR which is in whatever stage. Is there a flag that allows/enables this? 

Thanks

**Comment by steve6375** [comment]
If the first sector of the partition is all 0's then it is NOT a PBR!
A PBR is only valid if it has a 55 AA signature at the end of the 512-byte sector and contains various partition values inside. You have to format the volume first before you can install grub4dos.

**Comment by suntong** [comment]
Gotya!

**Comment by suntong** [comment]
`extlinux --install` get `extlinux` installed without a hiss though.
