### ISSUE TITLE
Cannot download 2019-07-26

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#204]
The download on page http://grub4dos.chenall.net/downloads/grub4dos-0.4.6a-2019-07-26/

http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2019-07-26.7z

just gives
{"error":"Document not found"}

**Comment by yaya2007** [comment]
In the previous period, chenall was repaired once. At that time, it was observed that the repair was successful. 

The current situation:
1. Http://grub4dos.chenall.net/website download is still abnormal. 
To be exact, it's http://dl.grub4dos.chenall.net/abnormal. 
2. Http://b.chenall.net/grldr can be downloaded, but it is an old version.
3. Https://github.com/chenall/grub4dos/releases can  be downloaded  a new version.
