### ISSUE TITLE
bootlace installing to PBR

### ISSUE THREAD

**Issue by suntong** [chenall/grub4dos#205]
BOOTLACE _can_ write GRLDR boot record **to PBR** as well as MBR, right?

However, this is what I got:

```
% bootlace64.com /dev/sdd2
Error: Invalid partition table. Must specify --floppy explicitly for floppy.
```

The PBR is just initialized with `extlinux`:

```
% extlinux --install /mnt/Live/boot/extlinux
/mnt/Live/boot/extlinux is device /dev/sdd2
```

and here is its content:

[sdd2.zip](https://github.com/chenall/grub4dos/files/3438216/sdd2.zip)

thanks

**Comment by yaya2007** [comment]
What file system is extlinux? 
Currently only partitions with filesystem type of FAT12, FAT16, FAT32, NTFS,EXT2，EXT3， EXT4 or EXFAT are supported.

**Comment by suntong** [comment]
extlinux is for EXT2，EXT3 & EXT4.

**Comment by yaya2007** [comment]
The BPb tables of EXT2, EXT3 and EXT4 are at 0x400. 
Pass up the first four sectors of the partition.

Install to disk:
bootlace64.com --floppy /dev/sdd2

Install to file:
bootlace64.com --floppy sdd2-1.img

**Comment by suntong** [comment]
Thanks. 

So I can simply use `--floppy` instead of `--floppy=N` for partitions on hard drive now? 

`bootlace` now can figure out `N` by itself, which is used to specify   the partition number: 0,1,2 and 3 for the   primary partitions, and 4,5,6,... for the logical partitions, right?

**Comment by yaya2007** [comment]
sdd2   2->Designated partition

**Comment by suntong** [comment]
Thanks @yaya2007
