### ISSUE TITLE
color command causes flashing in new version grldr 2017-07

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#206]
```
title TEST
graphicsmode 3
color standard red/white
clear
pause Press ENTER to continue...
chainloader /_ISO/e2b/grub/grldr_046
boot
```

Older versions OK
![image](https://user-images.githubusercontent.com/1469350/62004437-07878280-b11d-11e9-949f-1d2da5d515b7.png)

Latest version - flashing text on screen and grey background (tested in VBox)
![image](https://user-images.githubusercontent.com/1469350/62004446-2ab23200-b11d-11e9-9a6b-a79aca45ae85.png)

Maybe new compiled versions have changed a lot of internal variable positions?

**Comment by yaya2007** [comment]
The grub4dos-0.4.6a-2019-07-26 version has been revised. You can try it.

**Comment by yaya2007** [comment]
The grub4dos-0.4.6a-2019-07-16 version, tested in QEMU, normal.

**Comment by steve6375** [comment]
2019-06-17  fail - up to 2019-07-26
2019-06-13  fail
2019-06-09   OK
2019-05-12  OK
2019-09-19  OK

**Comment by steve6375** [comment]
To repro
Make an E2B USB flash drive
change \grldr to new version
add \\_ISO\MAINMENU\TEST.mnu file ...

```
title TEST
graphicsmode 3
color standard red/white
clear
pause Press ENTER to continue...
chainloader /_ISO/e2b/grub/grldr_046
boot
```
[TEST.zip](https://github.com/chenall/grub4dos/files/3440644/TEST.zip)



When first run will get problem - then will load old grldr - then run again - will be OK

**Comment by steve6375** [comment]
QEMU does not show problem - QEMU does not support blinking.
Use real system or VBox.

**Comment by steve6375** [comment]
2019-07-30 has same problem.  :-(

**Comment by steve6375** [comment]
Here is simple test menu

```
title TEST 1 - OK
graphicsmode 3
color standard red/white
clear
pause Press ENTER to continue...
errorcheck off
boot

title TEST 2 - ERROR
graphicsmode -1 800
graphicsmode 3
color standard red/white
clear
pause Press ENTER to continue...
errorcheck off
boot

```

**Comment by yaya2007** [comment]
Please test 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3450525/grldr.rar.txt)

**Comment by steve6375** [comment]
Looks good :-)
