### ISSUE TITLE
setmenu date&time

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#207]
This is nice feature but it cannot be removed easily except to use setmenu --string which removes all strings. Can we have  "-date&time" to remove so does not appear on all menus?
Also format may not be convenient. User may want US format or UK format or just time?
Maybe allow user to specify? e.g.
"date&time:dd-mm-yy hh:mm:ss"       e.g.  01-07-2019 10:02:21
"date&time:mm-dd-yy hh:mm:ss"
"date&time:hh:mm:ss"
"date&time:hh:mm"

**Comment by steve6375** [comment]
To simplify, maybe just support two more options?
"date&time:dd-mm"     e.g. 01-07-2019 10:02:21
"date&time:mm-dd"     e.g. 07-01-2019 10:02:21

**Comment by yaya2007** [comment]
1. No parameters specified, ISO8601 standard date format. 
setmenu --string=x=y=color="date&time"

2. Specified parameters 
setmenu --string=x=y=color="date&time=dd-MMM-yyyy  hh:mm:ss"
year        yyyy
month    MM, MMM
day         dd
hour        hh
minute    mm
second    ss
Variable position of year, month and day 
Separator variable 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3460471/grldr.rar.txt)

**Comment by steve6375** [comment]
small bug?
![image](https://user-images.githubusercontent.com/1469350/62359766-5fecc480-b50f-11e9-975f-943c1c1311cf.png)
![image](https://user-images.githubusercontent.com/1469350/62359816-7abf3900-b50f-11e9-90c9-2cb2d9887471.png)

Also how to remove date&time string without removing other strings?

**Comment by steve6375** [comment]
Suggested help text...
When STRING is date&time will update ISO8601 date format every second. Can use "date&time=FORMAT" where FORMAT can be any of dd MM MMM yyyy hh mm ss with separators, e.g. "date&time=[dd-MMM-yyyy    hh:mm:ss]".

**Comment by yaya2007** [comment]
HH?

**Comment by steve6375** [comment]
yes HH works!

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/62361773-96c4d980-b513-11e9-9fad-e1a5bd7e738f.png)
![image](https://user-images.githubusercontent.com/1469350/62361794-a04e4180-b513-11e9-9952-8e3c67b808e8.png)

**Comment by steve6375** [comment]
Would be nice if you could check for 'mm' rather than just 'm' so we can add a string like 'Time'?

![image](https://user-images.githubusercontent.com/1469350/62361985-fa4f0700-b513-11e9-9cc6-3d7553eac9cb.png)

![image](https://user-images.githubusercontent.com/1469350/62361967-f15e3580-b513-11e9-9f43-5b091cd38834.png)

**Comment by steve6375** [comment]
Two Q's
1. Will calling get_datetime which calls BIOS Int 1Ah add a significant delay into tunes (beep) and animation?
2. Up to 16 setmenu --string commands are allowed, does date&time count as one command, so now only 15 ordinary --string commands are possible+date&time?

**Comment by yaya2007** [comment]
1. Probably not. You can have a try.
2. Yes. The total is 16. 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3461038/grldr.rar.txt)

**Comment by steve6375** [comment]
why use HH instead of hh???  It is not logical? More logical to have DD MM MMM YYYY and hh mm ss.

![image](https://user-images.githubusercontent.com/1469350/62368586-f081cf80-b524-11e9-8d90-5e36b071b80f.png)
Also help formatting issue. Need  . and space.

**Comment by steve6375** [comment]
Might improve help if you added space or two to indent --string lines?
![image](https://user-images.githubusercontent.com/1469350/62379833-a5c18100-b53f-11e9-9e8b-27124da0ad4c.png)

**Comment by yaya2007** [comment]
> why use HH instead of hh??? It is not logical? More logical to have DD MM MMM YYYY and hh mm ss.
I refer to the following information:
https://blog.csdn.net/zhangxichao100/article/details/78124813
https://my.oschina.net/xinxingegeya/blog/394821

> Might improve help if you added space or two to indent --string lines?
You can help me to have a look.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3467335/grldr.rar.txt)

**Comment by steve6375** [comment]
I don't see 'ap' mentioned in URLs you gave? This string 'ap' also may appear in user text. Maybe 'AP' would be better?

Also it is 12:45pm here but 'ap' is printing 'AM' not 'PM' - when clock changed to 13:00 it went to PM - so bug in deciding AM or PM?    PM = after noon.
https://www.timeanddate.com/time/am-and-pm.html

```
Here's how to convert time on a 24-hour clock to the 12-hour system:

From 0:00 (midnight) to 0:59, add 12 hours and use am.
0:49 = 12:49 am (0:49 + 12)

From 1:00 to 11:59, just add am after the time.
11:49 = 11:49 am

From 12:00 to 12:59, just add pm after the time.
12:49 = 12:49 pm

From 13:00 to 0:00, subtract 12 hours and use pm.
13:49 = 1:49 pm (13:49 - 12)
```

**Help text**
Still needs cr before '--string= to delete all strings'.

Indent text to show notes for different commands?

![image](https://user-images.githubusercontent.com/1469350/62462488-78fbac80-b77f-11e9-9576-3e18a305d6e0.png)

**Comment by yaya2007** [comment]
There is "a" in URLs, because to print am/pm, for placeholder, select "ap". You can change it to "AP". 

In "date & time = FORMAT", strings can be displayed, which is an unexpected gain. Don't be a prerequisite. 

> Also it is 12:45pm here but 'ap' is printing 'AM' not 'PM' 

This is a mistake

**Comment by steve6375** [comment]
Suggested help text, use (space)(space) for indent.

![image](https://user-images.githubusercontent.com/1469350/62468538-3392ab80-b78e-11e9-967c-9ec1cd40b78a.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3467937/grldr.rar.txt)

**Comment by steve6375** [comment]
Almost OK!  Too many lines, now overflows screen. Can you shorten so all fits on 800x600? Top line of help text is missing.

Also some small adjustments to help...
Usual format is  hh:mm:ssAP (not AP hh:mm:ss)  -e.g.  02:45:03PM.

![image](https://user-images.githubusercontent.com/1469350/62471439-98510480-b794-11e9-9bd4-179e5f63df1c.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/62482445-06a1c100-b7ad-11e9-9784-44068cef1e52.png)
![image](https://user-images.githubusercontent.com/1469350/62482462-0ef9fc00-b7ad-11e9-8b32-3ef4d235760b.png)
setmenu --string=67=0=0xffffff="date&time=Date=dd/MM/yyyy Time=HH:mm:ss]"

Time no longer works...

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3470185/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks! Function seems OK now.

Maybe small changes to help text?

1 "If no X, text in middle."
2 Applies to all help text so move to bottom of help text with no indent
3 Capital N  "**N**aming rules...
4 "If W=0, menu box in middle. L=menu border thickness 0-4, 0=none" 

![image](https://user-images.githubusercontent.com/1469350/62524222-22e54280-b82d-11e9-96c7-49c31f5ff596.png)

**Comment by yaya2007** [comment]
"2 Applies to all help text so move to bottom of help text with no indent"
Applicable only to "--string=[X]..."

**Comment by steve6375** [comment]
add to bottom
`Note: * = default`
and change text for timeout to
"Use only 0xRRGGBB for COLOR."
?

**Comment by yaya2007** [comment]
ok

**Comment by yaya2007** [comment]
An additional function has been added:
--string=INDEX to delete the specified index.

Take a look at the help. 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3475836/grldr.rar.txt)

**Comment by steve6375** [comment]
This does not really help much. I want to allow user to toggle on and off the date on the menu, but the menu may also contain other strings so I do not know what INDEX the date&time string is.

If we have multiple strings on the menu we may not be sure which number the string is.

Also, we cannot list the strings to determine the number.

There may be multiple time&date strings added (e.g. if calls three menus each has own date&time string).

So can we also have:
**setmenu --string=d**   - delete ALL date&time strings (all 16 strings which are date&time)
**setmenu --string=l**    - list all strings (list with INDEX number)

If necessary, we could use  
setmenu --string=l > (md)0x300+1
and then find INDEX of string we want to delete.

setmenu --string=l

01 4=65=0xffffff="string1"
02 13=65=0xffffff="string2"
03 14=65=0xffffff="string3"
...
16 23=32=0xff00ff="string16"
 
even better would be
**setmenu --string=d="xxxxxxx"**      - delete all strings which contain xxxxxxx

e.g.
setmenu --string=d="date&time"     - delete all date&time strings
setmenu --string=d="Note:"             - delete all strings that contain "Note:"

So we could use this to delete any specific string (inc. date&time) without needing to know its index number.

**Comment by yaya2007** [comment]
It's complicated. Not so much thought. 
It was just suggested that only one string should be deleted. 

--string=INDEX to delete the specified index.  --string= to delete all strings.
Similar
--draw-box=INDEX to delete the specified index.  --draw-box= to delete all indexes

**Comment by steve6375** [comment]
Also, if possible
```
setmenu --string=65=0=0xffff="date&time"
setmenu --string=65=1=0xffff="date&time"
setmenu --string=65=2=0xffff="date&time"
```
should only add one string, not three.

**Comment by steve6375** [comment]
I dont really see the date&time function as a ---string  function. It may be better to have it as a separate function. e.g.
setmenu --date&time=X=Y=COLOR[="FORMAT"]
setmenu --date&time=


Then I could have simple menu entry for

title Display Time and date
setmenu --date&time=65=0=0xffffff
errorcheck off
boot

title Remove Time and date
setmenu --date&time=
errorcheck off
boot

and I do not care what strings have been defined by user.

**Comment by yaya2007** [comment]
setmenu --string=65=0=0xffff="date&time"
setmenu --string=65=1=0xffff="abcdefghi"
setmenu --string=65=2=0xffff="12345678"

**Comment by steve6375** [comment]
My point is that if you add three date&time commands (e.g. test from console or load a .cfg file which has date&time) but I do not want to remove any other strings.

setmenu --string=65=0=0xffff="date&time"
setmenu --string=65=1=0xffff="date&time"
setmenu --string=65=2=0xffff="date&time"

This adds strings 1 and 2 and 3 if test in console or if have a .cfg which calls another .cfg and both have time&date in them.

**Comment by yaya2007** [comment]
At present, there can only be one  "date & time"

**Comment by steve6375** [comment]
No
setmenu --string=65=0=0xffff="date&time"
setmenu --string=65=1=0xffff="date&time"
setmenu --string=65=2=0xffff="date&time"

will add three strings
(only last one will display)

**Comment by yaya2007** [comment]
yes
(only last one will display)
Because there is only one date control

**Comment by steve6375** [comment]
e.g. User can define multiple x strings on menu...
Menu.lst (shows x user strings and date&time)
menu1.lst (keeps user strings but does not display date&time)
menu2.lst (keeps user strings but displays date&time in different format)

How to do menu1 ? I do not want to delete strings. I do not know number of date&time string.
i.e. I want to delete date&time string but I do not know INDEX number.
If menu2.lst adds new date&time command, it adds to strings. If user selects menu1, menu2, menu1, menu2, menu1, menu2, etc.  then 16 strings will be exceeded because  date&time will be added by menu2 each time. So adding strings in menu2 will no longer work.

**Comment by yaya2007** [comment]
Now the situation is to execute the following commands:
configfile /menu1.lst
Reset "--string" parameter .
`	if (new_menu == 0)
	{
		num_string = 0;
		string_total = 0;
		string_enable = 0;
		p_string = (char *)MENU_TITLE;		//0x3A8000
		for (i=0; i<16; i++)
		{
			DrawBox[i].index = 0;
			strings[i].index = 1;
		}
		new_menu = 1;
	}`

**Comment by steve6375** [comment]
I want to keep all strings in menu1.lst  except date&time string.
I do not know the number of the date&time string because user has defined what strings he has on menu.

```
title Show Time and Date on menu
?????

title Remove Time and Date on menu
?????
```

How do I make these menu entries but keep all strings on menu?
I cannot use:
setmenu --string=    (this removes user defined strings!)
or
setmenu --string=n  (I do not know the number of the date&time string!)

**Comment by yaya2007** [comment]
I see. Let me think about it.

**Comment by steve6375** [comment]
OK

Also re. delete string feature:

setmenu --string=1
This does not **delete** string2 - it **disables** string2

setmenu --string=10=65=0xffffff="string1"
setmenu --string=11=65=0xffffff="string2"
setmenu --string=2
setmenu --string=12=65=0xffffff="string3"
setmenu --string=2

"string3" is still displayed.  There are 3 strings in list not 2.

Suggest change help text to 'permanently disable' rather than delete?

**Comment by yaya2007** [comment]
Press F2 toggle date display( not display), is it okay?

**Comment by yaya2007** [comment]
I don't understand how to control other people's menus. For example, menu 1 has several strings containing dates. Do you want to stop date display, keep other strings, and add strings in your own menu 2? Will this cause address conflicts?

How to control other people's menu 1?

**Comment by steve6375** [comment]
Using F2 for date is no good - it is also used for animation (and key stops sound). Do not use.

Main problem is that I want to display or not display date, so as minimum
setmenu --string=d


With E2B, the user can define his own strings for all menus.
He might want the Main Menu to display the Date and Time, but all sub-menus to display only the strings.
e.g.
setmenu --string=23=65=0xfff="Help:"
setmenu --string=24=65=0xfff="F9 = Reset"
setmenu --string=25=65=0xfff="F10 = Halt"
setmenu --string=26=65=0xfff="F11 = Run Ubuntu+persistence"

User has defined these in one .cfg file which is loaded on boot (\_ISO\MyE2B.cfg).
These are displayed on every menu and submenu.

Date and Time are displayed on Main menu with strings but on sub-menus, we only want strings or he may want menu entries to display or not display date&time.

Summary:
Main issue is how to have these two menu entries:

> title Show Time and Date on menu
> ?????
> 
> title Remove Time and Date on menu
> ?????

Number of predefined strings in menu are unknown.
Menu should work in any menu and user can select 20 times and it will still work.
How to do this?

**Comment by yaya2007** [comment]
--string=date&time to disable the date&time.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3476978/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks.

re. help text - should be...

--strings= to **delete** all strings    (not _disable_)

**Comment by yaya2007** [comment]
> Suggest change help text to 'permanently disable' rather than delete?

Now there are five disables, all changed to delete? 
I feel they mean the same thing.

**Comment by steve6375** [comment]
no they are not the same.
disable = still present but not active
delete = no longer present


If you add 16 strings then you cannot add any more.
If you use --string=1 or --string=16 to disable one item, then you still cannot **add** any more strings because the item is still present in the list of 16 strings.
The display of the string is disabled but the string is still present in the list (just disabled).
If you use --string=  then all strings are deleted and you can add more strings.
You can use  'clear all strings' instead of delete if you prefer?

**Comment by yaya2007** [comment]
OK
use 'clear all strings'

**Comment by steve6375** [comment]
Thanks.
re. Changes list, you forgot to  '--strings=INDEX will disable specified string'.

Also last line of help is
Note: * = default. **Use only 0xRRGGBB for COLOR**. INDEX range is 1-16.

Is this correct?

**Comment by yaya2007** [comment]
Yes. Not very practical. Only if you know the index number can you use it.

**Comment by steve6375** [comment]
I just noticed  a bug!
Not quite sure when it was introduced, but there is a default timeout of 99 seconds now.
It does not happen with 2019-06-17.
I will try to track it down. Can you try also?

**Comment by yaya2007** [comment]
I added that if the timeout setting is greater than 99, it should be processed according to 99. Did he cause trouble?

**Comment by steve6375** [comment]
2019-08-06 version and before does not show problem.
2019-08-07 and 08 always shows 99 second timeout.

**Comment by steve6375** [comment]
Can you change back please?

**Comment by steve6375** [comment]
timeout -1

I think maybe this command is the cause? It is valid command  for no timeout.

**Comment by yaya2007** [comment]
Timeout-1   //abnormal 

(# timeout-1 //Normal )

**Comment by steve6375** [comment]
Grub4dos Readme
03h	1	timeout in seconds to wait for a key press. 0xff stands for
		waiting all the time(endless).


grub and grub4dos:
0 = 0 seconds (no menu displayed)
1 = 1 second
-1 = infinite wait (no timeout)

Could set a timeout of  12345 if required.  Displays OK if menu has no border.
Please go back to old code.
![image](https://user-images.githubusercontent.com/1469350/62698565-5793fe00-b9d5-11e9-8ad7-c5e87b827d28.png)
![image](https://user-images.githubusercontent.com/1469350/62699028-79da4b80-b9d6-11e9-9d47-de770138de39.png)

**Comment by yaya2007** [comment]
What does Set - 1 do?

**Comment by steve6375** [comment]
-1 = infinite wait (no timeout)

same as grub2

**Comment by yaya2007** [comment]
Got it

**Comment by steve6375** [comment]
Thanks :-)
