### ISSUE TITLE
Animation only starts after key press if user input requested before menu is displayed

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#208]
If I set up an animation but have a  set /p ask=enter a number    in the .cfg file  before any title or iftitle lines

```
#code here to start animation

call Fn.70 3
clear
echo [1985]
set /p ask=Enter a number
set /p ask=Enter another number

title xxxx
etc.
```

then the wallpaper is displayed on the screen and the prompt appears
**Enter a number**
but the animation does not display.

However, as soon as the user presses a key, then the animation plays.

When the user presses ENTER key, the next prompt appears:
**Enter another number**
and the animation pauses until the user presses a key - then it starts again.

Is there any way to make the animation play before the question is asked?

![image](https://user-images.githubusercontent.com/1469350/64076148-08ca4300-ccb9-11e9-8046-9459f1747583.png)
User presses any key (2) and animation plays
![image](https://user-images.githubusercontent.com/1469350/64076154-18e22280-ccb9-11e9-9aa6-6bb1c68b695e.png)

**Comment by steve6375** [comment]
P.S. If I call a grub4dos batch file instead of using set /p line
then the animation plays immediately after the password prompt.

```
!BAT
# animation plays immediately...
password fred
```

so the code in the password entry routine allows animation to play but  set /p does not allow animation to play.

set /p stopping animation is only a small issue but it would be nice if there was an easy fix.
'pause' command also does not show animation.

**Comment by yaya2007** [comment]
Add to the menu 
write --bytes=1 0x835b 1

Put the batch file "before_title" in the root directory 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3565897/grldr.rar.txt)

**Comment by steve6375** [comment]
I can't seem to get it to work.

Does
`write --bytes=1 0x835b 1`
have to be issued before the `splashimage --animated=0x90=10:ms=90=590=300 (5)/e2b/sphereR_frame_0001.jpg` command?

when set /p ask=bbb  is executed - the animation does not start until I press a key.

Can you explain what it does and how it works please?

**Comment by yaya2007** [comment]
来回翻译太麻烦，就用中文了，见谅。
不太明白你的本意。为什么要用户输入数字，才开始播放动画？再输入数字停止播放？
你可以在指定的批处理文件，书写合适的语句，以达到你自己的目的。
set  /p  .....
当输入数字时，它并不工作，直到按回车才执行。
这时播放动画。动画不是独占模式，紧接着执行下一条
set  /p.....
等待输入。随意输入数字，解锁屏幕，动画正常播放。

**Comment by steve6375** [comment]
No
My intention is to display a wallpaper which asks user a question and display an animation
as soon as the  set /p  is executed, I want the animation to start so that the user sees both the wallpaper and the animation.

BUT - currently the animation does not start when set /p waits for input

HOWEVER - as soon as the user presses any key (a-z, 0-9, * any key) then the animation plays.

I want the animation to play immediately after  set /p so user sees animation before any input.

**Comment by yaya2007** [comment]
明白你的意图了。
另外我想知道，测试动画时，菜单背景图已经加载了？

**Comment by steve6375** [comment]
yes, background has been loaded with splashimage and then call Fn.70 3 is used to show it - as in the menu in first post.

**Comment by yaya2007** [comment]
OK, please test it. 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3569107/grldr.rar.txt)

**Comment by steve6375** [comment]
🥇 That seems to work well. It works for _pause_ and _set /p_.  Was much code changed?
Should I check for possible bugs - if so in what areas - user input - password input - animation issues?

**Comment by steve6375** [comment]
New grldr version seems OK. Will you create a new release version for this change please?
