### ISSUE TITLE
grub4dos not saving selected menu item to 0x8276

### ISSUE THREAD

**Issue by Mythenadia** [chenall/grub4dos#213]
grub4dos-0.4.6a-2018-07-01 and newer versions always store a 0x00 byte to location 0x8276 no matter which menu item is selected when booting grub4dos on a Panasonic Toughbook CF-30.  grub4dos-0.4.6a-2018-06-29 and earlier versions work correctly.  This problem does not occur on my other computer, a Dell Dimension 2400.  Since I use a grub4dos batch file to set /default to the contents of 0x8276 for the next bootup, I am unable to upgrade grub4dos beyond 2018-06-29 on the CF-30.

**Comment by steve6375** [comment]
It was supposed to be fixed in https://github.com/chenall/grub4dos/issues/181
I have 2019-09-09 and it seems to work
set /a CURDEF=*0x8276 & 0xff > nul

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/66716332-7ee7bc80-edc4-11e9-973c-e8ad7af9a957.png)
![image](https://user-images.githubusercontent.com/1469350/66716336-89a25180-edc4-11e9-85aa-63e804f58308.png)
![image](https://user-images.githubusercontent.com/1469350/66716341-93c45000-edc4-11e9-9605-bf0705fa04bd.png)
![image](https://user-images.githubusercontent.com/1469350/66716346-9c1c8b00-edc4-11e9-996d-b4efdbe97378.png)

**Comment by Mythenadia** [comment]
Thank you for your quick response.
Here's what I'm getting.  My apologies for the cam-quality screenshots.
My main boot menu with item 26 (Grub4DOS Command Line) selected:

![IMG_0724](https://user-images.githubusercontent.com/15078982/66783955-23422f80-eea7-11e9-9e9b-9d4160c16450.jpg)

After the grub4dos command line selection with grub4dos-0.4.6a-2018-06-29 and older:

![IMG_0726](https://user-images.githubusercontent.com/15078982/66784129-9055c500-eea7-11e9-96fd-3510c7911c04.jpg)

With grub4dos-0.4.6a-2018-07-01 and newer I get this:

![IMG_0725](https://user-images.githubusercontent.com/15078982/66784183-bd09dc80-eea7-11e9-94aa-5a249dc1bc50.jpg)

**Comment by steve6375** [comment]
Can you try a simple \menu.lst file with a few title lines

title 00
root ()

title 11
root ()

title 22
root ()

title 33
root ()

and use right-cursor to select one and then 'c' for command line.

Something you are doing in your menu may be causing the issue.
This simple test will check that it basically works (it works for me!).

Then maybe look at you menu to see what may be causing the issue - perhaps graphicsmode or you are corrupting memory somehow? Try to simplify your menu.lst as much as possible and attach it so we can test it.









e.g.

**Comment by Mythenadia** [comment]
steve6375,

Your simple /menu.lst worked correctly.
I then prepended grub4dos commands from my own /menu.lst, one line at a time, until the set /a command failed.  Once the offending command was found, I removed previously added lines in reverse order, again one at a time, to see if it was a combination of g4d commands causing the problem.  This single line is what causes the problem:

'# Define symbol at left of highlighted menu entry
'# sets 0x8276 (current selected menu entry) to zero
write 0x8308 0x00

**Comment by steve6375** [comment]
Write will write 4 bytes - so you corrupt  8038 8309 830a and 830b
only 8308 is the menu character - a single byte. The other 3 bytes are reserved for debug, etc.

you can specify the number of bytes to write - type  help write

`write --bytes=1 0x8308 0`



Instead use the setmenu command to turn off the triangle marker
type 
`help setmenu`

e.g. 
`setmenu --triangle-off`


https://www.rmprepusb.com/tutorials/grub4dos/grub4dos-internal-variables-and-functions
https://www.rmprepusb.com/tutorials/grub4dos/grub4dos-commands-primer

**Comment by Mythenadia** [comment]
write --bytes=1 0x8308 _anything_

blanks the triangle menu pointer and still sets 0x8276 to zero.

setmenu --triangle-off

does the same.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/67042194-4414ba00-f11f-11e9-9370-f073c731114a.png)
Seems OK to me. The menu entry of 3 is correct.

**Comment by steve6375** [comment]
To get the arrow back you need to write
write --bytes=2 0x8308 0x1110

asm.S
VARIABLE(menu_cfg) /*char menu_cfg[]*/
	.long 0x1110


As far as I can see from the code in Stage2.c, only  0x1110 is understood as 'print arrow' - any other value will not  print any character. So only 0x8308=0x1110 will print an arrow.

```
  if (*(unsigned short *)0x8308 == 0x1110)
  {
  if(!(menu_tab & 0x40))
	{
		gotoxy (MENU_BOX_X - 1, y);
		grub_putchar(highlight ? (menu_num_ctrl[2] = entryno,menu_cfg[0]) : ' ', 255);
	}
	else
	{
		gotoxy (MENU_BOX_E - 1, y);
		grub_putchar(highlight ? (menu_num_ctrl[2] = entryno,menu_cfg[1]) : ' ', 255);
	}
  }

```
I am not too sure what this code does - my C is not good enough.
either a  left arrow 11h or right arrow 10h is written if the menu is the highighted one.
but entryno is also involved? Maybe yaya can look at the code and explain?

**Comment by yaya2007** [comment]
"entryno" is the highlighted menu number .
menu_num_ctrl[2] = 0x8276.

"entryno" -> *0x8276

**Comment by steve6375** [comment]
OK - but there is a bug if 0x8308 does **not** contain 0x1110...

Example:
setmenu --triangle-on
(select menu entry 1)
read 0x8276              (returns 1) CORRECT
setmenu --triangle-off
(now highlight a different menu entry in menu)
read 0x8276             (returns 1)  ERROR !!!!

menu_num_ctrl[2] = 0x8276 is not updated.

**Comment by steve6375** [comment]
P.S. Would also be more compatible if the test for 8308 == 0x1110 was changed to

> if  byte at 0x8308 <> 0

then the character in 8308 and 8309 could be changed by the user and it would be compatible with previous menus.lst files which could change the arrow character by changing 0x8308.

**Comment by yaya2007** [comment]
Without triangles, the highlighted item number is not returned.
That's how primitive things are. 

8308==0x1110
That's how primitive things are. 
 it  be compatible with previous menus.
What do you want to change to as an indicator?

**Comment by steve6375** [comment]
In older versions, the user could change 0x8308 to remove arrow or change it to some other character - e.g. 0x16 for →, 0x07 for a dot

I suggest:

```
menu_num_ctrl[2] = entryno
  if (*(unsigned char *)0x8308 != 0)
  {
  if(!(menu_tab & 0x40))
	{
		gotoxy (MENU_BOX_X - 1, y);
		grub_putchar(highlight ? entryno ,menu_cfg[0] : ' ', 255);
	}
	else
	{
		gotoxy (MENU_BOX_E - 1, y);
		grub_putchar(highlight ?  entryno,menu_cfg[1] : ' ', 255);
	}
  }
```

This means 8308 is left-hand menu character and 8309 is right-hand menu character. 8308 must be <> 0 for character to be shown. if 0 then no LH or RH character.
Also, if user menu has
write 0x8308 0x16
or
write 0x8308 0
then he will still get expected result as with old versions even though writing 4 bytes.

**Comment by Mythenadia** [comment]
If I boot grub4dos-0.4.6a-2019-09-09 with this MENU.LST file,
![01 menu setmenu](https://user-images.githubusercontent.com/15078982/67145934-fe0d4280-f253-11e9-985b-c954b9c5f3c2.png)
use the right arrow key to select "33", then press "c" for a command line, I get
![02 cmd line](https://user-images.githubusercontent.com/15078982/67145982-53e1ea80-f254-11e9-80c4-1042b486be90.png)
which shows that "entryno" (0x8276) has been zeroed.

If I boot with this MENU.LST file,
![03 menu write](https://user-images.githubusercontent.com/15078982/67146016-a15e5780-f254-11e9-9618-8f5931c12474.png)
where "pqrs" is anything other than "1110",
select "33" then "c" to a command line again, I get
![04 cmd line](https://user-images.githubusercontent.com/15078982/67146043-dec2e500-f254-11e9-93b4-f4f269d68f56.png)
which also shows that entryno has been clobbered.

However if I boot with this MENU.LST,
![05 menu](https://user-images.githubusercontent.com/15078982/67146088-55f87900-f255-11e9-921f-8f0c1060250e.png)
select "33" then "c" to a command line, I get
![06 cmd line](https://user-images.githubusercontent.com/15078982/67146105-7cb6af80-f255-11e9-8dba-cf5dc2b196e6.png)
which shows that if either the setmenu --triangle-off or the write to 0x8308 commands are executed from a command line but not in MENU.LST, then entryno is untouched.

**Comment by steve6375** [comment]
No - the value has not been 'clobbered'!  It is just that the value has not changed.
If you set any value other than 1110 then the 8276 value is not UPDATED.
It is a bug and we are working on it.

**Comment by yaya2007** [comment]
Have a try 
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3747638/grldr.rar.txt)

**Comment by steve6375** [comment]
Same issue as bad download before! It just hangs.!!!
![image](https://user-images.githubusercontent.com/1469350/67156910-7d664900-f31c-11e9-8b1b-35d696710eb1.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3747657/grldr.rar.txt)
The previous time, it was because of the debugging code "getkey()". 
It's clean now.
Same file, upload again.

**Comment by steve6375** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/1469350/67157276-f6b46a80-f321-11e9-84cd-1ec14f7805a8.png)
8276 is now updated and can set a different character in 8308
![image](https://user-images.githubusercontent.com/1469350/67157297-35e2bb80-f322-11e9-8680-90c9f9eedd2c.png)
right-align character is set by 8309 - all OK.
  👍

**Comment by Mythenadia** [comment]
grub4dos-0.4.6a-2019-10-20 works perfectly!
Both the setmenu --triangle-off and the write --bytes=1 0x8308 0xNN work correctly in MENU.LST without interfering with the entryno 0x8276 update upon menu selection.
Thank you.

**Comment by steve6375** [comment]
Mythenadia - can you close this issue please, if it is now fixed in new version.

**Comment by Mythenadia** [comment]
Newest version posted at http://grub4dos.chenall.net/ is still grub4dos-0.4.6a-2019-09-09, which does not work correctly.

**Comment by yaya2007** [comment]
You can refresh it.
