### ISSUE TITLE
vol xxx command does not set root

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#214]
The vol help says that, e.g. 
`vol PTN2  `
will set PTN2 volume as root

I can't seem to get this to work?
![image](https://user-images.githubusercontent.com/1469350/66947129-3b9e7f80-f04a-11e9-93ad-6ef948b2ee79.png)

also --write is not documented in the help text. Also if " " is required for volume name, it does not mention this.

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3737979/grldr.rar.txt)

**Comment by steve6375** [comment]
bad grldr - does not boot????
Can you recompile and check please?

**Comment by yaya2007** [comment]
It can be started.
I have no problem testing it here

**Comment by yaya2007** [comment]
It can be started.

**Comment by steve6375** [comment]
No \menu.lst - just hangs...
Under VBOX and QEMU. I tried two different USB sticks. Same problem.
I re-downloaded the file 3 times. 

![image](https://user-images.githubusercontent.com/1469350/67089927-b679ae80-f1a0-11e9-8d82-1dc5929c2a9e.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3745981/grldr.rar.txt)

**Comment by steve6375** [comment]
Looks good :-)
