### ISSUE TITLE
help command query

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#215]
help help
![image](https://user-images.githubusercontent.com/1469350/67140577-be465b00-f253-11e9-8340-1d9b808d210b.png)

This does not make sense. Does it mean 'use --all to show all commands' ?

In any case, I can find no difference between
help
and
help --all

does it mean that some commands will show more information if we use --all, e.g.
help --all graphicsmode

Can you check code builtins.c please and change help help text?

**Comment by yaya2007** [comment]
static struct builtin builtin_help =
{
  "help",
  help_func,
  BUILTIN_MENU | BUILTIN_CMDLINE | BUILTIN_SCRIPT | BUILTIN_HELP_LIST,
  "help [--all | PATTERN ...]",
  "Display helpful information about builtin commands. Not all commands"
  " aren't shown without the option `--all'."
};

**Comment by steve6375** [comment]
Suggest:
```
static struct builtin builtin_help =
{
"help",
help_func,
BUILTIN_MENU | BUILTIN_CMDLINE | BUILTIN_SCRIPT | BUILTIN_HELP_LIST,
"help [--all | PATTERN ...]",
"Display information about built-in commands. Use option `--all' to show all commands."
};
```

But what does --all do?
I do not think --all has any affect?

**Comment by yaya2007** [comment]
For example, with -- all, you can list "call"

**Comment by steve6375** [comment]
ah OK.
So extra commands shown are setlocal, endlocal, call and pause.

Why is 'pause' not listed using help? Surely it is useful for menus, etc,?
pause is only listed using 'help -all'

**Comment by yaya2007** [comment]
This is easy to handle.
