### ISSUE TITLE
Support for braces { } no longer works?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#221]
See https://github.com/chenall/grub4dos/issues/165

I cannot get braces to work in a batch file or menu. Is it broken? I haven't tested it for some time.
Was it ever included?

**Comment by yaya2007** [comment]
The revision was not released.

Since there are few people using g4d batch processing now, I'm worried about introducing bugs.

There is no {} function. It can also be expressed.
Adding {} function can make the complex logical relation clear, easy to understand and write.
