### ISSUE TITLE
How to easily set a menu heading?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#222]
The current menu heading color (GRUB4DOS 0.4.6a 20190-XX-XX etc.'  can be changed using the colour command, but removing the heading or changing its text or position is very difficult. You have to use the undocumented initscript command to remove the grub4dos heading and replace it.

Could there be a setmenu --heading= command which we could add?

setmenu --heading=         does not display the GRUB4DOS heading
setmenu --heading=X=Y=COLOUR="HEADING"     - displays string
setmenu --heading==Y=COLOUR="HEADING"       - centres heading

Note:
Can issue infinite number of setmenu --headings= commands (always overwrites previous one),
setmenu --string= should NOT clear the heading, --heading should be a separate function and string.
color heading=0xrrggbb     may or may not affect the colour of the heading (nice if it did but not essential).

**Comment by yaya2007** [comment]
"--string=[iINDEX]=[X]=[-]Y=COLOR=\"STRING\"  \n"
	"  'i' is the structural identification.  INDEX: 0-15.\n"
	"  If no X, text in middle.\n"
	"  -Y represents the count from the bottom.\n"
	"  \"STRING\"=\"date&time=FORMAT\"  will update date FORMAT every second.\n"
	"  e.g. \"date&time=MMM.dd.yyyy  HH:mm:ss\"\n"
	"  e.g. \"date&time=dd/MMM/yy  AP hh:mm:ss\"\n"
	"  \"STRING\"=\"date&time\"  ISO8601 format. equivalent to: \"date&time=yyyy-MM-dd  HH:mm:ss\"\n"
	"  --string=iINDEX to disable/enable the specified index.\n"
	"  --string= to disable/enable all strings.\n"

struct string
{
	unsigned char enable;
	unsigned char start_x;
	char start_y;
	unsigned long long color;
	char string[101];
} __attribute__ ((packed));
#define MENU_TITLE					0x3A8000
struct string* strings = (struct string*) MENU_TITLE;

You can use "write" to modify the value starting from 0x3a8000.
You can use "echo -mem=0x3a8000=128" to view values

**Comment by steve6375** [comment]
You seems to have added an INDEX to the string function.
This is good but it is not what I am asking for.

I want to remove the GRUB4DOS heading at the top of the menu and I want to define a X\Y position for my own heading and a colour.

![image](https://user-images.githubusercontent.com/1469350/70860350-96ecd100-1f18-11ea-9615-834963a65fcc.png)

```
# Wipe out the GRUB4DOS heading and display a new menu heading on 2nd line
write (md)0x220+1 !BAT\necho -P:0000 $[0004] \x20                                                                                                   \0
initscript (md)0x220+1
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU ---"

```

I want a standard way to remove the GRUB4DOS heading without needing to use initscript
![image](https://user-images.githubusercontent.com/1469350/70860330-6ad15000-1f18-11ea-9166-7236a2eaf550.png)

e.g.

setmenu --heading=      - does not display the GRUB4DOS heading

**Comment by steve6375** [comment]
P.S.  

why setmenu --draw-box INDEX = **1 - 16**  but setmenu --string = **i0 - i15**  ??

**Comment by steve6375** [comment]
P.P.S
setmenu --string=   before deleted all strings
now it enables\disables.
**How can we delete strings?**
This breaks compatability
e.g.
setmenu --string=0=0=0x1ff="STRING1"
setmenu --string=1=0=0x1ff="STRING2"
setmenu --string=2=0=0x1ff="STRING3"
setmenu --string=3=0=0x1ff="STRING4"
setmenu --string=4=0=0x1ff="STRING5"
setmenu --string=5=0=0x1ff="STRING6"
setmenu --string=6=0=0x1ff="STRING7"
setmenu --string=7=0=0x1ff="STRING8"
setmenu --string=8=0=0x1ff="STRING9"
setmenu --string=9=0=0x1ff="STRING10"
setmenu --string=10=0=0x1ff="STRING11"
setmenu --string=11=0=0x1ff="STRING12"
setmenu --string=12=0=0x1ff="STRING13"
setmenu --string=13=0=0x1ff="STRING14"
setmenu --string=14=0=0x1ff="STRING15"
setmenu --string=15=0=0x1ff="STRING16"
setmenu --string=16=0=0x1ff="STRING17"  - not added
**setmenu --string=**          - previously deleted all strings - now just disables
setmenu --string=0=0=0x1ff="STRING1" - previously only this will display - now it is not added and no strings are displayed!

Please restore
setmenu --string=
so it **deletes** all strings.

**Comment by yaya2007** [comment]
"setmenu --ver-off" can close the heading.

	"--string=[iINDEX]=[X]=[-]Y=COLOR=\"STRING\"\n"
	"  'i' is the structural identification.  INDEX range is 1-16.\n"
	"  If no X, text in middle.\n"
	"  -Y represents the count from the bottom.\n"
	"  \"STRING\"=\"date&time=FORMAT\"  will update date FORMAT every second.\n"
	"  e.g. \"date&time=MMM.dd.yyyy  HH:mm:ss\"\n"
	"  e.g. \"date&time=dd/MMM/yy  AP hh:mm:ss\"\n"
	"  \"STRING\"=\"date&time\"  ISO8601 format. equivalent to: \"date&time=yyyy-MM-dd  HH:mm:ss\"\n"
	"  --string= to disable all strings.\n"
	"  --string=iINDEX to disable the specified index.\n"

Features of new version:
You can modify the [Iindex] string multiple times.
e.g. 
setmenu --string=i2=x1=y1=color1="STRING1"
setmenu --string=i2=x1=y1=color2="STRING1"
setmenu --string=i2=x1=y1=color1=""
setmenu --string=i2=x2=y2=color1="STRING1"

**Comment by steve6375** [comment]
I forgot about -ver-off !!!! My mistake - sorry!.

New iINDEX is better now and compatible.
BUT...
why is iINDEX **1-16** ??

but setmenu --draw-box uses INDEX **0-15**  ???
It is inconsistent!

iINDEX should be 0-15

Also syntax should be
```
"--string=[iINDEX=][X]=[-]Y=COLOR=\"STRING\"\n"
"INDEX range is i0-i15. Auto-increments if omitted.\n"
```

Since you cannot enable any string (or all strings), help text should say
"  --string= to **delete** all strings.\n"

**Comment by steve6375** [comment]
P.S. Are 64-bit colours supported (background+foreground) in graphicsmode with wallpaper? Does not seem to work...

**Comment by yaya2007** [comment]
Do not delete, direct iInput string .

lock command issues #223:
debug=0
Have a try.

**Comment by steve6375** [comment]
```
setmenu --ver-off
setmenu --string=i1=0=1=0x01ccFF="   xxx MENU ---"
setmenu --string=0=1=0x01ccFF="   yyyyyy MENU ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU a ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU b ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU c ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU d ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU e ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU f ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU g ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU h ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU i ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU j ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU k ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU l ---"
setmenu --string=0=1=0x01ccFF="          --- STEVE'S MENU m ---"
setmenu --string=30=1=0x01ccFF="          --- STEVE'S MENU n ---"
setmenu --string=31=1=0x01ccFF="          --- STEVE'S MENU o ---"
setmenu --string=32=1=0x01ccFF="          --- STEVE'S MENU p ---"
setmenu --string=
setmenu --string=i1==10=0x01ccFF="--- STEVE'S MENU0 ---"
setmenu --string=0=2=0x0AccFF="          --- STEVE'S MENU1 ---"
setmenu --string=0=3=0xA1ccFF="          --- STEVE'S MENU3 ---"
```

![image](https://user-images.githubusercontent.com/1469350/70903835-ad1d8e80-1ff7-11ea-80f5-258b34aa365a.png)

setmenu --string=i1==10=0x01ccFF="--- STEVE'S MENU0 ---"   is not working ???

**Comment by yaya2007** [comment]
新旧格式不能混合使用。
旧格式:依次顺序往字符串缓存池传送。
新格式:往指定字符串缓存位置传送。即插槽位置固定。

**Comment by steve6375** [comment]
OK - but why iINDEX 1-16 and not 0-15?
Also - how to centre the text **within the menu area** (as for a menu heading)?
maybe 
setmenu --string=c=1=0x01ccFF="MENU HEADING"
or
setmenu --string=i1=c=1=0x01ccFF="MENU HEADING"
???

**Comment by yaya2007** [comment]
是0-15，已经修改帮助。
对称中心
--string＝i1＝＝y＝color＝"xxxxx"

**Comment by steve6375** [comment]
```
setmenu --ver-off
setmenu --string=i0==1=0x01ccFF="MENU"
```
does not center in menu area - it centres across the whole screen.
![image](https://user-images.githubusercontent.com/1469350/70908774-f83d9e80-2003-11ea-9d83-1b85acdf62d7.png)

**Comment by yaya2007** [comment]
明白了。目前不能自动在菜单中心。

**Comment by yaya2007** [comment]
"P.S. Are 64-bit colours supported (background+foreground) in graphicsmode with wallpaper? Does not seem to work..."
can

**Comment by yaya2007** [comment]
"--string=[iINDEX]=[X|s|m]=[-]Y=COLOR=\"STRING\"\n"
	"  'i' is the structural identification. INDEX range is i0-i15. Auto-increments if omitted.\n"
	"  If the horizontal position is 's', \"STRING\" centres across the whole screen.\n"
	"  If the horizontal position is 'm' , \"STRING\" does center in menu area.\n"

**Comment by steve6375** [comment]
Thanks for m parameter - works and also == still works too :-)

Some issues still...
1. setmenu --string=i1=s=1=0xFFFFFF0001ccFF="MENU"   - no background in graphics mode
2. lock now works as before - errorcheck off stops lock from working, cannot suppress the 'Error 32:' message.
3. In help setmenu - use either center (US spelling) or centre (UK spelling) - choose one of these - since 'color' is US spelling, I suggest using center.
"  If the horizontal position is 's', \"STRING\" **centers** across the whole screen.\n"
"  If the horizontal position is 'm' , \"STRING\" **centers within** menu area.\n"

**Comment by steve6375** [comment]
I am very sorry - I made a mistake - I just tested --draw-box
and  --draw-box  uses INDEX 1-16, so --string should use iINDEX 1-16.

I was mistaken! Very sorry! Please go back to  iINDEX = i1 - i16.
maybe add help text for --draw-box (INDEX=1-16) too?

**Comment by yaya2007** [comment]
As for lock, you said it didn't work. I changed it to go back.
About the index of picture frame, I read the code, it's 1-16.

**Comment by steve6375** [comment]
Very sorry - I do not know why I thought it was 0-15 - I must have read an old description somewhere. Please change back to 1-16. 

re. lock - yes - your changes to lock didn't work.
So now lock only works if errorcheck = on as before. This seems wrong to me. 
lock should work if errorcheck is off or if errorcheck is on. i.e. if no password has been entered, lock should **always** prevent any further command from running no matter what the state is of errorcheck.

Also, I was looking for a way to suppress the English 'Error 32: ..' message so that there is not any message displayed at all.

Neither of these are very important if they are difficult to change.

**Comment by yaya2007** [comment]
在手机上来回翻译太麻烦了，抱歉，就使用中文了。
关于lock的作用:如果设置了密码，而没有输入密码，则认为发生了错误，阻止程序进一步执行。
关于errorcheck的作用:如果关闭，则发生如何错误，都不理会，就当没有发生错误，继续执行。

**Comment by steve6375** [comment]
No problem - Chrome translates automatically.
re. lock - OK - leave it as it is then - maybe add to `help lock `- 'errorcheck must be on' ?

**Comment by yaya2007** [comment]
OK

**Comment by yaya2007** [comment]
--draw-box 的 INDEX，原来在帮助里写的是 1-16，但是实测是 1-15。应当是 0-15，索引0有误，已经修正。
所以 --draw-box 与 --string 的 INDEX，统一为 0-15。

 'errorcheck must be on'已经添加。

	"--string=[iINDEX]=[X|s|m]=[-]Y=COLOR=\"STRING\"\n"
	"  iINDEX range is i0-i15. Auto-increments if omitted.\n"
	"  If the horizontal position is 's', \"STRING\" centers across the whole screen.\n"
	"  If the horizontal position is 'm', \"STRING\" centers within menu area.\n"
	"  -Y represents the count from the bottom.\n"
	"  \"STRING\"=\"date&time=FORMAT\"  will update date FORMAT every second.\n"
	"  e.g. \"date&time=MMM.dd.yyyy  HH:mm:ss\"\n"
	"  e.g. \"date&time=dd/MMM/yy  AP hh:mm:ss\"\n"
	"  \"STRING\"=\"date&time\"  ISO8601 format. equivalent to: \"date&time=yyyy-MM-dd  HH:mm:ss\"\n"
	"  --string= to disable all strings.\n"
	"  --string=iINDEX to disable the specified index.\n"

	"--draw-box=INDEX=START_X=START_y=HORIZ=VERT=LINEWIDTH=COLOR.\n"
	"  LINEWIDTH:1-255; all dimensions in pixels. INDEX range is 0-15.\n"
	"  --draw-box=INDEX to disable the specified index.  --draw-box= to clear all indexes.\n"

字符串的背景色允许显示。
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/3976409/grldr.rar.txt)

**Comment by steve6375** [comment]
Background colour is now working - thank you.
ISSUES
setmenu --string==1=1=0x01ccFF="--- STEVE'S MENU ---"  - does NOT work

Syntax in help should be:
"--string[=[iINDEX]]=[X|s|m]=[-]Y=COLOR=\"STRING\"\n"
"  iINDEX range is i0-i15. Auto-increments if =iINDEX is omitted.\n"

re. 0-15 or 1-16  - all previous documentation for --draw-box says 1-16. Now we have to change the documentation to say that we must use 0-15 - so your change makes the help documentation wrong. I would prefer  1-16  for --string and --draw-box because then all help documentation is compatible.

Did you see ask issue [#224](https://github.com/chenall/grub4dos/issues/224)?
set /p ask=What is your name    - user presses TAB and gets list of commands - can you fix please?

**Comment by yaya2007** [comment]
关于0-15或者1-16，不用太纠结。
首先不影响兼容性。以前肯定不能使用0，现在可以使用了。以前肯定不能使用16，否则早就反馈回来了，就是说以前最多使用到15。
二是只要做到--string与--draw-box的索引表述一致即可。

**Comment by steve6375** [comment]
OK

**Comment by steve6375** [comment]
When are you going to make a release of this new version? I would like to put it into Easy2Boot.

**Comment by yaya2007** [comment]
tomorrow

**Comment by steve6375** [comment]
Seems good! Thanks.
Slight issue is help text - colour for draw-box and string is now 0xrrggbb00RRGGBB  not  'Use only 0xRRGGBB for COLOR' .
Maybe change in next version?

**Comment by yaya2007** [comment]
画线框不会有背景色吧

**Comment by steve6375** [comment]
yes, sorry, --string and --timeout can use background colour, draw-box does not.

**Comment by steve6375** [comment]
date&time broken ???

setmenu --string=i4=71=1=0xffffff="date&time=[hh:mm:ss AP]"

FORMAT is not parsed ????
![image](https://user-images.githubusercontent.com/1469350/71321897-6f69ab80-24b8-11ea-8cd3-dbc6cfa4cc5f.png)


graphicsmode -1 800
splashimage --fill-color=0x1fff
setmenu --string=i4=71=1=0xffffff="date&time=[hh:mm:ss AP]"
![image](https://user-images.githubusercontent.com/1469350/71322094-48f93f80-24bb-11ea-868c-b4b19a7e738f.png)

**Comment by steve6375** [comment]
not fixed in 2019-12-23
Please fix.
