### ISSUE TITLE
lock command issues

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#223]
Minor issues with lock command:

1. lock command does not work if errorcheck off has been set
2. Cannot suppress the lock command error message
![image](https://user-images.githubusercontent.com/1469350/70849239-94846b80-1e73-11ea-9932-58d16c5fdce9.png)

e.g.

```
password 123

title lock test
errorcheck off
lock
commandline

title lock - suppress error message
errorcheck on
debug 0
debug msg=0
lock > nul
commandline

```

**Comment by yaya2007** [comment]
Turn on/off or display the error check mode, or toggle it if no argument.
You've turned off error checking, but you want to display errors.  contradiction.

**Comment by steve6375** [comment]
There are two different problems.
First problem - lock only works if errorcheck is on. lock does not work if errorcheck is off. The lock command should not be afffected by the state of errorcheck status. The first menu goes to the commandline even when the user has not entered a password.
Second problem - I cannot prevent lock command from displaying the Error 32 message. I want to suppress the error message and just go back to the menu. The second menu always display the Error 32 message and I cannot find a way to suppress it.

**Comment by steve6375** [comment]
lock does not seem to work at all now!  :-(
a menu password is set - but it just ignores lock command

**Comment by steve6375** [comment]
lock was restored to original behaviour. Text will be added to  help lock.
