### ISSUE TITLE
standard and background colour no longer ignored if wallpaper used

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#226]
in 2019-12 versions
If use wallpaper and graphics mode - e.g. 800x600
If standard or normal has a background color - in previous versions then 'transparent' was used, but in recent versions the background color is used.

also $[0104] in echo is using standard background color

e.g.
```
graphicsmode -1 800 ;; splashimage /girl_blue_eyes.jpg
setmenu --ver-off 
 
color normal=light-magenta/cyan highlight=white/light-red  helptext=yellow/black  standard=black/red  border=0x1f

setmenu --string=10=0=0xFFFF00="--- STEVE'S MENU ---"
/hotkey -A > nul
```
![image](https://user-images.githubusercontent.com/1469350/71406215-6cdd9200-262f-11ea-8afd-dc7da21b1f09.png)

previous versions
![image](https://user-images.githubusercontent.com/1469350/71406354-d2318300-262f-11ea-90a1-bb3e97b2395f.png)

**Comment by yaya2007** [comment]
新版本请使用32位颜色表示。
没有特殊情况，加载背景图时，字符串以不使用背景色为好。

**Comment by yaya2007** [comment]
把 normal 放在第二位，或者更后。

**Comment by steve6375** [comment]
OK - but it is not compatible with previous versions.
Actually, I prefer it this new way :-)

**Comment by steve6375** [comment]
fixed
