### ISSUE TITLE
escape sequences in setmenu --string

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#227]
2019-12-24

```
graphicsmode -1 800 ;; splashimage /girl_blue_eyes.jpg
setmenu --ver-off
font /unifont.hex.gz
setmenu --string=79=36=0xFFFFCC="\X00A92017 easy2boot.com"
```
![image](https://user-images.githubusercontent.com/1469350/71408599-b7aed800-2636-11ea-9d59-248081f67fff.png)

**Comment by steve6375** [comment]
Also color black/cyan  does not work

```
splashimage --fill-color=0xCC77EE
color normal=black/cyan highlight=white/blue helptext=yellow/black standard=light-cyan/black border=light-green/black
```


![image](https://user-images.githubusercontent.com/1469350/71409542-e1b5c980-2639-11ea-9225-a3e44fec879b.png)

**Comment by yaya2007** [comment]
\x00表示终止符，结束字符串显示。

**Comment by steve6375** [comment]
\X00A9 is a valid unicode character ©

setmenu --string=79=36=0xFFFFCC="\X00A92017 easy2boot.com"  - this worked OK on 2012-10-28 version but not on 2019-12 versions.

**Comment by yaya2007** [comment]
2019-12-24版本已经修正.

**Comment by steve6375** [comment]
No - not fixed - hello  ->> **helloello**
Problem with string parsing
![image](https://user-images.githubusercontent.com/1469350/71438728-c5279900-26ee-11ea-8dbc-d31f957a2f72.png)

graphicsmode -1 800 ;; splashimage --fill-color=0xc68822
setmenu --ver-off --auto-num-on 
font /unifont.hex.gz
color 0xa
setmenu --string=
/hotkey -A > nul
setmenu --string==0=0x00="\X00A92017 hello"

**Comment by steve6375** [comment]
setmenu --string=i1=10=0=0x00="\x08 hello"
![image](https://user-images.githubusercontent.com/1469350/71438873-50089380-26ef-11ea-8461-f0f0a75ff3f0.png)

**Comment by yaya2007** [comment]
setmenu --string=79=36=0xFFFFCC="\X00A92017 easy2boot.com"
这个字符串位于菜单帮助显示区域, 被覆盖了.
试一试: setmenu --string=70=-0=0xFFFFCC="\X00A92017 easy2boot.com"

**Comment by steve6375** [comment]
Please look at examples!!!
setmenu --string==0=0x00="\X00A92017 hello"  >>> **helloello**   ERROR!
setmenu --string=i1=10=0=0x00="\x08 hello"     >>> **hellollo**      ERROR!

See screenshots!!!
Please test.   helloello  is not correct!!!

**Comment by steve6375** [comment]
setmenu --string=i1=10=0=0x00="\x08 123456"
setmenu --string=i2=70=0=0xFFFFCC="\X00A9 123456"

![image](https://user-images.githubusercontent.com/1469350/71477600-c934e300-27e2-11ea-9e40-43b6bf593af8.png)

**Comment by yaya2007** [comment]
抱歉！以前没有搞明白。原来是字符串解析后数量改变了。已经修正。
关于字符的背景色问题，现在的规则是：
在有背景图像时，只有字符串可以显示背景色。这就与以前兼容了。

**Comment by steve6375** [comment]
Thanks.  👍

**Comment by steve6375** [comment]
P.S. date&time does not use background colour.
setmenu --string=i3=75=0=0xFF000000FFFFFF="date&time=[dd-MMM-yyyy HH:MM:ssAP]"  = TRANSPARENT.
Is this a bug ?
![image](https://user-images.githubusercontent.com/1469350/71514015-c1357b80-2894-11ea-88de-16a18d8707f9.png)

**Comment by yaya2007** [comment]
确实有问题。已经修正。

**Comment by steve6375** [comment]
Looks good. 👍

**Comment by steve6375** [comment]
Problem with using m - does not work if box command is not used to set menu X Y size.
setmenu  --string=i1=m=0=0xFFFFFF000000FF="MY MENU"
Is this a bug ? s works OK.

```
graphicsmode -1 800
default 1
timeout 5
# set menu background colour to grey (444444) and menu text colour to yellow (FFFF00) (format is 0xrrggbb00RRGGBB)
color normal=0x44444400FFFF00
# set selected menu item to transparent 
color highlight=0xFF0000
setmenu --ver-off
# turn off menu outline border (use lower-case L)
setmenu --box l=0
# set grub4dos heading colour to black so we cannot see it
color heading=0
# clear any previous setmenu --string commands
setmenu --string=
setmenu  --string=i1=m=0=0xFFFFFF000000FF="MY MENU"

title Reboot
reboot

title grub4dos command line\nThis will take you to the command console\nPress ESC key to get back to the menu
commandline

title Power off\nSwitch off the system
halt

title   ---\n
errorcheck off
root ()

title Reload grub4dos\nReload grub4dos without rebooting
find --set-root /grldr
chainloader /grldr
```
![image](https://user-images.githubusercontent.com/1469350/71542704-66b62100-2961-11ea-95fb-29d4709ee867.png)

**Comment by yaya2007** [comment]
不算bug。box那样设置太变态。除了测试，没有人那样设置。

**Comment by yaya2007** [comment]
不算bug。box那样设置太变态。除了测试，没有人那样设置。

**Comment by yaya2007** [comment]
不算bug。box那样设置太变态。除了测试，没有人那样设置。

**Comment by steve6375** [comment]
graphicsmode -1 800
setmenu --ver-off
setmenu  --string=i1=m=0=0xFFFFFF000000FF="MY MENU"
![image](https://user-images.githubusercontent.com/1469350/71545166-b73c7700-297f-11ea-9f0c-614dd0dbfdc0.png)

Using s works OK, only m causes a problem.

**Comment by yaya2007** [comment]
Bug excludes.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/4007636/grldr.rar.txt)

**Comment by steve6375** [comment]
looks good 👍

**Comment by steve6375** [comment]
Problem!  m no longer works !!!  Not centred in menu.
```
graphicsmode -1 800
default 4
timeout -1
# set menu background colour to grey (444444) and menu text colour to yellow (FFFF00) (format is 0xrrggbb00RRGGBB)
color normal=0x44444400FFFF00
color border=0xFFFF00
# set selected menu item to transparent 
color highlight=0xFF0000
setmenu --ver-off
# set grub4dos heading colour to black so we cannot see it
color heading=0
# clear any previous setmenu --string commands
setmenu --string=
setmenu  --string=i1=m=1=0xFFFFFF000000FF="MY MENU"
setmenu --box x=13 y=3 w=60 h=23 l=1
color --64bit helptext=0x444444000000FF

title Reboot
reboot
```
![image](https://user-images.githubusercontent.com/1469350/71557175-6b9ad380-2a3a-11ea-8b15-e4af667338af.png)

**Comment by steve6375** [comment]
great! thanks.
