### ISSUE TITLE
password + date&time issue

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#228]
2019-12-30

If use
setmenu --string=75=0=0xffffff="date&time"
set pwd=123

then when you press p and enter password, the password prompt is also written to line 0
![image](https://user-images.githubusercontent.com/1469350/71785264-88fd0e00-2ff5-11ea-8893-7e5b96f23578.png)

**Comment by yaya2007** [comment]
It doesn't affect the use, it's just not beautiful.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/4024430/grldr.rar.txt)

**Comment by steve6375** [comment]
👍
