### ISSUE TITLE
grub4dos does not see 'valid' partition

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#232]
This partition is valid for Windows 10 and grub2, but is ignored by grub4dos.

![image](https://user-images.githubusercontent.com/1469350/73369144-0987f500-42aa-11ea-953e-ed43b5b6cabf.png)
![image](https://user-images.githubusercontent.com/1469350/73394532-b7f55f80-42d5-11ea-9c47-4a1b37ad4507.png)

**Comment by yaya2007** [comment]
磁头号是:0-fe，没有ff。
判断一个块有没有分区表，g4d是这样做的:激活位是00或80？磁头号小于ff?...

**Comment by steve6375** [comment]
grub2 and Windows have no problems with the FF FF FF parameters but grub4dos does not see the partition and will not boot from it (but \grldr is loaded OK).
grub4dos also must have non-zero type number.
Why head number < 0xff? I suggest this limitation is removed.
So criteria is:
1. Activation bit 00 or 80
2. Type number is not 0
3. Sector ends with 55 AA

**Comment by yaya2007** [comment]
给我一个设置磁头号为ff的充分理由。xxx忽略之类的话就免了。

**Comment by steve6375** [comment]
As I already said. grub2 and Windows see such a partition. grub2 can boot from such a partition.
Grub4dos does not boot from such a partition.
The FF FF FF partition was created by the a1ive grub2  'partnew' command.
This has now been fixed in new versions of a1ive grub2.
However, I see no harm in ignoring the head parameter as it is better to be able to boot to the partition than fail to boot (when grub2 boots OK).
Since the FF FF FF bug is fixed in a1ive grub2 now, I will close this issue.
