### ISSUE TITLE
map+chainloader not working with non-contiguous file 

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#233]
![image](https://user-images.githubusercontent.com/1469350/75100130-d2171a80-55c1-11ea-8477-b5968477a333.png)
File is on a FAT32 partition

**Comment by steve6375** [comment]
errorcheck is on
debug  is 1

**Comment by yaya2007** [comment]
debug=3试一试

**Comment by steve6375** [comment]
I thought map now supported non-contiguous files now?

**Comment by yaya2007** [comment]
现在map支持非连续文件.
不清楚为什么会返回磁盘读错误.

**Comment by steve6375** [comment]
If I make the iso contiguous then it boots ok.

Here is another file which also has same issue - this time on an NTFS partition
![image](https://user-images.githubusercontent.com/1469350/75106778-d53cf580-5617-11ea-8973-b0454fbc18cc.png)

**Comment by steve6375** [comment]
map command does not fail
![image](https://user-images.githubusercontent.com/1469350/75109218-55178f80-5619-11ea-8f4b-93f4262e2657.png)
older version works
![image](https://user-images.githubusercontent.com/1469350/75109395-5f865900-561a-11ea-9cd7-d4cab4c1a41f.png)

**Comment by steve6375** [comment]
2019-08-09 OK
2019-09-09 OK  (E2B v1.B6)

2019-10-28 FAIL (E2B v1.B7)
2019-12-30 FAIL
2020-01-28 FAIL

**Comment by steve6375** [comment]
No \menu.lst file.
File is on an NTFS volume.

![image](https://user-images.githubusercontent.com/1469350/75109669-61055080-561d-11ea-8522-f9989fb4536a.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/75109763-90688d00-561e-11ea-9452-b9adbb1a0df3.png)

**Comment by yaya2007** [comment]
Send the screenshot of BPb table of FAT32 partition

**Comment by steve6375** [comment]
I have the same issue with several files on two different USB drives.
Also one file was on a FAT32 volume and other files are on an NTFS volume.
I don't think it is anything to do with BPB or FAT or NTFS.
If I make the file contiguous then there is no error.
So it only happens on non-contiguous files.
Bug was introduced in 2019-10-28 version.

**Comment by steve6375** [comment]
Differences.

![image](https://user-images.githubusercontent.com/1469350/75142768-a7c17c00-56eb-11ea-822a-58aa7455633b.png)

???
![image](https://user-images.githubusercontent.com/1469350/75142685-8496cc80-56eb-11ea-8d19-f6bc26226de4.png)

**Comment by steve6375** [comment]
or maybe changes in
fsys_iso9660.c  ????
![image](https://user-images.githubusercontent.com/1469350/75148516-b877ef00-56f7-11ea-9f7d-43390636db03.png)

**Comment by steve6375** [comment]
Can you reproduce the problem?

**Comment by yaya2007** [comment]
试一试
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/4253916/grldr.rar.txt)

**Comment by steve6375** [comment]
grubfm.iso on FAT32 (2 fragments) OK
Win10_1909_64.iso on NTFS (4 fragments) OK
(both fail on previous versions)

**Comment by steve6375** [comment]
BobOmbs.iso on NTFS (4 fragments 3GB) OK

**Comment by steve6375** [comment]
Will you do a release version soon?

**Comment by steve6375** [comment]
Thank you! Great work. It looked like a lot of changes! 💯

**Comment by steve6375** [comment]
What happened to the release version? Was there a bug?
Why has it been removed?

**Comment by a1ive** [comment]
> What happened to the release version? Was there a bug?
> Why has it been removed?

http://bbs.wuyou.net/forum.php?mod=viewthread&tid=419164&extra=

**Comment by h8nor** [comment]
You can take [a template](https://github.com/FromEndWorld/LOFFER/generate) that will automatically update a static site on Github Pages. This server uses Jekyll, so no additional apps will need to be installed on the local machine.
