### ISSUE TITLE
[Feature Request] Format mem mapped partition?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [chenall/grub4dos#235]
Could you add ability to format a mem mapped device as ntfs?

**Comment by yaya2007** [comment]
不能

**Comment by BiatuAutMiahn** [comment]
please explain?

**Comment by yaya2007** [comment]
格式化的工具多了去了。有windows下的，有linux下的。格式化映射后的磁盘，完全可以先建立一个磁盘，格式化后再映射。我觉得，你的提议没有必要做。当然我不反对有闲心的人士去做此项事情。

**Comment by BiatuAutMiahn** [comment]
fair enough, thank you
