### ISSUE TITLE
问下 grub4dos 识别 gpt 分区吗？

### ISSUE THREAD

**Issue by Cooky-12** [chenall/grub4dos#236]
老机子只有 bios， gpt 装 linux
查了一圈，
一种是 hybrid mbr
一种是 grub2 + 特殊分区
另一种就是 syslinux 的 gptmbr.bin 即保持兼容又能从单独分区的 pbr 引导
syslinux 则是要吧 ldlinux.sys 的物理位置写死
只有 grub4dos 引导装在 pbr 的情况下又不需要把 grldr 物理位置写死
所以问下 gptmbr.bin -> pbr -> grldr 之后 grldr 能照常用吗？

**Comment by chenall** [comment]
只要你能启动到GRUB4DOS就可以发现有支持gpt分区格式.

**Comment by Cooky-12** [comment]
> 只要你能启动到GRUB4DOS就可以发现有支持gpt分区格式.

好哒，我去试试

**Comment by Cooky-12** [comment]
> 只要你能启动到GRUB4DOS就可以发现有支持gpt分区格式.

VBOX 里试了试，引导成功，分区也都识别了，非常感谢。
