### ISSUE TITLE
Request: ability to skip certain drive detection

### ISSUE THREAD

**Issue by SomeDude3** [chenall/grub4dos#239]
I would like to be able to tell Grub4DOS to skip detection of certain drive for example the third hard drive on a SAS/SATA port, and thus completely ignores that drive and doesn't bother trying to read the said drive.

**Comment by yaya2007** [comment]
You mean, don't look for SAS/SATA type disks? 
This can't be done.Because grub4dos only reads the disk through BIOS. He doesn't know what type of disk it is.

You mean,Don't look for a third disk?
I'm afraid that's not in line with most people's wishes .

**Comment by SomeDude3** [comment]
Yes, a user could specify which disk to not attempt to be read at boot time or tell grub4dos to not look for the specified disk. Sometimes a disk can force grub4dos to cease booting and throws out an error message and confusing the bootloader thinking it is a floppy disk which isn't. When the drive in question is pulled, grub4dos boots fine.

**Comment by steve6375** [comment]
Could you paste a screenshot of what you see please and describe how to reproduce the problem.
Do you have a native 4k sector internal SATA hard disk attached?
Does grub4dos fail to load the menu.lst and hang or exit to the console?
What do you observe?

**Comment by SomeDude3** [comment]
upon boot it shows "Try (fd0): extended or non-MS-Skip error" and yes it is a native 4K sector drive with zero emulation for 512 byte sector. So basically Grub4Dos doesn't even reach menu.lst or it's own internal menu.lst embedded inside the grldr file. You cannot do anything when the error pops up and you cannot do anything before the error either. However I did find out that if you chainload grub4dos from grub2, it loads up without any issue using the .exe version of grub4dos. I'm thinking the bootloader probably lacks the ability to read from 4K native drive, but I don't know. To reproduce the problem, is to insert a 4K native drive and boot grub4dos off on any other drive that has mbr and uses 512byte emulation, even a USB flash drive. Take out the 4K drive and try booting again it will succeed. I don't know if capacity of the drives matters or not but I do not yet own any other drive with a different capacity with 4K native sectors without emulation. The 4Kn drive in question is an 8TB drive.
So perhaps add support for 4Kn drive or the ability to skip it altogether would be great if possible.
Thank you in advance.

**Comment by yaya2007** [comment]
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=418662&extra=page%3D2

**Comment by steve6375** [comment]
Could you paste a screenshot of what you see please and describe how to reproduce the problem.
As I understand it, you are saying that grub4dos will not boot from a MBR USB flash disk if a native4K disk is present in the same system.
Due to language difficulties, a picture is much better.
Please post a picture of the error that you see.

**Comment by SomeDude3** [comment]
@yaya2007 The forum doesn't seem to pertain to my booting issue, and that forum said not able to run DOS when the 4K device is present and doesn't say anything about grldr booting and seems to point out that DOS cannot be booted. Maybe that could be the actual issue, but miss worded. Also I cannot download from the forum because it requires registration and cannot create an account due to the language barrier. Could you post a direct link here and upload that version of Grub4DOS somewhere else like on MEGA or mediafire?
Should I continue using Grub2 to get around the issue?
@steve6375 Yes, you have understood correctly. As for the picture:
![Grub4DOS4KnError](https://user-images.githubusercontent.com/63427332/79145432-441c0c80-7d86-11ea-8ede-4aa2bd9aa225.jpg)
That literally all it says and only a three finger salute (Control+Alt+Delete) will work.
Should I continue using Grub2 to get around the issue?

**Comment by yaya2007** [comment]
Can't download attachments without registering? I'm sorry!

This unpublished version supports booting from a native 4K disk.
Support native 4K disk boot from FAT, exFAT, NTFS partition.
Boot to grub4dos environment, of course .

You can load a normal disk image from a native 4K disk. 
You can load a 4K disk image from a normal disk

You can try and hope to solve your problem .

**Comment by yaya2007** [comment]
[grub4dos-0.4.6a-2020-01-29.7z.txt](https://github.com/chenall/grub4dos/files/4472574/grub4dos-0.4.6a-2020-01-29.7z.txt)

**Comment by SomeDude3** [comment]
No problem and thank you for the download. Surprisingly it didn't work, the error is the same. Even in MBR or PBR. However when using UMBR with your provided version of Grub4DOS and the latest Grub4DOS boots up without any issue.
Linked [here](http://chenall.net/post/grub4dos_umbr/#more) is what fixed the issue. So I we can call this issue resolved.

**Comment by yaya2007** [comment]
Is one of your disks a GPT partition?

**Comment by SomeDude3** [comment]
As a matter of fact it is. Actually two of them. One of them is a 4TB drive but has 512Byte sectors and another is that 4Kn drive. The grldr rest on the non GPT disk though as that is serving as my "boot" drive. I had the 4TB one in for years without issue.

**Comment by SomeDude3** [comment]
Welp it appears to have been an user error on my part. I apologize for wasting everyone's time. It appeared that Wingrub was the issue when I used it on a primary boot disk a long time ago, and it took a while for the error to eventually crop up.
