### ISSUE TITLE
Would you release a ia32 UEFI version ?

### ISSUE THREAD

**Issue by galaxy001** [chenall/grub4dos#247]
I am trying to use grub4dos with windows 10 x86, and I find the UEFI release will not run under 32 bit EFI.

Would you release a ia32 UEFI version ?

**Comment by a1ive** [comment]
Yes, we are working on this.

**Comment by yaya2007** [comment]
[BOOTIA32.rar.txt](https://github.com/chenall/grub4dos/files/5658636/BOOTIA32.rar.txt)

**Comment by galaxy001** [comment]
I have test it with the example menu.lst.

The binary will not load `/menu.lst`, and Chinese mode will make all characters become squares.

These few days are local black-Monday, so I donot have extra time to test it.

I hope you can include the default mini menu.lst to add more search path for external menu.lst.

------

Hoping there will be a reason for closing this issue. Will this project continue trying to support IA32 ?

**Comment by a1ive** [comment]
> Hoping there will be a reason for closing this issue. Will this project continue trying to support IA32 ?

See https://github.com/chenall/grub4dos/releases/tag/2020-12-10-50084c6
> I hope you can include the default mini menu.lst

Already included.
> The binary will not load /menu.lst

The configuration file should be /efi/grub/menu.lst.

> Chinese mode will make all characters become squares.

There is no such thing called "Chinese mode". If you use the graphic mode, then you need to load the font, which is already mentioned in the sample menu.lst.

See http://reboot.pro/topic/22400-grub4dos-for-uefi/ for details in English.

**Comment by galaxy001** [comment]
https://github.com/chenall/grub4dos/blob/3c1d05f39e49ec1d7543caa825df00068b96620b/preset_menu.lst#L6-L14

I thought it should load `/menu.lst`, isn't it ?

**Comment by a1ive** [comment]
https://github.com/chenall/grub4dos/blob/50084c662fdcf46e83a58c4b5f3f060ed3b0454b/stage2/disk_io.c#L4161
