### ISSUE TITLE
configfile command appears broken

### ISSUE THREAD

**Issue by pendrivelinux** [chenall/grub4dos#252]
Nice work on grub4dos for UEFI. It is coming along nicely. 
I'd like to report an issue experienced when trying to load another configuration file.

When using the configfile command to load another configuration file (for example: configfile /pathto/new.lst), the following error is reported;
Error 28
 "selected item cannot fit into memory"

**Comment by yaya2007** [comment]
The file name path is too long .
Post the original "/pathto/new.lst".

**Comment by pendrivelinux** [comment]
@yaya2007 
The configfile path is broken on the last version of "Grub4Dos for_UEFI 2021-01-12" though it works fine in the "Grub4Dos for_UEFI 2020-12-29" build.

For example the path can be as short as follows with menu2.lst being at root, and Error 28 will still result:
configfile /menu2.lst

**Comment by pendrivelinux** [comment]
@yaya2007 The broken configfile path issue appears fixed as of "Grub4Dos for_UEFI 2021-01-22".

Thank You!
