### ISSUE TITLE
能问下 EFI 版怎么加载 efi 文件？ 

### ISSUE THREAD

**Issue by Cooky-12** [chenall/grub4dos#256]
是 chainloader 那个 efi 文件然后 boot ？
用的 grub4dos-for_UEFI-2021-02-10.7z 的 boot 之后没有任何反应还在提示符下
而且还能继续输入命令，会是和那个 efi 文件不兼容？

我是在 z8350 的老破烂平板上启动 archlinux 的启动盘，但是平板的 bios 启动不了 archlinux 的 efi 文件，我就试试换成 grub4dos 的，结果还真起来了，但是不能 chainloader archlinux 的 efi 文件，也许是垃圾平板的 bios 太垃圾启动不了 archlinux 的 efi 文件？

结果最后还是自己写 menu.lst 把启动盘带起来

**Comment by yaya2007** [comment]
看来，问题你已经自己解决了。
可否把有关的菜单貼出来。

**Comment by Cooky-12** [comment]
> 看来，问题你已经自己解决了。
> 可否把有关的菜单貼出来。

半解决吧……感觉是没办法用 arch 的 efi 了。
menu.lst 完全就是照着 arch 启动盘的参数改的直接加载 kernel 和 initrd，
自己做的 arch efi 启动盘也很简单，U盘建个 FAT32 分区，把 iso 文件解压到那个分区，用 grub4dos 的 efi 替换 arch 的 efi 文件，然后启动的时候从那个分区引导。
很神奇的是 arch 的 efi 有时能加载有时不能加载，只有 grub4dos 的 efi 是一直能加载的，看来确实是 bios 有 bug ……
