### ISSUE TITLE
New additional ext folder into last grub4dos-0.4.6a versions, for MBR and also for UEFI

### ISSUE THREAD

**Issue by Taviruni** [chenall/grub4dos#258]
First I want to thank you for all the work and time you spend on this fantastic program, in its two versions MBR and UEFI.

New additional **ext folder** into grub4dos-0.4.6a-2021-01-27.7z  (for MBR) and into grub4dos-for_UEFI-2021-02-10.7z

This is not really an issue, it is really a request of info about where we should locate the new additional **ext folder**, and also a brief description of each file contained into that folder, and additionally the syntax required to use/run those commands on MBR and also on UEFI versions.

Thanks in advance for your answer.

Your very grateful friend

alacran (from reboot.pro)

**Comment by Taviruni** [comment]
I'm going to (partially) answer myself, the **ext folder** contains a set of the previously called **grubutils** (external utilities that can be run from grub4dos).

On this page on **RMPrepUSB** site by our fellow **steve6375**, I found a brief description and info of their use, at least for the MBR version of grub4dos:  https://www.rmprepusb.com/tutorials/grubutils

The page also includes interesting info to make use of this utilities on the creation of Batch files for grub4dos (MBR version).

NOTE: It seems the linked page on RMPrepUSB is not very recent and some info could be outdated.

**It would be good if some of our chinese friends, that come frecuently to reboot.pro forum, and have more knowledge of the recent developments in grub4dos for MBR and also for UEFI could give us a more complete and updated info.**

alacran (from reboot.pro)

**Comment by chenall** [comment]
这里面也有一些资料 http://chenall.net/categories/GRUB4DOS/
中文的资料应该主要在 http://bbs.wuyou.net 

我英文比较菜，仅限于大致看得懂的程度，使用英文发贴对于我来说是一个折磨 :cry:

**Comment by Taviruni** [comment]
Thanks for your answer.

I will read your links.

alacran (from reboot.pro)

**Comment by whileloopa** [comment]
[Example use and info about "hotkey" external command (in Chinese).](http://grub4dos.chenall.net/utils/hotkey/)
And at the (grub>) command prompt, type "command" to find out current working directory.
If external commands are put in this directory you can execute them directly.
If external commands are put in another directory, you have to use the "command" keyword
grub> command (bd)/path-to-ext-folder/wenv
