### ISSUE TITLE
Does calc | work?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#26]
In console
e.g.
calc 4 | 6 ;; echo %@retval%

calc 4|6 works, but if there are spaces it doesn't!

help calc
shows spaces between arguments, some things do not work with spaces between operators. e.g.

| % >> << 

but * / - + ^ & work with spaces

grub4dos 0.4.5c 2014-11-15  and 2015-01-10

**Comment by steve6375** [comment]
P.S. Can help for calc command make it clear that  ^ is XOR and not power function?

**Comment by steve6375** [comment]
Also this doesn't work

calc 6 % 2

??

**Comment by chenall** [comment]
I do not understand what you mean?
Current  `^` is already XOR.

**Comment by steve6375** [comment]
Yes - but the help text
help calc
does not explain what ^ means - in some languages ^ means 'to the power of' e.g.  2^2=4. Can you add some help text to say ^ means XOR.
also please fix spaces
calc 4 | 6    does not work
calc 4|6    works

help calc - text says there should be space between parameters but it only works if no spaces.
operators | % >> <<  cannot have spaces,
but * / - + ^ & work with spaces and without.

**Comment by chenall** [comment]
Ok,Thanks.

**Comment by steve6375** [comment]
Help text not yet changed in 0.4.5c  (just a reminder!)
