### ISSUE TITLE
grub4dos efi stops showing just a cursor

### ISSUE THREAD

**Issue by A-Shahbazi** [chenall/grub4dos#260]
It happens either chainloading bootx64.efi from grub2 efi loader or directly booting to grub4dos bootx64.efi from boot menu(with the slight difference that chainloading through grub2 doesn't show the cursor).
Both grub2 and microsoft efi loaders work on my system so there should be some issue with grub4dos efi.
I did't know what data to provide because the system stops responding there and I have to power off.
grub4dos bios loads perfectly, BTW.

**Comment by yaya2007** [comment]
title boot efi file
chainloader /efi/boot/grub2x64.efi

titleboot windows
chainloader /efi/microsoft/boot/bootmgfw.efi

**Comment by A-Shahbazi** [comment]
> title boot efi file
> chainloader /efi/boot/grub2x64.efi
> 
> titleboot windows
> chainloader /efi/microsoft/boot/bootmgfw.efi

menu items weren't the issue. However, I checked with the 2021-04-24 build and the issue seems to be solved(both when chainloading and booting from boot menu)

**Comment by A-Shahbazi** [comment]
PS: I was experiencing the issue with 2021-02-10 build.
