### ISSUE TITLE
Questions about grub4dos efi

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#263]
Sorry for asking here but I have some Q's and observations:
1. If grub4efi executes a menu.lst file - what is the best way to determine if the menu file is being run in EFI64, EFI32 or Legacy grub4dos?
2. Where can I find EFI32 and EFI64 equivalents of the Legacy hotkey utility which adds first letter hotkey to menu system?
3. If a Legacy utility (such as hotkey) is executed within the UEFI64 grub4dos version - it hangs (e.g. hotkey -u). Could it just not execute?
4. Can parttype command be implemented please?
5. Page scrolling  - does not seem to quit when prompted with  '[Hit Q to quit, or any other key to continue]'
6. Ctrl-C - Terminate batch job (Y/N)? - does not quit when Y is typed when executing a batch file
7. What are files in \ext folder in download and how are they used and where are source files?
8. What are \x86_64-efi and \i386-efi folders in download?
9. root command does not check for invalid path and does not return an error - e.g.  root (hd0,0)/noexist

**Comment by a1ive** [comment]
> 1. If grub4efi executes a menu.lst file - what is the best way to determine if the menu file is being run in EFI64, EFI32 or Legacy grub4dos?

By default, grub4dos loads `/menu.lst`, while grub4efi loads `/efi/grub/menu.lst`.
You can use the variable `%@uefi%` to determine whether IA32 UEFI or X64 UEFI.
> 2. Where can I find EFI32 and EFI64 equivalents of the Legacy hotkey utility which adds first letter hotkey to menu system?

https://github.com/chenall/grub4dos/blob/630dc20f6e6b184a87f227ddbf6e723721d38b1d/ChangeLog_UEFI.txt#L101
> 3. If a Legacy utility (such as hotkey) is executed within the UEFI64 grub4dos version - it hangs (e.g. hotkey -u). Could it just not execute?

You can't execute ANY legacy utilities.
The package contains external commands for the corresponding environment, but there are still some problems under uefi, please download them here.
https://github.com/chenall/grubutils/releases/download/latest/g4eext-2021-04-26.zip
> 4. Can parttype command be implemented please?
> 5. Page scrolling - does not seem to quit when prompted with '[Hit Q to quit, or any other key to continue]'
> 6. Ctrl-C - Terminate batch job (Y/N)? - does not quit when Y is typed when executing a batch file
> 9. root command does not check for invalid path and does not return an error - e.g. root (hd0,0)/noexist

I can't answer these questions.
> 7. What are files in \ext folder in download and how are they used and where are source files?

see (3).
> 8. What are \x86_64-efi and \i386-efi folders in download?

You have to use `grub-mkimage` to create the efi file with custom built-in menus (like grub2).
https://github.com/chenall/grub4dos/blob/630dc20f6e6b184a87f227ddbf6e723721d38b1d/build#L143

**Comment by steve6375** [comment]
Thanks for reply.  setmenu --hotkey seems to hang ??? Can't see it mentioned in help output (help setmenu) either.

**Comment by steve6375** [comment]
hangs
![image](https://user-images.githubusercontent.com/1469350/117492330-5e182680-af69-11eb-98ac-de45686e6742.png)
![image](https://user-images.githubusercontent.com/1469350/117498221-6bd1aa00-af71-11eb-9a95-985356d3374f.png)

**Comment by yaya2007** [comment]
I test normal here.
%@uefi% == 0,  Legacy.

**Comment by steve6375** [comment]
hotkey seems to run from batch file/menu file - just not from command line.
How can we uninstall  hotkey (to reset all settings and re-install)?

re. @uefi   this is not defined in legacy grub4dos. What do you mean by %@UEFI% == 0  ???

**Comment by steve6375** [comment]
setmenu --hotkey [F8] "reboot"

This hangs when run from batch file and as a menu entry.

**Comment by steve6375** [comment]
setmenu --hotkey -A
hangs if run from a batch file from command line (not from a menu)

**Comment by yaya2007** [comment]
> How can we uninstall hotkey (to reset all settings and re-install)?
setmenu --hotkey -u

> @UEFI this is not defined in legacy grub4dos
yes.
"%@UEFI%"==    "64"/"32"/""    x64/ia32/Legacy

**Comment by steve6375** [comment]
setmenu --hotkey -u
hangs if run in batch file :-(

**Comment by yaya2007** [comment]
Is the hotkey of g4d and G4e external or internal? It's rather tangled. You can only choose one.

**Comment by steve6375** [comment]
Internal.
Presumably external g4d  hotkey would still work?

**Comment by yaya2007** [comment]
[grub4dos-0.4.6a-2021-05-13.7z.txt](https://github.com/chenall/grub4dos/files/6471356/grub4dos-0.4.6a-2021-05-13.7z.txt)

**Comment by steve6375** [comment]
It seems OK - however the hotkey utility no longer works properly, so it is no longer compatible.
This means that the new version will not work with menus that use the hotkey utility.
The menu appears OK (no ^A displayed) but hotkeys do not work and first letter jump feature does not work.

**Comment by yaya2007** [comment]
Emphasize compatibility, so both G4D and G4E application use external hotkeys. 

Hotkey example：
hotkey -A [F4] commandline
title ^F3 reboot
title [F3] reboot
title ^W BOOT W10n64.iso
title [W] BOOT W10n64.iso
title ^ctrl+d commandline

**Comment by steve6375** [comment]
Is new build OK ?

![image](https://user-images.githubusercontent.com/1469350/118792064-34c39880-b88f-11eb-82d9-302b3ce25d93.png)

**Comment by a1ive** [comment]
> Is new build OK ?
> 
> ![image](https://user-images.githubusercontent.com/1469350/118792064-34c39880-b88f-11eb-82d9-302b3ce25d93.png)

same
