### ISSUE TITLE
Latest grub4dos (Legacy) release fails with SYSTEM STACK RUNOUT error

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#264]
If I replace \grldr in Easy2Boot USB drive with latest version, I get this error message and menu fails to display - drops to commandline.
![image](https://user-images.githubusercontent.com/1469350/117532775-2f3d9700-afe1-11eb-868c-9f630599a63d.png)
grub4dos-0.4.6a-2021-04-28.7z\grub4dos-0.4.6a\grldr used

error is produced when this line is executed
/%grub%/AUTOMN.g4b .automenu /_ISO/MAINMENU

**Comment by steve6375** [comment]
grub4dos-0.4.6a-2021-01-27.7z is OK

**Comment by yaya2007** [comment]
How to reproduce ？

**Comment by steve6375** [comment]
1. Make an Easy2Boot USB drive
2. replace /grldr

**Comment by yaya2007** [comment]
Please provide AUTOMN.g4b .automenu 
MAINMENU

**Comment by steve6375** [comment]
https://www.fosshub.com/Easy2Boot.html?dwl=Easy2Boot_v2.08_password_is_e2b.zip

**Comment by steve6375** [comment]
[E2B Files (reduced).zip](https://github.com/chenall/grub4dos/files/6445792/E2B.Files.reduced.zip)
Copy to empty NTFS Partition 1 USB drive (only partition).

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/6448960/grldr.rar.txt)

**Comment by steve6375** [comment]
It does not crash but there is a problem with it.
If you replace \grldr on an easy2boot USB drive, you get multiple menu entries
![image](https://user-images.githubusercontent.com/1469350/117663080-29d67d00-b198-11eb-8583-659dbfc77251.png)
Here is old grldr which works as expected
![image](https://user-images.githubusercontent.com/1469350/117663236-55596780-b198-11eb-9fb5-a483096d789f.png)

**Comment by yaya2007** [comment]
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/6457902/grldr.rar.txt)

**Comment by steve6375** [comment]
That seems good now :-) thanks
P.S. Do you intend to add  setmenu --hotkey  to legacy grub4dos to make it compatible with EFI grub4dos?
Would be very nice if both versions supported same commands, so we can use same 'theme' menu settings for both and then just load different  file for menu entries depending on MBR, UEFI32 or UEFI64 environment.

**Comment by yaya2007** [comment]
Do you mean to add built-in hotkey in grub4dos? It can be considered.

**Comment by steve6375** [comment]
thanks
