### ISSUE TITLE
Splashimage --animate parameters in grub4efi are not compatible with grub4dos legacy

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#265]
The delay parameter in grub4dos for efi is not compatible with grub4dos legacy.
So a .cfg file which contains settings for the menu (background, hotkeys, language, fonts, animation, etc.) will not work for both  grub4dos legacy and grub4dos efi.

Please could you use the same delay syntax as for legacy grub4dos so that documentation and cfg files, etc. are identical.
i.e.  number = timer ticks,  or nnn:ms specifies milliseconds (as in legacy vesion).

**Comment by yaya2007** [comment]
adoption

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6448963/BOOTX64.rar.txt)
