### ISSUE TITLE
grub4dos legacy hotkey issue

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#266]
![image](https://user-images.githubusercontent.com/1469350/119953853-56f79d80-bf96-11eb-969e-dc88d659137e.png)

Using todays grldr and ext\hotkey

Also spelling mistake
![image](https://user-images.githubusercontent.com/1469350/119954156-9d4cfc80-bf96-11eb-9385-67163d837a39.png)

Old hotkey is OK
![image](https://user-images.githubusercontent.com/1469350/119954419-ddac7a80-bf96-11eb-89b5-291cf53a2e6c.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/119954669-2401d980-bf97-11eb-8abf-06837f20b472.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/119955443-f701f680-bf97-11eb-907f-b8a99326f164.png)
This is not compatible with previous versions?

**Comment by a1ive** [comment]
> ![image](https://user-images.githubusercontent.com/1469350/119955443-f701f680-bf97-11eb-907f-b8a99326f164.png)
> This is not compatible with previous versions?

yes.
http://bbs.c3.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=422652&pid=4294379&fromuid=505580
(1510#)

**Comment by yaya2007** [comment]
[g4d_hotkey.rar.txt](https://github.com/chenall/grub4dos/files/6563956/g4d_hotkey.rar.txt)

**Comment by steve6375** [comment]
Looks OK :-) thanks
