### ISSUE TITLE
Hello, can you mount multiple discs

### ISSUE THREAD

**Issue by xuese333** [chenall/grub4dos#268]
Similar to the Debian 3 DVD discs, the first is for booting, the second and the third are for software, and they are mounted at the same time

**Comment by a1ive** [comment]
你指的是 GRUB4DOS 的 UEFI 版本还是 BIOS 版本？
ISO 内具体是什么系统？

**Comment by xuese333** [comment]
那个版本都可以，linux系统，Debian有3张dvd光盘，第一张是系统安装光盘，第二张第三张是工具光盘，安装时有软件在第二张和第三张内，所以一张光盘不行。大致的意思就是启动的时候直接挂载三张光盘，cdrom1~3

**Comment by a1ive** [comment]
GRUB4DOS 创建出的虚拟磁盘只在 bootloader 阶段有效。进入 Linux 或其他系统之后虚拟磁盘就不存在了，无法达到你想要的效果。

**Comment by xuese333** [comment]
好的，谢谢
