### ISSUE TITLE
0.4.6a and exFAT - Warning: messages issue

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#27]
debug 1
parttype (hd0,3) | set check=

on large 256GB exFAT drive, check is set to '!! number of heads for drive 80 restored from 255 to 256.'

also get  'get-diskinfo ....' messages on ls command if debug 2 or 3 used.
works OK on latest 0.4.5c.

does not work on 2014-11-27 0.4.6a or later (not tried earlier) - e.g. under VBox:
![image](https://cloud.githubusercontent.com/assets/1469350/5738527/2e15af32-9be5-11e4-8555-77e839404db6.png)

I think similar issue was fixed in 0.4.5c.

Also, if use debug 3  then extra messages cause problems:
e.g.
debug 3
parttype (hd0,0) | set check=

![image](https://cloud.githubusercontent.com/assets/1469350/5738790/57aa86ee-9be8-11e4-9ef8-aa6578f60888.png)

**Comment by chenall** [comment]
if debug >1 then  debug is on,it will show all message.

**Comment by steve6375** [comment]
My point is that some messages are sent to  stdio when they should be sent to stderr.

e.g.
debug 1
parttype (hd0,3) | set check=

does NOT WORK!!! on large exFAT drives because error messages are sent to stdio.

e.g. 'getdisk_info ...' and  '!! number of heads for drive 80 restored from 255 to 256.' messages are sent to stdio and not error output and so above command does not work as expected.

**Comment by chenall** [comment]
Ok,Please try this
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-01-15.7z

**Comment by steve6375** [comment]
better - but still some problems...

Problem 1
write 0x8274 0x10002001 > nul
echos to screen even though redirected to nul!

Problem 2
debug 2  (or 3)
parttype (hd0,0) > (md)0x300+1
cat (md)0x300+1

displays: 'Initial estimation: Cmax=1023, Hmax=254.... etc  etc.
so cannot debug!

Problem 3
in a batch file
ls | call :copyfiles
does not work unless debug 0 is used (this can be worked around by using debug 0 first)

There may be some more bugs but E2B hangs/crashes in "LstFExt.g4b /_ISO/WINDOWS/SVR2012 .iso" at the line  'ls | call :copyfiles'  and cannot debug easily as debug needs to be 0 and using your new debug command doesn't help as it works when I use that! It runs OK when enumerating some folders but not SVR2012 folder!

Why are these exFAT warning messages necessary to be seen on every disk related command? Maybe just on root command?

**Comment by chenall** [comment]
1. because the debug/warning info will send to "stderr", can not redirected to nul! 
I think we need a new args for debug.e.g.
debug stdout=[0|1]
3. what is `ls` output?

http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-01-16.7z

**Comment by steve6375** [comment]
If I set debug stdout=1 it is better but still problems:

partype  with debug 2  and debug stdout = 1 or 0
![image](https://cloud.githubusercontent.com/assets/1469350/5773431/83204afc-9d5a-11e4-9bc6-3f1b11996ba5.png)

redirect to nul on write command - messages are output! In 0.4.5c using > nul suppresses messages.
![image](https://cloud.githubusercontent.com/assets/1469350/5773980/a2af8a94-9d60-11e4-9568-11bc1c5674b9.png)


LstFExt.g4b is still hanging on one particular folder (it lists all file with a particular extension) - this may be a exFAT file handling issue? DD=1 in example below:
![image](https://cloud.githubusercontent.com/assets/1469350/5773835/1843b854-9d5f-11e4-8186-eab7922fe9bf.png)
![image](https://cloud.githubusercontent.com/assets/1469350/5773851/3d9b3af0-9d5f-11e4-87ce-918299a6c913.png)

maybe 
debug errmsg=[0|1|on|off]
not everyone understands what stdout means!

**Comment by steve6375** [comment]
lsFExt.g4b
========

!BAT
:: GRUB4DOS batch script. See Tutorials at www.rmprepusb.com  [SSi]
::
:: Uses: List current root drive for files with a matching file extension (case insensitive)
:: Usage:  %1 is folder to search, %2 is a partial filestring to find
::
::         (bd)\LstFExt.g4b  /_ISO .iso [SILENT]
::
:: variables FILEDIR  FILEPATH   FILENAME  FILEEXT  are set on return if successful
::
:: A list of set FILE_xx=sdsdsd commands will be in memory at (md)0x900 after completion
:: If this batch file is called, e.g. 'call (md)0x900+0x10', then the FILE_xx variables will be set
::
:: Note: debug is ON after completion
::
:: Advanced example with debug enabled - searches a hard disk image for a .com file
::  
:: title Test FileSearch
:: map  (bd)/harddisk.img (hd2)
:: map --hook
:: root (hd2,0)
:: # set DD=1
:: pager off
:: # look for a file with a .iso extension - param1=start folder   param2=extension
:: (bd)/LstFExt.g4b / .iso
:: if not "%FILEPATH%"=="" echo FILE FOUND AT %FILEPATH%! 
:: if "%FILEPATH%"==""  echo No file with matching extension found!
:: # get all filenames as FILE_x variables...
:: call (md)0x900+0x10
:: echo FILE_1=%FILE_1%  FILE_2=%FILE_2%
:: pause
:: root
::
:: This script requires GRUB4DOS 2010-12-14 or later.
::
:: History
:: =======
:: version 2 2013-05-13
:: version 3 2014-07-14 improve speed - no delmod on exit to keep in memory
::=============================================================================

::set DD=0
::Uncomment line below to show debug lines or set DD=1 before calling
::set DD=1


if "%1"=="" goto :eof
if "%2"=="" goto :eof
set sh=%3

:: we don't want any extra messages - debug off = 0  so large exFAT drives work (grub4dos bug)! 
debug off

:: Variables: %0=/xx/xxx.bat %~nx0=automenu.bat %~nx1=.automenu %1=.automenu %~x1=.automenu
::echo 0=%0 nx0=%~nx0 nx1=%~nx1 nx2=%~nx2 nx3=%~nx3 1=%1 x1=%~x1

:: Check if loaded - if not load it
if not "%MOD%"=="1" delmod -l %~nx0 > nul || insmod %0 > nul

set FILEDIR=
set FILEPATH=
set FILENAME=
set FILEEXT=
set FCOUNT=0

set n=0
:: set COUNT in memory to start at 0
write 0x500004 0 > nul
:: clear batch file in memory
echo !BAT > (md)0x3000+1

:: reset finish flag
:: WRITE FINISH FLAG INTO MEMORY at 0x500000 = 0  (set to 1 when we find a match)
::write 0x500000 0  > nul


:: %1 is folder  %2 is search string
:: get the Search String
set SS=%2
if not "%SS:~0,1%"=="." echo 2nd parameter must start with . for a valid file extension! && pause && goto :eof
:: get the folder into DIR variable

set DIR=%1
if not "%DIR:~0,1%"=="(" set DIR=()%DIR%
::echo Using %DIR% as start folder for search
if "%DIR%"=="()/" set DIR=()

echo !BAT > (md)0x900+0x10
::echo Looking for first %SS% file, starting at %DIR%/ - please wait...

:: bugfix no need to ls dir as it is done in :cpa!
:: ZZZZ  ls %DIR%/ | call :cpa
call :cpa


:endloop
set DIR=
set SS=
:: set root back to top level at end!
root (bd)/ > nul

:: call the batch file to get variables
call (md)0x3000+1
:: get FILE_n variables
echo -e \x0 >> (md)0x900+0x10
######call (md)0x900+10
::debug 1
::echo %0 HAS FINISHED
set sh=
set n=
write 0x500004 0 > nul
errorcheck on
::delmod %~nx0 > nul

exit

:: ----------------------- SUBROUTINES ----------------------

:.findfile
if "%DD%"=="1" echo @findfile  Checking %DIR%/%1
if "%1"=="" endlocal && goto :EOF

setlocal
::If is a directory or ZERO length - ignore it
::ZZZcat --length=0 ()%DIR%/%1 > nul || goto :EOF

:: if not correct file then ignore
if "%DD%"=="1" echo findfile: checking %~x1 extension for %SS%
if /i not "#%SS%#"=="#%~x1#" goto :EOF
:: WE FOUND A MATCH!!!!!!

#echo %sh% %SS%
if not "%sh%"=="SILENT" echo %1 

read 0x500004 > nul
set n=%@retval%
set /a n=%n% + 1 > nul
write 0x500004 %n% > nul


:: make a batch file in memory to get the variables later on
echo !BAT > (md)0x3000+1
echo set FILEPATH=%DIR%/%1 >> (md)0x3000+1
echo set FILENAME=%1 >> (md)0x3000+1
echo set FILEEXT=%SS% >> (md)0x3000+1
echo set FCOUNT=%n% >> (md)0x3000+1
::echo FOUND %DIR%/%1
if "%DIR%"=="()" set DIR=/
echo set FILEDIR=%DIR% >> (md)0x3000+1
if "%DIR%"=="/" set DIR=()
echo -e \x0 >> (md)0x3000+1

:: add ISO variable  FILE_n=filename
echo set FILE_%n%=%1 >> (md)0x900+10

endlocal

:: THIS SECTION FOR DEBUG
if not "%DD%"=="1" goto :DD1
echo calling (md)
:: call the batch file to get variables
call (md)0x3000+1
echo called (md) OK
:: if "%DD%"=="1" echo ********** SHOW ALL VARIABLES **************
:: if "%DD%"=="1" set
:: if "%DD%"=="1" echo ********************************************
:: if "%DD%"=="1" echo PAUSED FOR DEBUG && pause
::pager on
debug 1

:DD1
:: signal we have found a match!
::write  0x500000 1 > nul
:: ZZZZread 0x500000 > nul
goto :eof


:cpa
if "%DD%"=="1" echo @CPA: Current Root: %DIR% - Changing source root to %DIR%/
::ZZZif not exist %DIR%/ errorcheck off
debug 0
root %DIR%/ > nul
pause aaa
ls
echo
set D

pause bbb
ls
ls | call :copyfiles
pause ccc
goto :EOF

:copyfiles
if "%DD%"=="1" echo @COPYFILES %1 && pause
if "%1"=="" goto :eof
::checkrange 1 read 0x500000  > nul && goto :EOF
::If is a directory

:: DONT DO SUBDIRS
::cat --length=0 /%1 > nul || goto :sub-dir

if "%DD%"=="1" echo @COPY FILE
call :.findfile %1
shift
goto :copyfiles

:sub-dir
if "%DD%"=="1" echo @SUB_DIR %1
setlocal
set DIR=%DIR%/%1
call :cpa
endlocal
shift
goto :copyfiles

**Comment by steve6375** [comment]
Does not hang if use  new debug xxx.g4b command, however filename is not correct??
CHOOSE\ FRO    ???  should be CHOOSE\ FROM\ A\ LIST.key


![image](https://cloud.githubusercontent.com/assets/1469350/5774381/0136337a-9d65-11e4-94c2-8788ad955552.png)

**Comment by steve6375** [comment]
0.4.5c on same exFAT USB drive - file name is correct
![image](https://cloud.githubusercontent.com/assets/1469350/5774484/42e8c35e-9d66-11e4-8316-12dc95b71d1b.png)

**Comment by chenall** [comment]
There has bug in prev version(bat script running bug)
please try new.

debug msg=0|1|2|3

0 ==> will disable all message even debug 2
1 ==> show stdmsg to stdout,warnning and error message to stderr.
2 ==> show stdmsg and warnning stdout,error message to stderr.
3 ==> show all message to stdout.

to stderr means cannot not using > nul suppresses messages and cannot redirect by `|`

http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-01-16-test.7z

**Comment by steve6375** [comment]
good idea! :+1:
so we can use 0 and 1 for normal usage.
To debug batch files, etc. we can use new
debug xxx.g4b
command :-)
new version works fine now with E2B :+1: 

So debug 3  no longer single-steps - so helo message is incorrect???
can we do same for 0.4.5c  (if not already done)

suggest  
debug help
debug:debug [on | off | normal | status | INTEGER]
or
debug Batchfile [ARG1] [ARG2] etc.
sets the message level:  0=off=no messages, 1=on=warning+error messages to stderr, 2=error messages to stderr, 3=all messages to stdout, -1=do not show timeout countdown for 'pause --wait=n' command.

**Comment by chenall** [comment]
for not show timeout countdown for 'pause --wait=n' 
using "pause --wait=n >nul" or debug off

with new version if you do not want to show message at boot time.you can manually modify GRLDR
at Offset 0x2073(default is 2),change to 0 will disable message.

**Comment by steve6375** [comment]
pause --wait=3 Can you see this? > nul           -> does not show any message!
debug 0 ;; pause --wait=3 Can you see this?   -> still shows timeout countdown and message
debug -1 ;; pause --wait=3 Can you see this?   -> shows message but no countdown - correct!
This is all expected and OK (same as before) - not asking for change

I cannot find 02 at 0x2073 in new 0.4.5c grldr??? There is x02 at 0x2007 and 0x20F3 ??
cat --locate=\02x --skip=0x1000 --length=0x1400 /grldr

Can you give write command to patch that location please so I can test?

**Comment by chenall** [comment]
OK,I think we need another way to control "pause --wait"

the message show control is 0.4.6a only does not in 0.4.5c. 

0x2073 is the offset in grldr file,in grub4dos command can using debug msg=N to change.

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/5792032/de9ff692-9efa-11e4-9b35-b8ada623046b.png)

**Comment by steve6375** [comment]
debug -1  and pause --wait=3 fred   seems to work OK in 0.4.6a? Why change it?

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/5792054/c04c7e30-9efb-11e4-8acc-b9f950d05b1a.png)

**Comment by chenall** [comment]
using 2015-01-18
http://grub4dos.chenall.net/downloads/grub4dos-0.4.6a-2015-01-18/

**Comment by steve6375** [comment]
thanks!
