### ISSUE TITLE
No parttype command in grub4efi

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#272]
Please can you add parttype command to make it compatible with grub4dos.
It is needed for E2B.

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-22_2.zip](https://github.com/chenall/grub4dos/files/6861855/grub4dos-for_UEFI-2021-07-22_2.zip)
plz try.

**Comment by a1ive** [comment]
Does `parttype` also work for GPT part table under grub4dos (BIOS)?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126632719-8abed5d9-3d04-4ba5-9d02-384cb10c618d.png)
Thanks!
It is fine for me.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126633086-06877f90-febc-46e1-8fbf-be47ed0b34b5.png)
But grub4dos is different...

**Comment by a1ive** [comment]
(hd1) is GPT?

**Comment by steve6375** [comment]
sorry - ignore grub4dos legacy previous post! Wrong VM so hd1 was legacy.

**Comment by a1ive** [comment]
So everything ok? I will push the commit.
It is possible to do it to show the correct gpt part type, but then it would be incompatible with previous versions, so it would be better to keep showing 0xEE?

**Comment by steve6375** [comment]
yes, its OK, thanks.
If you wanted to make it support GPT then suggest  new commands, maybe partnew-gpt and parttype-gpt  ???
but I don't need them at present.
