### ISSUE TITLE
Issue with animation

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#273]
![image](https://user-images.githubusercontent.com/1469350/126611402-f354372a-0986-4248-aec1-5333c621b353.png)

Same animation works fine in grub4dos

set ANIMFD3=/_ISO/docs/Templates/Animate/E2B_GIF.ima
set ANIMATE=0x90=3=9=615=160 (fd3)/frame_0001.bmp
[E2B_GIF.zip](https://github.com/chenall/grub4dos/files/6860960/E2B_GIF.zip)

Seems to first draw image with white border first?
Then it starts rotating. Actual animation is working OK and is transparent, but the first image seems to be drawn on background first.

**Comment by steve6375** [comment]
More info
If I go into grub4efi console and use splashimage command to reload the background
then it works OK (see next post).
I think issue is caused by writing text to screen
1. In menu.lst - run splashimage command for background
2. write text to screen using echo commands
3. run splashimage animation command
4. configfile /newmenu.lst  which contains  title  menu

I notice that during 2 above, the background screen can be seen on each line of text.
![image](https://user-images.githubusercontent.com/1469350/126617100-0014bce7-a0cf-40fd-8ce9-ac4cebce4e29.png)

This does not happen with grub4dos.
It is similar to using
call Fn.70 3
in old grub4dos

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126617336-11fe6fb7-7cd7-4cb5-b798-f40fda15b837.png)
![image](https://user-images.githubusercontent.com/1469350/126617393-2937ba25-b28a-4c87-87c4-f4841d732059.png)

**Comment by yaya2007** [comment]
E2B_GIF.zip损坏

**Comment by steve6375** [comment]
E2B_GIF.zip seems OK - I downloaded it from the link above
![image](https://user-images.githubusercontent.com/1469350/126752138-138726ec-5ec2-4e8b-9983-eb8c403eac57.png)


You need to unzip it to obtain E2B_GIF.ima
then map it to fd3

```
set ANIMFD3=/E2B_GIF.ima
set ANIMATE=0x90=3=9=615=160 (fd3)/frame_0001.bmp
#set up animation
echo %@time% Loading animation %ANIMATE%
map --mem --read-only %ANIMFD3% (fd3) 
map --hook
splashimage --animated=%ANIMATE% 
```

**Comment by yaya2007** [comment]
我测试没有问题。

如果是
set ANIMATE=0x03=3=9=615=160 (fd3)/frame_0001.bmp
这样才有背景色。

**Comment by steve6375** [comment]
The problem is caused by the   **pause --wait=3** command

please try  menu.lst file:

```
graphicsmode -1 800
splashimage /_ISO/MAINMENU/background.jpg
clear
set ANIMFD3=/_ISO/docs/Templates/Animate/E2B_GIF.ima
set ANIMATE=0x90=3=9=615=160 (fd3)/frame_0001.bmp
map --mem --read-only %ANIMFD3% (fd3)
map --hook
splashimage --animated=%ANIMATE%
pause --wait=3

title test
root ()
boot

```
![image](https://user-images.githubusercontent.com/1469350/126860017-e1fa0b92-2b32-4074-9b08-094b0e03536c.png)

Works OK if grub4dos legacy
![image](https://user-images.githubusercontent.com/1469350/126860134-cee62268-13a3-40d7-b214-6e03e9415961.png)

**Comment by steve6375** [comment]
I can workaround this issue by using command
```
splashimage
clear
```
just before  configfile menunew.lst is run

**Comment by yaya2007** [comment]
就是pause --wait=3惹的祸。
解决就好。

**Comment by steve6375** [comment]
When a new menu is displayed, grub4efi should do an _internal_ call to splashimage to repaint the screen just before menu background is displayed.
This would solve the problem.
The issue does not occur in grub4dos, only grub4efi has this issue.

**Comment by steve6375** [comment]
Here is  menu.lst and menu2.lst demo of the issue of animation producing non-transparent background when menu2 is selected:

menu.lst
```
graphicsmode -1 800
splashimage /background.jpg
set ANIMFD3=/E2B_GIF.ima
set ANIMATE=0x90=3=9=615=160 (fd3)/frame_0001.bmp
map %ANIMFD3% (3)
splashimage --animated=%ANIMATE%
/ext/hotkey -A

title ^ctrl+M Menu2
configfile /EFI/grub/menu2.lst

title ^Ctrl+C commandline
commandline

title ^Ctrl+R reload grub4efi
chainloader (bd)/EFI/BOOT/BOOTX64.efi
```
![image](https://user-images.githubusercontent.com/1469350/127316755-86d8062e-f282-4bc7-8b27-e288cccdb4fa.png)
menu2.lst
```
title [Ctrl+M] MENU1
configfile /EFI/grub/menu.lst

title [Ctrl+C] commandline
commandline

title [Ctrl+R] reload grub4efi
chainloader (bd)/EFI/BOOT/BOOTX64.efi
```
![image](https://user-images.githubusercontent.com/1469350/127316804-3ed2fb10-667c-4cc2-b3c1-ebb4352c4b9d.png)

[TESTANIM.zip](https://github.com/chenall/grub4dos/files/6892815/TESTANIM.zip)

**Comment by steve6375** [comment]
P.S. test file also shows issue with hotkey
If you use the 'reload grub4efi' menu entry, then hotkey no longer works.
![image](https://user-images.githubusercontent.com/1469350/127317737-af9a5c32-2f86-47eb-8bf2-25b432c12620.png)

**Comment by yaya2007** [comment]
已经解决，曾经提交过一次。
再提交一次。
见 #281
