### ISSUE TITLE
grub4efi setkey doublequote not working

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#274]
`setkey at doublequote`

does not seem to be working (under VBOX)

`pause --test-key` produces 0022  (unshifted = 0027)

`setkey doublequote at`
does work OK.

**Comment by yaya2007** [comment]
没有问题呀。
在bios状态
单引号：扫描码=28，ASCII字符码=27。双引号：扫描码=28，ASCII字符码=22。

在uefi状态
一般情况只显示ASCII字符码，特殊情况会显示扫描码。
单引号：ASCII字符码=27。双引号：ASCII字符码=22。

再举个例子
按键            扫描码        ASCII字符码       显示值
a                                    61                      0061
Shlft+a        1                 41                      0041
Ctrl+a         2                 61                      2000061
Alt+a          4                 61                      4000061

**Comment by steve6375** [comment]
There is a problem
`setkey at doublequote`
does not work

i.e. when I press the doublequote key  it still displays "  - it should display @

**Comment by yaya2007** [comment]
要获得doublequote，在键盘按 Shlft+“，显示 0022。

我不清楚这句话的意思。”it still displays " - it should display @“

键盘上，【2，@】是一组，【-,_】是一组。

**Comment by steve6375** [comment]
First press Shift+" key  (near ENTER key on USA keyboard)
![image](https://user-images.githubusercontent.com/1469350/126860434-3c946811-befb-463f-9f30-260d6137df23.png)

You will see " symbol on screen
Now use the command
`setkey at doublequote`
Now press Shift+" key (same key as before)
you still see " symbol on screen (@ is expected)
The setkey command does not work for this key

**Comment by steve6375** [comment]
P.S. I am actually using a UK keyboard
![image](https://user-images.githubusercontent.com/1469350/126860526-c1cf413b-b3dd-4408-a0f0-c869cd0c64ec.png)
and the key labelled @  is same as USA key labelled "
setkey at doublequote works on legacy grub4dos OK, but does not work on grub4efi.
Other setkey commands seem OK.

**Comment by yaya2007** [comment]
明白了。你是说 setkey 这个函数。现在不能使用，需要改造。等待日后处理。

**Comment by steve6375** [comment]
setkey function works OK
just does not work for " key

**Comment by yaya2007** [comment]
setkey函数虽然保留，但是内容被屏蔽。就是说，空运行。
我想知道，英式键盘与美式键盘，排列不一样，但是扫描码与 ASCII字符码应当是相同的吧。

**Comment by steve6375** [comment]
I am not sure what you mean?

setkey at doublequote   **does not work**
setkey doublequote at   does work
setkey at plus                 does work
setkey numbersign backslash does work
setkey tilde bar              does work

same commands all work with grub4dos.

**Comment by steve6375** [comment]
In builtins.c
```
  {"semicolon",	0x003B},	// ;
  {"colon",			0x003A},	// :
  {"quote",			0x0027},	// '
  {"doublequote",	0x2822},	// "
  {"backquote",	0x0060},	// `
  {"tilde",			0x007E},	// ~
  {"backslash",	0x005C},	// "\"
  {"bar",				0x007C},	// |
```

Note doublequote should be 0x0022  not 0x2822

**Comment by steve6375** [comment]
```
  {"parenright",0x0029},	// )
  {"minus",			0x0C2D},	// -
  {"underscore",0x005F},	// _
```
minus should be 0x002D

**Comment by steve6375** [comment]
`{"ctrlbackspace",	0x0008},	// 	(DEL)  2000008`

pause --test-key  gives 0x007f   (actually 0x200007f printed)

**Comment by steve6375** [comment]
others in table look OK, I checked many of them.
cannot add to table for Alt+a, etc. because table is 16-bit and code produced is 32-bit
a = 0x0061
Alt+a = 0x04000061
This means some keyboards cannot be fully supported because they use alt codes for standard characters like **at**, **dollar** etc.
e.g. Swedish kbd
setkey at A2
setkey dollar A4
setkey braceleft A7
setkey bracketleft A8
setkey bracketright A9
setkey braceright A0
setkey backslash Aminus


would be better to change table to use full 32-bit codes?

**Comment by yaya2007** [comment]
{"oem102",    0x565c},
  {"shiftoem102",   0x567c},
  {"Acomma",        0x3300}, 
  {"Aperiod",       0x20002E}, 
  {"Aslash",        0x3500},
这是什么键？

"shiftF1" 与 "F1" 键代码相同。

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6876807/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Acomma  is Alt+,

here is  , and Alt+,
![image](https://user-images.githubusercontent.com/1469350/126960585-9cb8d25e-26da-4c4c-be61-049b712987f6.png)
here is F1 and Alt+F1
![image](https://user-images.githubusercontent.com/1469350/126960888-8d62c1d6-d5bf-4230-a4bc-83e29893c45f.png)

what is BOOTX64.rar.txt ???
setkey doublequote at    is still not fixed in that file - did you change table???

**Comment by steve6375** [comment]
table in builtins.c has two errors

doublequote should be 0x0022
minus should be 0x002D

**Comment by steve6375** [comment]
it seems that high word has bits set for modifier keys
0x40kkkk = Left Alt or Right AltGr
0x20kkkk = Left Ctrl or Right Ctrl
0x60kkkk = Ctrl+Alt

**Comment by steve6375** [comment]
on extended UK kbd on a laptop and PC, under UEFI the oem102 key  returns correct characters for UK =  \ and |
005c and 002f
setkey can change these using bar and backslash
```
setkey  xx bar
setkey yy backslash
```
Note that on extended keyboard with extra oem102 key on left of Z key, the command
`setkey at bar`     changes both shift+oem102 and the | key which is next to the Enter key
![image](https://user-images.githubusercontent.com/1469350/126966310-182f869e-99c0-4e70-895d-3fdfc6644625.png)
so  oem102 key name is not required or useful for uefi.
