### ISSUE TITLE
grub4efi - insmod not working with batch files

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#276]
insmod /test.g4b

```
!BAT

Pause Hi!
```
![image](https://user-images.githubusercontent.com/1469350/126628478-446f264c-3ddd-4fe5-a649-be0f2a7d8f68.png)

file is in UTF-8 format

Is this not supported?

**Comment by yaya2007** [comment]
6月19日版本测试，确实有问题。已经修正，改日一并上传。

**Comment by yaya2007** [comment]
有关批处理的修改。请统一测试。
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6871813/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
seems OK - cannot test fully because parttype command is missing.
insmod and map --mem (md) seems OK though
thanks!

**Comment by steve6375** [comment]
batch files seem OK now with insmod, thanks for quick work!
