### ISSUE TITLE
grub4efi - map --mem fails with (md) device

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#277]
echo Q2a
map --mem (md)+4 (99)
echo Q2b

![image](https://user-images.githubusercontent.com/1469350/126636394-0af5ed39-b568-4515-8c4d-472d21dc02b0.png)

**Comment by yaya2007** [comment]
使用6月19日版本测试，正常。

**Comment by steve6375** [comment]
There is a problem when running the commands from a batch file, but the results seem to vary
e.g. from a large batch file
![image](https://user-images.githubusercontent.com/1469350/126751357-a8a69194-d753-4b9c-9abe-c3d68b9c19d5.png)

but same code from a small batch file:
![image](https://user-images.githubusercontent.com/1469350/126751712-fa4e77fc-54c7-4e9d-ad12-a27f90d083a3.png)

**Comment by a1ive** [comment]
@yaya2007 uefi 下的 `(99)` 是什么设备？

**Comment by yaya2007** [comment]
（99）是软盘。
0x80(128)以下是软盘。
99=0x63

**Comment by yaya2007** [comment]
批处理的问题见#276
