### ISSUE TITLE
Can grub4efi support beeper/speaker commands?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#278]
e.g. beep command  and maybe play tunes?

(not important, but maybe nice to make beeps to notify user?).

**Comment by steve6375** [comment]
https://github.com/fpmurphy/UEFI-Utilities-2018/tree/master/MyApps/Beep

**Comment by a1ive** [comment]
yes, it's possible.
what beep code do you use under grub4dos(bios)?

**Comment by steve6375** [comment]
beep command already supported by grub4dos
![image](https://user-images.githubusercontent.com/1469350/126759651-33fe7048-cd8e-44b7-85f9-941c5aa92809.png)

but really only simple immediate beep is actually 'needed'.

**Comment by a1ive** [comment]
`beep [--start|--mid|--end] [--play=N] [--nowait] FREQUENCY DURATION FREQUENCY DURATION ...`
What does the "--start|--mid|--end" option mean?

**Comment by steve6375** [comment]
beep

2018-06 and later – play tones [Frequency Hz] [Duration ms]

beep [–start|–mid|–end] [–play=N] [–nowait] FREQUENCY DURATION FREQUENCY DURATION …

FREQUENCY: Hz. DURATION: ms. Max: 126 notes per command.

N: 0-255. 0 is stop play, 255 is continuous play (any key stops play).

When the syllable is a lot, can be written in different lines.

The use of [–start|–mid|–end] specifies parts of the same tune.

beep 200 500 0 100 300 500

beep –nowait –play=3 200 500 0 100 300 500 0 200

beep –start 330 440 330 220 392 220 440 220 522 220 522 220 440 220 392 440 393 220 440 220 392 880

beep –mid 330 440 330 220 392 220 440 220 522 220 522 220 440 220 392 440 392 220 440 220 392 880

beep –mid 392 440 392 440 392 440 330 220 392 220 440 440 440 440 392 880

beep –end –play=255 –nowait 293 660 330 220 261 220 293 220 261 220 220 220 196 1320

https://rmprepusb.com/tutorials/021-guide-to-grub4dos/021b/

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-23_2.zip](https://github.com/chenall/grub4dos/files/6868791/grub4dos-for_UEFI-2021-07-23_2.zip)
beep FREQUENCY DURATION FREQUENCY DURATION …
other options (`--nowait`, `--play=`, `--start` etc) are not supported.

**Comment by steve6375** [comment]
Thanks
but problem with silence  (freq = 0)

try
beep 0  500

**Comment by a1ive** [comment]
what problem?

**Comment by steve6375** [comment]
I get  random noise

e.g.
beep 0 1000

get silence for 1/2 second - then  brrrrrrrr noise for 1/2 second

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-23_2.zip](https://github.com/chenall/grub4dos/files/6869098/grub4dos-for_UEFI-2021-07-23_2.zip)

**Comment by steve6375** [comment]
🥇 :-)
