### ISSUE TITLE
May be useful to add a screenshot facility to grub4efi?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#279]
To assist bug reporting on real systems.
https://blog.fpmurphy.com/

**Comment by a1ive** [comment]
`load -n /CrScreenshotDxe.efi`
https://github.com/LongSoft/CrScreenshotDxe

**Comment by steve6375** [comment]
If works OK, maybe add to ext folder?

**Comment by a1ive** [comment]
I don't think it's suitable to be ported as an external command.
ext commands currently only work properly under x64 uefi.

**Comment by steve6375** [comment]
I tested under UEFI64 VBox
Seems to save TWO .png files - I get  small square at top-left when saving
green - red - green - red
according to  github  red means a problem, but it seems to work OK (but saves two images each time).
So presumably it thinks save went wrong and has re-tried so I get two images in root of FAT32  Ptn 2?

**Comment by a1ive** [comment]
I think this is because the UEFI firmware provides two GOPs (Graphics Output Protocol), and the screenshot driver performs a screenshot operation on each GOP instance.
https://github.com/LongSoft/CrScreenshotDxe/blob/cf2fc003bf08a4badc3efe3540c109fa88fb0008/CrScreenshotDxe.c#L131

**Comment by steve6375** [comment]
OK, but each png appears to be identical.
Why does the red square appear = error ?

**Comment by a1ive** [comment]
> Why does the red square appear = error ?

This does not happen on VmWare Player and my laptop.

**Comment by steve6375** [comment]
I have two MBR partitions
ptn1: NTFS
ptn2: FAT32

boot ptn is set to NTFS because my menu.lst is on NTFS partition.
maybe red square is because it tries to save on NTFS ptn ???

**Comment by a1ive** [comment]
Just ignore it, the final generated screenshot is normal anyway. I've found a lot of weird problems with the uefi firmware for vbox before.
