### ISSUE TITLE
grub4efi - legacy utilities hang

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#280]
If you attempt to load a legacy utility such as the legacy hotkey utility, grub4efi hangs.
Is it possible to check the file and if it is a legacy utility (not grub4efi compatible) and not run it?

**Comment by steve6375** [comment]
P.S. Even better would be if  legacy+efi binaries could be combined and work under both legacy and efi environments.
Then same command (e.g. hotkey)  would work in both environments...

**Comment by a1ive** [comment]
> Even better would be if legacy+efi binaries could be combined and work under both legacy and efi environments.

too difficult.

**Comment by yaya2007** [comment]
“Is it possible to check the file and if it is a legacy utility (not grub4efi compatible) and not run it?”
这个估计有可能。

**Comment by yaya2007** [comment]
这个功能实现了。
他包含parttype函数，可以测试有关的问题，包含批处理等等。
[BOOTX64.EFI.txt](https://github.com/chenall/grub4dos/files/6872114/BOOTX64.EFI.txt)

**Comment by steve6375** [comment]
Thanks
It is not loading hotkey now???
I have renamed it to hotkeyefi

did you try to implement binary check and it has an error?

![image](https://user-images.githubusercontent.com/1469350/126862750-427b2d07-4aff-428c-a423-84b9ec4e6d2d.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126862880-3fe4f4f2-ebfb-43ea-b2f3-bd19c82b548d.png)

Still getting a message...

```
:.iso
if "%ISOASK%"=="1" goto :.isoask

:.isodefault
:.isodef
# main ISO boot entry
# Change ISOC to defragged file if %ISOC% was fragmented
if not exist NONCONTIG call :.contigfix
if not exist CD partnew (%E2BDEV%,3) 0x0 %ISOC% || if not exist NONCONTIG blocklist %ISOC% && if not exist NONCONTIG call echo -e %emsg% && if not exist NONCONTIG pause --wait=5
errorcheck off
echo iso1
map  %ISOC% (0xff) > nul || map --mem %ISOC% (0xff)
# Add firadisk reference to the ISO file into upper memory
echo iso1a
map --mem (md)+4 (99)
echo iso1b
map --hook
echo iso1c
write (99) [FiraDisk]\nStartOptions=cdrom,vmem=find:%~pnx1;\n\0
echo iso1d
call :lab_uuid
echo iso1e
pause
```

**Comment by steve6375** [comment]
with  debug msg=3 added
![image](https://user-images.githubusercontent.com/1469350/126862942-dbe2bc29-69ec-4857-8262-1d62ae171ff1.png)

**Comment by yaya2007** [comment]
[bin.rar.txt](https://github.com/chenall/grub4dos/files/6872142/bin.rar.txt)

**Comment by steve6375** [comment]
Thanks - now hotkey loads
but for some reason  first letter hotkey jump feature is not working
`hotkey -A`

if press 'R' key then it should jump to menu entry beginning with r

but if I run command  hotkey -A from commandline once menu has loaded then it works OK.
Also works OK in simple  menu.lst file.
Must be something in my large menu.lst which is interfering with it.
It used to work before. I think it stopped working before the change to the hotkey utility binary was made.

Will continue to investigate...

**Comment by steve6375** [comment]
The issue is caused when calling another configfile from first  menu.lst file

e.g.

menu1.lst
```
hotkey -A
configfile /menu2.lst
```

Now menu2.lst does not have first letter hotkey jump facility but does have menu hotkey  ^A feature
I think it used to work before (not 100% sure though...)

**Comment by steve6375** [comment]
appears to be fixed in 25-07 version. Thanks!
