### ISSUE TITLE
grub4efi hotkey utility does not install if reload grub4efi

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#281]
1. UEFI64 boot to grub4efi (from a1ive grub2) under VBOX
2. run  hotkey -A  (says it has installed and menu works OK with hotkeys and ^A title hotkeys, etc.)
3. run chainloader /grub4efi/bootx64.efi   (reload grub4efi)
4. run hotkey -A (does NOT say installed and menu does not show hotkeys)

![image](https://user-images.githubusercontent.com/1469350/126775501-c55b585a-02ee-4694-ba35-aa92888a363b.png)
(I renamed hotkey utility so it is not confused with legacy hotkey utility)

**Comment by steve6375** [comment]
P.S.  `hotkey -u `  is not documented in  usage/help text produced by the program.

**Comment by yaya2007** [comment]
热键函数只能在菜单中加载。
在命令行加载失败。

我感觉在命令行加载，只是为了测试某些功能。不会真的有应用环境吧。

**Comment by steve6375** [comment]
It also shows same issue when used in a menu.
That is how I found the problem.
I had a menu.lst which used  chainloader /efi/grub/bootx64.efi to reload  grub4efi and I found that hotkey command in menu.lst no longer worked!

**Comment by steve6375** [comment]
still same issue.
Boot to menu.lst which uses  hotkey -A  (has many title ^Ctrl+A xxxx entries, etc. - see screenshot) - ALL OK, but...
choose menu entry  which has these commands
`"@map --unhook ;; map --unmap=0:0xff ;; root (bd)/ ;; chainloader /grub4efi/bootx64.efi ;; boot"`
or use global hotkey ctrl+F8
`if "%@uefi%"=="64" ()/%grub%/hotkeyefi [Ctrl+F8] "@map --unhook ;; map --unmap=0:0xff ;; root (bd)/ ;; chainloader /grub4efi/bootx64.efi ;; boot" > nul`

When menu reloads -  hotkey does not install
![image](https://user-images.githubusercontent.com/1469350/126875726-3bf5df84-d2d8-469e-be00-260e58e980c0.png)

If then drop to command line to run hotkey command, it does not seem to run??
![image](https://user-images.githubusercontent.com/1469350/126875760-4c0e7bcb-68c5-4aee-b028-ae9449856fdb.png)

**Comment by a1ive** [comment]
> `"@map --unhook ;; map --unmap=0:0xff ;; root (bd)/ ;; chainloader /grub4efi/bootx64.efi ;; boot"`
> or use global hotkey ctrl+F8
> `if "%@uefi%"=="64" ()/%grub%/hotkeyefi [Ctrl+F8] "@map --unhook ;; map --unmap=0:0xff ;; root (bd)/ ;; chainloader /grub4efi/bootx64.efi ;; boot" > nul`

I don't think "map --unmap" & "map --unhook" will work under UEFI.
https://github.com/chenall/grub4dos/blob/25162728b1cc1ea0e31b02148afbf88210951317/stage2/builtins.c#L6861-L6872

**Comment by steve6375** [comment]
The problem is that hotkey does not work after reloading grub4efi bootx64.efi (whether I use --unhook and --unmap or not).

**Comment by yaya2007** [comment]
hotkey函数的帮助信息，增加 -u 内容。

运行 chainloader /grub4efi/bootx64.efi 后，是一个新的系统，hotkey函数需重新加载。
测试与 #289相同。

**Comment by steve6375** [comment]
No - you do not understand, of course I load hotkey again - it is in menu.lst file.

1. Load grub4efi
2. run hotkey -A  (in menu.lst) >> menu works fine
3. reload grub4efi (chainloader /bootx64.efi)
4. run hotkey -A  (in menu.lst)  >>>  hotkey is NOT INSTALLED, hotkey --status does not work, menu shows ^F1, ^Ctrl+L, etc.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/127121620-8c395b45-c909-44d2-9da8-a36d7b1bb6e5.png)

Does it check memory location to see if already installed maybe?

**Comment by yaya2007** [comment]
已经解决，曾经提交过一次。
再提交一次。
[grub4dos-for_UEFI-2021-08-02.rar.txt](https://github.com/chenall/grub4dos/files/6913764/grub4dos-for_UEFI-2021-08-02.rar.txt)

**Comment by steve6375** [comment]
The rar file works, but the hotkey  in the ext folder of latest grub4efi  does not work.
Can you update hotkey in  efi utils please?
