### ISSUE TITLE
grub4efi - Issue when calling batch file with no blank line at end

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#282]
![image](https://user-images.githubusercontent.com/1469350/126863780-9e1018f4-5a90-4a09-b4e7-41c431dc2817.png)
[MyE2B.zip](https://github.com/chenall/grub4dos/files/6872150/MyE2B.zip)

Extra character 'P' appended to  beep
![image](https://user-images.githubusercontent.com/1469350/126863803-4ffcf2a6-da02-429e-af06-e69777ad7678.png)

OK if add new line to end of file

**Comment by yaya2007** [comment]
终于找到问题的根源了。

**Comment by yaya2007** [comment]
测试同 #287

**Comment by steve6375** [comment]
fixed, thanks! 👍
