### ISSUE TITLE
grub4efi - call Fn.70 issue

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#283]
in grub4dos Fn.70 0  would turn off cursor but not display splashimage background (bit 0 = cursor, bit 1 = background bitmap).
but with grub4efi, it turns off cursor but the **background splashimage is displayed** 
![image](https://user-images.githubusercontent.com/1469350/126867507-41213a60-c0ea-4402-a391-c59448b3c03e.png)
with grub4efi:
Fn.70 0 has no cursor + background
Fn.70 1  has cursor on and no background
Fn.70 2  has no cursor + background (same as 0)
Fn.70 3  same as 1

Need to get  Fn.70 0  to turn off cursor but **not** display background image.

**Comment by steve6375** [comment]
Also this issue:

Want to display text without background

Cursor is left on menu when use Fn.70 1 or 3

Note: it seems that the strange cursor always appears in same place on menu no matter what is echo'd to screen or when???

```
#prevent background from being displayed
#0 and 2 displays background
#1 and 3 does not display background
call Fn.70 1
color normal=white/black highlight=red/black  > nul
graphicsmode -1 1024
splashimage --fill-color=0x000099
#splashimage /_ISO/img0_1024x768.jpg
echo display some text
echo more text to display
pause --wait=3

title Reload
chainloader /_ISO/e2b/grub/bootx64.efi

title E2B
configfile (bd)/_ISO/e2b/grub/menuefi.lst


```

![image](https://user-images.githubusercontent.com/1469350/128842103-cee62d8f-4a7f-49e5-91b7-a2d7b25ff558.png)

![image](https://user-images.githubusercontent.com/1469350/128842328-8c09eb58-71af-4c9d-bb57-d4d5e156cb9b.png)

**Comment by yaya2007** [comment]
call Fn.70 1
惹的祸

**Comment by steve6375** [comment]
If Fn.70 1 is not used we background which is not wanted..
![image](https://user-images.githubusercontent.com/1469350/128986334-9b14cc4e-b19f-4325-92bd-93a093bc6085.png)
I do not want background, so I use Fn.70  as with grub4dos which works OK
![image](https://user-images.githubusercontent.com/1469350/128986471-362fb36e-7a80-42cf-b84a-69be2fb2623d.png)

**Comment by yaya2007** [comment]
不理解你为什么要使用Fn.70

正常进入命令行，有光标，没有背景色。

按上面你给的示例，没有惹祸的那一句，有关闭，也没有杂乱的背景色。没有看到，惹祸的那一句起了什么作用

**Comment by yaya2007** [comment]
不理解你为什么要使用Fn.70

正常进入命令行，有光标，没有背景色。

按上面你给的示例，没有惹祸的那一句，有关闭，也没有杂乱的背景色。没有看到，惹祸的那一句起了什么作用

**Comment by steve6375** [comment]
I want to display text with no background before menu is displayed.
Can you not see that the background is displayed in picture 1 above?

So to remove the background I must use call Fn.70 1 - which works OK, but **a remnant cursor is permanently left on the menu** when it is displayed - as shown in pictures.
![image](https://user-images.githubusercontent.com/1469350/129034953-69970499-fa6c-4faa-9352-a0a7242b3a39.png)

grub4efi has a bug which puts cursor? on menu screen
