### ISSUE TITLE
grub4efi - @random is not very random!

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#285]
Seems to be only a counter, the value is always ascending.
Always starts at low number on first call

grub4efi
![image](https://user-images.githubusercontent.com/1469350/126868969-132aefc1-9930-4a04-92ac-1b41945717b3.png)

grub4dos
![image](https://user-images.githubusercontent.com/1469350/126868901-400d7e7b-e32f-4804-b729-91f27c735eb3.png)

**Comment by steve6375** [comment]
If do not call it for a few minutes, next call returns 0
![image](https://user-images.githubusercontent.com/1469350/126869025-65b6f9d9-d469-4fec-ad0a-eab445eee9d5.png)

**Comment by yaya2007** [comment]
返回0是个问题。已经修正。

**Comment by steve6375** [comment]
OK, but still problem of not a random number.
@random should return a value between 0 and 32767
 so 
`set /a num=%@random% / 3277 + 1`
will return num between 1 and 10, but under grub4efi we get
![image](https://user-images.githubusercontent.com/1469350/126890818-28fe5476-1cd6-4232-a978-976acb4bd098.png)

**Comment by yaya2007** [comment]
/3277+1 不是个好办法。

set /a num=(%@random% & 10) + 1
或许更合适

**Comment by steve6375** [comment]
Not compatible with grub4dos.
@random is not random in grub4efi - it seems to be a counter?
@random should return a random value between 0 and 32767 to be compatible with grub4dos
can you change algorithm so that  using or\xor\and (maybe?) we get random number between 0 and 32767 please?
use the number as an internal seed perhaps? Is there no C rand function?

**Comment by steve6375** [comment]
//		WENV_RANDOM   =  (WENV_RANDOM * (*(unsigned int *)&datetime) + (*(int *)0x46c)) & 0x7fff;
    		WENV_RANDOM = (datetime.minute * datetime.second) & 0x7fff;
		sprintf(p,"%d",WENV_RANDOM);

0x46c was bios tick counter but you have changed code to remove randomness.
maybe you can use C (rand) function  and &  or XOR the result ?
![image](https://user-images.githubusercontent.com/1469350/126897663-71417f45-83da-47cb-a323-ef74394f1059.png)

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-25_2.zip](https://github.com/chenall/grub4dos/files/6873830/grub4dos-for_UEFI-2021-07-25_2.zip)
try this.
![1](https://user-images.githubusercontent.com/10670106/126898449-3be38d49-3600-4d46-b14e-5c511c8aa6b9.png)
```
unsigned seed = 1103515245 * datetime.minute * datetime.second + 12345;
WENV_RANDOM = ((seed << 16) | (seed >> 16)) & 0x7fff;
```

**Comment by steve6375** [comment]
anything based on seconds will not work because successive calls within 1 second will always return exactly same result.
maybe you can define a static variable for the seed and then use that to seed on each successive call?

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-25_2.zip](https://github.com/chenall/grub4dos/files/6873865/grub4dos-for_UEFI-2021-07-25_2.zip)
```
static unsigned seed = 42;
...
seed = (datetime.minute * datetime.second) * seed + 12345;
WENV_RANDOM = ((seed << 16) | ((seed >> 16) & 0xffff)) % 32768;
```

**Comment by steve6375** [comment]
Looks better but...
shifting by say 10 may be better because on the first call, the seed will often be less than a 16-bit number and so shifting right can give 0 - so first call always is low number of 0 or 1 or 2?
```
59*59*42+12345 = 0x26B53
1*1*42+12345 = 0x3063
0*0*42+12345 = 0x3039
```

and maybe XOR would be better?

![image](https://user-images.githubusercontent.com/1469350/126899648-311e5a92-be5e-4c9f-8886-214321beb4e5.png)

**Comment by a1ive** [comment]
[grub4dos-for_UEFI-2021-07-25_2.zip](https://github.com/chenall/grub4dos/files/6874052/grub4dos-for_UEFI-2021-07-25_2.zip)
Setting the initial value of `seed` to a larger number will solve the problem, e.g. `0x14530529`
> and maybe XOR would be better?

I don't know if using XOR or other operators would make the result more "random".
I'll let @yaya2007 decide how to generate random numbers.

**Comment by yaya2007** [comment]
感觉应当可以了。
测试同 #287

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126949390-f9071933-1f35-49e4-9a76-aae4651745fe.png)
![image](https://user-images.githubusercontent.com/1469350/126949572-ea9a6d98-83cd-419f-afeb-f3d28ceee0b9.png)

Looks good :+1:
