### ISSUE TITLE
grub4efi - internal menu appears for 1 second

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#286]
1. Boot to  grub2
2. chainloader (hd0,0)/grub4efi/bootx64.efi  (NTFS partition)
3. internal grubefi menu appears for 1 second
4. (hd0,0)/efi/grub/menu.lst  is then loaded

How can I avoid the internal menu appearing for 1 second?
What path does the 'configfile' command look for in the  internal menu.lst file?

![image](https://user-images.githubusercontent.com/1469350/126893235-747542f5-ed9c-4ac9-bf0b-4dbca29a3382.png)

The root is set to (hd0,0)/
and the file /efi/grub/menu.lst exists, but the command 'configfile' does not load it.

P.S. Also the 1 second delay is sometimes much shorter than 1 second. This means that if the user wants to use the internal menu by pressing a key and stopping the timeout, sometimes the timeout is so quick that the key press is missed.

help configfile  - provides no information as to default path

grub4dos 'configfile' command loads the default config file.

Suggest  grub4efi 'configfile' command loads the default config file.
Suggest timeout is 2 seconds to allow user time to press a key, or make the timeout 1  command always wait for 1 second.

**Comment by yaya2007** [comment]
这个预置菜单执行：
find --set-root /efi/grub/menu.lst
configfile /efi/grub/menu.lst
一是设置根目录，二是运行菜单。

其实主要是提供一种加载菜单的可选择方法。
现在修改为0秒。
测试同 #287

**Comment by steve6375** [comment]
Embedded internal menu does not show any configfile command before a title command?

26/7/2021 latest test version provided just now...
![image](https://user-images.githubusercontent.com/1469350/126950262-128b0ad0-b340-4ced-8d6e-eba901af3baf.png)

**Comment by yaya2007** [comment]
就当这个预置菜单不存在
