### ISSUE TITLE
grub4efi - strange mappings causing floppy disk devices to be lost

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#287]
When I boot to E2B Main menu I get this map status
![image](https://user-images.githubusercontent.com/1469350/126894734-1c216a10-5af9-423f-a4c7-e3f203b29ee8.png)
The 3 is for the animation as expected.

but after loading a new sub-menu, new devices are mapped ???
![image](https://user-images.githubusercontent.com/1469350/126894814-8c8ab521-bc14-4d96-909d-22325316f807.png)

This is due to the  map file (0xff) command which is adding extra floppy drive mappings :
![image](https://user-images.githubusercontent.com/1469350/126895104-f71d298b-fcbc-456d-8fef-ba58bc423d01.png)

map --unmap=4  does not unmap it

![image](https://user-images.githubusercontent.com/1469350/126895148-4ec89671-cc90-425a-925e-1d65c28ee1db.png)

map --unmap does not seem to work?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/126895301-9fa16efa-1541-4967-83bb-8c4ada253cf0.png)

**Comment by steve6375** [comment]
This is also causing a problem with animation as (3) is used to hold the floppy disk image

Load MainMenu and get animation:
![image](https://user-images.githubusercontent.com/1469350/126906775-4b118d80-e1c0-4e31-b7a2-3620e3a3cc17.png)

![image](https://user-images.githubusercontent.com/1469350/126906675-acd32276-620e-42ad-b7fd-f9917bfa9b9a.png)
Now load 2nd menu (which uses map file (0xff) in the menu)...
Now the floppy image (2) has been changed and we no longer get the animation on the new menu!
![image](https://user-images.githubusercontent.com/1469350/126906711-60071d38-98ff-4487-ae94-939e6bed4be5.png)


![image](https://user-images.githubusercontent.com/1469350/126906739-b06d4251-600b-48e5-8cf0-23272bfcd313.png)

mapping of isos to  (0xff) has caused  (3) to be re-mapped and the original map to (3) is lost.

**Comment by steve6375** [comment]
Suggest if you need to map EFI bootable part of an ISO to a floppy disk, you do NOT use 0-3 ?

**Comment by yaya2007** [comment]
修改为：映射硬盘、光盘时，分区映射为fd6及以上。
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6876269/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
thanks.
![image](https://user-images.githubusercontent.com/1469350/126948931-01aa8d30-16fe-4b16-87f7-1e62a6715f21.png)
What is maximum number of floppy devices that could be reached?
