### ISSUE TITLE
grub4efi util request - Windows editor for internal menu in .efi files

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#288]
BootIce provides a nice Windows editor for changing the internal menu in grldr file.
It would be nice to have similar Windows utility for grub4efi?
Is position of internal menu fixed?
any size limit? Encoding supported?
I can patch it as hex file in NotePad++, so presumably no checksum to worry about.

![image](https://user-images.githubusercontent.com/1469350/126898573-ab703b28-d6be-4f1c-8f42-eb93b727d37c.png)

**Comment by a1ive** [comment]
grub4efi uses [mkimage](https://github.com/grub4dos/mkimage) (a modified grub-mkimage) to generate the EFI executable (which can contain built-in menus, fonts, etc.).
> Is position of internal menu fixed?

maybe not.

**Comment by steve6375** [comment]
Thanks for reply, sorry but I am probably being a bit thick but I don't understand.
So mkimage.exe is a Windows executable which can make a 32 or 64-bit efi  file
But what is the source? Is it the grub4dos.mod? Where does that come from?
How do I simply change the internal menu using it?

**Comment by a1ive** [comment]
same as grub2.
It uses `x86_64-efi/kernel.img` or `i386-efi/kernel.img`.
You can find them in github release 7z archive.

**Comment by steve6375** [comment]
Ah, that makes sense now! Thanks 👍

**Comment by a1ive** [comment]
The main difference between mkimage and grub-mkimage is that the embed module header types are defined differently.
https://github.com/grub4dos/mkimage/blob/67dc668d39ec875e2e97628feb3a84fad4bfcae7/include/grub/kernel.h#L25
https://github.com/grub4dos/grub/blob/1ea4e5ef09c06552402bf676ce262a661372f08d/include/grub/kernel.h#L27
