### ISSUE TITLE
grub4efi hotkey -A does not work when new menu is loaded using configfile

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#289]
menu.lst

```
hotkey -A
configfile /menu2.lst
```

First letter hotkey jump does not work in menu2

**Comment by yaya2007** [comment]
[bin.rar.txt](https://github.com/chenall/grub4dos/files/6883721/bin.rar.txt)

**Comment by steve6375** [comment]
not fixed.
Same issue.

**Comment by yaya2007** [comment]
不好意思，上传错了。晚些时候再上传。

**Comment by yaya2007** [comment]
[hotkey.rar.txt](https://github.com/chenall/grub4dos/files/6884615/hotkey.rar.txt)

**Comment by steve6375** [comment]
setmenu -u ??????   do you mean  hotkey -u  ???

hotkey -A    now not working at all !!!
no first letter hotkey jump even on first menu ???

![image](https://user-images.githubusercontent.com/1469350/127143686-732593e6-d11f-48e5-a74c-d9baed240a29.png)

**Comment by yaya2007** [comment]
应当是 hotkey -u

**Comment by yaya2007** [comment]
已经解决，曾经提交过一次。
再提交一次。
见 #281
