### ISSUE TITLE
grub4dos 2021-07-08 issues

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#293]
requires new hotkey, fat, etc. utilities - will not run old versions.

hotkey -A no longer works  - no first letter jump - now same as grub4efi hotkey which also no longer works

**Comment by yaya2007** [comment]
今天发布的grub4dos for uefi，需要匹配新的外部命令，如fat，hotkey等等。

**Comment by steve6375** [comment]
but  hotkey -A  does not work  
You have broken both  grub4efi  hotkey -A  and grub4dos hotkey -A

When you run
`hotkey -A`

You should be able to press a key to select the menu entry that begins with that key

e.g.

press L and it should jump to highlight the menu entry beginning with the letter L

This no longer works in both  new 28-07-2021 grub4dos and grub4efi  = BUG 
Please fix

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/127304098-8eb0fb71-75ed-412f-9d8b-d95e598bdfcd.png)
suggest better English/description
```
hotkey -nb         disable auto-run when hotkey pressed (menu entry is only selected)
hotkey -nc         disable default menu hotkeys (b,c,e,p) and disable menu selection by typing menu numbers
```

is
`title Boot ^Win 10`
correct??    It shows ^ is that intentional
![image](https://user-images.githubusercontent.com/1469350/127306247-8766215a-1c34-46b4-a513-87c58685989a.png)

Shouldn't it be
`title ^W Boot Win 10`
or maybe
`title ^Ctrl+W Boot Win 10`

**Comment by steve6375** [comment]
P.S. I made a simple USB stick using 28-07-2021 grub4efi and hotkey and...  hotkey -A works!
First letter jump is working.

But it does not work on my E2B USB drive which boots to 2nd partition first to grub2.
I first boot to a1ive grub2  bootx64.efi and then chainload grub4efi efi file.
Is there any reason you can think of why  hotkey -A does not work when grub4efi is loaded in this way?
Will it load in a different memory location and cause this issue?

**Comment by yaya2007** [comment]
我感觉是路径问题，试一试:
(驱动器)/路径/hotkey

**Comment by steve6375** [comment]
It is not path. I use (bd)/%grub%/efi_utils/hotkey -A and still get the issue.
I can run from command line and still get issue
![image](https://user-images.githubusercontent.com/1469350/127318745-780fe017-abc8-47f3-89b8-816f06ba6e38.png)

hotkey works in that it installs  hotkey OK
The menu does not display  ^Ctrl+A   ^Ctrl+U  etc. - so it must be working. I can use Ctrl+A  Ctrl+U to run menu entries.
ctrl+F8 works too.

The problem is  -A is not working   - first menu letter  auto-select

**Comment by steve6375** [comment]
I think I have found the problem
```
hotkey -u
hotkey -A

```
works OK


but
```
hotkey -u
hotkey [Ctrl+F8] "@root (bd)/ ;; chainloader /efi/boot/bootx64.efi ;; boot"
hotkey -A

```
The hotkey -A does not work

**Comment by yaya2007** [comment]
我明天测试一下

**Comment by yaya2007** [comment]
[grub4dos-for_UEFI-2021-07-29.rar.txt](https://github.com/chenall/grub4dos/files/6900002/grub4dos-for_UEFI-2021-07-29.rar.txt)

**Comment by steve6375** [comment]
Sorry - hotkey still not working!   I made a mistake in testing.

hotkey -u
hotkey [F8] "ls /"
hotkey -A
![image](https://user-images.githubusercontent.com/1469350/127488655-b6b43b33-6088-432e-be6b-ed882c058592.png)
![image](https://user-images.githubusercontent.com/1469350/127488730-390ae6c3-16e2-4883-ac77-69708e604c44.png)

If press r is does not select 3rd menu item

also if reload  grub4efi bootx64.efi  and then load hotkey, hotkey  does not work at all.

**Comment by yaya2007** [comment]
加载bootx64.efi之后，就是一个新环境，肯定不会有hotkey。

就好比windows7重启，之前运行的office需要重新启动。

**Comment by steve6375** [comment]
> After loading bootx64.efi, it is a new environment, and there will be no hotkey.
> 
> It is like restarting windows7, the previously running office needs to be restarted.

Of course! I know that!  hotkey is run by menu.lst   but it does NOT load and is NOT active.

Please try sample test file and add to a FAT32 USB drive
1. Boot to FAT32 USB - it loads bootx64.efi and then loads menu.lst - menu.lst loads  hotkey and presents a menu - all OK (except first letter jump does not work)
 
![image](https://user-images.githubusercontent.com/1469350/127489944-5a8f9d44-316c-456e-83fb-21fc19e87921.png)
![image](https://user-images.githubusercontent.com/1469350/127489994-82d0e26c-eae8-418f-bb8a-bfe3bb2c7a7a.png)

2. Use 3rd menu item which runs chainloader /EFI/BOOT/BOOTX64.efi to reload grub4efi
 - it loads bootx64.efi and then loads menu.lst - menu.lst loads  hotkey and presents a menu  BUT HOTKEY DOES NOT WORK
![image](https://user-images.githubusercontent.com/1469350/127490058-82aaab53-234e-471a-bf75-75b2f3882e15.png)

[TESTANIM2.zip](https://github.com/chenall/grub4dos/files/6900377/TESTANIM2.zip)
```
graphicsmode -1 800
splashimage /background.jpg
set ANIMFD3=/E2B_GIF.ima
set ANIMATE=0x90=3=9=615=160 (fd3)/frame_0001.bmp
map %ANIMFD3% (3)
splashimage --animated=%ANIMATE%
debug 3
debug msg=3
/ext/hotkey -u
/ext/hotkey [F8] "ls / ;; pause"
/ext/hotkey -A

title ^Ctrl+M Menu2
configfile /EFI/grub/menu2.lst

title ^Ctrl+C commandline
commandline

title ^Ctrl+R reload grub4efi
chainloader (bd)/EFI/BOOT/BOOTX64.efi
```

**Comment by yaya2007** [comment]
[grub4dos-for_UEFI-2021-07-31.rar.txt](https://github.com/chenall/grub4dos/files/6910852/grub4dos-for_UEFI-2021-07-31.rar.txt)

**Comment by steve6375** [comment]
hotkey -A fixed
reload bootx64.efi + hotkey fixed
animation transparent in new menu fixed
👍  great :-) thanks...

BUT STILL ERRORS:
ctrl+w prints w
alt+w prints w
ctrl+alt+w prints w
`setkey at Aw `  changes w key and alt+w and ctrl+w
