### ISSUE TITLE
grub4efi - setkey Alt codes query?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#294]
I think  Abackquote is wrong in table  in builtins.c??
`setkey at Abackquote` is actually changing the doublequote key now!!

` {"backquote",	0x0060},	// `
```
  {"Aminus",         0x20002D},  //-
  {"Aequal",	    0x20003D},  //=
  {"Abracketleft",  0x200028},  //(
  {"Abracketright", 0x200029},  //)
  {"Asemicolon",    0x20003B},  //;
  {"Aquote",           0x200027},  //'
  {"Abackquote",    0x2000**22**}, // 2a00 is alt+shift  反引号?
  {"Abackslash",     0x20005C},  //'\'
```
backquote is 0060  {top left key below ESC key) = grave accent
so **Abackquote should be   0x2000060**   ???

also **Abracketleft** seems wrong - it is Alt+[  so **should be  0x200005B** 
and **Abracketright should be 0x200005D**

**Aquote should be  0x2000027**  (quote is  0027)

P.S. Why are some Alt codes 0x200 and some are 0x400 ??
```
  {"Aq",        0x**400**0071},	// A=Alt or AltGr.	Provided by steve.
  {"Aw",        0x**400**0077},
  {"Ae",        0x**400**0065},
  {"Ar",        0x**200**0072},
  {"At",        0x2000074},
  {"Ay",        0x2000079},
  {"Au",        0x2000075},
  {"Ai",        0x2000069},
```
etc
pause --test-key  shows 0x400 for all Alt+ keys ?????

**Comment by yaya2007** [comment]
[Uploading BOOTX64.rar.txt…]()

**Comment by steve6375** [comment]
Aquote seems OK now but...

Abackquote    Alt+`   (unshifted key below ESC key)
Abracketleft    Alt+[
Abracketright  Alt+]

still not working
![image](https://user-images.githubusercontent.com/1469350/127485394-41392878-5515-4a5c-9401-c2a74f94fa6e.png)
http://kbdlayout.info/kbdusx

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6904340/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
better but still some issues!
letters and Ctrl+ and Alt+ are affected as well as A+letter, e.g.

`setkey at Aq`   changes    q and Alt+q and Ctrl+q
`setkey at Aw`  changes    w and Alt+w and Ctrl+w
etc. etc. for all letter keys
`setkey at ctrlF1` changes  F1 and Alt+F1 and Ctrl+F1
etc.

also 
Av  has wrong key code (it changes g key instead of v key)
Az has wrong value code (it changes bar | key)

![image](https://user-images.githubusercontent.com/1469350/127622122-39e67a1a-cedc-4996-89f9-7c667a4682a5.png)

**Comment by steve6375** [comment]
Under  grub2 typing Alt+1 and Ctrl+1 do not produce any characters in the console
but under grub4efi,  Alt+1 and Ctrl+1 produce '1'  - so grub4efi keyboard handler has a bug?

**Comment by steve6375** [comment]
Esc does not produce 0 ???
![image](https://user-images.githubusercontent.com/1469350/127631140-3a563751-8b11-4101-a2da-7836872c35ce.png)
![image](https://user-images.githubusercontent.com/1469350/127631264-950489f7-1e7f-42f3-b2cc-6a5e94ca75bf.png)
![image](https://user-images.githubusercontent.com/1469350/127631942-6e3b3c8e-d99b-4f7e-8b3b-68f98d83905c.png)

**Comment by steve6375** [comment]
setkey Table seems to have many wrong codes ???
0x400nnnn = Alt
0x200nnnn = Ctrl  (e.g.  		if (checkkey() == 0x2000063)  is correct for Ctrl+C)
0x20nnnn = ???
![image](https://user-images.githubusercontent.com/1469350/127634358-068e9268-f3f0-4cea-9a3d-b02aeb2246fa.png)

**Comment by steve6375** [comment]
shared.h
![image](https://user-images.githubusercontent.com/1469350/127636299-92945e0b-022d-4109-ae79-d2487208d9cc.png)
unsigned short = 0xFFFF max

should be unsigned int ???

**Comment by yaya2007** [comment]
static struct keysym keysym_table[] =
{
  {"escape",		0x17011B},	// ESC	17011b
  {"1",					0x0031},	// 1
  {"exclam",		0x0021},	// !
  {"2",					0x0032},	// 2
  {"at",				0x0040},	// @
  {"3",					0x0033},	// 3
  {"numbersign",0x0023},	// #
  {"4",					0x0034},	// 4
  {"dollar",		0x0024},	// $
  {"5",					0x0035},	// 5
  {"percent",		0x0025},	// %
  {"6",					0x0736},	// 6
  {"caret",			0x005E},	// ^
  {"7",					0x0037},	// 7
  {"ampersand",	0x0026},	// &
  {"8",					0x0038},	// 8
  {"asterisk",	0x002A},	// *
  {"9",					0x0039},	// 9
  {"parenleft",	0x0028},	// (
  {"0",					0x0030},	// 0
  {"parenright",0x0029},	// )
  {"minus",			0x002D},	// -
  {"underscore",0x005F},	// _
  {"equal",			0x003D},	// =
  {"plus",			0x002B},	// +
  {"backspace",	0x0008},	// BS
  {"ctrlbackspace",	0x2000008},	// 	(DEL)  2000008
  {"tab",				0x0009},	// Tab
  {"q",					0x0071},	// q
  {"Q",					0x0051},	// Q
  {"w",					0x0077},	// w
  {"W",					0x0057},	// W
  {"e",					0x0065},	// e
  {"E",					0x0045},	// E
  {"r",					0x0072},	// r
  {"R",					0x0052},	// R
  {"t",					0x0074},	// t
  {"T",					0x0054},	// T
  {"y",					0x0079},	// y
  {"Y",					0x0059},	// y
  {"u",					0x0075},	// u
  {"U",					0x0055},	// U
  {"i",					0x0069},	// i
  {"I",					0x0049},	// I
  {"o",					0x006F},	// o
  {"O",					0x004F},	// Q
  {"p",					0x0070},	// p
  {"P",					0x0050},	// P
  {"bracketleft",	0x005B},	// [
  {"braceleft",		0x007B},	// {
  {"bracketright",0x005D},	// ]
  {"braceright",	0x007D},	// }
  {"enter",			0x000D},	// Enter
  {"a",					0x0061},	// a
  {"A",					0x0041},	// A
  {"s",					0x0073},	// s
  {"S",					0x0053},	// S
  {"d",					0x0064},	// d
  {"D",					0x0044},	// D
  {"f",					0x0066},	// f
  {"F",					0x0046},	// F
  {"g",					0x0067},	// g
  {"G",					0x0047},	// G
  {"h",					0x0068},	// h
  {"H",					0x0048},	// H
  {"j",					0x006A},	// j
  {"J",					0x004A},	// J
  {"k",					0x006B},	// k
  {"K",					0x004B},	// K
  {"l",					0x006C},	// l
  {"L",					0x004C},	// L
  {"semicolon",	0x003B},	// ;
  {"colon",			0x003A},	// :
  {"quote",			0x0027},	// '
  {"doublequote",	0x0022},	// "
  {"backquote",	0x0060},	// `
  {"tilde",			0x007E},	// ~
  {"backslash",	0x005C},	// "\"
  {"bar",				0x007C},	// |
  {"z",					0x007A},	// z
  {"Z",					0x005A},	// Z
  {"x",					0x0078},	// x
  {"X",					0x0058},	// X
  {"c",					0x0063},	// c
  {"C",					0x0043},	// C
  {"v",					0x0076},	// v
  {"V",					0x0056},	// V
  {"b",					0x0062},	// b
  {"B",					0x0042},	// B
  {"n",					0x006E},	// n
  {"N",					0x004E},	// N
  {"m",					0x006D},	// m
  {"M",					0x004D},	// M
  {"comma",			0x002C},	// ,
  {"less",			0x003C},	// <
  {"period",		0x002E},	// .
  {"greater",		0x003E},	// >
  {"slash",			0x002F},	// /
  {"question",	0x003F},	// ?
  {"space",			0x0020},	// Space
  {"F1",				0xB3B00},	//b3b00
  {"F2",				0xC3C00},	//c3c00
  {"F3",				0xD3D00},	//d3d00
  {"F4",				0xE3E00},	//e3e00
  {"F5",				0xF3F00},	//f3f00
  {"F6",				0x104000},	//104000
  {"F7",				0x114100},	//114100
  {"F8",				0x124200},	//124200
  {"F9",				0x134300},	//134300
  {"F10",				0x144400},	//144400
  /* Caution: do not add NumLock here! we cannot deal with it properly.  */
  {"home",			0x54700},	//54700
  {"uparrow",		0x14800},	//上箭头  14800
  {"pageup",		0x94900},	// PgUp		94900
  {"leftarrow",	0x44B00},	//左箭头 	44b00
  {"rightarrow",0x34D00},	//右箭头  34d00
  {"end",				0x46F00},	//64f00
  {"downarrow",	0x25000},	//下箭头 	25000
  {"pagedown",	0xA5100},	// PgDn		a5100
  {"insert",		0x75200},	// Insert	75200
  {"delete",		0x85300},	// Delete	85300
//  {"shiftF1",		0x5400},
//  {"shiftF2",		0x5500},
//  {"shiftF3",		0x5600},
//  {"shiftF4",		0x5700},
//  {"shiftF5",		0x5800},
//  {"shiftF6",		0x5900},
//  {"shiftF7",		0x5A00},
//  {"shiftF8",		0x5B00},
//  {"shiftF9",		0x5C00},
//  {"shiftF10",		0x5D00},
  {"ctrlF1",		0x20B3B00},
  {"ctrlF2",		0x20C3C00},
  {"ctrlF3",		0x20D3D00},
  {"ctrlF4",		0x20E3E00},
  {"ctrlF5",		0x20F3F00},
  {"ctrlF6",		0x2104000},
  {"ctrlF7",		0x2114100},
  {"ctrlF8",		0x2124200},
  {"ctrlF9",		0x2134300},
  {"ctrlF10",		0x2144400},
  {"Aq",        0x4000071},	// A=Alt or AltGr.	Provided by steve.
  {"Aw",        0x4000077},
  {"Ae",        0x4000065},
  {"Ar",        0x4000072},
  {"At",        0x4000074},
  {"Ay",        0x4000079},
  {"Au",        0x4000075},
  {"Ai",        0x4000069},
  {"Ao",        0x400006f},
  {"Ap",        0x4000070},
  {"Aa",        0x4000061},
  {"As",        0x4000073},
  {"Ad",        0x4000064},
  {"Af",        0x4000066},
  {"Ag",        0x4000067},
  {"Ah",        0x4000068},
  {"Aj",        0x400006A},
  {"Ak",        0x400006B},
  {"Al",        0x400006C},
  {"Az",        0x400007A},
  {"Ax",        0x4000078},
  {"Ac",        0x4000063},
  {"Av",        0x4000066},
  {"Ab",        0x4000062},
  {"An",        0x400006E},
  {"Am",        0x400006D},
  {"A1",        0x4000031},
  {"A2",        0x4000032},
  {"A3",        0x4000033},
  {"A4",        0x4000034},
  {"A5",        0x4000035},
  {"A6",        0x4000036},
  {"A7",        0x4000037},
  {"A8",        0x4000038},
  {"A9",        0x4000039},
  {"A0",        0x4000030},
//  {"oem102",    0x565c},
//  {"shiftoem102",   0x567c},
  {"Aminus",        0x400002D},  //-
  {"Aequal",				0x400003D},  //=
  {"Abracketleft",  0x400005B},  //[
  {"Abracketright", 0x400005D},  //]
  {"Asemicolon",    0x400003B},  //;
  {"Aquote",        0x4000027},  //'
  {"Abackquote",    0x4000060},  //`
  {"Abackslash",    0x400005C},  //'\'
  {"Acomma",        0x400002C},  //,
  {"Aperiod",       0x400002E},  //.
  {"Aslash",        0x400002F},  //'/'
};

**Comment by yaya2007** [comment]
"Under grub2 typing Alt+1 and Ctrl+1 do not produce any characters in the console"
确实返回1

"ret & 0xFF"
//ret & 0xFF

"unsigned short = 0xFFFF max"
unsigned int = 0xFFFF max

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6910896/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
???

Typing  Alt+w in console  >> w
`setkey at Aw`    >>  
 type w = @,
 type ctrl+w=@
 type alt+w=@
 type alt+ctrl+w = @ 

still wrong

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/127734262-80eebe44-a555-4cfe-9421-239cdcdad72f.png)

**Comment by steve6375** [comment]
a1ive grub2/grubfm does not produce any characters when typing
alt+1
ctrl+1
alt+w
ctrl+w
![image](https://user-images.githubusercontent.com/1469350/127734389-7e692e1a-d20b-4674-b745-51f8ec492535.png)
![image](https://user-images.githubusercontent.com/1469350/127734434-e71f695f-7ff8-4fca-8090-ae3dc023f558.png)

**Comment by yaya2007** [comment]
a1ive grub2/grubfm does not produce any characters when typing
alt+1
ctrl+1
alt+w
ctrl+w

这是UEFI控制台产生的，也就是UEFI控制芯片产生的。
grub4dos for uefi 打印屏幕没有任何加工。

**Comment by yaya2007** [comment]
a1ive grub2/grubfm does not produce any characters when typing
alt+1
ctrl+1
alt+w
ctrl+w

这是UEFI控制台产生的，也就是UEFI控制芯片产生的。
grub4dos for uefi 打印屏幕没有任何加工。

**Comment by steve6375** [comment]
So are special keys no longer supported with hotkey?
currently  Alt and Ctrl  keys do not work
Aw Az ctrlF1 etc.
Can this be fixed?

**Comment by yaya2007** [comment]
试一试
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6930813/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Looks great!
Where can I check builtins.c to check table?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/128175541-d5e4c56b-296b-41d2-aa97-dbafac57fae4.png)

**Comment by steve6375** [comment]
default codes for
F1
ctrl+F1
alt+F1
![image](https://user-images.githubusercontent.com/1469350/128176419-bc321f10-7cc7-47d2-8d22-3f79862eace5.png)

**Comment by yaya2007** [comment]
上面有详细的键盘映射表。那里面没有
AF1，没有shiftF1。

**Comment by steve6375** [comment]
why remove them?
help text says they are supported and they are supported in grub4dos legacy?

**Comment by yaya2007** [comment]
g4e和g4d的键盘映射表是一样的。是你几年前提供的，可能是你忘了。
只是注释掉shiftFn。前面已经解释了:
F1和shiftF1的代码相同。这个你自己可以测试，验证。

**Comment by steve6375** [comment]
CtrlF1 and AltF1 ???

**Comment by yaya2007** [comment]
ctrlF1已经存在。
altF1你以前没有提供。g4d里面也没有。

你如果另外有必要的，充分的需求，可以新补充提供一个键盘映射表。

**Comment by steve6375** [comment]
yes, you are correct. You can easily add AltFx codes...
AltF1, etc. codes are same as ctrlF1, etc. except use 0x40xxxxx instead of 0x20xxxxx.

Your table has   **pageup**, **pagedownn**, **downarrow**, **uparrow**, **leftarrow**, **rightarrow**, **delete**, **home** and **end**  which I don't think should be there because these are needed by the menu system.

Also help text may need changing?
![image](https://user-images.githubusercontent.com/1469350/128221835-191daaa2-6218-47c3-bd5a-c78e74e5e93c.png)

**Comment by yaya2007** [comment]
贵人多忘事，这个帮助信息还是几年前由你提供的。直到昨天，我才真真了解这个函数的功能和运行机理。
可以按照你的要求，修改帮助信息，增加AFn
。

**Comment by yaya2007** [comment]
修正了 shiftFn。
这样就与 0.4.6a 一致了。可以正常使用 [ctrl|shift]F1-10。
为了保持与 0.4.6a 一致，不再增加[alt]F1-10。
[BOOTX64.EFI.txt](https://github.com/chenall/grub4dos/files/6935745/BOOTX64.EFI.txt)

**Comment by steve6375** [comment]
Thanks!
Sample BOOTX64.EFI seems to print new line and debug info in console?
![image](https://user-images.githubusercontent.com/1469350/128296241-aa0c7111-2b7f-4d3f-9525-4784f3e20429.png)

**Comment by yaya2007** [comment]
对不起，乌龙了。
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6936717/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Many thanks!
