### ISSUE TITLE
grub4efi - Each new line in a batch files causes a keyboard character to be removed from kbd buffer?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#295]
```
!BAT

#WORKS
echo test 1 - press a key now...
call Fn.73 3 ;; call Fn.20 ;; set /A key=%@retval% & 0xFFFF

#WORKS
echo test 2 - press a key now...
call Fn.73 3 |; call Fn.20
set /A key=%@retval% & 0xFFFF

#WORKS
echo test 3 - press a key now...
call Fn.73 3 ;; call Fn.20
set /A key=%@retval% & 0xFFFF

#WORKS
echo test 4 - press a key now...
call Fn.73 3 || call Fn.20
set /A key=%@retval% & 0xFFFF


echo DO NOT WORK
echo test 5 - press a key now...
call Fn.73 3
call Fn.20 ;; set /A key=%@retval% & 0xFFFF

#DOES NOT WORK
echo test 6 - press a key now...
call Fn.73 3 && echo done wait
call Fn.20
set /A key=%@retval% & 0xFFFF


#DOES NOT WORK
echo test 7 - press a key now...
call Fn.73 3
call Fn.20 
set /A key=%@retval% & 0xFFFF
```

![image](https://user-images.githubusercontent.com/1469350/127694118-715cb3f3-03b5-465b-9fb5-eeb27f78f2ed.png)

It seems that when a new line in the batch file is executed, if there is a keyboard character in the buffer, it is getting absorbed?
Maybe you are checking for the user pressing a key (e.g. ctrl+c) and this is absorbing a keyboard character if one was pressed by the user? Is this because there is no  'check-kbd' call which does not remove a characters from the keyboard buffer???

It also means that when a batch file is running, the user cannot press a key for when the menu loads - he must always wait until the menu is loaded and then press  a key.

Note:  Fn.73 in both grub4dos and grub4efi return 0, so that is expected and is not a problem.

**Comment by yaya2007** [comment]
bat_run_script函数有一个checkkey
if (checkkey() == 0x2000063)

它检测ctrl+c

**Comment by steve6375** [comment]
yes, I know, but it also removes character from the keyboard buffer.

Is there no way to make it just detect  ctrl+c  and only remove key from buffer if ctrl+c was pressed?

**Comment by yaya2007** [comment]
明天试一试读端口

**Comment by yaya2007** [comment]
经测试，通过读端口64失败。可能是键盘锁关闭。在BIOS，可通过 int15 开启，在 UEFI 视乎没有办法。
你提的问题暂时无法解决。
