### ISSUE TITLE
grub4efi - cmp command not working

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#296]
![image](https://user-images.githubusercontent.com/1469350/127737622-80ab2bf3-21c0-4203-8d40-083346297337.png)

**Comment by yaya2007** [comment]
已经修复.
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6913719/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Looks good! thanks
