### ISSUE TITLE
grub4efi - Request - detect if a USB drive is 'Removable' or 'Fixed' type

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#298]
It would be very useful if we can detect the type of USB drive (or any drive) in grub4efi
The RMB bit in the Inquiry command determines whether a drive is fixed or removable
https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
![image](https://user-images.githubusercontent.com/1469350/127764577-f33bb21d-26b0-4b80-b280-3089647bd78d.png)

Windows Setup will automatically detect /AutoUnattend.xml file if it is on Removable media, so this means I can automate the install of Windows by using an XML file to load the ISO as a virtual disk when WinPE/Setup boots.
However, this only works if the USB drive is 'Removable'.

If I could check if the drive was the 'Removable' type then I would know I can use an XML file.
If the USB drive was the Fixed type then I would know that using an XML file would not work and I could warn the user or use a different method (e.g. reboot to grub2 and use wimboot).

A separate command could be used to return media type or maybe the geometry command could be used to return media type?

**Comment by a1ive** [comment]
这个可以实现。我觉得这个功能比较适合放到外部命令grubutils里面。

**Comment by steve6375** [comment]
That would be great!

**Comment by a1ive** [comment]
[efidiskinfo.zip](https://github.com/chenall/grub4dos/files/6912797/efidiskinfo.zip)
```
efidiskinfo --rm (hd0)
echo %?%
```
0 = FALSE, 1 = TRUE.
![1](https://user-images.githubusercontent.com/10670106/127774035-8e5e3f7a-3231-444d-bda2-e37a2095692f.png)
![2](https://user-images.githubusercontent.com/10670106/127774038-65a62fcc-35cd-479a-b0d1-eee313e4a8a9.png)
The command line also accepts disks in the format "(hdx,y)", and the partition number will be ignored.

**Comment by steve6375** [comment]
Looks great! thanks
![image](https://user-images.githubusercontent.com/1469350/127782428-94b1a8c7-99cf-4ed3-855a-da587520c073.png)

**Comment by a1ive** [comment]
> Windows Setup will automatically detect /AutoUnattend.xml file if it is on Removable media, so this means I can automate the install of Windows by using an XML file to load the ISO as a virtual disk when WinPE/Setup boots.
However, this only works if the USB drive is 'Removable'.

How do you determine if a disk is 'Removable' under BIOS?

**Comment by steve6375** [comment]
I can't!

**Comment by steve6375** [comment]
if it is possible, it would also be useful to detect of a device is connected via  USB2 or USB3?
i.e. not if it is a USB 3 device, but if it is using USB 3 port.
e.g.
USB 2 drive in USB 3 port -> USB 2
USB 2 drive in USB 2 port -> USB 2
USB 3 drive in USB 3 port -> USB 3

**Comment by a1ive** [comment]
[efidiskinfo.zip](https://github.com/chenall/grub4dos/files/6924010/efidiskinfo.zip)
```
efidiskinfo --usb-spec (hdx)
echo %?%
```

The USB specification is complex and I am not sure if my implementation is correct.
I'm also not sure that the UEFI firmware necessarily includes an xHCI (USB 3.0) driver, as the UEFI Spec only requires USB 2.0 compatibility.
![03121619](https://user-images.githubusercontent.com/10670106/128015456-d074738f-9f32-4ac9-b76a-d597551c49ee.png)
(hd0) SanDisk USB 3.0 in USB 2.0 port.
(hd1) Kingston USB 3.0 in USB 3.0 port.
![03121743](https://user-images.githubusercontent.com/10670106/128015640-a357f23f-126f-4655-b0fe-9d9ab0a366f0.png)
(hd0) Kingston USB 3.0 in USB 2.0 port.
(hd1) SanDisk USB 3.0 in USB 3.0 port.

**Comment by steve6375** [comment]
using a usb 3 drive, Efidiskinfo on my Asus Z87 reports usb 2 on a usb 3 port, but on my ideapad 300 it reports as usb 3. On ideapad, when connected via a usb 2 cable it reports as usb 2.
So it is reporting the current usb mode, not the specification.

**Comment by a1ive** [comment]
> So it is reporting the current usb mode, not the specification.

![1](https://user-images.githubusercontent.com/10670106/128035345-3af47743-201a-4f54-b22a-2aef53abf0b5.png)
I used this field.
It is the current USB mode, but the USB Spec calls it the "USB Specification Release Number".
If UEFI firmware doesn't have 3.0 driver, then it will work under 2.0.
If we want to get the exact USB port information corresponding to the USB flash drive, then we probably should not get it directly via "EFI USB I/O PROTOCOL".
Instead, we might have to enumerate the PCI to get the relevant information, which would be a bit of a pain.
https://www.usb.org/documents
USB Spec is too complex and difficult to understand, and my English is not very good, so if you can find the code to implement it that would be a big help.

**Comment by steve6375** [comment]
OK, thanks.  So it is really the 'USB Driver Protocol'.
