### ISSUE TITLE
grub4efi - request for efi version of chkpci grub4dos utility

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#299]
![image](https://user-images.githubusercontent.com/1469350/127784587-9b6066c3-c3fb-4b60-9126-7989ff92410b.png)
The FILE and -w functions are not needed.

This is just a 'nice to have' and is not needed for E2B but it would be useful to list PCI IDs.

**Comment by yaya2007** [comment]
请测试。
[chkpci.rar.txt](https://github.com/chenall/grub4dos/files/6914045/chkpci.rar.txt)

**Comment by steve6375** [comment]
great, thanks!
