### ISSUE TITLE
grub4efi - vol command hangs on non-existent GPT partition

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#300]
![image](https://user-images.githubusercontent.com/1469350/127826604-fb0a94c5-dd4f-497f-8569-0618d8d60c04.png)

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6920620/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
thanks!
