### ISSUE TITLE
grub4efi - grubfm_multiarch.iso does not boot

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#302]
https://github.com/a1ive/grub2-filemanager/releases/download/v7.4.0/grubfm_multiarch.iso

map /grubfm_multiarch.iso (0xff)
chainloader (0xff)

We get a press a key to boot from CD/DVD
but on pressing a key it does not boot.

**Comment by a1ive** [comment]
can't reproduce.
> press a key to boot from CD/DVD

this message seems to be from bootmgfw.efi?

**Comment by steve6375** [comment]
hmmmm
it works if put as first entry in the main menu.lst.
but if I load the E2B menu, then after that it doesn't work.
So something must be affecting it.
I will try to narrow it down but my guess is that it is the  multiple map isofile  commands that I do is causing the issue...

**Comment by steve6375** [comment]
If I remove two Windows ISOs from MAINMENU folder so E2B does not enumerate them, then it works and boots OK.
So the map command must be failing and thus the previous map command (which was for the Windows ISO) is still active.
So this is same bug as the  map issue I reported before.

**Comment by a1ive** [comment]
bootmgfw.efi only supports reading `bcd` and other files from `(cd0)`, even if it is located on `(cd1)`. (Fxxk Microsoft!)
So in grub2, you need to use 'map -f' to put the virtual CD at the top of the disc list.
In grub4dos this is done by default, and perhaps yaya does not take into account the case of map multiple discs
