### ISSUE TITLE
grub4efi - ?_UUID variable is destroyed by cat --locate command

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#304]
![image](https://user-images.githubusercontent.com/1469350/128240471-03836513-5212-4848-a4da-7a2cfd5a3e2e.png)

**Comment by steve6375** [comment]
P.S. When using ntloader, how do we specify a file path/name containing spaces?

file=/_ISO/AA BB/Boot x64.wim

**Comment by steve6375** [comment]
?_UUID seems to be the same as ?
for both grub4dos and grub4efi
???

**Comment by yaya2007** [comment]
"?_UUID"不是一个专属变量，它等同于"?"，可用于任何函数，把指定值传递出来。

空格可使用冒号"："替代。

**Comment by steve6375** [comment]
So ?_BOOT is an exclusive variable but ?_UUID is not?
What is the purpose of ?_UUID? Why not just use ? instead?
It seems very strange.

**Comment by yaya2007** [comment]
目前，cat，uuid，map 在使用。

**Comment by steve6375** [comment]
maybe update uuid  help text? No mention is made of ? or ?_UUID
and that ?_UUID is a temporary variable which may be changed by other commands.
![image](https://user-images.githubusercontent.com/1469350/128332955-edf4c17e-2069-4d0d-b64b-dcaf592edb65.png)
maybe add
'uuid of DEVICE is returned in temporary variables ? and ?_UUID.'

**Comment by yaya2007** [comment]
好的

**Comment by steve6375** [comment]
P.S. Latest test version has debug code in chainloader ???
![image](https://user-images.githubusercontent.com/1469350/128342434-46401a66-04d0-4702-9ae1-8a226dfe32d5.png)
It waits for keypress.

**Comment by steve6375** [comment]
###

**Comment by yaya2007** [comment]
不好意思，又带了调试代码。

**Comment by yaya2007** [comment]
已经提交官网。
