### ISSUE TITLE
grub4dos-0.4.6a-2021-07-28 failed to boot memtest (restarts PC)

### ISSUE THREAD

**Issue by xrayer** [chenall/grub4dos#305]
I tried to update my year old grub4dos with latest version grub4dos-0.4.6a-2021-07-28 and found that it is unable to load Memtest 4.3.7 image that I have in menu - the PC immediatelly reboots, I cannot see any message.
I reverted to the next older version 2020-08-09-0da21fe and it loads Memtest OK. Something has broken between...
Machine: core i7-2600k with Award BIOS (pre-UEFI), 4GB RAM, bare/plain DOS (no memory managers, etc.)

**Comment by yaya2007** [comment]
可以提供 grub4dos-0.4.6a-2020-08-09 到 grub4dos-0.4.6a-2021-07-28 之间，具体是哪个版本出现问题？
我如何重现问题？

**Comment by xrayer** [comment]
Hi, please could you write it in english? I don't understand chinese "spreaded tea" :)

**Comment by a1ive** [comment]
1. Please provide the download link.
2. Please provide the configuration menu you use to load memtest
3. It would be good to test exactly which version introduced the bug.

**Comment by xrayer** [comment]
Memtest image here:
http://rayer.g6.cz/1tmp/MEMTEST.BIN

Menu.lst entry:
title MemTest
kernel /DOS/PLUS/memtest.bin

As I told the last working version I can get is 2020-08-09-0da21fe. I don't see any DOS releases between this and the latest version 2021-07-28 (releases between are only UEFI but I can't see more DOS versions)

**Comment by yaya2007** [comment]
The uploaded attachment cannot be downloaded

**Comment by a1ive** [comment]
> The uploaded attachment cannot be downloaded

[MEMTEST.zip](https://github.com/chenall/grub4dos/files/6954782/MEMTEST.zip)

**Comment by xrayer** [comment]
I don't see any problem with downloading it.

**Comment by steve6375** [comment]
I get the same issue in VBox 5
latest grldr causes memtest.bin to crash
Previous 2020 version is OK.

**Comment by yaya2007** [comment]
grub4dos-0.4.6a-2021-01-27.7z补丁，引发了这个问题。
拿grub4dos-0.4.6a-2021-07-28.7z版本为例，我本地编译的可以正常运行，而官网编译的则不能运行。

这个是chenall提供的补丁。我不擅长编译，chenall也忙，a1ive帮忙看看。

**Comment by a1ive** [comment]
> grub4dos-0.4.6a-2021-01-27.7z补丁，引发了这个问题。
> 拿grub4dos-0.4.6a-2021-07-28.7z版本为例，我本地编译的可以正常运行，而官网编译的则不能运行。
> 
> 这个是chenall提供的补丁。我不擅长编译，chenall也忙，a1ive帮忙看看。

2021-01-27及以后发布的版本，都是在 github action 上编译的，用的是 gcc-4.8。以前的版本，是在 travis-ci 上编译的，用的是 gcc-4.6。
我记得有人说过 gcc-4.8 编译会导致不能启动  memtest86。@chenall
http://bbs.c3.wuyou.net/forum.php?mod=viewthread&tid=404409

**Comment by yaya2007** [comment]
我本地也是gcc-4.8。但是编译环境是32位的。是不是因为32/64的问题。

**Comment by chenall** [comment]
我这些天再抽空看一下.

刚好也看到这里的信息

https://github.com/actions/virtual-environments

目前使用的编译环境 21-09-20 会被删除, 得测试新的编译环境,我也忘了之前用 16.04 具体是什么原因了^_^

**Comment by chenall** [comment]
@yaya2007 麻烦你先用你那边的编译环境 (colinux gcc) ,编译一个让他测试下看看,如果可以的话我直接把0.4.6a版改成使用 colinux  编译好了.

**Comment by chenall** [comment]
@xrayer 

Please try this, (complited with  colinux_dev)

https://transfer.sh/1Fsr7yA/grub4dos-0.4.6a-2021-08-12.7z

**Comment by yaya2007** [comment]
@chenall
不好意思，我刚刚看到。
colinux gcc 4.8编译得肯定行。我自己前两天已经测试过了。

**Comment by xrayer** [comment]
Booting memtest now works OK, did you found the root cause? Thanks for fix.
