### ISSUE TITLE
grub4efi - batch files are very slow to execute

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#310]
Large batch files seem to run very slowly in grub4efi (much slower than grub4dos).
Could this be due to the Ctrl+C checking that is done after every line of the batch file?
Would it be possible to have a way to disable the Ctrl+C checking?
Then I could see if it was the cause of this issue.
maybe a debug switch like  
debug ctrl-c-trap=0 (do not check)  
debug ctrl-c-trap=1 (check for ctrl+c) ???

This would also solve the issue of the check absorbing key presses when it is not wanted.

**Comment by steve6375** [comment]
Example:
bubble sort batch file
grub4dos =  0.5 seconds
grub4efi = 75 seconds !!!!!

**Comment by yaya2007** [comment]
给一个测试批处理

**Comment by steve6375** [comment]
Test under VBox 5
![image](https://user-images.githubusercontent.com/1469350/129029201-d0a5af4f-efbc-42a1-be74-a4a7c74e1b84.png)
![image](https://user-images.githubusercontent.com/1469350/129030649-339b6c81-0ca1-4e90-9e96-b5039daf47ab.png)



```
!BAT
echo %@TIME%
if exist @uefi echo UEFI || echo MBR BIOS
set c=1
:loop
set x=1
set y=2
set z=3
set /a c=%c%+1 > nul
if %c%<=5000 goto :loop
echo %@TIME%
```

**Comment by steve6375** [comment]
On IdeaPad300
MBR - instant!
UEFI - 25 seconds

**Comment by yaya2007** [comment]
是Ctrl+C检测引起的。
debug ctrl-c-trap=0
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6973607/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Wow!!  Much faster!
Thanks!
Is this final solution or can  the uefi checkkey code be improved to make it faster and not absorb key-presses?
will default state be  0 or 1 ?

**Comment by yaya2007** [comment]
现在默认1。
checkkey我再看看，恐怕不容易。

**Comment by yaya2007** [comment]
没有什么再调整的了。
