### ISSUE TITLE
Issue with variables in a batch file ending with %*

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#311]
![image](https://user-images.githubusercontent.com/1469350/128874433-7aefc86d-61c7-42d7-9416-5fe7d61effcf.png)

why is  echo fred2=%fred%*   producing bad result but only in a batch file?
Same command when run from command line produced expected result.
same in many (all) versions?
Is this expected for a batch file?

**Comment by yaya2007** [comment]
批处理应当使用
echo %%fred%%*

**Comment by steve6375** [comment]
Why? %* is being recognised as 'all parameters' but it is preceded by a %fred  so the parser should recognise that it is a variable and not %*?
