### ISSUE TITLE
grub4efi - dd fails when using a menu entry

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#312]
1. Boot to grub4efi menu.lst (UEFI64)
```
title Test dd
call /test.g4b
errorcheck off
boot

title e2b
configfile (bd)/_ISO/e2b/grub/menuefi.lst
boot
```

2. Select Test dd menu
this runs batch file  /test.g4b

```
!BAT
errorcheck on
debug 3
debug msg=3
dd if=(hd0)0+1 of=(hd0)31+1
echo
echo
echo
dd if=(hd0)0+1 of=(hd0)31+1 || pause dd failed
pause
goto :eof
```

Result: dd fails !!!

![image](https://user-images.githubusercontent.com/1469350/129073960-075cd714-3747-41f3-8638-d2885859e188.png)

However, if run /test,g4b from command line then it works OK!!!
![image](https://user-images.githubusercontent.com/1469350/129074080-395bf8c8-26e7-43c6-8d81-26fe44392943.png)

**Comment by steve6375** [comment]
```
title test dd
dd if=(hd0)0+1 of=(hd0)31+1 || pause dd failed
errorcheck off
boot
```

This also fails
![image](https://user-images.githubusercontent.com/1469350/129074590-27697c74-cd23-42df-a055-b5c396a785f0.png)

**Comment by yaya2007** [comment]
在qenu虚拟机测试：
1. 批处理正常
 !BAT
errorcheck on
debug 3
debug msg=3
echo
echo
echo
dd if=(hd0)0+1 of=(hd0)1+1 || pause dd failed
pause
goto :eof

2.命令行正常
dd if=(hd0)0+1 of=(hd0)1+1 || pause dd failed

**Comment by steve6375** [comment]
yes
But it fails when run from a menu.lst file
Just try simple menu and you will see
```
title test dd
errorcheck on
dd if=(hd0)0+1 of=(hd0)31+1
errorcheck off
boot

```
![image](https://user-images.githubusercontent.com/1469350/129224115-206fe6d3-8016-44f9-ba98-7c71a8af2a7c.png)

**Comment by steve6375** [comment]
P.S.  buf= and buflen= are not supported in grub4efi??
![image](https://user-images.githubusercontent.com/1469350/129223709-f70bf4b6-460f-4720-8ee3-21e138f7d266.png)

**Comment by steve6375** [comment]
builtins.c

Is this the problem?

![image](https://user-images.githubusercontent.com/1469350/129232704-75b71f9d-ad0d-41fa-8a8f-610dce5f5cae.png)

**Comment by steve6375** [comment]
Similar code is also in write_func too
![image](https://user-images.githubusercontent.com/1469350/129233258-57782948-f47e-49ab-be24-fa868934ebb0.png)

**Comment by yaya2007** [comment]
dd是一个危险的函数。因此，原作者做了如下限制：
如果不是映射驱动器，只允许在命令行运行，禁止在菜单或者脚本中运行。

**Comment by steve6375** [comment]
Please remove this restriction. It makes no sense.
grub4dos does not have this restriction. a1ive grub2 does not have this restriction. grub4efi partnew/parttype does not have this restriction. Linux and Windows dd command does not have this restriction.
Menu files and batch files are carefully written.
If dd can only be used manually from the command line then there is no point in providing the dd command!
Many functions in Easy2Boot and other grub4dos based menus use dd to change disk contents.

**Comment by yaya2007** [comment]
这个限制，源于grub4dos，不是g4e修改的。

**Comment by steve6375** [comment]
I use grub4dos for many years in E2B.
I use dd for many years
Writing to disk using dd in grub4dos works OK.
Please check grub4dos source code - isn't the code non-active due to `#if 0` statement?
One of main purposes of dd is to edit disk!
Please remove code in grub4efi so we can write to disks.

grub4dos - builtins.c
![image](https://user-images.githubusercontent.com/1469350/129344175-c5577a30-2f91-4f14-bb75-706fc7572121.png)

**Comment by steve6375** [comment]
shared.h  grub4dos
![image](https://user-images.githubusercontent.com/1469350/129344428-c9146d1c-7d70-4481-8ad3-e88664415e40.png)

**Comment by yaya2007** [comment]
刚才看了一下代码，确实g4d屏蔽了2处有关代码。

不知何时g4d屏蔽的。我制作g4e时，代码还没有屏蔽。

g4e可以修改过来。保存一致。

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/6985652/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
great! Many thanks!
