### ISSUE TITLE
grub4efi - error numbers do not match grub4dos documentation

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#313]
ERR_INTERNAL_CHECK,
  ERR_KERNEL_WITH_PROGRAM,
  ERR_HALT,
  ERR_PARTITION_LOOP,
  ERR_NOT_ENOUGH_MEMORY,
  ERR_NO_VBE_BIOS,
  ERR_BAD_VBE_SIGNATURE,
  ERR_LOW_VBE_VERSION,
  ERR_NO_VBE_MODES,
  ERR_SET_VBE_MODE,
  ERR_SET_VGA_MODE,
  ERR_LOAD_SPLASHIMAGE,
etc.
These error numbers have changed due to insertion of new error code ERR_WRITE_TO_NON_MEM_DRIVE.
error numbers are not the same as grub4dos and so makes diagnositics harder.
Please move ERR_WRITE_TO_NON_MEM_DRIVE to end of list in shared.h

![image](https://user-images.githubusercontent.com/1469350/129320286-800af3ac-31d5-4780-9ec2-d5e3bd3d4ff6.png)
![image](https://user-images.githubusercontent.com/1469350/129320495-e8938148-723d-416e-a3d2-b0ac1a2fa08f.png)

**Comment by yaya2007** [comment]
见 #312

**Comment by steve6375** [comment]
Thanks
