### ISSUE TITLE
grub4efi - $[ABCD] colour setting not working in console mode

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#320]
![image](https://user-images.githubusercontent.com/1469350/130211084-3c25a1f7-aad4-4223-8af7-e07318e89720.png)

![image](https://user-images.githubusercontent.com/1469350/130210591-a2258dd2-033f-4840-8bd4-81b861dadedc.png)
![image](https://user-images.githubusercontent.com/1469350/130211179-23c120ad-53b3-44d9-8aed-443a83d0e83a.png)

In grub4dos works OK
![image](https://user-images.githubusercontent.com/1469350/130210785-3ad1213c-ab8c-4e32-80b6-1baa20f5f6ec.png)
![image](https://user-images.githubusercontent.com/1469350/130211517-035cda14-dad2-4e05-b918-238d0de32db8.png)

**Comment by yaya2007** [comment]
见 #319

**Comment by steve6375** [comment]
Looks good 👍
