### ISSUE TITLE
grub4efi - text on background not compatible with grub4dos

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#324]
menu.lst
```
graphicsmode -1 800
call Fn.70 3
splashimage /_ISO/docs/Templates/Blue/blue.bmp.gz
map --mem --read-only /_ISO/docs/Templates/Animate/E2B_GIF.ima (fd3)
map --hook
splashimage --animated=0x90=3=9=615=160 (fd3)/frame_0001.bmp
echo Hello
echo
echo How do I get the background to be displayed?
pause
```

Fn.70  is not working in same way as with grub4dos???

Using grub4dos:
![image](https://user-images.githubusercontent.com/1469350/130359918-1da12340-5732-4711-a947-946b859f296e.png)

Using grub4efi:
![image](https://user-images.githubusercontent.com/1469350/130359243-533f51cf-24b2-4ed0-b2b0-6ac5df0c6d11.png)

**Comment by steve6375** [comment]
Fn.70 1 and 2 are compatible with grub4dos
0 and 3 are not compatible with grub4dos


grub4efi Fn.70 3
![image](https://user-images.githubusercontent.com/1469350/130360511-c4a623b1-2597-46d1-8ab2-ec808eb6d2d3.png)

grub4dos Fn.70 3
![image](https://user-images.githubusercontent.com/1469350/130360461-0f57309c-a6de-41a2-b2eb-eeb90cbc7f81.png)


grub4efi Fn.70 2
![image](https://user-images.githubusercontent.com/1469350/130360399-c3fa9fc7-049e-4c4c-8a94-d585e15482b1.png)

grub4dos Fn.70 2
![image](https://user-images.githubusercontent.com/1469350/130360363-8f08c45a-f868-4d07-a3db-f6b56b9c4e0b.png)

grub4efi Fn.70 1
![image](https://user-images.githubusercontent.com/1469350/130360586-19ab7521-76b5-4625-a78d-3dec653e6320.png)

grub4dos Fn.70 1
![image](https://user-images.githubusercontent.com/1469350/130360545-e659d562-ef43-40c0-bad7-6f8f3c96cfef.png)

grub4efi Fn.70 0
![image](https://user-images.githubusercontent.com/1469350/130360624-8fdc8e75-6c51-4d4b-aa46-f535197f0e35.png)

grub4dos Fn.70 0
![image](https://user-images.githubusercontent.com/1469350/130360650-d388a209-6e2b-4bf1-884a-b83662869ee3.png)

**Comment by steve6375** [comment]
maybe part of the issue is that
https://github.com/chenall/grub4dos/blob/efi/stage2/graphics.c
animation code has
setcursor (2)   call ??

**Comment by yaya2007** [comment]
graphicsmode -1 800
call Fn.70 3
splashimage /_ISO/docs/Templates/Blue/blue.bmp.gz
Should be 
graphicsmode -1 800
splashimage /_ISO/docs/Templates/Blue/blue.bmp.gz
call Fn.70 3
clear

Please test 
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/7104367/BOOTX64.rar.txt)

#283 Same problem

**Comment by steve6375** [comment]
much better -thank you -  but a bit strange!

Fn.70 0  = non-background, no cursor OK
Fn.70 1 = non-background, with cursor OK
Fn.70 2 = background, no cursor  (indented text??)  
Fn.70 3 = background, **no cursor**  (indented text??)

![image](https://user-images.githubusercontent.com/1469350/131983747-c8160692-2ec7-4020-ac28-74bf602b9351.png)

so it seems to be more compatible, except Fn.70 3 does not show any cursor, and strange indented lines when in console terminal.

**Comment by steve6375** [comment]
Still not compatible with grub4dos

```
#bit 0 set = cursor on
#bit 1 set = graphics background on


title 70 0 - cursor off - background off  (FAIL - background behind text)
set n=0
color normal=cyan/black highlight=red/black  > nul
graphicsmode -1 1024
splashimage --fill-color=0x000099
call Fn.70 %n%
clear
echo display some text  Fn.70 %n%
echo more text to display
pause
errorcheck off
boot

title 70 1 - cursor on - background off  (OK)
set n=1
color normal=yellow/black highlight=red/black  > nul
graphicsmode -1 1024
splashimage --fill-color=0x000099
call Fn.70 %n%
clear
echo display some text  Fn.70 %n%
echo more text to display
pause
errorcheck off
boot

title 70 2 - cursor off - background on  (OK)
set n=2
color normal=green/black highlight=red/black  > nul
graphicsmode -1 1024
splashimage --fill-color=0x000099
call Fn.70 %n%
clear
echo display some text  Fn.70 %n%
echo more text to display
pause
errorcheck off
boot

title 70 3 - cursor on - background on (FAIL - no cursor )
set n=3
color normal=white/black highlight=red/black  > nul
graphicsmode -1 1024
splashimage --fill-color=0x000099
call Fn.70 %n%
clear
echo display some text  Fn.70 %n%
echo more text to display
pause
errorcheck off
boot


title Reload
chainloader /_ISO/e2b/grub/bootx64.efi

title E2B
configfile (bd)/_ISO/e2b/grub/menuefi.lst
```

![image](https://user-images.githubusercontent.com/1469350/132124798-f7c5fab7-df49-490b-9ff2-802a9806d2f8.png)
text has background behind it


![image](https://user-images.githubusercontent.com/1469350/132124812-c8699224-4bc2-42a4-bcb8-9b73b2eaa89a.png)
no cursor

**Comment by yaya2007** [comment]
Give it a try

**Comment by yaya2007** [comment]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/7112702/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
console issue is fixed, but  test menu still shows same bugs as above...

Fn.70 0   -  cursor is on  - **FAIL**
Fn.70 1 -  cursor on, no background - OK
Fn70 2 -  cursor off, background on - OK
Fn70 3 - cursor  is off - **FAIL**

**Comment by yaya2007** [comment]
在命令行，必须有光标，不能关闭。
在菜单，不能有光标，不可打开。

**Comment by steve6375** [comment]
OK - so it is a limitation of EFI environment?

**Comment by a1ive** [comment]
> OK - so it is a limitation of EFI environment?
> If so, I am happy ;-)

No.
> EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.EnableCursor() 
Summary 
Makes the cursor  visible  or invisible. 
Prototype 
typedef EFI_STATUS (EFIAPI *EFI_TEXT_ENABLE_CURSOR)  (  IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL  *This, IN  BOOLEAN                           );

**Comment by steve6375** [comment]
???

**Comment by yaya2007** [comment]
在命令行，要使用键盘输入字符，有光标，似乎方便一些。你非要关闭。
在菜单模式，只是显示预先设置好的一些信息，要光标有何用?``

**Comment by steve6375** [comment]
User may be prompted to type in characters when in graphics menu mode.
If no cursor then commands like wait or secret password entry will not display cursor which may be wanted.
Should be compatible with grub4dos Fn.70.

**Comment by yaya2007** [comment]
Hope it meets your needs
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/7118264/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Thank you - looks good. Will close when new version released.
Many thanks again.
