### ISSUE TITLE
0.4.6a Problem with ISOs on exFAT volumes

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#33]
This problem does not occur with 0.4.5c (e.g. 2015-01-20)
Using 230GB SSD formatted as exFAT under VBox

*fresh* boot:
![image](https://cloud.githubusercontent.com/assets/1469350/5887589/adaeacf0-a3d1-11e4-9b6f-cbcc8e778fb2.png)

if map --hook  and ls (0xff)/  we get:
![image](https://cloud.githubusercontent.com/assets/1469350/5887595/e79b93c4-a3d1-11e4-9064-b40dc09f3be2.png)

but 0.4.5c is OK
![image](https://cloud.githubusercontent.com/assets/1469350/5887601/311add16-a3d2-11e4-9337-050992352a77.png)
![image](https://cloud.githubusercontent.com/assets/1469350/5887611/3ac7305c-a3d3-11e4-9477-0106b458f834.png)

Also NTFS is OK
![image](https://cloud.githubusercontent.com/assets/1469350/5887649/78b97b66-a3d5-11e4-86a5-3b166a16d3b7.png)

The weird thing is, if I boot to 0.4.5c and then chainloader /grldr_046_2015-01-24 on the exFAT drive -   then it works!!!

**Comment by steve6375** [comment]
I tried latest version and map --iso-types=x  and cannot make any of them work.

**Comment by steve6375** [comment]
Are you able to reproduce/fix this? I think the problem may be due to uninitialised memory in exFAT code.
If I boot using 0.4.5c and then chainloader /grldr_046  then it works OK, but if I just boot directly to grldr which is 0.4.6a version then I get this problem.

**Comment by steve6375** [comment]
Same problem on 2GB exFAT drive!
1. Make 2GB exFAT drive using RMPrepUSB - exFAT option and choose grub4dos option to install MBR.
2. Add 0.4.6a /grldr and an ISO
3. boot
debug 2
map /new.iso (0xff)
>>> many errors
map --hook
ls (0xff)/
>>> many errors

If use 0.4.5c \grldr then works fine - no problems!
if boot 0.4.5c and  then chainloader \grldr_046a  then works fine too!
Only if fresh/clean boot to grldr v 0.4.6a do you get errors!!!

**Comment by yaya2007** [comment]
0.4.6a 2015_01_20  for expat OK?

**Comment by steve6375** [comment]
No - 0.4.6a does not work with exFAT - 2015-01-20 or many previous or after!

**Comment by yaya2007** [comment]
感谢 steve6375 费心的对比测试，并提供了详尽的资料。

似乎可以得出结论： 问题在exFAT。
但是对比测试只能用 1 个变量，而 “fresh boot” 与 “but 0.4.5c is OK” 却有 2 个变量，即版本号与主分区0.
“fresh boot”             80，20 21 00，07，FE FF FF，00000800，1D1C3D42
“but 0.4.5c is OK”   80，00 01 00，00，3F E0 D4，00000000，001EA800 
正是分区长度 1D1C3D42 惹出事端。
位于 bios.c 的 get_diskinfo 函数。
如果将 exFAT 的主分区0修改为：  80，00 01 00，00，3F E0 D4，00000000，001EA800 应当 OK。

当然分区长度比较大就做错误处理是否恰当，就得请教不点或其他高人。

**Comment by yaya2007** [comment]
@steve6375 
在某 issues，你反映 iso9600_Joliet 在使用 ls 命令时，文件名偶尔出现乱码。
问题是由于没有执行 “unicode16大尾转小尾” 的操作。
我仔细查看代码没有找到原因。反编译了从官方下载的 grldr，也没有找到原因。
请问：是使用官方下载的 grldr？还是下载源码自己编译的 grldr？
可否上传出问题的那个 grldr？

**Comment by steve6375** [comment]
re. exFAT problem - Disk is same in both screenshots - **only** difference is \grldr file has been changed.
“but 0.4.5c is OK” 80，00 01 00，00，3F E0 D4，00000000，001EA800  >> This is **ISO** that is being mapped, not the exFAT disk.
In 0.4.6a I get warnings about  exFATdisk geometry - in 0.4.5c I do not and it works OK.

CASE 1 - WORKS
1. \grldr is 0.4.5c version
2. Boot to menu.lst and goto console
3. use map/hook/ls command - all OK - no error.

CASE 2 - FAILS
1. \grldr is 0.4.6a version
2. Boot to menu.lst and goto console
3. use map/hook/ls command - FAILS!

CASE 3 - WORKS
I can get 0.4.6a to work as follows if I first boot to 0.4.5c:
1. \grldr is 0.4.c
2. boot to grub4dos menu and goto console
3. chainloader /grldr_046  (reloads grub4dos menu)
4. use map/hook/ls command - all OK - no error.

**Comment by steve6375** [comment]
re. 在某 issues，你反映 iso9600_Joliet 在使用 ls 命令时，文件名偶尔出现乱码。

I cannot reproduce this problem of garbled text with newer versions of 0.4.6a - if I find the problem again I will report to you. 

Please look at exFAT problem. Very reproducible.
Format a USB drive using RMPrepUSB - exFAT and say Yes to install grub4dos MBR so you can boot to exFAT.
![image](https://cloud.githubusercontent.com/assets/1469350/5987745/e602338e-a934-11e4-84cd-dfaf607fc3b3.png)

**Comment by yaya2007** [comment]
初步修正。
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=327458&pid=3041075&page=82&extra=#pid3041075

**Comment by steve6375** [comment]
That version seems to work with exFAT (initial testing OK)  :+1:

**Comment by chenall** [comment]
did you try new version?
http://grub4dos.chenall.net/downloads/grub4dos-0.4.6a-2015-02-08/

**Comment by steve6375** [comment]
Yes - looks OK so far. thanks. Will close in about a week if no problems found. Thanks!

**Comment by steve6375** [comment]
Still looking good. Will close now. Thanks for fixing it. :+1:
