### ISSUE TITLE
Feature request - set different colours in title command

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#339]
Would it be possible to define coloured text in the menu entry and the menu entry help text.

title $[0xff0000]This is a $[0xaabbcc]title\nThis is $[0x0e]text$[0x0f] and this\n2nd line $[]is help too.

or some other way to have multiple colours in title and iftitle lines?

**Comment by yaya2007** [comment]
"title [[$[0xCD]]TITLE] [\\n[$[0xCD]]NOTE]",
  "$[0xCD] Sets the 64 bit number color for TITLE and NOTE.\n"
  "        C=background(high 32 bits), D=Character(low 32 bits).\n"
  "$[] Restore COLOR STATE STANDARD."	

example 
title boot $[0xff00ff]Windows$[]10\nVersion $[0xff00]1905.28$[]
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/7325929/BOOTX64.rar.txt)
