### ISSUE TITLE
command set-ext setting is lost/corrupt

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#34]
after a call to batch file, one of the CHECK paths is /ggg(md)/LstFExt.g4b  ??
and /_ISO/e2b/grub/ggg.g4b has disappeared! 

![image](https://cloud.githubusercontent.com/assets/1469350/6021050/65618c66-abaa-11e4-86cd-f478d67d1172.png)

Main.g4b
=======
# set default extension for executables
command --set-ext=.g4b
# set default path for executables
command --set-path=/%grub%
call CountFiles.g4b

CountFiles.g4b
===========
!BAT
echo -n Counting Windows Install ISOs %redir%
insmod /%grub%/LstFExt.g4b > nul
echo -n %redir%
# get filecount of WINDOWS ISOs for next WINDOWS menu
debug 3 ;; ggg ;; pause 33c
LstFExt.g4b /_ISO/WINDOWS/XP .iso SILENT
debug 3 ;; ggg ;; pause 33d
...
...

LstFExt.g4b
=========
debug 3 ;; ggg ;; pause LstFextA1 delmod -l %~nx0 
delmod -l %~nx0 
debug 3 ;; ggg ;; pause LstFextA4

**Comment by chenall** [comment]
Please try new.

**Comment by steve6375** [comment]
Fixed I think - thanks!
