### ISSUE TITLE
splashimage animation bug when using bit 5

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#340]
The following code hangs on last test when bit 5 is set

```
title TEST ANIMATION
graphicsmode -1 800
clear
set ANIMFD3=/PK_GIF.ima
map --mem %ANIMFD3% (fd3) > nul
map --hook > nul
echo Using 0x10  infinite animation
set ANIMATE=0x10=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
splashimage --animated=%ANIMATE%

pause stop animation...
splashimage --animated=0

pause show 1 loop - now test bit 5...
echo using 0x21 - 1 loop - wait
set ANIMATE=0x21=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
splashimage --animated=%ANIMATE%
pause show 1 loop
errorcheck off
boot
```

The problem seems to be caused by the infinite play.
If you change 0x10  to 0x11 (or 0x01)  AND let the animation **finish** before pressing ENTER, then second animation works and does not crash/hang.
[Anim_bug.zip](https://github.com/chenall/grub4dos/files/7315598/Anim_bug.zip)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/136658901-9fb6c67d-6020-4624-96c7-1824893e362c.png)

also help does not explain that using  0x00 is stop play and 0x10 is for infinite play

e.g.
splashimage --animated=0x00=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP  - does not display !!!

splashimage --animated=0x10=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP  - display infinite animation

should say **0x10** is repeat play and type=0x00 is disable?

**Comment by yaya2007** [comment]
所需内容，帮助信息里都有。
times(0=repeat play)
type=00:disable

有可能表述不准确或者不详细。也有可能百度翻译不贴近。
若干年前开发动画功能时，有关帮助信息，你也参与了讨论，可能时间久了，有所淡忘。
重新修改了一下帮助：
  "splashimage --animated=[type]=[duration]=[last_num]=[x]=[y] START_FILE\n"
  "type: bit 0-3: times(If zero, infinite loop.)\n"
  "      bit 5: Do not display menu.    bit 7: transparent background\n"
  "If type=0, stop working.\n"
  "duration: [10] unit is a tick. [10:ms] units are milliseconds,\n"
  "naming rules for START_FILE: *n.???   n: 1-9 or 01-99 or 001-999\n"
  "hotkey F2,control animation:  play/stop."

**Comment by steve6375** [comment]
Help test does not mention bit 4. Help text says 'if zero, infinite loop'  but  this does not work

if zero, stops play.

Help text does not explain how to get infinite loop.

e.g. for infinite play  type = 0x10

**Comment by steve6375** [comment]
But  can you explain why this code hangs?
```
title TEST ANIMATION
graphicsmode -1 800
clear
set ANIMFD3=/PK_GIF.ima
map --mem %ANIMFD3% (fd3) > nul
map --hook > nul

set ANIMATE=0x10=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
splashimage --animated=%ANIMATE%

splashimage --animated=0

set ANIMATE=0x21=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
splashimage --animated=%ANIMATE%


pause press ENTER
errorcheck off
boot
```

BUT this code does not hang and works as expected:
```
title TEST ANIMATION
graphicsmode -1 800
clear
set ANIMFD3=/PK_GIF.ima
map --mem %ANIMFD3% (fd3) > nul
map --hook > nul

#####set ANIMATE=0x10=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
#####splashimage --animated=%ANIMATE%

#####splashimage --animated=0

set ANIMATE=0x21=1=75=695=225 (fd3)/PK/PK_GIF_frame_0001.BMP
splashimage --animated=%ANIMATE%


pause press ENTER
errorcheck off
boot

```

**Comment by yaya2007** [comment]
位4没有定义，使用无效。
位0—位3，是循环次数。1播放1次 ，2播放2次。0无限循环。

**Comment by steve6375** [comment]
0 is not infinite loop - 0 is stop play

**Comment by steve6375** [comment]
Bits 0-4 : 0x00=stop play, 0x01-0x0F=play n times, 0x10=infinite play
Bit 5 : 1=play and wait until finished, 0=play now in background
Bit 7 : 1=transparent, 0=opaque

Is this better for help?

**Comment by yaya2007** [comment]
0停止播放，是位0—位7全部为0。
比如：
90  无限循环
93  循环3次
00  停止播放

**Comment by steve6375** [comment]
0x90 is  transparent (bit 7) + infinite loop  - bit 4 is set  - so bit 4 is NOT invalid!

What should I use for  opaque + infinite loop ? must be 0x10  ???
