### ISSUE TITLE
Request: How to get current graphics mode?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#35]
http://reboot.pro/topic/16340-graphicsmode-syntax/#entry190353

**Comment by chenall** [comment]
with new version can get current graphics mode by graphics_inited
graphics_inited ((*(int **)0x8304)[23])
```
set /a n=23<<2+*0x8304&0xffffffff
set /A n=*%n%*0xffffffff
echo current graphics mode is %n%
```

**Comment by steve6375** [comment]
I used 0.4.6a 2015-02-09 but this doesn't seem to work for graphicsmode 3? Is code correct???
set /a n=23<<2+*0x8304&0xffffffff
set /A n=*%n%*0xffffffff
echo current graphics mode is %n%

**Comment by steve6375** [comment]
set /a n=23<<2+*0x8304&0xffffffff
set /A n=*%n%&0xffffffff
echo current graphics mode is %n%

typo fixed
Now this works for graphicsmode 0x11B  but not for graphicsmode 3 which reports 0 in 0.4.6a 2015-02-09
0.4.5c 2015-01-20 does not report correctly.

**Comment by chenall** [comment]
graphicsmode 3 is text mode

graphics_inited is set when using graphics mode

**Comment by steve6375** [comment]
OK - so 0 = text mode
