### ISSUE TITLE
grub4efi Only BOOTIA32.EFI  stoped boot if memory  143  or reboot if  memory more than  143 gcc version 8.4 

### ISSUE THREAD

**Issue by memoarfaa** [chenall/grub4dos#356]
qemu-system-i386 -bios OVMF32.fd -cdrom efiboot.iso -boot d  -m 143

![2022-05-30_17-55-35](https://user-images.githubusercontent.com/12494184/171030150-3d0c1ef0-c911-4f03-9cce-ed464c0f77f4.png)

qemu-system-i386 -bios OVMF32.fd -cdrom efiboot.iso -boot d  -m 144
reboot for ever

@chenall  @yaya2007  @a1ive

**Comment by yaya2007** [comment]
Compile with gcc4.8

**Comment by memoarfaa** [comment]
but both 4.6a and x86_64 efi work fine only i386 efi give this error

**Comment by memoarfaa** [comment]
edit configure 
replace
 if { ac_try='${OBJCOPY-objcopy} -O binary conftest.exec conftest'

with
{ ac_try='${OBJCOPY-objcopy} --only-section=.text -O binary conftest.exec conftest'

build with  
CFLAGS="-fno-stack-protector -fno-pie -no-pie" ./build

you can look at 
https://stackoverflow.com/questions/43367427/32-bit-absolute-addresses-no-longer-allowed-in-x86-64-linux

and this
https://wiki.ubuntu.com/ToolChain/CompilerFlags

**Comment by memoarfaa** [comment]
close as resloved see  
https://github.com/chenall/grub4dos/issues/315#issue-971609878
