### ISSUE TITLE
grub4dos snake utility not working

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#359]
Not a very important issue, but it does not seem to run at all...

**Comment by yaya2007** [comment]
The function seems to be to write the screen directly.
I don't care about these old functions anymore.

**Comment by steve6375** [comment]
OK - maybe remove it from  ext  folder then?

**Comment by yaya2007** [comment]
These external commands are the works of predecessors. I just made UEFI adaptation. I think it's better to keep it as it is. Users can choose to use or give up.

**Comment by yaya2007** [comment]
These external commands are the works of predecessors. I just made UEFI adaptation. I think it's better to keep it as it is. Users can choose to use or give up.

**Comment by a1ive** [comment]
![1](https://user-images.githubusercontent.com/10670106/178273525-e2e85892-4368-4dc9-a41e-6faaa62cba50.png)
It works properly.
You need to set to `text` mode first. `graphicsmode 3`

**Comment by steve6375** [comment]
my mistake, I thought I tried that!
Its a shame, it is too slow  to play anyway...
