### ISSUE TITLE
0.4.6a does not report error using partnew with non-contigous files

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#36]
0.4.6a haiku file is non-contiguous - but partnew seems to partially work but does not report error:
map does not report error.
![image](https://cloud.githubusercontent.com/assets/1469350/6098068/ac9f6f7a-afca-11e4-9a6f-81506eda65bf.png)

![image](https://cloud.githubusercontent.com/assets/1469350/6098027/7828a294-afc9-11e4-8e6b-aa67dbcd5222.png)

![image](https://cloud.githubusercontent.com/assets/1469350/6097995/9e5fc830-afc8-11e4-9bd2-558512862487.png)
![image](https://cloud.githubusercontent.com/assets/1469350/6098015/1a9d72bc-afc9-11e4-80e0-e313f6a2e97a.png)

0.4.5c
![image](https://cloud.githubusercontent.com/assets/1469350/6097997/b1858ff8-afc8-11e4-9472-90722deefd7a.png)

**Comment by chenall** [comment]
0.4.6a can map with non-contigous files

**Comment by steve6375** [comment]
You cannot use partnew with non-contiguos files - it is not possible.
The file must be contiguous for partnew - how can you create a partition that is not contiguous?

**Comment by yaya2007** [comment]
use partnew with non-contiguous files：
Just a warning, continue to run?
Or by the error handling, the end of the map?

**Comment by steve6375** [comment]
I think must return error - what value is a bad/broken partition? Then is compatible with 0.4.5c
e.g
partnew (hd0,3) 0x0 /myiso.iso || echo ERROR!

**Comment by steve6375** [comment]
Is there a new version yet please?

**Comment by steve6375** [comment]
Can partnew just return an error if the file is not contiguous please? It is the last serious bug that needs fixing before I can use 0.4.6a for Easy2Boot as default version. Then we can move from 0.4.5c to 0.4.6a and drop development of 0.4.5c (once grubinst has been updated to work with 0.4.6a).

**Comment by yaya2007** [comment]
官网已更新,请测试.

**Comment by steve6375** [comment]
Thank you very much yaya - :+1:
