### ISSUE TITLE
Can't compile branch 046a_ahci_nvme

### ISSUE THREAD

**Issue by mcluskyism** [chenall/grub4dos#362]
Hello, I am sure I am missing something obvious
My environment is: Windows 10 64bit PC - MinGW 32bit with gcc.exe (GCC) 4.6.2
Following this [tutorial](https://pete.akeo.ie/2014/11/compiling-grub4dos-on-mingw.html) I get **undefined reference** errors at the stage `CCLD   pre_stage2.exec.exe` from `pre_stage2_exec-asm.o` to `stage2/asm.S`
Into latter one I find **#include "shared.h"** (`stage2/shared.h`) which seems to me to contain the needed definitions
What's going wrong?
P.S. same with pristine source of **master** branch
Log attached [build.txt](https://github.com/chenall/grub4dos/files/9126023/build.txt)
Thank you

**Comment by yaya2007** [comment]
Are you sure that windows 10 64bit PC can use MinGW 32bit? Try compiling with 32bit virtual machine.

**Comment by mcluskyism** [comment]
Hello @yaya2007 sorry for the delay and thanks for the reply.
The laptop on which I compile is corporate, I cannot have Admin rights, so I cannot install any virtual machine manager, but only portable applications like MinGW 32bit (very old version _mingw-get-inst-20120426_ ).
So you suspect the problem is due to the different bitness?
Could you suggest another GitHub repository, to try a build and see if the problem is actually due to different processor architectures?
Or maybe I need to pass some specific parameter to gcc? (which is 32bit)
Thanks for your attention

**Comment by yaya2007** [comment]
Read the log attached build Txt, like the source file asm S is wrong, such as:
\grub4dos\stage2/asm. S:5688: undefined reference to `prime_ end'
And my `prime_ End'at 5694

Take a look at asm S is the head:
#define ASM_ FILE
#define repair_ memory_ holes 1        //Is there any？
#include "filesys.h"
#include "shared.h"
#define ABS(x) ((x) - EXT_ C(main) + 0x8200)

. file "asm.S"
. text

**Comment by mcluskyism** [comment]
Hello @yaya2007 hello to everyone involved, if it helps, I have cloned the sources with `git clone --depth 1 --branch 046a_ahci_nvme https://github.com/chenall/grub4dos.git`
I have (in the MinGW's $PATH) `git version 2.37.1.windows.1` portable 32bit edition.
Did I do something wrong?
Thank you

**Comment by yaya2007** [comment]
Take a look at asm S is the head，
Whether there are the following two sentences, if not, add them.

#define ASM_ FILE
#define repair_ memory_ holes 1

**Comment by mcluskyism** [comment]
Hello @yaya2007 sorry, I did not understand.
Yes, the two strings are there, into `stage2/asm.S`
Line    37: `#define ASM_FILE`
Line    38: `#define repair_memory_holes 1`
I can't attach the file, the format is not supported even if I compress it .zip

**Comment by yaya2007** [comment]
Cannot download

**Comment by mcluskyism** [comment]
@yaya2007 can you browse a pastebin? same `stage2/asm.S` is [here](https://pastebin.com/BHriUU7L) Thanks for your help

**Comment by yaya2007** [comment]
Forbidden (#403)
Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.

**Comment by yaya2007** [comment]
You can put asm S sent here.

**Comment by mcluskyism** [comment]
I retry to publish it here, yesterday I was unable to attach the file, according to GitHub the format `.S` is not supported (I also tried to compress it .zip) maybe i try to rename it as asm.S.txt ... nothing, not even if I rename it works, GitHub won't let me load ... can I drop you an email? my preferred address is _**federico.segato.1974_at_gmail.com**_

**Comment by yaya2007** [comment]
[asm.rar.txt](https://github.com/chenall/grub4dos/files/9164683/asm.rar.txt)

**Comment by mcluskyism** [comment]
Hello, finally the GitHub upload worked!
I don't use WinRAR, I prefer 7-Zip, however first rename the file by removing the txt extension, you will get a 7z archive, and inside the archive you will find `stage2/asm.S` coming from my build folder. [asm.7z.txt](https://github.com/chenall/grub4dos/files/9169626/asm.7z.txt)
Thanks for your patience.

**Comment by yaya2007** [comment]
I uploaded asm S is the grub4dos for UEFI version, which is invalid.
Download your asm S version, which is consistent with my comparison. Therefore, the problem lies in the compilation environment. I'm not good at this. I can't help you. Sorry.

**Comment by yaya2007** [comment]
In shared.h
extern unsigned long minimum_ mem_ hi_ in_ map;
Add below

extern unsigned longprime_ end；
extern unsigned long new_ end；

have a try

**Comment by mcluskyism** [comment]
Hello @yaya2007 sorry, but neither string `extern unsigned longprime_end;` or `extern unsigned long new_end;` are present into `stage2\shared.h` as it is cloned from Git source [shared.7z.txt](https://github.com/chenall/grub4dos/files/9182633/shared.7z.txt)
No source file contains these two strings in the entire cloned repository, tried with find | grep.
Meanwhile, with the help of QEMU [portable](http://lassauge.free.fr/qemu/QEMU_on_Windows.html), I created a WinXP Pro SP3 32bit machine, tried a build into virtualized environment with same MinGW 32bit toolchain, and I got the exact same errors [build-QEMU.txt](https://github.com/chenall/grub4dos/files/9182746/build-QEMU.txt), try to compare it with _**build.txt**_ from my Opening Post.
So i don't think it's a bitness problem, maybe it is the toolchain that is not correct?
I'm still with gcc.exe (GCC) 4.6.2 - which gcc / toolchain do you use to have an error-free compilation?
Thank you
.

**Comment by mcluskyism** [comment]
Hi everyone, sorry if I look dull.
I added the two strings `extern unsigned long prime_end;` and `extern unsigned long new_end;` after `extern unsigned long minimum_mem_hi_in_map;` into `stage2/shared.h` [shared.7z.txt](https://github.com/chenall/grub4dos/files/9193391/shared.7z.txt) but that's not enough, I am attaching the log [buillog2.txt](https://github.com/chenall/grub4dos/files/9193395/buillog2.txt) 
Same errors with QEMU, virtual guest WinXP Pro SP3 32bit, same MinGW 32bit toolchain, same source with edited `shared.h` ... at this point I don't think it's a bitness problem, please see the log [QEMUbuildlog.txt](https://github.com/chenall/grub4dos/files/9193662/QEMUbuildlog.txt)
Could you please recommend a toolchain, already tested, and which produces a compilation without errors?
P.S. I deleted some of my previous comments, too much cluttering

**Comment by mcluskyism** [comment]
Won't fix but please see [https://github.com/chenall/grub4dos/issues/398](https://github.com/chenall/grub4dos/issues/398)
