### ISSUE TITLE
new version of grub4dos slic utility required

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#366]
Chenall loaded the slic utility as a module which is used in his NTBOOT code which can run bootmgr and make a BCD file.

Please can you make a new version of slic for the latest grub4dos version as the old slic version is no longer compatible and so NTBOOT no longer works.
[slic.zip](https://github.com/chenall/grub4dos/files/9172715/slic.zip)
The old version (binary) is attached.

**Comment by steve6375** [comment]
actually slic was apparently not made by chenall!
http://reboot.pro/index.php?showtopic=16429&page=38#entry192952
So I will close this.

**Comment by a1ive** [comment]
https://github.com/liudongmiao/grub4dos-patch
this version of slic?

**Comment by steve6375** [comment]
I guess that could be it?
Not sure if it is useful or needed these days as it is probably only for Win7?

**Comment by a1ive** [comment]
> Not sure if it is useful or needed these days as it is probably only for Win7?

Windows 7 and Windows Server (2008-2022)

**Comment by a1ive** [comment]
It seems that the binary you uploaded is not the same as the link I posted.
Maybe you need to contact the original author.

**Comment by steve6375** [comment]
no idea who that was! Thanks for helping though.
