### ISSUE TITLE
Literal config data with spaces passed via --config-file fails to run when booted from GRUB 2.02

### ISSUE THREAD

**Issue by crass** [chenall/grub4dos#368]
The documentation suggests that this should work, but the example does not work:

https://github.com/chenall/grub4dos/blob/6bc0594fbb28823487df45f65e487bfaa4dc1305/README_GRUB4DOS.txt#L1337

If I have `--config-file=serial`, then I will be taken to the commandline where I can run `terminal console serial` successfully. However, if I use `--config-file="ls; serial"`, then running at the command line `terminal console serial` fails with `Device not initialized yet` because `serial` was not run yet. However, using `--config-file="ls;serial"`, with no space, allows `terminal console serial` to run successfully. Even using  `--config-file="serial "` (with a trailing space) causes `serial` not to be run.

Is anyone else seeing this?

**Comment by steve6375** [comment]
The grub2 command parsing seems to be fussy (I think is has changed with new compiled versions).

Try separating commands using ;; (assuming recent grub4dos 0.4.6a) and define a variable first, e.g.

```
set g4d_cmd="map (rd) (fd0) ;; map --hook ;; chainloader (fd0)+1 ;; rootnoverify (fd0)";
kernel (hd0,0)/grub.exe --config-file=$g4d_cmd

```

**Comment by crass** [comment]
> The grub2 command parsing seems to be fussy (I think is has changed with new compiled versions).

Can you be more explicit? I know grub2 pretty well, and I don't think the issue is a grub2 parsing issue.

> Try separating commands using ;; (assuming recent grub4dos 0.4.6a) and define a variable first, e.g.
> 
> ```
> set g4d_cmd="map (rd) (fd0) ;; map --hook ;; chainloader (fd0)+1 ;; rootnoverify (fd0)";
> kernel (hd0,0)/grub.exe --config-file=$g4d_cmd
> ```

This doesn't work either. Like I said originally, the issue is with the **spaces**. When I take out the spaces, things work. The problem is, if I want to use any arguments to commands, I can not because of the spaces. I'm wondering if there's an alternate way of encoding spaces. I'm using grub4dos version 0.4.6a-2022-07-19.

Also, I'm noticing now that the docs should be updated. Grub2 has no `kernel` command. It should instead be `linux`. However, that is what I'm doing, so that's not the issue.

**Comment by steve6375** [comment]
what exact lines did you try?
```
set g4d_cmd="ls ;; serial ;; terminal console serial";
linux16 (hd0,0)/grub.exe --config-file=$g4d_cmd
```
![image](https://user-images.githubusercontent.com/1469350/184316948-1f96b111-1944-4873-8f79-9a0e9ebd4d7b.png)

**Comment by crass** [comment]
> what exact lines did you try?

```
              GNU GRUB  version 2.11~git20220812-021440.d3f3f2679

   Minimal BASH-like line editing is supported. For the first word, TAB   
   lists possible command completions. Anywhere else TAB lists possible   
   device or file completions. ESC at any time exits.                     


grub> set g4dconfig="ls ;; serial ;; terminal console serial"
grub> echo linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"
linux (hd0,msdos1)//grub4dos-0.4.6a-2022-07-19/grub.exe --config-file=ls ;;
serial ;; terminal console serial
grub> linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"     
grub> boot
```

![image](https://user-images.githubusercontent.com/740863/184336860-7718d62a-c0eb-455d-8540-88087f4c2478.png)

None of the commands get run in the above. At a minimum output of the `ls` command should be shown. Now if I have a config with no spaces, here's what I get:

```
              GNU GRUB  version 2.11~git20220812-021440.d3f3f2679

   Minimal BASH-like line editing is supported. For the first word, TAB   
   lists possible command completions. Anywhere else TAB lists possible   
   device or file completions. ESC at any time exits.                     


grub> set g4dconfig="ls;serial;terminal"                     
grub> echo linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"
linux (hd0,msdos1)//grub4dos-0.4.6a-2022-07-19/grub.exe --config-file=ls;serial
;terminal
grub>  linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"
grub> boot
```
![image](https://user-images.githubusercontent.com/740863/184337423-19f52f5f-f6c4-471f-bd71-a53cd1d5321b.png)
Here you can see the output of the `ls` and `terminal` commands, so they are running.

**Comment by steve6375** [comment]
```
grub> set g4dconfig="ls ;; serial ;; terminal console serial"
grub> echo linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"
linux (hd0,msdos1)//grub4dos-0.4.6a-2022-07-19/grub.exe --config-file=ls ;;
serial ;; terminal console serial
grub> linux ($g4droot)/${grub4dos} --config-file="$g4dconfig"     
grub> boot
```

You have doublequotes  at --config-file="$g4dconfig"
I do not.
Try removing the doublequotes.
I think doublequotes signifies a config filename

linux ($g4droot)/${grub4dos} --config-file=$g4dconfig

**Comment by crass** [comment]
Wow, ok yes, the problem is with the double quotes. As stated above, when I use double quotes and there are no spaces, then g4d does run the command. So double quotes does not tell g4d to process as a file unconditionally. I think this is a bug in g4d.

This part of the documentation is pretty misleading also:
https://github.com/chenall/grub4dos/blob/6bc0594fbb28823487df45f65e487bfaa4dc1305/README_GRUB4DOS.txt#L62-L68

I see now that I was not reading this part of the documentation carefully. Its talking about GRUB, not GRUB2. A variant of  this example does work in GRUB:
https://github.com/chenall/grub4dos/blob/6bc0594fbb28823487df45f65e487bfaa4dc1305/README_GRUB4DOS.txt#L1335-L1339

Thanks for helping to get this working for me.

**Comment by steve6375** [comment]
grub2 changed its compiler some time ago, AFAIK, gcc 2.x?? and ever since then it has not worked as stated in the old grub4dos docs.
Note the line must be less than 255 characters in grub2 (when variables expanded), so the $g4dconfig string cannot be too long.

**Comment by crass** [comment]
> Note the line must be less than 255 characters in grub2 (when variables expanded), so the $g4dconfig string cannot be too long.

Hmm, this seems like it could be fixed. I've created issue #370 to address this.

**Comment by crass** [comment]
Is this issue fixed? Or is this a "won't fix"?

The documentation patch was to document a quirk in grub4dos, but I think it would be better to just fix the quirk. The issue here is that grub4dos doesn't handle literal configs passed via `--config-file="<config literal>"`. However, `--config-file=<config literal>` works. They should both work as I see it.

**Comment by a1ive** [comment]
I'd prefer not to fix it.
