### ISSUE TITLE
Allow for larger than 255 byte commandline when booting from GRUB2

### ISSUE THREAD

**Issue by crass** [chenall/grub4dos#370]
> Note the line must be less than 255 characters in grub2 (when variables expanded), so the $g4dconfig string cannot be too long.

_Originally posted by @steve6375 in https://github.com/chenall/grub4dos/issues/368#issuecomment-1213375941_

This seems to be because grub.exe is not built with boot protocol >= 2.06 which would allow G4D to specify the command line size. It seems like it should be updated to allow for a command line of size 4096, like mentioned in the docs for when booting from dos.

Here's the relevant section in GRUB2:
https://github.com/crass/grub/blob/e7b8856f8be3292afdb38d2e8c70ad8d62a61e10/grub-core/loader/i386/linux.c#L711-L714

I'd suggest allowing a 4096 byte commandline to be inline with the max size of the commandline when booting using the DEVICE command in CONFIG.SYS, see:
https://github.com/chenall/grub4dos/blob/0.4.6a/README_GRUB4DOS.txt#L2223-L2232

**Comment by a1ive** [comment]
https://github.com/chenall/grub4dos/blob/d38a0550ba8c82dbfb32e7377a76cbf6182a689a/stage2/dosstart.S#L952-L954

**Comment by a1ive** [comment]
@yaya2007 
https://github.com/chenall/grub4dos/blob/d38a0550ba8c82dbfb32e7377a76cbf6182a689a/stage2/dosstart.S#L1031-L1060
这堆东西是干什么用的？

**Comment by yaya2007** [comment]
NTLDR 先将 grldr (或者 grldr_mbr) 加载到 0xd000 处。执行了一些本身的未知代码，然后跳转到 0xd256 处(只验证了一个版本的文件，其他是否也是跳转到此处未知)，把控制权交给 grldr。这些 0x90 空操作代码是用来提前接应 NTLDR 的。

**Comment by a1ive** [comment]
> NTLDR 先将 grldr (或者 grldr_mbr) 加载到 0xd000 处。执行了一些本身的未知代码，然后跳转到 0xd256 处(只验证了一个版本的文件，其他是否也是跳转到此处未知)，把控制权交给 grldr。这些 0x90 空操作代码是用来提前接应 NTLDR 的。

@yaya2007  https://www.kernel.org/doc/html/latest/x86/boot.html
Linux/x86 启动协议 2.06 版记录命令行长度的位置是 0x238，我把这一堆改到从 0x23C 开始应该不会出问题吧？

**Comment by yaya2007** [comment]
应当没有问题

**Comment by a1ive** [comment]
[grub4dos-0.4.6a.zip](https://github.com/chenall/grub4dos/files/9332745/grub4dos-0.4.6a.zip)
Seems OK.
@steve6375 please try this, max size of cmdline is 4096.
![1](https://user-images.githubusercontent.com/10670106/184523949-69707220-0606-4d9d-a71f-ab1ea2d6dec7.png)

**Comment by steve6375** [comment]
longer lines seem OK. I thought you were saying this was a grub2 issue not  a grub4dos issue!

**Comment by a1ive** [comment]
> longer lines seem OK. I thought you were saying this was a grub2 issue not a grub4dos issue!

Could you please test booting grub.exe in DOS (and NTLDR)?

**Comment by steve6375** [comment]
FreeDOS
![image](https://user-images.githubusercontent.com/1469350/184535271-0312c879-4218-40fb-9932-cfaf352d57dc.png)

shorter lines work.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/184535373-980bb82e-45b8-49d8-8e59-c7dd7f69f492.png)
Last line worked

Doc says 128 characters for config-file param, so seems about right.
