### ISSUE TITLE
grub4dos对变量名有什么要求吗？

### ISSUE THREAD

**Issue by daiaji** [chenall/grub4dos#371]
![图片](https://user-images.githubusercontent.com/25875791/186411373-a45e8169-3751-4313-b6d3-abe0a65becaf.png)
uuid打不全
变量名长度有限制吗？
内存限制所以只有8个字符？

**Comment by a1ive** [comment]
https://github.com/chenall/grub4dos/blob/334e3aa0d3e796e67620d3308cfe68b56a10ba8b/README_GRUB4DOS_CN.txt#L3755-L3770

> set [/p] [/a|/A] [/l|/u] [VARIABLE=[STRING]]
 	variable  指定环境变量名（**最长8个字符**）。
 	string    指定要指派给变量的一系列字符串（最长512个字符）。

**Comment by daiaji** [comment]
难顶，历史包袱太重了。

**Comment by steve6375** [comment]
It is for compatibility with older grub4dos.
Behaviour is correct.
Otherwise older grub4dos batch files may fail.

**Comment by daiaji** [comment]
> It is for compatibility with older grub4dos. Behaviour is correct. Otherwise older grub4dos batch files may fail.

But old scripts must never use variable names longer than eight characters (wasn't that a limitation all along?), and I don't think the compatibility makes any sense.

**Comment by steve6375** [comment]
Older grub4dos had same behaviour, you could use 9 character variables without error.
