### ISSUE TITLE
Add hide / unhide commands for grub4dos UEFI

### ISSUE THREAD

**Issue by anwar-alsilwy** [chenall/grub4dos#373]
I need to perform hide / Unhide commands to the partitions.
Those commands are already included in grub4dos Legacy, But they are not included on grub4dos-UEFI.
Please, We need those commands so much,
I hope you add it next release.

**Comment by yaya2007** [comment]
Please give it a try
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/9452789/BOOTX64.rar.txt)

**Comment by anwar-alsilwy** [comment]
Sorry for late reply
Ok, the {hide} command added and working as expected,
But the {unhide} command is still missing.

**Comment by yaya2007** [comment]
"hiddenflag [--set | --clear] [PARTITION]",
  "Hide/unhide PARTITION by setting/clearing the \"hidden\" bit in"
  " its partition type code, or report the hidden status."
  " The default partition is the current root device."

**Comment by anwar-alsilwy** [comment]
I'm sorry for late reply, I'm kind of busy
I will test your both help solutions "hiddenflag [--set | --clear] [PARTITION]", and n "partnew" command ...

**Comment by anwar-alsilwy** [comment]
I tested hiddenflag --set , --clear for all of partition kinds (07, EF, 0C ..etc) on both grub4dos (legacy & uefi) and it's working great 👍
Also, I tried partnew command on both (legacy & uefi),
The values of CHS are identical to the original after restore partition, that's perfect 😃
I hope you add these new changes to the official release.
Thank you so much yaya 🙂
