### ISSUE TITLE
iftitle and errorcheck off problem 0.4.6a

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#38]
Bug in 0.4.6a 2015-02-09 (and previous versions) BUG
0.4.5c is OK

I cannot provide a simple test case for this, but it happens when a menu entry fails to run and grub4dos re-displays the menu.

If have a menu with some iftitles - e.g.

iftitle [if exist /bootmgr] fred
xx
xx

if errorcheck is on and a menu entry fails to run, then 'fred' is re-displayed in menu after the menu entry has failed, but if errorcheck is off (e.g. from calling a batch file before returning to the menu) then does not work and menu is not shown.

iftitle [if exist ()/bootmgr] fred
also gives same problem

However, if I use 
iftitle [if exist (bd)/bootmgr] fred

then it works and menu is listed even with errorcheck off.

This happens when a menu entry has failed to boot and the menu is re-displayed. I am using a menu in memory configfile (md)0xa000+0x50

0.4.5c works OK and if exist /bootmgr works OK.

**Comment by chenall** [comment]
我没有办法重现这个错误,不过猜测你的菜单里面有使用了configfile命令,除非运行configfile命令否则iftitle命令不会重新执行的.

**Comment by steve6375** [comment]
0.4.5c works OK
If I change the \grldr file to 0.4.6a then the same menu does not work - so must be a problem in 0.4.6a.
I will try to simplify the problem and update.

**Comment by steve6375** [comment]
Closed a cannot repro
