### ISSUE TITLE
grub4dos: graphicsmode command changes mode

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#386]
graphicsmode -1 800
graphicsmode
pause
graphicsmode 3
graphicsmode
pause

![image](https://user-images.githubusercontent.com/1469350/200529089-5a27f0ea-ac97-4d01-902e-4e313189b569.png)
![image](https://user-images.githubusercontent.com/1469350/200529148-d06270d5-a610-4c99-993e-156a717c8e1f.png)

The second graphicsmode command changes the mode back to 800x600 and reports the mode as 143

![image](https://user-images.githubusercontent.com/1469350/200529469-34b07751-a09c-468c-ab80-bb0719738155.png)

**Comment by yaya2007** [comment]
have a try
Try to solve 381 problems at the same time
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/9985648/grldr.rar.txt)

**Comment by steve6375** [comment]
looks good for this issue. thanks.
