### ISSUE TITLE
$[xxxx] and scroll bug

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#39]
menu.lst
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
echo $[1064] sdssssssssssssssssssssssssssssssssss ;; echo fred
pause

![image](https://cloud.githubusercontent.com/assets/1469350/6137339/f956a684-b16f-11e4-869a-79e3444a563a.png)

**Comment by chenall** [comment]
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-02-11.7z

**Comment by steve6375** [comment]
fixed! thanks. :+1:
