### ISSUE TITLE
grub4efi: can't list directories and files in UDF ISO 

### ISSUE THREAD

**Issue by memoarfaa** [chenall/grub4dos#405]
@yaya2007  
can you please fix bug with map command  if memory more thane 2GB

https://user-images.githubusercontent.com/12494184/228414403-ae4828db-ffe2-45a0-8544-6b847a5c1f92.mp4

**Comment by yaya2007** [comment]
I don't understand the problem you're reflecting. My memory is 8Gb, working properly.

**Comment by memoarfaa** [comment]
the problem is map command in UEFI Mode  can't list file and directories if memory more than 2GB.
this also tested in real PC
 to reproduce the problem
1- boot to grub4efi
2- map ISO to (0xff) drive
3- use ls command

https://user-images.githubusercontent.com/12494184/228490513-b6ad8769-5a54-4955-b623-eda066b6afbe.mp4

**Comment by steve6375** [comment]
I have IdeaPad 300 notebook with 8GB RAM
I boot from FAT32 USB drive with just bootx64.efi and Ubuntu 18.04.6 desktop ISO file (can have simple menu.lst)
Boot from notebook (real system)
Menu top shows: 2023-03-29, Mem: 160K/1733M/5928M, Free_mem_start: 0x1000
but the map command hangs

Something is very wrong with memory handling, I think.
I also get problems in VBOX 5.
However, if I load grub4efi from a grub2 UEFI64 boot using grub2 chainloader command first - on real system, IdeaPad does map ISO OK and does boot to Ubuntu ISO's grub2 menu.

**Comment by yaya2007** [comment]
I see that the directories and files are already listed. Not all listed？

**Comment by memoarfaa** [comment]
> I see that the directories and files are already listed. Not all listed？

In last video.
The directories and files only listed  if installed memory  equal  2048 MB or 2GB.
When change installed memory to  4096 MB or 4GB directories and files not listed.

**Comment by steve6375** [comment]
I also tried USB boot on my Asus Z87 PC - it maps ISO and boots to ISO grub2 menu OK.
Top of menu shows 2023-03-29, Mem: 320K/2754M/13054M  Free_mem_start: 0x8000

So I get map error and hang on IdeaPad 300 and VBOX5 but works on Asus Z87 PC.
Maybe memory map dependent bug?

**Comment by yaya2007** [comment]
Set memory 3072MB.

est using QEMU virtual machine, normal.

Test using VirtualBox 7 virtual machine, normal.
Without using Virtual Machine USB Boot, in VirtualBox ->Settings ->USB Device, check USB. When starting, press ESC to enter the boot manager and select a USB device.

Please follow the above method to test. If the problem persists。

**Comment by steve6375** [comment]
VBOX 7 as described above gives same issue 3072MB and 4076MB
map fails to work on first attempt and returns back to menu

![map_ubuntuiso1](https://user-images.githubusercontent.com/1469350/228759938-01516a5c-cbf6-4ce5-bac2-259c80046a11.jpg)

on 2nd attempt from menu, map works and lists files inside the ISO on (0xff), but chainloader crashes

If just boot to grub4efi commandline and type in map command manually then  VBOX 7 crashes with a 'VirtualBox - Guru Meditation'  critical error!  Memory is 1775MB or 3072MB

![IMG_20230330_082955640](https://user-images.githubusercontent.com/1469350/228762452-6f0c22b8-ed4a-4835-9d9c-6d0d912ec674.jpg)

**Comment by yaya2007** [comment]
Try this，You should first confirm that the startup was successful at 1024 MB before discussing it.
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/11109269/BOOTX64.rar.txt)

**Comment by steve6375** [comment]
Do you mean set VBOX7 virtual memory to 1024MB?
What do you expect? map command extra debug? screenshot of what?

**Comment by steve6375** [comment]
![IMG_20230330_093040001](https://user-images.githubusercontent.com/1469350/228779431-bba767b5-36db-41ba-b714-308268e53516.jpg)
With new version, map still gives error messages but ls will list files (VBOX 7 1024MB ICH9 USB3 boot
but chainloader command hangs

**Comment by yaya2007** [comment]
The title is>2GB causing a problem. I want to distinguish.
You can test a<2GB and then a>2GB

Some improvements have been made to the crash problem.

**Comment by yaya2007** [comment]
I have seen that the first item number of these two CDROMs is 0, which is abnormal.

**Comment by steve6375** [comment]
I think that only applies to QEMU.
Here is VBOX7 result for 1024MB

![IMG_20230330_093040001](https://user-images.githubusercontent.com/1469350/228780428-e9e6e9e4-037f-4fa5-b172-100af01ad30d.jpg)

 Are you saying that it works for you using VBOX7??? Why can't you test and see same errors?

For me VBOX5+VMUB, VBOX7 and (some) real systems give similar results (map doesn't work - or does semi-work even though error messages and does list files in (0xff) but chainloader hangs).

**Comment by steve6375** [comment]
P.S. If I use QemuBootTester to UEFI boot then 1000MB and 1024MB both boot to Ubuntu grub2 menu  OK
![image](https://user-images.githubusercontent.com/1469350/228789654-7c5fe1ed-ae64-4d2b-853f-88ab86a67e98.png)

**Comment by memoarfaa** [comment]
@yaya2007 
I've been busy the past few days but after the full test
the problem not related to grub4efi map command it's related to grub4efi UDF ISO  like this issue https://github.com/chenall/grub4dos/issues/357

Full test result show on my laptop Asus G75VW 
1- Grub4efi  can't list directories and files if ISO filesystem is  UDF filesystem even though i downgrad my memory to 2GB
2- In qemu and VirtualBox 7 installed in  my laptop Asus G75VW  directories and files only listed if memory < 2GB
3-In Hyper-V installed in my laptop Asus G75VW directories and files listed if memory < 2GB or if memory > 2GB 
4- grub4dos directories and files listed if memory < 2GB or if memory > 2GB 
5- this video show new test result with diffrence ISO filesystems


https://user-images.githubusercontent.com/12494184/230711538-a49ad747-90b3-4e46-ba82-e102bd1ee090.mp4

ISO used in test 



[grub4efi.iso.zip](https://github.com/chenall/grub4dos/files/11183017/grub4efi.iso.zip)

**Comment by yaya2007** [comment]
Thank you for accurately locating the problem.
Please test.
[BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/11185280/BOOTX64.rar.txt)

**Comment by memoarfaa** [comment]
> Thank you for accurately locating the problem. Please test. [BOOTX64.rar.txt](https://github.com/chenall/grub4dos/files/11185280/BOOTX64.rar.txt)

on my laptop Asus G75VW
map UDF ISO from usb Hang

In qemu and VirtualBox 7 installed in my laptop Asus G75VW
Boot from UDF ISO Hang

https://user-images.githubusercontent.com/12494184/230841272-1f9565ce-5725-4e32-9dd9-dc314fe3ed19.mp4

**Comment by yaya2007** [comment]
Please test。issue #404

**Comment by memoarfaa** [comment]
> Please test。issue #404

Works fine thank you friend
