### ISSUE TITLE
Acronis True Image 2021 fails to boot using EFI

### ISSUE THREAD

**Issue by JP95Git** [chenall/grub4dos#407]
Acronis True Image 2021 boots fine in VirtualBox using EFI, so I tested it in Grub4DOS using EFI with this configuration:

```
title Acronis True Image 2021 (Build 39216) efi  
# https://download.acronis.com/AcronisTrueImage2021.iso
set iso=/Acronis-True-Image-2021.iso
find --set-root %iso%
map %iso% (0xff)
chainloader (0xff)
```

Usually you get a graphical menu to select "True Image" or "System Report". In Grub4DOS the menu was displayed in text and followed by an error:
Error 0x1480001: An EFI runtime error.
| line ...
| file: c:/jenkins_agent/....
| function WaitForAnyOfKeys

Searching for the error brings only one result:
https://forum.acronis.com/forum/acronis-true-image-2017-forum/help-needed-error-notfallmedium-erstellt-error-0x1480001-english-created-rescue-media-error-0x1480001
But this solution does not help:
- The ISO works fine in EFI in VirtualBox, so the ISO is fine. The problem seems be in Grub4DOS.
- My keyboard (USB) works fine in Grub4DOS using EFI.
- My keyboard works fine in True Image 2021 using the same ISO, but in BIOS mode.

The issue happens with the beta from issues # 404 and with the release from 2023-03-29.

**Comment by yaya2007** [comment]
Try the G4E of 408 #

**Comment by JP95Git** [comment]
Does not work. I got the error 
Failed to load virtual disk image. (0)

Tested on a exFat and NTFS partition.

**Comment by liuzhaoyzz** [comment]
try map --mem,Acronis True Image can boot and select boot menu,linux/windows method.

# https://download.acronis.com/AcronisTrueImage2021.iso

title Acronis True Image 2021 (Build 39216) efi  
set iso=/Acronis-True-Image-2021.iso
find --set-root %iso%
map **--mem** %iso% (0xff)
chainloader (0xff)

**Comment by liuzhaoyzz** [comment]
Sorry,I test Acronis-True-Image-2021.iso only in grub4dos_BIOS,not g4e.

in g4e2023-5-7,it failed.
title /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso
find --ignore-floppies --ignore-cd --set-root /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso
map --mem --top /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso (0xff)
#map --hook
#map --e820cycles=-1
chainloader (0xff)

![Ubuntu64-2023-05-18-18-39-05](https://github.com/chenall/grub4dos/assets/9776716/53d21d3a-7f4b-4259-9792-251bf6d9e512)

**Comment by liuzhaoyzz** [comment]
grub2UEFI by alive can boot Acronis-True-Image-2021.iso successfully.
menuentry "/linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso" "/linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso" {
search --no-floppy --set --file $2
map -f --mem --type=CD $2
}

![Ubuntu64-2023-05-18-14-00-06](https://github.com/chenall/grub4dos/assets/9776716/efb00fc1-169c-4dbe-85fa-5ce248952a40)
![Ubuntu64-2023-05-18-13-58-27](https://github.com/chenall/grub4dos/assets/9776716/b8d55603-e013-4860-9704-f834253da630)

**Comment by JP95Git** [comment]
Also tested this
https://github.com/chenall/grub4dos/files/11506842/BOOTX642023-05-07.zip
Still the same error, ...WaitForAnyOfKeys....

**Comment by JP95Git** [comment]
Where can I find "grub2UEFI by alive"? Perhaps we can boot this:
UEFI -> GRUB4DOS -> grub2UEFI -> TrueImage

**Comment by steve6375** [comment]
You cannot boot to grub4dos from UEFI - you must boot to grub4efi.
You can boot to alive grubfm from grub4efi
Easiest is to just boot to the multiarch ISO file from grub4efi

```

map /grubfm_multiarch.iso (0xff)
chainloader (0xff)
boot
```

https://github.com/a1ive/grub2-filemanager
https://github.com/a1ive/grub2-filemanager/releases
https://github.com/a1ive/grub2-filemanager/releases/download/v7.4.0/grubfm_multiarch.iso

**Comment by liuzhaoyzz** [comment]
What steve6375 said is really a easier way to learn and use.

grubfilemanager was wrote by Alive，he modified grub2，and participated in the development of  g4e.

http://wuyou.net/forum.php?mod=viewthread&tid=417233&extra=page%3D1
Can you visit Chinese web site？

https://github.com/a1ive/grub/releases/tag/latest

It is very slow when we visit github,for the firewall.

**Comment by JP95Git** [comment]
Please excuse the misunderstandings. My issues are only related to Grub4DOS using EFI, so I wrote only Grub4DOS in some comments, sorry about that.

I was able to boot grubfm_multiarch.iso using Grub4DOS using EFI. It is a very nice menu, like Ventoy, but I got the same error as in Grub4DOS using EFI, namely the WaitForAnyOfKeys-Error. If I understood the above comments correctly, you did not get an error, so maybe I have a bug in the UEFI firmware.

Using the right keywords in Google and some trial and error, I was able to find a working configuration to boot Acronis True Image 2021 with Grub4DOS using EFI:

```
title Acronis True Image 2021 (Build 39216) (efi, working)
# quiet is required or else you will be stuck in console.
# Remove the lang-parameter to use the english language.
# https://download.acronis.com/AcronisTrueImage2021.iso
set iso=/Acronis-True-Image-2021.iso
find --set-root %iso%
map %iso% (0xff)
root (0xff)
kernel /dat10.dat quiet force_modules=usbhid lang=de_DE.UTF-8
initrd /dat11.dat /dat12.dat
```

Does this configuration works for you?

Since Grub4DOS using EFI seems to be very slow on my machine: How long does it take for you to boot the above configuration?

**Comment by liuzhaoyzz** [comment]
Good job!I test OK with your menu:
title /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso
find --ignore-floppies --ignore-cd --set-root /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso
map --mem --top /linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso (0xff)
map --hook
kernel (0xff)/dat10.dat quiet force_modules=usbhid lang=en_US.UTF-8
initrd (0xff)/dat11.dat (0xff)/dat12.dat

**Comment by liuzhaoyzz** [comment]
grub2_BIOS & GRUB2_UEFI can boot,too,with this grub.cfg:
menuentry "/linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso" "/linux1/AcronisTrueImage/AcronisTrueImage2021_39287.iso" {
set gfxpayload=keep
search --no-floppy --set --file $2
loopback loop $2
linux (loop)/dat10.dat quiet force_modules=usbhid lang=en_US.UTF-8
initrd (loop)/dat11.dat (loop)/dat12.dat
}
