### ISSUE TITLE
bootlace.com under DOS is unable to write the bootloader if EBIOS is unavailable

### ISSUE THREAD

**Issue by 1ras** [chenall/grub4dos#421]
bootlace.com cannot write the bootloader under DOS if EBIOS is unavailable. It says success but noting is actually written. This is due to https://github.com/chenall/grub4dos/blob/4fe13e664b9c5b2ac20e48d0577e6c1f43fd91b1/stage2/bootlace.inc#L5070

I am wondering if this is a typo and should be `cmpl` instead?
At least it works with this change.

**Comment by yaya2007** [comment]
[bootlace.com cannot write the bootloader under DOS if EBIOS is unavailable. It says success but noting is actually written. This is due to](url)
yes

[I am wondering if this is a typo and should be cmpl instead?
At least it works with this change.](url)
It's an error, next update.

**Comment by 1ras** [comment]
I can confirm that issue is resolved.
Thanks for providing grub4dos!
