### ISSUE TITLE
http://dl.grub4dos.chenall.net/grub4dos-for_UEFI-2023-10-14.7z  - Document not found??

### ISSUE THREAD

**Issue by msetzerii** [chenall/grub4dos#429]
getting Document not found when clicking to download new file.
The regular grub4dos version does download.

**Comment by msetzerii** [comment]
Link to 10-14 still not found, but was able to get newer.
http://dl.grub4dos.chenall.net/grub4dos-for_UEFI-2023-10-16.7z
But not seeing on main page yet?

**Comment by msetzerii** [comment]
Page is updated to show 10-16, but the links are still pointing to 10-14 file that isn't there?
Perhaps it is in process of being corrected??
[grub4dos-for_UEFI-2023-10-14.7z](http://grub4dos.chenall.net/downloads/grub4dos-for_UEFI-2023-10-14/)
发表于 [2023-10-16](http://grub4dos.chenall.net/downloads/grub4dos-for_UEFI-2023-10-14/)

**Comment by msetzerii** [comment]
Error on Page. Top entry shows 10-14, but link to that is bad.
Next link on page is 10-16 and that one is correct? Not sure why it shows as older option??
http://grub4dos.chenall.net/

**Comment by yaya2007** [comment]
I don't know why, but after the official website was compiled and released, there was chaos. Fortunately, there are two download addresses.
