### ISSUE TITLE
map command fails on Endian ISO (0.4.6a only)

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#43]
http://www.endian.com/us/community/download/efw/
EFW-COMMUNITY-3.0.0-devel-201401151045.iso
map command works and can boot to linux shell under 0.4.5c but not 0.4.6a

![image](https://cloud.githubusercontent.com/assets/1469350/6325560/d20fe9d4-bb40-11e4-8138-c90fe905ba3c.png)
![image](https://cloud.githubusercontent.com/assets/1469350/6325583/f492a0a0-bb40-11e4-80df-87543e57db95.png)
![image](https://cloud.githubusercontent.com/assets/1469350/6325609/4a66b4e4-bb41-11e4-8227-d3bffdf19fd1.png)

**Comment by yaya2007** [comment]
EFW-COMMUNITY-3.0.0-devel-201401151045.iso 放在什么类型的分区？ 
ext2?ntfs?iso9660?

**Comment by steve6375** [comment]
NTFS OK, exFAT OK, #FAT32 Error#. Have not tested ext2

**Comment by steve6375** [comment]
I made a copy of the file (from same drive - to same drive). The copy is OK but not the original file.
![image](https://cloud.githubusercontent.com/assets/1469350/6345722/abaafae8-bc00-11e4-8f02-0788e69b8ecb.png)
Under 0.4.5c, the original file is OK
![image](https://cloud.githubusercontent.com/assets/1469350/6345752/eecefb44-bc00-11e4-9ad8-2cdabf0822ef.png)

**Comment by yaya2007** [comment]
我这里测试 FAT32 没有问题。
对于 FAT32 文件系统，只有当 ‘下一簇号 < 2 或者下一簇号 >= 卷内的总簇数’，才会返回错误信息：Inconsistent filesystem structure

要定位问题，需提供：
PBR，根目录（含EFW-COMMUNITY-3.0.0-devel-201401151045.iso），FAT表

**Comment by yaya2007** [comment]
或许 FAT32 有 bug。若可以提供出错的简化副本，那最好。
复制后的 EFW-COMMUNITY-3.0.0-devel-201401151045.iso 有可能 FAT表正确了。

**Comment by yaya2007** [comment]
“根目录（含EFW-COMMUNITY-3.0.0-devel-201401151045.iso）”
这句应当修正为：含 EFW-COMMUNITY-3.0.0-devel-201401151045.iso 文件的目录。为了取得这个文件的起始簇号。

**Comment by steve6375** [comment]
SORRY! Drive is NTFS not FAT32!!

Sector at LBA 0

============= SECTOR DATA ================
[Sector 0]  0MB
0000 33 C0 EB 5C 90 00 20 39 - FF FF 00 00 00 00 00 00  3Àë\. 9 ÿÿ......
0010 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0020 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0030 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0040 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0050 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0060 FA 31 DB 8E D3 BC 80 05 - E8 00 00 5B 81 EB 6B 00  ú1ÛŽÓ¼€. è..[ëk.
0070 C1 EB 04 8C C8 01 C3 8E - DB 53 6A 7D CB 68 00 20  Áë.ŒÈ.ÃŽ ÛSj}Ëh. 
0080 17 BC 00 90 FB 16 07 B9 - 12 00 B8 01 02 89 CB 4B  ¼.û.¹ .¸..‰ËK
0090 C1 E3 09 BA 80 00 51 53 - E8 A4 00 5B 59 72 04 E2  Áã.º€.QS è¤.[Yr.â
00A0 E9 F6 DC 0E 1F 9C 31 F6 - 31 FF B9 DF 00 FC F3 A5  éöÜœ1ö 1ÿ¹ß.üó¥
00B0 BB FC 1F 66 B8 05 4D CB - 93 66 39 07 75 03 E8 39  »üf¸.MË “f9.u.è9
00C0 1C EA C6 00 00 20 16 1F - 66 39 07 74 28 66 60 BF  êÆ..  f9.t(f`¿
00D0 03 00 B8 11 02 99 BB 00 - 02 B9 02 00 E8 80 00 73  ..¸.™». .¹..è€.s
00E0 02 75 EF 66 61 66 39 07 - 75 4D C7 06 08 00 00 FF  .uïfaf9. uMÇ....ÿ
00F0 80 26 04 00 FE 9D 72 33 - 0E 1F AD 88 E6 AD 89 C1  €&..þr3 ­ˆæ­‰Á
0100 24 3F 74 14 B0 01 BF 03 - 00 B4 02 68 00 0D 07 31  $?t°.¿. .´.h...1
0110 DB E8 4B 00 73 03 75 F1 - F9 E8 5C 11 0F 87 F3 1B  ÛèK.s.uñ ùè\‡ó
0120 83 C6 0C 81 FE FE 01 72 - CF 77 0C BE B2 31 B0 04  ƒÆ.þþ.r Ïw.¾²1°.
0130 B9 01 00 31 D2 EB CF BE - 91 01 E8 4D 00 EB FE 1E  ¹..1ÒëÏ¾ ‘.èM.ëþ
0140 06 52 56 57 55 F9 CD 13 - 5D 5F 5E 5A 07 1F C3 FA  .RVWUùÍ ]_^Z.Ãú
0150 B8 00 20 8E D0 BC DC 8F - FB 66 61 07 1F EB C1 60  ¸. ŽÐ¼Ü ûfa.ëÁ`
0160 50 53 51 FE C8 00 C1 D0 - E0 00 C7 B0 01 E8 CF FF  PSQþÈ.ÁÐ à.Ç°.èÏÿ
0170 59 5B 58 72 04 FE C8 75 - E7 61 73 09 60 31 C0 E8  Y[Xr.þÈu ças.`1Àè
0180 BD FF 61 4F F9 C3 B4 0E - CD 10 2E AC 3C 00 75 F6  ½ÿaOùÃ´ Í.¬<.uö
0190 C3 0D 0A 4D 69 73 73 69 - 6E 67 20 4D 42 52 2D 68  Ã..Missi ng MBR-h
01A0 65 6C 70 65 72 2E 00 00 - 00 00 00 00 00 00 00 00  elper... ........
01B0 00 00 00 00 00 00 00 00 - FA 01 45 E0 00 00 80 20  ........ ú.Eà..€ 
01C0 21 00 07 FE FF FF 00 08 - 00 00 68 D5 73 07 00 FE  !..þÿÿ.. ..hÕs..þ
01D0 FF FF 21 FE FF FF 68 DD - 73 07 3F 00 00 00 00 00  ÿÿ!þÿÿhÝ s.?.....
01E0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
01F0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 55 AA  ........ ......Uª


Disk Signature bytes (1B8h-1BBh) = FA 01 45 E0

Partition 1   SIZE=61050.676MiB   Type: 07 NTFS  *ACTIVE*
START POS   = CYL:0 HD:32 SEC:33       END POS = CYL:1023 HD:254 SEC:63
START (LBA) = 2,048 (00000800) SIZE (LBA) = 125,031,784 (0773D568) [End=125,033,831]

Partition 2   SIZE=0.031MiB   Type: 21 Hidden(rsvd)       
START POS   = CYL:1023 HD:254 SEC:63       END POS = CYL:1023 HD:254 SEC:63
START (LBA) = 125,033,832 (0773DD68) SIZE (LBA) = 63 (0000003F) [End=125,033,894]

Partition 3   SIZE=0MiB   Type: 00        
START POS   = CYL:0 HD:0 SEC:0       END POS = CYL:0 HD:0 SEC:0
START (LBA) = 0 (00000000) SIZE (LBA) = 0 (00000000)

Partition 4   SIZE=0MiB   Type: 00        
START POS   = CYL:0 HD:0 SEC:0       END POS = CYL:0 HD:0 SEC:0
START (LBA) = 0 (00000000) SIZE (LBA) = 0 (00000000)

P1   Start=2,048 (1,048,576 bytes) End=125,033,831 (64,017,321,472 bytes)
P2   Start=125,033,832 (64,017,321,984 bytes) End=125,033,894 (64,017,353,728 bytes)

Drive 2  SanDisk Extreme  F/W Rev.=0001  Serial No.= [ bytes = 00 00 00 00 00 00 00 00 ]
Reported size 64,023,257,088 bytes (59.6263GiB)  Last LBA 125,045,423
RMPrepUSB Max 64,017,354,240 bytes (59.6208GiB)  Last LBA 125,033,894



[Sector 2048]  1MB
0000 EB 52 90 4E 54 46 53 20 - 20 20 20 00 02 08 00 00  ëRNTFS     .....
0010 00 00 00 00 00 F8 00 00 - 3F 00 FF 00 00 08 00 00  .....ø.. ?.ÿ.....
0020 00 00 00 00 80 00 00 00 - 67 D5 73 07 00 00 00 00  ....€... gÕs.....
0030 00 00 0C 00 00 00 00 00 - 02 00 00 00 00 00 00 00  ........ ........
0040 F6 00 00 00 01 00 00 00 - 22 18 FD 6C 32 FD 6C 8C  ö....... "ýl2ýlŒ
0050 00 00 00 00 FA FC B6 00 - 31 C0 BD 00 7C 8E D0 8D  ....úü¶. 1À½.|ŽÐ
0060 66 E0 FB 89 56 FE 50 B4 - 41 BB AA 55 CD 13 1F 72  fàû‰VþP´ A»ªUÍr
0070 10 81 FB 55 AA 75 0A F6 - C1 01 74 05 C6 86 AA 01  ûUªu.ö Á.t.Æ†ª.
0080 42 16 07 66 81 BE FC 07 - 47 52 55 42 74 13 BB 00  B.f¾ü. GRUBt».
0090 7E 66 8B 86 1C 00 66 40 - E8 E1 00 E8 DE 00 E8 DB  ~f‹†.f@ èá.èÞ.èÛ
00A0 00 66 31 C0 8B 46 0B 89 - 46 FC E8 8C 00 88 CB 8A  .f1À‹F.‰ FüèŒ.ˆËŠ
00B0 46 0D E8 84 00 88 CD 00 - DD 80 ED 09 88 6E FB 8A  F.è„.ˆÍ. Ý€í.ˆnûŠ
00C0 46 44 E8 65 00 80 F9 03 - 76 05 B0 01 E9 FB 00 88  FDèe.€ù. v.°.éû.ˆ
00D0 4E F9 8A 46 40 E8 52 00 - 80 F9 01 75 ED 88 4E FA  NùŠF@èR. €ù.uíˆNú
00E0 66 8B 46 30 88 E9 66 D3 - E0 66 03 86 1C 00 66 89  f‹F0ˆéfÓ àf.†.f‰
00F0 46 F4 BA 01 00 8A 4E FA - D3 E2 89 D1 BB 00 20 53  Fôº..ŠNú Óâ‰Ñ». S
0100 E8 79 00 E2 FB 5B 81 3F - 46 49 75 6C 89 D1 E8 34  èy.âû[? FIul‰Ñè4
0110 00 89 DF B0 80 E8 40 02 - 72 5E BB 00 38 66 31 C0  .‰ß°€è@. r^».8f1À
0120 B0 05 E8 8A 03 89 DF E9 - D6 00 08 C0 78 04 88 E9  °.èŠ.‰ßé Ö..Àx.ˆé
0130 EB 09 F6 D8 2C 09 88 C1 - C3 30 C9 FE C1 66 D1 E8  ë.öØ,.ˆÁ Ã0ÉþÁfÑè
0140 73 F9 FE C9 C3 53 57 89 - DF 8B 47 06 48 89 C3 F7  sùþÉÃSW‰ ß‹G.H‰Ã÷
0150 66 FC C1 E1 09 39 C1 75 - 1F 89 D9 89 FB 03 5F 04  füÁá.9Áu ‰Ù‰û._.
0160 8B 07 83 EF 02 03 7E FC - 83 C3 02 3B 05 75 09 8B  ‹.ƒï..~ü ƒÃ.;.u.‹
0170 17 89 15 E2 F0 5F 5B C3 - B0 02 EB 4E 66 60 66 31  ‰âð_[Ã °.ëNf`f1
0180 D2 66 52 66 50 06 53 6A - 01 6A 10 66 31 C9 66 FF  ÒfRfP.Sj .jf1Éfÿ
0190 76 18 59 66 F7 F1 42 59 - 52 31 D2 66 F7 F1 86 D6  vYf÷ñBY R1Òf÷ñ†Ö
01A0 59 86 C5 C0 E4 06 08 E1 - B8 01 02 89 E6 8A 56 FE  Y†ÅÀä..á ¸..‰æŠVþ
01B0 CD 13 61 66 61 72 37 66 - 40 03 5E 0B 73 09 52 8C  Íafar7f @.^.s.RŒ
01C0 C2 80 C6 10 8E C2 5A C3 - 30 00 00 86 C8 01 EB 1E  Â€ÆŽÂZÃ 0..†È.ë
01D0 4E 6F 20 67 72 6C 64 72 - 00 00 00 00 00 00 00 00  No grldr ........
01E0 00 00 00 00 00 00 00 00 - 00 00 00 20 D3 A1 BE C8  ........ ... Ó¡¾È
01F0 7D AC B4 0E CD 10 3C 00 - 75 F7 EB FE 00 00 55 AA  }¬´Í<. u÷ëþ..Uª

NTFS
000B Bytes Per Sector = 512 (0200h)
000D Sectors Per Cluster = 8 (08h)
0015 Media Descriptor = 248 (F8h) HDD
0020 Total Log. Sectors (big) = 0 (00000000h)
0028 Total Sectors on HDD = 000000000773D567h
0030 Log. Cluster no. for $MFT file = 00000000000C0000h
0038 Log. Cluster no. for $MFTMirr file = 0000000000000002h
0040 Clusters per MFT Record = 246 (F6h)
0044 Clusters per Index Buffer = 34 (22h)
0048 Volume ID Serial No. = 8C6CFD326CFD1822h

[Sector 6293506]  3073MB
0000 46 49 4C 45 30 00 03 00 - CC 11 00 02 00 00 00 00  FILE0... Ì......
0010 01 00 01 00 38 00 01 00 - 58 01 00 00 00 04 00 00  ....8... X.......
0020 00 00 00 00 00 00 00 00 - 04 00 00 00 01 00 00 00  ........ ........
0030 07 00 00 00 00 00 00 00 - 10 00 00 00 60 00 00 00  ........ ...`...
0040 00 00 18 00 00 00 00 00 - 48 00 00 00 18 00 00 00  ....... H......
0050 41 1C AB FB BD 37 D0 01 - 41 1C AB FB BD 37 D0 01  A«û½7Ð. A«û½7Ð.
0060 41 1C AB FB BD 37 D0 01 - 41 1C AB FB BD 37 D0 01  A«û½7Ð. A«û½7Ð.
0070 06 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0080 00 00 00 00 00 01 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0090 00 00 00 00 00 00 00 00 - 30 00 00 00 70 00 00 00  ........ 0...p...
00A0 00 00 18 00 00 00 02 00 - 52 00 00 00 18 00 01 00  ....... R......
00B0 05 00 00 00 00 00 05 00 - 41 1C AB FB BD 37 D0 01  ........ A«û½7Ð.
00C0 41 1C AB FB BD 37 D0 01 - 41 1C AB FB BD 37 D0 01  A«û½7Ð. A«û½7Ð.
00D0 41 1C AB FB BD 37 D0 01 - 00 10 00 00 00 00 00 00  A«û½7Ð. .......
00E0 00 10 00 00 00 00 00 00 - 06 00 00 00 00 00 00 00  ....... ........
00F0 08 03 24 00 4D 00 46 00 - 54 00 4D 00 69 00 72 00  ..$.M.F. T.M.i.r.
0100 72 00 00 00 00 00 00 00 - 80 00 00 00 48 00 00 00  r....... €...H...
0110 01 00 40 00 00 00 01 00 - 00 00 00 00 00 00 00 00  ..@..... ........
0120 00 00 00 00 00 00 00 00 - 40 00 00 00 00 00 00 00  ........ @.......
0130 00 10 00 00 00 00 00 00 - 00 10 00 00 00 00 00 00  ....... .......
0140 00 10 00 00 00 00 00 00 - 11 01 02 00 00 00 00 00  ....... .......
0150 FF FF FF FF 00 00 00 00 - 20 00 00 00 20 02 00 00  ÿÿÿÿ....  ... ...
0160 01 02 00 00 00 00 00 05 - 20 00 00 00 20 02 00 00  ........  ... ...
0170 80 00 00 00 48 00 00 00 - 01 00 40 00 00 00 01 00  €...H... ..@.....
0180 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
0190 40 00 00 00 00 00 00 00 - 00 10 00 00 00 00 00 00  @....... .......
01A0 00 10 00 00 00 00 00 00 - 00 10 00 00 00 00 00 00  ....... .......
01B0 11 01 02 00 00 00 00 00 - FF FF FF FF 00 00 00 00  ....... ÿÿÿÿ....
01C0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
01D0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
01E0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 00 00  ........ ........
01F0 00 00 00 00 00 00 00 00 - 00 00 00 00 00 00 07 00  ........ ........

What other sectors do you need?

**Comment by steve6375** [comment]
2014-02-17 0.4.6a works. Will test later versions...

**Comment by yaya2007** [comment]
NTFS 比较复杂。试一试 debug = 0x7FFFFFFF，他会提供较多信息。

**Comment by steve6375** [comment]
2014-11-29 FAIL
2104-11-26 FAIL
2014-12-27 FAIL
2015-01-22 FAIL
2015-01-18 FAIL
2015-01-09 FAIL

With debug 0x7fffffff , blocklist command says
![image](https://cloud.githubusercontent.com/assets/1469350/6347081/f5abf60e-bc0c-11e4-8d13-e4bcf2d57380.png)

**Comment by yaya2007** [comment]
debug 0x7fffffff
map /EFW-COMMUNITY-3.0.0-devel-201401151045.iso (0xff)
看看返回什么。

**Comment by steve6375** [comment]
2013-12-31 WORKS
2013-11-3- WORKS
2014-01-17  WORKS
2014-06-24 FAILS
2014-08-17 FAILS

0.4.6a 2015-02-15 for blocklist and map...
![image](https://cloud.githubusercontent.com/assets/1469350/6347346/2df44b22-bc0f-11e4-91f8-0959cbea9bf8.png)

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/6347435/07b2d072-bc10-11e4-9ee1-4b80b5b65d74.png)
2014-02-17 output

**Comment by yaya2007** [comment]
这之间有3处更改：
0e9f46227fab6f3103f44b4c05c7e653bd62361a
fix FAT32 file name/directory name upper/lower case issue issue 167

4ab9c3c131ed5cb7de5ba0d8421e62613132ea7e
fix build issue

5792b3810472031a6824013332ce1b213accb06c
using for build temp dir default is SET to '/tmp/grub4dos-temp'

更改似乎与 NTFS 无关。是不是 gcc 编译的问题？

**Comment by steve6375** [comment]
I used your download for all tests (grldr file).
Did you see difference in LBA address from 2014-01-17 version (6295836 v. 6295838).
Difference of 2

**Comment by steve6375** [comment]
0.4.5c for same drive
![image](https://cloud.githubusercontent.com/assets/1469350/6348286/2c5a7226-bc16-11e4-9b9e-726471b30a95.png)

**Comment by steve6375** [comment]
Compare 'bad' iso with copy on same drive (good iso)
![image](https://cloud.githubusercontent.com/assets/1469350/6348427/6ee0a222-bc17-11e4-9ef1-327e671f1e91.png)

0.4.6a 2015-02-15
![image](https://cloud.githubusercontent.com/assets/1469350/6348451/b4cf8ca8-bc17-11e4-9b11-c4294ebc7710.png)

**Comment by yaya2007** [comment]
<6295838,0,1024>是读磁盘<扇区，偏移，长度>
此时读磁盘越界。
越界的条件是：如果(偏移+长度) > 属性流长度
在常驻属性。

**Comment by yaya2007** [comment]
可否把 0-62a0000扇区复制成文件上传？

**Comment by steve6375** [comment]
http://1drv.ms/1ER5nEw

This should show the problem. I filled all other files with 0's and then deleted them to make the image small.

**Comment by yaya2007** [comment]
已经修正。请测试。

**Comment by steve6375** [comment]
Where? Cannot find a new version?

**Comment by yaya2007** [comment]
不知为什么，官网现在才更新。

**Comment by steve6375** [comment]
Seems to Work :-)  Thanks
Will close in a day or so after testing more.
