### ISSUE TITLE
Links to new releases giving Document not found??

### ISSUE THREAD

**Issue by msetzerii** [chenall/grub4dos#435]
Found different links that seem to work:
https://github.com/chenall/grub4dos/releases/tag/for_UEFI
https://github.com/chenall/grub4dos/releases/tag/0.4.6a

Following http://grub4dos.chenall.net/
Takes one to 
http://dl.grub4dos.chenall.net/grub4dos-0.4.6a-2024-02-26.7z that gives document not found.

**Comment by chenall** [comment]
Sorry, there might be some problem with the file upload, I'll try to fix it.
You can download it directly from github
https://github.com/chenall/grub4dos/releases

**Comment by yaya2007** [comment]
`Sorry, there might be some problem with the file upload, I'll try to fix it.
You can download it directly from github `
帮忙处理下#429,433，能不能删除前面的无效链接项目？7

**Comment by yaya2007** [comment]
chenall
非常好！

**Comment by chenall** [comment]
已处理
