### ISSUE TITLE
UEFI ,BCD菜单下能挂载grub4dos吗？我想让BCD做为主菜单

### ISSUE THREAD

**Issue by goldsoft8888** [chenall/grub4dos#439]
UEFI ,BCD菜单下能挂载grub4dos吗？
我想让BCD做为主菜单

**Comment by a1ive** [comment]
不能。

**Comment by goldsoft8888** [comment]
那有什么办法BCD菜单下执行命令或shell？ 我想做个一键还原

**Comment by a1ive** [comment]
这与本项目无关，请查阅微软相关文档。

**Comment by steve6375** [comment]
You can add grub and then run clonezilla for one key press restore
https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/
AFAIK  UEFI BCD will only boot Microsoft EFI files.

**Comment by goldsoft8888** [comment]
MBR,  bcd菜单可以挂载grub4dos,  如果GPT也能挂，就好了。可以做VHD启动的一键还原，找这个的人挺多啊，建议作者开发一个。就是EFI的应用软件。如果有同类软件，给推荐一个也行。

**Comment by goldsoft8888** [comment]
> 您可以添加 grub，然后运行 clonezilla 一键还原 https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/ AFAIK UEFI BCD 将仅启动Microsoft EFI 文件。

不方便，想用BCD做主菜单，

**Comment by steve6375** [comment]
> > 您可以添加 grub，然后运行 clonezilla 一键还原 https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/ AFAIK UEFI BCD 将仅启动Microsoft EFI 文件。
> 
> 不方便，想用BCD做主菜单，

If you want to use BCD, why not just boot to a winpe installation on a separate partition and automatically run a restore program.

**Comment by goldsoft8888** [comment]
> > > 您可以添加 grub，然后运行 clonezilla 一键还原 https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/ AFAIK UEFI BCD 将仅启动Microsoft EFI 文件。
> > 
> > 
> > 不方便，想用BCD做主菜单，
> 
> 如果要使用 BCD，为什么不直接启动到单独分区上的 winpe 安装并自动运行还原程序。

BCD已经挂载了PE，但是操作麻烦，想一键还原，

**Comment by goldsoft8888** [comment]
> > > > 您可以添加 grub，然后运行 clonezilla 一键还原 https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/ AFAIK UEFI BCD 将仅启动Microsoft EFI 文件。
> > > 
> > > 
> > > 不方便，想用BCD做主菜单，
> > 
> > 
> > 如果要使用 BCD，为什么不直接启动到单独分区上的 winpe 安装并自动运行还原程序。
> 
> BCD已经挂载了PE，但是操作麻烦，想一键还原， GRUB4DOS增加了操作的复杂性，不如像老版本一样，用实模式挂载到BCD简单方便

**Comment by a1ive** [comment]
> > > > > 您可以添加 grub，然后运行 clonezilla 一键还原 https://rmprepusb.com/tutorials/142-automated-uefi-windows-restore-using-clonezilla/ AFAIK UEFI BCD 将仅启动Microsoft EFI 文件。
> > > > 
> > > > 
> > > > 不方便，想用BCD做主菜单，
> > > 
> > > 
> > > 如果要使用 BCD，为什么不直接启动到单独分区上的 winpe 安装并自动运行还原程序。
> > 
> > 
> > BCD已经挂载了PE，但是操作麻烦，想一键还原， GRUB4DOS增加了操作的复杂性，不如像老版本一样，用实模式挂载到BCD简单方便

这是微软的问题。
> 可以做VHD启动的一键还原，找这个的人挺多啊，建议作者开发一个。就是EFI的应用软件。

建议不要乱提建议。
bootmgfw.efi 根本就不能启动 EFI 可执行程序。微软也没有公开它自己的 Boot Application 相关文档。
