### ISSUE TITLE
Request:  set -n /p 

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#48]
set /p:3 ask=enter input > nul
always throws a carriage return. If you just remove the carriage return it might break existing code.
Can you add a -n or /n switch to suppress the carriage return please?

also if no text then  **set /p ask=**  reports an error. Is it possible to use set /p without any prompt text?

e.g. get input within 3 seconds
echo -n $[0005]Please enter input : 
set -n /p:3 ask=

e.g. get password but don't show typed characters
color standard 3
echo -n Password : 
color standard 0
set -n /p:3 ask=text > nul
color standard 3

**Comment by chenall** [comment]
The carriage return is write by get_cmdline,not in set_func,
currently has no good way, you can try to use batch script.
e.g.

```bat
!BAT
call :get_pass pass Password:
echo Pass: %pass%
goto :eof

:get_pass
setlocal
set baseaddr=0x60000
set offset=%baseaddr%
echo -n %2
call :getchar %1
echo
write %offset% 0 > nul
endlocal && call Fn.0 0 %baseaddr% | set %1=
goto :eof

:getchar
call Fn.19
set /A key=%@retval% > nul
if %key%==0x1C0D goto :eof
if %key%==0x11B goto :Esc
::Support backspace
if %key%==0xE08 goto :Back
write --bytes=1 %offset% %key% > nul
set /A offset=%offset%+1 > nul
goto %0
:Back
set /A offset=%offset%-1 > nul
goto %0
:Esc
set offset=%baseaddr%
goto :eof
```

**Comment by steve6375** [comment]
I don't understand? Why does this work then?
![image](https://cloud.githubusercontent.com/assets/1469350/6651091/a6e2a784-ca2b-11e4-8b8d-122ecee4d7a9.png)

**Comment by chenall** [comment]
`echo -n fred`-n does not automatically add a carriage return
so 
echo -n fred && echo -n fred 
output fredfred
but set /p call func get_cmdline,This function will reset the cursor position..

**Comment by steve6375** [comment]
!BAT
:: get password and print * for each character
:: returns password in %pass%

:: Usage: getpass.g4b [prompt]
:: e.g.  getpass.g4b $[0104]Please\x20enter\x20password:\x20

call Fn.70 1 && set CUR=%@retval%
if "%1"=="" call :get_pass pass Password:\x20 || call :get_pass pass %1
call Fn.70 %CUR% && set CUR=
echo Pass: [%pass%]
goto :eof

:get_pass
setlocal
set baseaddr=0x60000
set offset=%baseaddr%
echo -e -n %2
call :getchar %1
echo
write %offset% 0 > nul
endlocal && call Fn.0 0 %baseaddr% | set %1=
goto :eof

:getchar
call Fn.19
set /A key=%@retval% > nul
if %key%==0x1C0D goto :eof
if %key%==0x11B goto :Esc
::Support backspace
if %key%==0xE08 goto :Back
write --bytes=1 %offset% %key% > nul
set /A offset=%offset%+1 > nul
echo -n *
goto %0

:Back
if %baseaddr%==%offset% goto %0
set /A offset=%offset%-1 > nul
call Fn.4 ;; set /A r=%@retval% > nul
set /a x=%r%>>8 > nul
set /a y=%r%&0xff > nul
#echo %x% %y%
if not %y%<=0 set /a y=%y%-1  > nul
#echo %x% %y%
call Fn.5 %y% %x%
echo -n -e \x20
call Fn.5 %y% %x%
goto %0

:Esc
set offset=%baseaddr%
goto :eof


-----------------

Thanks for the code, I tweaked it a bit and added check for Back.  :-) Now prints * for characters entered with cursor
![image](https://cloud.githubusercontent.com/assets/1469350/6651271/be3c4fb4-ca32-11e4-8126-4c309c65b96b.png)

**Comment by steve6375** [comment]
What I really want is to have a 3 seconds timeout using set /p:10 pass=xxxxx
and have coloured prompt on *same* line
e.g.
echo -n $[0005]Please enter input : 
set /p:3 ask=

**Comment by chenall** [comment]
>call Fn.70 1 && set CUR=%@retval%

Should be
```
call Fn.70 1 ;; set CUR=%@retval%
```

>1.What I really want is to have a 3 seconds timeout using set /p:3 pass=xxxxx

use api e.g
```bat
!BAT
setlocal
set color4=0x000000;0x0000AA;0x00AA00;0x00AAAA;0xAA0000;0xAA00AA;0xAA5500;0xAAAAAA;0x555555;0x5555FF;0x55FF55;0x55FFFF;0xFF5555;0xFF55FF;0xFFFF55;0xFFFFFF;
set /a tmp=42<<2+*0x8304&0xffffffff > nul
set /A color32=%tmp% > nul
set /A color64=%tmp%+4 > nul
call :set_color 5
set /p ask=Please enter input : 
echo -n
goto :eof
:color4_32
set /A %2=%color4:~%1,8% > nul
goto :eof

:color_8_64
setlocal
set /a b=%1>>4*9 > nul
set /a f=%1&0xf*9 > nul
call :color4_32 %b% b
call :color4_32 %f% f
endlocal && set /A %2=%b%<<32|%f% > nul
goto :eof

:set_color
setlocal
call :color_8_64 %1 c64
write %color32% %1 > nul
write --bytes=8 %color64% %c64% > nul
goto :eof
```

>How can I have no prompt text in set /p (this gives error)

This may be BUG,

**Comment by steve6375** [comment]
Thanks, I tweaked it slightly :-)

...
!BAT
:: Get a string from user after prompting in coloured text
:: Syntax: ColPrompt <colour> <"prompt"> [timeout in secs]
:: Returns: %ask% = user input string
::
:: Usage: ColPrompt.g4b 5  "Please\x20Input\x20Password\x20:\x20" 3
:: Usage: ColPrompt.g4b 14 "Please Input Password : "
:: Usage: ColPrompt.g4b 1 
:: Colors = 0=black, 1=blue, 2=green, 3=l cyan, 4=red, 5=magenta, 6=l brown, 7=grey, 8=d grey, 9=l blue, 10=l green, 11=cyan, 12=l red, 13=l magenta  ,14=yellow  ,15=white

setlocal
set ask=
set TIME=
set COL=%1
if not exist COL set COL=7
set T=%2
if not exist T set T="Password:\x20"
call Fn.0 0 %T% > (md)0x301+1
echo -e -n !BAT\nset T= > (md)0x300+1 ;; cat (md)0x301+1 >> (md)0x300+1
call (md)0x300+1
if not "%3"=="" set TIME=:%3
:: set up equivalent 64-bit values for colors 0-F
set color4=0x000000;0x0000AA;0x00AA00;0x00AAAA;0xAA0000;0xAA00AA;0xAA5500;0xAAAAAA;0x555555;0x5555FF;0x55FF55;0x55FFFF;0xFF5555;0xFF55FF;0xFFFF55;0xFFFFFF;
set /a tmp=42<<2+*0x8304&0xffffffff > nul
set /A color32=%tmp% > nul
set /A color64=%tmp%+4 > nul
:: color32 is the location to write 32-bit color value - e.g. 0x0d
:: color64 is the location to write 64-bit color value - e.g. 0xFF55FF
call :set_color %COL%
set /p%TIME% ask=%T%
::restore colors with echo -n
echo -n

endlocal && set ask=%ask%
goto :eof

:color4_32
set /A %2=%color4:~%1,8% > nul
goto :eof

:color_8_64
setlocal
set /a b=%1>>4*9 > nul
set /a f=%1&0xf*9 > nul
call :color4_32 %b% b
call :color4_32 %f% f
endlocal && set /A %2=%b%<<32|%f% > nul
goto :eof

:set_color
setlocal
call :color_8_64 %1 c64
write %color32% %1 > nul
write --bytes=8 %color64% %c64% > nul
goto :eof
...

**Comment by steve6375** [comment]
Fix for 
**set /p ask=**
please?

**Comment by steve6375** [comment]
Thanks :-)
