### ISSUE TITLE
VIA PCI USB 2.0 controller not detected

### ISSUE THREAD

**Issue by Nin-ho** [chenall/grub4dos#49]
= Using a PCI add-on VIA USB 2.0 adapter (PCI id of enhanced controller : 1106-3104)
on an older DELL-Intel motherboard (with Pentium III, i815 ICH2)
= This is NOT detected by Grub4DOS : Error 81 No USB device found !

**Comment by yaya2007** [comment]
1. After the failure, hot restart, successful or not?
2. Download the test, screenshots feedback.
http://bbs.wuyou.net/forum.php?mod=attachment&aid=MjExNTQ4fDk4NGNlNTJifDE0MjY0NzczOTV8NDIzMjYyfA%3D%3D

**Comment by Nin-ho** [comment]
1. After the first failure (Err 81), if I retry   "usb --init " a second time, it hangs forever at
" ... Scanning USB devices ..." Technically machine isn't hung : interrupts still allowed, but the scan 
never completes. tryin different delays does not modify the issue.

If by hot restarting, you meant 'control-alt-del' , then it does not help either. Reexecuting
Grub4DOS after reloading DOS, '>usb init' still gives error 81 once, and hangs if retried a second time.

2. Downloading your test now. I don't have a camera to take screenshots unfortunately :(

**Comment by Nin-ho** [comment]
... Here is the debug dump copied using hand & good ol' pencil :+1: 
________________________________________________________________________
0003 0210 0002 2049 4350 0000 0000 0003 0252 0080 4008 FF9F FC00 0611 0431 0000
1002
FFFF [2 x 16 times]

0004 FFFF [ 8 times]
________________________________________________________________________
When restarted, it outputs the first 13 values again (until FC00)
and there it hangs (waiting) forever...

HTH

**Comment by yaya2007** [comment]
Please re download the test
http://bbs.wuyou.net/forum.php?mod=attachment&aid=MjExNjY3fGU1MWQyN2E2fDE0MjY1NzYwMjB8NDIzMjYyfA%3D%3D

**Comment by Nin-ho** [comment]
Output, omitting leading zeroes from groups of four HEX 

3 210 2 2049 4350 0 0 3 252 80 4008 FC00
1000 9500 422 0 200 0 0 0 100 100 400 0 0 0 8E01 0
0 0 0 0 C0C4 0 0 0 0 0 0 0 0 0 0 0

4 1000 1000 1000 1803 1005
1201 2 0 40 1615 1312 0 102 301  902 2000 101 80 9609 400 2
806 5000 705 8102 2 7 502 200 200 AA
0 7A 57FF 200 AA00 AA01 0 AC8 AA07 AA08 AA09 AA09 AA0A AA0B 82

**Comment by yaya2007** [comment]
已经修正，请从官网下载测试。

**Comment by Nin-ho** [comment]
Superb ! Issue *resolved* by this yaya2007/grub4dos, 03/18/2015 commit  !
_____________________________________________________________

You Yaya, Sir, are a wizzard ! Now, if only you could have a deep look into issue nr. 47...
Also, I assume, You are the author of updated "di1000dd.sys" DOS driver for USBMSD ?
It would be so nice to have a version upgraded for 4K-byte sectors !

**Comment by steve6375** [comment]
This new version has a problem with Haswell Asus Z87A mainboard (using USB 2.0 port)
If I boot to new version and run usb --init, it says 'no devices found - restart' but the USB keyboard no longer works (even CTRL-ALT-DEL does not work).
If I boot to grub4dos 20150304 and then run usb --init, it says 'no USB devices found - restart' but keyboard is working OK afterwards.

**Comment by yaya2007** [comment]
对于 ‘Haswell Asus Z87A mainboard’， grub4dos 20150304 版本只是使 usb 主控停止工作；而新版本则接管了主控的控制权，由于 grub4dos 的 usb 驱动不包含键盘及鼠标驱动，故影响使用 usb2.0 的键盘及鼠标（使用 usb1.0 的键盘及鼠标不受影响）。

为何出现 'no USB devices found - restart' ？没有插 U盘？如果已经插入U盘，请使用测试专用 grldr 反馈屏幕信息。

**Comment by yaya2007** [comment]
不好意思，我刚看到  #24
