### ISSUE TITLE
Fatal error message on NTFS drives

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#51]
If accessing valid sectors near the end of an NTFS drive (e.g. within 50 sectors of the end of the physical drive)...
e.g. cat --hex (hd0)0x7740a79+1
you get the error message:
**Fatal! Inconsistent data read from (0x80)125045343+127**
However, the operation does work OK!
This 'Fatal' message cannot be suppressed, even with debug 0  or debug msg=0.
cat --hex (hd0)0x7740a79+1 > nul   does suppress the message.
BUT

debug 0
debug msg=0
cat --hex (hd0)0x7740a79+1 | set A=

does not work correctly.

As the commands actually do work successfully and return the correct sector contents, this message seems to be a warning rather than an error and also should be in the stderr stream or at least suppressed with debug msg=0.

**Comment by chenall** [comment]
It seems this should be an error message
```
 // Compare with previous read data
    if (plast[0] != BADDATA1) 
    {   // Read data changed, error.
	grub_printf("\nFatal! Inconsistent data read from (0x%X)%ld+%d\n",drive,sector,nsec);
	return -1; // error
    }
```

I will change it with error message next build.

**Comment by steve6375** [comment]
Is the problem that for NTFS, 127 sectors at a time are used?
So a read of 1 sector near the end of the drive actually works, but many of the other sectors in the 127 block fail (as it is past the end of the drive)

try on an NTFS drive 
cat --hex (hd0)<last sector>+1

it does seem to return the correct data, but still reports 'Fatal! error'.

**Comment by steve6375** [comment]
This seems fixed now??
I get no error message at all even accessing the last sector - did you fix it?

**Comment by chenall** [comment]
Nothing change for it,
but i will change this message to stderr.

**Comment by steve6375** [comment]
Seems to be fixed.. Thanks
