### ISSUE TITLE
bios utility and int 13h AH=48 bug?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#52]
When making a bios call for int13h AH=48h, the buffer area seems to need to contain non-zero bytes in bytes 0 and 1 of the buffer area

This works:
> write 0x60000 0x1212
:: get size of disk from INT 13h AH=48 into memory at DS:SI+10h  - edx=80h is hard disk 0, 81h would be hard disk 1
/bios int=0x13 eax=0x4800 edx=0x80 ds=0x6000 esi=0x0
read 0x60010

This fails

> write 0x60000 0x12
:: get size of disk from INT 13h AH=48 into memory at DS:SI+10h  - edx=80h is hard disk 0, 81h would be hard disk 1
/bios int=0x13 eax=0x4800 edx=0x80 ds=0x6000 esi=0x0
read 0x60010

also write 0x60000 0  causes a fail too.

I cannot work out why??

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/6885170/225e3866-d60b-11e4-865a-184049637a05.png)

**Comment by Nin-ho** [comment]
Per IBM/MS/et al. specification, the 1st word of the parameters buffer (@0x60000 in your case)
should be filled with the buffer [i]size[/i] on call, i.e. must be (at least) 0x001A for EDD version 1.0,
up to 0x42 (EDD 3.0). Your failed attempt put 0x0012 there, which was too small and G4D's int 13 
rightly flagged it by returning with the carry flag set.

**Comment by steve6375** [comment]
Thanks, the description is not very clear.  It just says
00h    WORD    (call) size of buffer

not '(on call)'  which would have been clearer!
