### ISSUE TITLE
Feature request: auto-hotkey feature based on first letter in a menu

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#53]
If I have a large menu, I would like a to enable a feature where if a letter is typed, the first menu beginning with that letter is highlighted. If the same letter is typed again, then the next menu entry beginning with that letter is highlighted.
e.g.
titile Ubuntu x86
xxxx
titile Fedora x86
xxxx
titile PClinuxOS x64
xxxx
titile Ubuntu x64
xxxx
titile Fedora v3
xxxx
titile Ubuntu 14.04
xxxx
title ^Ctrl+D Dos
xxx
title Extra software
xxx

so if the user types 'u' the first matching line starting with u (uppercase or lowercase) is selected - e.g.  menu 0. Then if the user presses u again, it goes to item menu 3. Then if he presses 'f' it goes to menu 4. If he presses 'f' again, it goes to menu 1, etc.
This is in addition to the hotkey feature. Command keys such as p, b, c and e will only work if SHIFT is pressed. e.g.
e  -> Extra software menu selected
E -> edit menu
p -> PClinuxos menu selected
P -> password prompt
b -> no action (no matching menu)
B -> boot current menu entry
CTRL+D or CTRL+d - uses hotkey utility to immediatly run Dos entry

This allows a user to easily navigate a large menu to find an entry.
Is this possible?

**Comment by chenall** [comment]
Try this
http://chenall.qiniudn.com/hotkey-2015-04-06.zip

**Comment by steve6375** [comment]
Thanks! Almost perfect! but if I have a menu with

title etest
title ptest
title ctest
title btest

then E=edit, B=boot, C=commandline, P=password do not work

Can you look for SHIFT+b  or maybe SHIFT+CTRL+b  for boot, etc so we can still use these commands please?

**Comment by steve6375** [comment]
If this is difficult or would cause problems, I can define a hotkey to disable it, e.g.

# turn off auto-select to allow e,c,b,p to work
()/%grub%/hotkey [ALT+Z] "hotkey -u ;; hotkey" > nul

**Comment by steve6375** [comment]
Another problem

if 
hotkey -A
hotkey [ALT+Z] "echo test ;; pause"

then autohotkey function is disabled

**Comment by chenall** [comment]
Command keys such as p, b, c and e will only work if SHIFT is pressed. when hotkey -A
http://chenall.qiniudn.com/hotkey-2015-04-06-new.zip

>hotkey [ALT+Z] "echo test ;; pause"
>then autohotkey function is disabled
>?????

**Comment by steve6375** [comment]
hotkey -A

now press g and first menu
title gtest
xx
title gtest
xxx

is selected

Now type SHIFT+C and in console add hotkey for something - e.g.

hotkey [ALT+Z] "echo test ;; pause"

now press ESC for menu and press g  - the autoselect feature has been disabled

**Comment by steve6375** [comment]
P.S. can you upate help/usage message too please?
Thank you very much - this is great!

**Comment by steve6375** [comment]
Bug:
There is a problem when using number keys to select a menu

Create a menu with more than 11 entries and use  hotkey -A

menu.lst
cat /menu1.lst > (md)0xA000+0x50
hotkey -A
configfile (md)0xA000+0x50


menu1.lst
=======
default 1
title abc
title def
title ^H submenu
configfile /menu2.lst
title ghi
etc.
etc.


menu2.lst
title Go back
configfile (md)0xa0000+0x50

User..
press 1 key to select menu #1 
press H key to load submenu
run Go Back menu
>> Menu entry 1 is selected due to  default 1  in menu  = OK expected
press 1 key

>>> Main Menu goes to 11 not 1  = ERROR

So keyboard buffer is not being cleared in hotkey ???

**Comment by steve6375** [comment]
Bug #2 - if there is no password set and no menu beginning with E then when the user presses e it goes to the edit menu.  It should only go to the edit menu if SHIFT is pressed.
i.e the user presses e and nothing should happen - if he pressed SHIFT+e then it should go to the edit menu. Same for p and c and b - e.g. user presses b and it boots current selected item, or presses c and it goes to command line.

**Comment by chenall** [comment]
http://grub4dos.chenall.net/utils/hotkey/

**Comment by steve6375** [comment]
bug 1 fixed - thanks!
bug 2 not fixed
Please try demo at
https://drive.google.com/file/d/0B44X_H05wMHFX0NiV2VMWnJWZnc/view?usp=sharing

**Comment by chenall** [comment]
Because I want to retain the use the number keys to select the menu item function

**Comment by steve6375** [comment]
But if user types  hotkey letter then  old number should be cleared.

**Comment by chenall** [comment]
This is a grub4dos function,not control by hotkey.
hotkey can only disable the numeric keys to select the menu item function.

**Comment by steve6375** [comment]
Can configfile command clear the old number?

**Comment by chenall** [comment]
我看了一下grub4dos源码,好像不行,看来需要修改grub4dos源码让它在加载菜单前自动清除

**Comment by steve6375** [comment]
Shall I close this and raise a new bug report on grub4dos?

**Comment by chenall** [comment]
Okay, it would be better

**Comment by steve6375** [comment]
Closed, New hotkey feature is great! thanks!
