### ISSUE TITLE
%~x1 doesn't work with very long filenames

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#54]
grub4dos 0.4.6a 2015-03-24

problem first found with filename string=
WIN8.1_ENT_REVIEW_9600.16384.WINBLUE_RTM.130821-1623_X86FRE_ENTERPRISE_EVAL_EN-US-IRM_CENA_X86FREE_EN-US_DV5.ISO
also this fails
12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678.ISO
fails on 102 characters

This file is OK (101 characters)
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567.ISO

%~n1 %~x1 and %~nx1 seem to be failing if filename is very long

It is only failing in a batch file - I cannot seem to reproduce the problem in a test batch file.

e.g.
win8mn.g4b .automenu WIN8

With files in \_ISO\WINDOWS\WIN8 folder

If you download Easy2Boot from www.easy2boot.com, the \_ISO\e2b\grub\win8mn.g4b file can be found (without debug code).

![image](https://cloud.githubusercontent.com/assets/1469350/6998912/ea24a974-dbe8-11e4-8039-650b7c9a0025.png)

see makemenu0 line - only %1 is echoed to screen!

![image](https://cloud.githubusercontent.com/assets/1469350/6998920/49b9d95e-dbe9-11e4-9fa3-4a4122692e5d.png)

**Comment by chenall** [comment]
because current has 128 character limit full path (%~x,%~n).

**Comment by steve6375** [comment]
9600.16384.WINBLUE_RTM.130821-1623_X86FRE_ENTERPRISE_EVAL_EN-US-IRM_CENA_X86FREE_EN-US_DV5.ISO
is a valid filename of Microsoft download = 94 characters
So if path was more than 30 or so characters, this would fail because too long.
Is it difficult to fix?

**Comment by chenall** [comment]
I will fix it later.

**Comment by chenall** [comment]
max 1024 characters,
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-04-07.7z

**Comment by steve6375** [comment]
Great! Fixed!
