### ISSUE TITLE
Setting long variable names are ignored

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#55]
![image](https://cloud.githubusercontent.com/assets/1469350/7003386/70409302-dc51-11e4-85e5-d6f29b91f021.png)

I know variable names are 8 characters max,  if 9 chars then it is reduced to 8, but if more than 9 then it is ignored.
I would expect
set AUTOMENUOFF=1
to set as
AUTOMENU=1

This seems inconsistent behaviour?

**Comment by chenall** [comment]
current only check the previous 8 characters,Others are filtered

**Comment by steve6375** [comment]
But it is not consistent
8 characters --> OK
9 characters --> variable name shortened to 8 characters
10 characters --> variable not written
11 characters --> variable not written
etc

why does 9 characters get shortened to 8  but  10 characters is ignored.
Also - why no error message if variable name >8 characters? Should be debug 1 level message if variable is not set?

**Comment by steve6375** [comment]
This now breaks all old grub4dos batch files that use variable names of 9 characters!!!!
e.g. E2B no longer works

e.g. set CHECKBIOS=1   now doesn't work

I think it should shorten all variable names to 8 characters and issue a WARNING message.

e.g.
set CHECKBIOS=1     >> CHECKBIO=1
set CHECKBIOSA=A  >> CHECKBIO=A
set CHECKBIOSAA=B >> CHECKBIO=B

etc.

**Comment by chenall** [comment]
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-04-08.7z

**Comment by steve6375** [comment]
Something broken/moved !!!
automatic numbering of menus not working

**Comment by steve6375** [comment]
Found problem!

set STARTMENU=3
echo %STARTMENU%

result
> %STARTMENU%

variables of > 8 characters are not shortened to 8 characters

**Comment by steve6375** [comment]
ignore 0x8274 symptoms, problem is 9 character variables don't work..

set ABCDEFGHI=1
echo %ABCDEFGH%
does now work.

**Comment by steve6375** [comment]
P.S. message
Name [xxxx] incorrect or too long(max 8 chars)!
requires space after 'long' e.g.
Name [xxxx] incorrect or too long (max 8 chars)!

for correct English.

**Comment by chenall** [comment]
>9 character variables don't work.
there is bug in pre version,
More than 8 chars or incorrect name should keep original.
Maybe we need a new set of parameters to maintain this compatibility?

**Comment by steve6375** [comment]
No need for new set - for compatibility just shorten all variables to 8 chars + show warning.

Old batch files will not use 10 chars or more variables because they don't work.
Old batch files will only use 9 characters of less.
So no problem.

New grub4dos should just shorten all variables to 8 characters - no compatibility problem.

Just need to make

set ABCDEFGHIJKL=1
echo %ABCDEFGHIJKL%
echo %ABCDEFGHIJK%
echo %ABCDEFGHIJ%
echo %ABCDEFGHI%

work same as 
echo %ABCDEFGH%

**Comment by steve6375** [comment]
If this is very difficult to do, we can go back to old code + warning if variable > 8 show warning (debug 2 level)?
if variable > 9 show Error (debug 1 level)

rules are:
if 9 chars then shorten to 8 + warning
if >9 chars then error + error

**Comment by chenall** [comment]
http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-04-12.7z
9 chars old compatibility + warning
>9 do nothing + error

**Comment by steve6375** [comment]
Thanks - looks good. :-)

suggest for message:

Warning: VAR name  [xxxxx] shortened to 8 chars!

**Comment by chenall** [comment]
Thanks. :+1:

**Comment by steve6375** [comment]
0.4.5c also needs updating as 9 character variables don't work in  2015-04-08 version

**Comment by steve6375** [comment]
2015-04-08 is still broken...
9 character variables do not work in this version - please delete it
set ABCDEFGHI=1
does not work and could cause compatibility problems

**Comment by chenall** [comment]
0.4.5c updated,
