### ISSUE TITLE
"boot -1" should not restore BIOS "number of hard disks"

### ISSUE THREAD

**Issue by Nin-ho** [chenall/grub4dos#57]
> boot -1
... signals BIOS a "failed" boot attempt, and that the next boot option should now be attempted.

Before giving control back to BIOS however, Grub4DOS will restore the number of hard disks
at absolute address 0x0000475, that is a bug, preventing a legacy OS from "seeing" any added
disks (such as done by:  > usb --init )

**Comment by chenall** [comment]
seems this is control by bios.
`boot -1` just call "int $ 0x18"

**Comment by Nin-ho** [comment]
Oh, I see... Also, different BIOSes might act different in this respect. Well,
there is not much we can do anyway. Closing as : not-a-bug.

**Comment by Nin-ho** [comment]
Dear chenall,

The email sent to ninho@ninho.tk with subject
"Re: [grub4dos] "boot -1" should not restore BIOS "number of hard"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to ninho@ninho.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
