### ISSUE TITLE
Add fork for DavidB's grubinst and grubinst_GUI

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#58]
DavidB is unwell - could you add his versions of grubinst and grubinst_GUI as a fork please and maintain them. I think they are much better than the current version and have many bug-fixes and improvements.
http://reboot.pro/topic/20238-improving-grubinst-and-grubinst-gui-in-windows-and-linux/page-13#entry191845

**Comment by chenall** [comment]
Merged!
https://github.com/chenall/grubutils

**Comment by steve6375** [comment]
Thanks
