### ISSUE TITLE
Set background highlight color

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#59]
e.g.
color highlight=cyan/red
color highlight=0xFF00FF

In graphicsmode, for the menu highlight I can use
color highlight=cyan/red
to set the background colour to red
I can then set a 24-bit value using, e.g.
color highlight=0xFF00FF
but this always sets a  transparent background colour for the highlighted menu.
How can I use a 24-bit colour value for the foreground and a non-transparent colour for the background colour? Is this possible (either using a 15-colour value or a 24-bit colour).

**Comment by chenall** [comment]
use 64 bit color
e.g.
color highlight=0x00ffff0000ff00ff
hi 32 bit bg-color
lo 32 bit fg-color

**Comment by steve6375** [comment]
Thanks!
