### ISSUE TITLE
Request: align menu text from right to left option

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#62]
Some languages (arabic/persian/malay/hebrew) are written from right to left.
http://en.wikipedia.org/wiki/Right-to-left
Is it possible for grub4dos right-align menu entries?
I presume the languages are also supported in unifont font???
Needs to be supported using menusetting.gz too.

**Comment by memoarfaa** [comment]
yes it well be very useful 
but you need to use fribidi to alight the words itself 
before add setting in  menu.lst you need alight words in menu.lst it self by fribidi
the unifont will not read it until use fribidi (http://fribidi.org/)
commands to alight menu.lst in windows by fribidi.exe(http://fribidi.org/download/win/)
"fribid.exe -c, --charset UTF-8 --nopad --clean mymenu.lst > menu.lst

**Comment by steve6375** [comment]
setmenu --right-align  now does this. Thanks!
