### ISSUE TITLE
grub4dos.chenall.net seems down

### ISSUE THREAD

**Issue by pbatard** [chenall/grub4dos#63]
I tried from multiple computers, on different continents, but the server seems unreachable.

Is there another server where official binary releases can be obtained? I saw from a recent issue that http://chenall.qiniudn.com/grub4dos-0.4.6a-2015-04-07.7z might be the latest, but I'm wondering if there's something more recent than this.

Of course, I can build my own binaries. But I'd rather use the official ones to include in Rufus... :smile:

**Comment by pbatard** [comment]
Seems to be working now.

**Comment by chenall** [comment]
grub4dos.chenall.net => chenall.gitcafe.io => 207.226.141.162
