### ISSUE TITLE
0.4.6a bug if two 'if exists' used on same line

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#64]
![image](https://cloud.githubusercontent.com/assets/1469350/7898807/650dcd14-0704-11e5-826c-007380b2e407.png)

0.4.6a 2015-05-18 screen corruption/crash if two 'if exist' commands used on same line AND file exists.
If only one if exist is used then is OK.
0.4.5c 2015-05-18 is OK.
USB NTFS drive under VBox.

**Comment by chenall** [comment]
I can not reproduce this problem, maybe BUG in graphics mode

**Comment by steve6375** [comment]
No - maybe to do with ISO??  This test is clean boot, no graphics mode, no menu.lst
![image](https://cloud.githubusercontent.com/assets/1469350/7933712/fdc83088-0918-11e5-8241-299e7a9744ba.png)

**Comment by steve6375** [comment]
Also TAB completion does not work correctly, e.g.
ls /pmagic/ <TAB> says file not found
ls /pmagic/f <TAB> completes to /pmagic/fu.img
![image](https://cloud.githubusercontent.com/assets/1469350/7933778/85a2006a-0919-11e5-924e-bff9625ce05a.png)

**Comment by chenall** [comment]
there has bug in UDF,
You can  disabe UDF(write --bytes=1 0x830c 0xFC)
or wait yaya to fix the problem.

**Comment by steve6375** [comment]
Looks good, thanks!
