### ISSUE TITLE
0.4.6a Multiple initrd files cause error

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#65]
title PMAGIC TEST
set ISOSCAN=/_ISO/MAINMENU/pmagic_2015_05_04.iso 
map %ISOSCAN% (0xff)
map --hook
root (0xff)
kernel /pmagic/bzImage load_ramdisk=1 prompt_ramdisk=0 rw gfxpayload=text loglevel=9 iso_filename=%ISOSCAN% eject=no edd=on vga=normal vmalloc=512MiB 
initrd /pmagic/initrd.img /pmagic/fu.img /pmagic/m32.img
boot

![image](https://cloud.githubusercontent.com/assets/1469350/7898900/cff87e1a-0706-11e5-8826-6664ceaf24d8.png)

2015-05-18 0.4.5c works OK (all three .img files are loaded and it boots). 
2015-05-18 0.4.6a fails as in screenshot.

**Comment by chenall** [comment]
Please Make sure the file exists,e.g
ls /pqmagic/initrd.img
...

**Comment by steve6375** [comment]
Yes all three files exist.
As I said, 0.4.5c works using same menu. It is bug with 0.4.6a.

**Comment by steve6375** [comment]
works if   
write --bytes=1 0x830c 0xFC   
used to disable UDF support.

**Comment by chenall** [comment]
Please
