### ISSUE TITLE
Query: How to detect if running 0.4.5c or 0.4.6a

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#69]
Is the version number and letter stored in an 'official' memory location?
I would like to detect if I am currently running 0.4.5c or 0.4.6a.
Using cat --locate="0.4.6a" (md)0xaaaa+0xbb  is not reliable when reloading different grldr:
e.g.
chainloader /grldr046
then if we load 0.4.5c...
chainloader /grldr045
and we have both "0.4.5c" and "0.4.6a" strings in memory because 0.4.6a is larger than 0.4.5c.

What is best method to determine what version is running (not date string, but version).

My code is:
iftitle [cat --locate="GRUB4DOS 0.4.5" (md)0x200+0x50]  Load Grub4dos 0.4.6a
echo Loading Grub4Dos 0.4.6...
chainloader /grldr_046

::check for help text which only occurs in 0.4.6
iftitle [cat --locate="usb --delay" (md)0x200+0x50 && if "%GRUB_DUN%"==""] USB DRIVER
debug 1
usb --init
echo
debug off
pause --wait=3
:: don't do usb --init again in menu.lst
set GRUB_DUN=1
configfile /menu.lst

iftitle [cat --locate="usb --delay" (md)0x200+0x50] Load grub4dos 0.4.5c
echo Loading Grub4Dos 0.4.5...
chainloader /grldr_045

**Comment by yaya2007** [comment]
0.4.6a:
echo -v

**Comment by steve6375** [comment]
Thanks, but that is for very new versions of 0.4.6a only. Is there a reliable way for older versions of 0.4.6a?

**Comment by moxiea** [comment]
Like javascript in different web browsers,I think you can use the feature detection:

```bash
errorcheck off
#(hd) is for new version only，so we use 'cat (hd)+1' detect version
cat (hd)+1
#older version return 23(Error while parsing number)，newer version return 21
checkrange 23 errnum && write 0x60100 3
errorcheck on
checkrange 3 read 0x60100 && kernel
```

but i did not test more, so u can try first.

[source from](http://chenall.net/post/grub4dos_micrope/)

**Comment by steve6375** [comment]
Thanks for the idea, I use 'help' output to check for a feature.
e.g.
help usb > (md)0x300+1
cat --locate="usb --delay" (md)0x300+1 > nul && set GV=046 && echo grub4dos 0.4.6 detected!

**Comment by steve6375** [comment]
I am closing this issue as it does not seem there is a universal way to get the grub4dos version that is actually running.
