### ISSUE TITLE
splashimage of jpg fails loading 2nd image 0.4.6a 2015-07-16

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#70]
splashimage 1.bmp  >> OK
splashimage 2.jpg    >> OK
splashimage 2.jpg    >> BAD
OR
splashimage 2.jpg    >> OK
splashimage 2.jpg    >> BAD
![image](https://cloud.githubusercontent.com/assets/1469350/8767121/2ae4b072-2e4a-11e5-9ed2-74129dfb08c4.png)

If run from command console it crashes.
800x600 jpg and bitmap used.

**Comment by steve6375** [comment]
Same problem with 2015-07-24

**Comment by yaya2007** [comment]
It seems that the command line can not load the image. I test, the menu is loaded 2 times without a problem. I can't think of, in the menu to load 1 images, and then load 1 to cover the top 1, is there any special significance?

**Comment by steve6375** [comment]
If I have two menus

menu1.lst
menu2.lst

each have different jpg background. Menu2 crashes when it loads the different jpg.

**Comment by yaya2007** [comment]
Got it

**Comment by steve6375** [comment]
Still problems loading 2nd jpg.

graphicsmode -1 800
splashimage /bunny2.jpg

title ^F9 reboot
reboot

Press F9 and reboots as expected, but if load 2nd jpg
splashimage /bunny2.jpg
then F9 key does not work (no hotkeys work)

memory corruption?

**Comment by steve6375** [comment]
This seems to be fixed in 2015-08-03 - did you find the bug and fix it?

**Comment by steve6375** [comment]
Seems OK now, thanks
