### ISSUE TITLE
jpg decoding has flaws/defects

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#71]
splashimage xx.jpg shows lines and artifacts in decoding of  jpg's saved by MSPaint.

800x600 jpg with no text displays OK with splashimage, but after saving jpg using **MSPaint**, the jpg with text does not display OK. So something to do with encoding/decoding???

![image](https://cloud.githubusercontent.com/assets/1469350/8767314/9941dc88-2e50-11e5-8f95-db7ca5088035.png)
Splashimage shows lines, etc.
After MSPAINT
![image](https://cloud.githubusercontent.com/assets/1469350/8767316/ac7126e2-2e50-11e5-8a3d-b04df8186b85.png)

It is very noticeable if you have text in the image  This image does not display well:
![newe2b](https://cloud.githubusercontent.com/assets/1469350/8767352/a14fd6fe-2e51-11e5-9348-0a6e22b45010.jpg)
Here is 800x600 jpg (original file) which was not saved with MSPaint and displays OK

Part of splashimage result:
![image](https://cloud.githubusercontent.com/assets/1469350/8767348/7b085f52-2e51-11e5-96ac-313322a34e47.png)

**Comment by steve6375** [comment]
This jpg was saved using IrfanView with 94% Quality - it does not load at all.
![original_94q](https://cloud.githubusercontent.com/assets/1469350/8768204/5fbcf4ce-2e6f-11e5-811b-6a129b10699e.jpg)
![image](https://cloud.githubusercontent.com/assets/1469350/8768206/816d571c-2e6f-11e5-9d0d-10c2102fe1e7.png)

**Comment by steve6375** [comment]
If you go to
http://image.online-convert.com/convert-to-jpg
and convert an image to a jpeg using default settings ('Pretty Good') then the resulting jpg is displayed with flaws by splashimage.
But, if you set to 'Best Quality'  then it seems to be OK.
![image](https://cloud.githubusercontent.com/assets/1469350/8772581/3e665eea-2ec5-11e5-872c-a2d5cf65f641.png)

Same with PAINT.Net - save at 95%Quality and it has flaws. Save at 100% quality and it is OK.

**Comment by steve6375** [comment]
Same problem with 2015-07-24

**Comment by yaya2007** [comment]
Source code author statement, the image of some flaws. I also noticed that I just couldn't find the cause. Fortunately, just use the display of the background image, you can tolerate.

**Comment by steve6375** [comment]
Image is always OK if saved with 100% quality but that means the file size is **much** larger than 95% quality which is standard quality for jpg files.
If you cannot solve, suggest you document that must use 100% Quality setting.

**Comment by steve6375** [comment]
New 2015-08-07 does not work with some jpg files - e.g. 
![14981](https://cloud.githubusercontent.com/assets/1469350/9133477/ce81fe30-3cf3-11e5-868e-ad4f6a9fca4a.jpg)

If save using MSPaint then it is OK.
Images obtained from http://wall.alphacoders.com/by_resolution.php?w=800&h=600

**Comment by steve6375** [comment]
If load some jpgs they sometimes do not display properly (depends on what jpg was loaded previously - e.g. try 'bad' jpg above followed by this jpg...

Symptom:
![image](https://cloud.githubusercontent.com/assets/1469350/9133581/b935792a-3cf4-11e5-9b9e-ec9245924aac.png)

This is jpg - sometimes loads OK, sometimes loads with errors (depends on previous jpg).
![800-600-14981](https://cloud.githubusercontent.com/assets/1469350/9133599/e163da5e-3cf4-11e5-9d38-12636164f1d5.jpg)

**Comment by yaya2007** [comment]
SOF2 mode is not supported

**Comment by steve6375** [comment]
Thanks
