### ISSUE TITLE
mapping of prdgm.ima file causes 'file not contiguous' error

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#78]
http://files.easy2boot.com/200001305-08a0d09976/prgdm.7z
(password to unzip file is 123)
This particular file always causes a 'file not contiguous' error or 'too many non-contiguous blocks' even though the file is contiguous. I tried 0.4.5c old versions and 0.4.6a latest versions. 

map /prdgm.ima (fd0)  >>> fails

map --mem /prgdm.ima (fd0)  >>> OK

**Comment by yaya2007** [comment]
"map --mem /prgdm.ima (fd0)"  After decompression, send to memory,so successful.
"map /prdgm.ima (fd0) "  Run directly from disk,but,file is compressed,so failed.Please extract and then perform

**Comment by steve6375** [comment]
OK thanks, did not realise it was compressed!
