### ISSUE TITLE
find --set-root issue with 0.4.6a

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#82]
Booting from USB drive - On a certain PC with 3 drives  2 ssd (120GB, 480GB) and 1 hdd (3 TB) - the command below always causes a hang/crash of grub4dos 0.4.6a. 2015-05 version. Latest version 0.4.6a also same issue.
But 0.4.5c is OK.
![findbug](https://cloud.githubusercontent.com/assets/1469350/10007735/a31f2606-60bf-11e5-8213-d4c91d8cb13e.jpg)
WINHELPER.USB is not present on hd3.

**Comment by steve6375** [comment]
Here is partition table of hd3
![parttable](https://cloud.githubusercontent.com/assets/1469350/10033508/ce972154-6181-11e5-98bb-ff91e8deca03.jpg)

**Comment by yaya2007** [comment]
Partition type =0xee, is the GPT partition structure. Under normal circumstances, the partition 0, partition 1 no content.
Please confirm:
1 HD3 partition structure gpt;
2 WINHELPER.USB is the partition on this disk 0

**Comment by steve6375** [comment]
![gr800hd3](https://cloud.githubusercontent.com/assets/1469350/10072606/ef2f837c-62ba-11e5-9ad3-10327133367e.jpg)
![hd3withgparted](https://cloud.githubusercontent.com/assets/1469350/10072607/f1bb4e82-62ba-11e5-89db-4470817e6595.png)

WINHELPER.USB is not present on any drive in the system.

**Comment by yaya2007** [comment]
root (hd3,0)
root (hd3,1)
root (hd3,2)
root (hd3,3)
root (hd3,4)
What's the result?

**Comment by steve6375** [comment]
Problem occurs on hd0,0 only

![rootresults](https://cloud.githubusercontent.com/assets/1469350/10101896/61c8249c-6393-11e5-9eac-f1c6b8060f85.jpg)

**Comment by steve6375** [comment]
(hd3)+1 is all 0's except for partition table as in first screenshot.
here is 0.4.5c results
![rootresults045c](https://cloud.githubusercontent.com/assets/1469350/10103598/a89ed740-639c-11e5-9aa8-e7a48a91160f.jpg)

**Comment by yaya2007** [comment]
Please screenshot on hd3:
1. LBA(2)
    n=Offset 0x20 (8 bytes)   The starting sector of the partition 0
2. LBA(n)

**Comment by steve6375** [comment]
![lba2](https://cloud.githubusercontent.com/assets/1469350/10118107/403c283a-6467-11e5-9435-ea8c4fbb38b3.jpg)
![lba0x800](https://cloud.githubusercontent.com/assets/1469350/10118108/404139d8-6467-11e5-9314-0c4589d49eac.jpg)

it seems to be all 0's ???

**Comment by steve6375** [comment]
I have had no further reports since 2016-09 version so I think this is now fixed.
