### ISSUE TITLE
UTF-8 unifont issue with 0.4.6a 2015-10-12

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#84]
![image](https://cloud.githubusercontent.com/assets/1469350/10574423/c9cfcf64-764d-11e5-98c9-9ac9ec626f96.png)
![image](https://cloud.githubusercontent.com/assets/1469350/10574428/d290b582-764d-11e5-8d19-8355f6b47abb.png)
Space or graphics character before all UTF-8 characters (using unifont.hex)
Does not happen with earlier 0.4.6a - e.g. 2015-08-25
![image](https://cloud.githubusercontent.com/assets/1469350/10574465/1067bb12-764e-11e5-9fba-5fa7d171c566.png)
![image](https://cloud.githubusercontent.com/assets/1469350/10574473/1d5d6ace-764e-11e5-8ef7-d0d3e773a3b5.png)

**Comment by steve6375** [comment]
2015-09-13 OK
2015-09-15 BAD  - so bug introduced here!

**Comment by yaya2007** [comment]
Please send me the menu

**Comment by steve6375** [comment]
https://onedrive.live.com/redir?resid=8A0F146CC7416BA9!2123&authkey=!AA4N5sRY3K9fkGM&ithint=file%2c7z

**Comment by steve6375** [comment]
Do you have the files now to test?
