### ISSUE TITLE
Menu highlight background not full width 0.4.6a

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#94]
In early versions of 0.4.6a, the highlight menu selection bar extended across the width of the menu (0.4.5c is same)
Later versions of 0.4.6a have a short background bar

2015-06-05  all across
2015-06-17 all across
2015-07-09 short      <<<<<<  issue starts here
2015-07-16 X
2015-07-24 X
2015-08-20  short

![image](https://cloud.githubusercontent.com/assets/1469350/12868767/593fa6a2-cd05-11e5-9aff-1f343d31f965.png)
![image](https://cloud.githubusercontent.com/assets/1469350/12868775/9540c56e-cd05-11e5-8cde-98bda756d4f9.png)

**Comment by steve6375** [comment]
**menu.lst**

```
color highlight=white/red
title TEST
reboot
```

This shows the problem

**Comment by 2012yaya2007** [comment]
Some people need, so changed.
"all across" and "short" Does not affect the use of.

**Comment by steve6375** [comment]
It does affect the use because user cannot easily see where the selection is - e.g. if use

title
reboot

then cannot see a bar
It is not compatible with 0.4.5c and earlier versions of 0.4.6a.
If some users want a short bar then **default** should be **long** bar + setmenu option for short bar.

![image](https://cloud.githubusercontent.com/assets/1469350/12880916/3afcaa9e-ce3d-11e5-9cc8-2b25c9f08b95.png)

**Comment by wdlkmpx** [comment]
The commit it was introduced in is BIG ... https://github.com/chenall/grub4dos/commit/5c469149afba623452bc2b01ed720d503df1b669

But I do agree, having both "long" and "short" bars is a good idea..

**Comment by steve6375** [comment]
Fixed. Thanks.
