### ISSUE TITLE
New abort command required

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#95]
The following menu will cause grub4dos to return to the original menu and highlight the same menu entry that was previously selected

```
title ddd
echo fred
echo doris
errorcheck off
boot
```

using boot is not good because there may already be code in the boot segment. Also there is no way to 'abort' from a menu - e.g.

```
title sss
echo fred
set /p ask=Do you want to continue Y/N : 
if  /i not "%ask%"=="Y"   abort
map /ss.iso (0xff)
map --hook
chainloader (0xff)
```

**Comment by 2012yaya2007** [comment]
Workaround
"abort" = goto n
n: Not executable menu item

**Comment by steve6375** [comment]
Can you give example of goto n in use ??

```
graphicsmode -1 1024

title test
echo 1
goto 99
echo 2
pause 3
boot
```

This gives blank screen until press cursor key after run menu...

**Comment by 2012yaya2007** [comment]
title 16
echo

title 17
echo 1234
set /p ask=Do you want to continue Y/N :
if  /i not "%ask%"=="Y"   goto 16
echo 4321

**Comment by steve6375** [comment]
That is not the same. Need a 'menu abort' method...

**Comment by chenall** [comment]
how about using `exit`.it's easy to add this function.

**Comment by steve6375** [comment]
OK

**Comment by steve6375** [comment]
Latest version 2016-03-10 does not solve issue
Cannot use exit in menu

title X8 exit
pause aaaa
exit
pause bbbbb
boot

> > ![image](https://cloud.githubusercontent.com/assets/1469350/13674081/0878819c-e6d4-11e5-9cbf-4767b8299e55.png)

**Comment by chenall** [comment]
You may be using an older version...

**Comment by steve6375** [comment]
I think version is correct. Also yaya 2016-03-11 is same.
![image](https://cloud.githubusercontent.com/assets/1469350/13697637/9f7b30f2-e766-11e5-9977-ec599ee72db5.png)
Did you try example menu?

**Comment by chenall** [comment]
I have tested it works correct,

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/13706217/1560a6f0-e79c-11e5-9f6c-467d32385bdd.png)

grub4dos edit
![image](https://cloud.githubusercontent.com/assets/1469350/13706244/28895312-e79c-11e5-8e13-773defa0ef17.png)

select menu option
![image](https://cloud.githubusercontent.com/assets/1469350/13706250/35b26d3a-e79c-11e5-8f6d-48e2aa570e86.png)

**Comment by 2012yaya2007** [comment]
2016-03-10 Release version,Very good, "exit" function has been achieved.
After that, I will update my test version.
2016-03-11 version is test version.

**Comment by steve6375** [comment]
OK, thanks!
