### ISSUE TITLE
font-high=24 and then clearing fonts changes space character + hotkey hang

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#96]
```
graphicsmode -1 1024
# load 24 high font file
font --font-high=24 /yxt.hex

title TEST1 - reload font
font
font --font-high=24 /yxt.hex
configfile /menu.lst

title TEST2 - clear font
font
configfile /menu.lst

title reboot
reboot
```

![image](https://cloud.githubusercontent.com/assets/1469350/13461370/d39152a8-e078-11e5-8a33-3c6912f7d0ee.png)

**Comment by steve6375** [comment]
The yxt.hex and sft.hex font files do not contain the 0020 hex (space) character.
They both start as 0021 hex.
I added 0020 line but still gives same problem.

**Comment by steve6375** [comment]
2016-03-04 better but a bug now when changing to 16 font...

font --font-high=24 /yxt.hex
**font**
font /unifont.hex.gz

does not set font to default unifont, must use
font --font-high=16 /unifont.hex.gz

also cannot load different font - says font already loaded.

e.g.
font --font-high=24 /yxt.hex
**font**
font /sft.hex               ------ "font already loaded" error

font is not clearing ???

**Comment by steve6375** [comment]
if font --font-high=16 /unifont.hex.gz  required after using 24 high font then is OK, but  

```
font --font-high=24 /yxt.hex
font --font-high=24 /sft.hex
```

should work without error. Previous 0.4.5c and 0.4.6a would allow consecutive loading of font files

**Comment by steve6375** [comment]
also if have loaded 24 font already, then
```
font
font font-high=16  /unifont.hex.gz
```

only works from command line, but does not work from a menu.lst file

**Comment by steve6375** [comment]
If using 16 high unifont,  font command does not clear fonts and go to BIOS fonts
**menu.lst**

```
font /unifont.hex.gz
font

title test
reboot
```

should now display BIOS fonts for 0000 to 00FF

**Comment by steve6375** [comment]
Also
grub4dos 0.4.5c

**font && echo clear font**

this does not work on 0.4.6a 2016-03-04 (no echo) as returns false,

**Comment by 2012yaya2007** [comment]
Try

**Comment by steve6375** [comment]
hotkey causes hang if. If remove hotkey then no problem.
In Easy2Boot, I have menu.lst in memory at (md)0xa000+0x50 - the following menu hangs! Contents of (md)0xa000+1 is  OK. but if I use cat (md)0xa000+0x50 then it hangs!
Only hangs if hotkey used.
**menu.lst**

```
graphicsmode -1 1024
/_ISO/e2b/grub/hotkey -A

```

```
title font sft
font
font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz
font --font-high=24 /_ISO/e2b/grub/sft
errorcheck off
# hangs on this line
cat (md)0xa000+0x50
# never gets here
pause
configfile (md)0xa000+0x50
```

**Comment by steve6375** [comment]
This works once but hangs on 2nd time

```
graphicsmode -1 1024
/_ISO/e2b/grub/hotkey -A
title font sft test
font --font-high=24 /_ISO/e2b/grub/sft
errorcheck off
pager off
cat (md)0xa000+0x50
configfile (md)0xa000+0x50

```

**Comment by steve6375** [comment]
This crashes immediately you run the sft menu
works if hotkey removed or font command removed.

```
graphicsmode -1 1024
/_ISO/e2b/grub/hotkey -A
cat /menu.lst > (md)0xa000+0x50

title font sft
font --font-high=24 /_ISO/e2b/grub/sft
errorcheck off
pager off
cat (md)0xa000+0x50
configfile /menu.lst

```

OK if remove hotkey or if do not run  font command

**Comment by 2012yaya2007** [comment]
test

**Comment by 2012yaya2007** [comment]
test
[grldr.zip.txt](https://github.com/chenall/grub4dos/files/160329/grldr.zip.txt)

**Comment by steve6375** [comment]
new grldr.zip does not work at all

menu.lst
graphicsmode -1 1024
title test
boot

No menu text displayed??
![image](https://cloud.githubusercontent.com/assets/1469350/13554420/598afc96-e39f-11e5-8339-d482dc588ebb.png)

**Comment by 2012yaya2007** [comment]
Graphics mode, do not load fonts?

**Comment by steve6375** [comment]
Graphics mode - no text!

**Comment by 2012yaya2007** [comment]
No font, show what

**Comment by steve6375** [comment]
try
**menu.lst**
graphicsmode -1 1024
title test
boot

**Comment by 2012yaya2007** [comment]
This is very normal.There is no font file, showing a blank.
Add font /unifont.hex.gz, try it.

**Comment by steve6375** [comment]
No, it is not normal. You do not need to load a font for English. It uses BIOS font.
(and even if I do load Unifont, the cat command still crashes!)

**Comment by 2012yaya2007** [comment]
In VBE graphics mode, BIOS characters cannot be used. You can use the command line,or in VGA text mode.

**Comment by steve6375** [comment]
This menu works on 0.4.5c and 0.4.6a 2015 and displays a menu.

**menu.lst**

```
graphicsmode -1 1024
title test
boot
```

It does not work on the new 'grldr.zip.tzt' version you posted.

**Comment by 2012yaya2007** [comment]
got it thank you
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/160709/grldr.rar.txt)

**Comment by steve6375** [comment]
OK, crash solved. fonts load better 

PROBLEM: 'font' command  now resets graphicsmode!

menu.lst

```
graphicsmode -1 1024

title font uni  BAD GRAPHICSMODE IS RESET
font
pause fffff
font /unifont.hex.gz
pause uni
errorcheck off
boot

title font +  font ltb24  BAD \n GRAPHICS MODE IS RESET
font
font --font-high=24 /_ISO/e2b/grub/ltb24
pause 222
errorcheck off
boot

```

**Comment by steve6375** [comment]
If  --font-high is not specified, then it should default to 16

e.g.
font --font-high=24 /ltb24
font /unifont.hex.gz

should work, but it does not.

**Comment by 2012yaya2007** [comment]
There is no need to use "font"
graphicsmode -1 1024

title font uni  BAD GRAPHICSMODE IS RESET
font /unifont.hex.gz
pause uni
errorcheck off
boot

title font +  font ltb24  BAD \n GRAPHICS MODE IS RESET
font --font-high=24 /_ISO/e2b/grub/ltb24
pause 222
errorcheck off
boot

**Comment by steve6375** [comment]
Yes, font should restore BIOS font  to 0000-007F only

This menu works on previous versions of 0.4.5c and 0.4.6a 2016-01

menu.lst

```
title test~ ÀÁÂÃÄ TEST a©a b·b cÀc nñn p‰p üüüüüüü
font /unifont.hex.gz
font
errorcheck off
boot

```

In previous versions, this causes  bios fonts to be used for 0000-007F and unifont for >007F

![image](https://cloud.githubusercontent.com/assets/1469350/13568491/6c3998a6-e459-11e5-9b65-7bc90fe46ac5.png)

**Comment by 2012yaya2007** [comment]
0.4.6a
title test~ ÀÁÂÃÄ TEST a©a b·b cÀc nñn p‰p üüüüüüü
font /unifont.hex.gz
errorcheck off
boot
same ok

**Comment by steve6375** [comment]
No, it is not the same because 0000-007F is in unifont.
if you use font command then 0000-007F should be in BIOS font.
the command 'font' should change 0000-007F to use BIOS font (but if non-16 high font the command 'font' does nothing

if command = 'font' with no parameters {
if ( normal 16 high font in use)  use BIOS font for 0000-007F
}

**Comment by steve6375** [comment]
20160307 still has hotkey problem!

menu.lst

```
graphicsmode -1 1024
# Works OK if next line deleted
/hotkey -A

title test font+hotkey \n Run menu then use cursor in menu
font --font-high=24 /yxt
pause yxt loaded
errorcheck off
pause goto 0
goto 0

title reboot
reboot

```
1. Run menu 0
2. Press cursor down - HANGS!

![image](https://cloud.githubusercontent.com/assets/1469350/13599642/f8fdae72-e51b-11e5-8a08-5083d45a5a27.png)

**Comment by 2012yaya2007** [comment]
Memory conflict.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/164223/grldr.rar.txt)

**Comment by steve6375** [comment]
Thanks, but something is broken in this version if load 24 pixel fonts. 
Fonts (sft 24 high) seem to load OK but when menu is displayed it is blank. 
unifont.hex.gz gives no problem. Problem happens after loading sft 24 pixel font
hotkey is not the cause.
sft is loaded ok and large fonts are displayed (echo works OK), but when menu is displayed it is blank and in 16 pixel high mode
![image](https://cloud.githubusercontent.com/assets/1469350/13621290/69918060-e58e-11e5-8578-9d601d6233cb.png)
if I go to command prompt and type 'font' then I get 16 pixel font - ESC = menu OK.
if I go to command prompt and type 'font --font-high=24 /sft' - ESC - menu OK....
![image](https://cloud.githubusercontent.com/assets/1469350/13621931/f8af8e1e-e592-11e5-9608-29edf120a01b.png)

if I type 'configfile /menu.lst' then I get blank menu, problem seems to be with configfile command with 24 high font loaded?

**Comment by 2012yaya2007** [comment]
Close the hotkey, try it.
Use the hotkey, font size  not too large.

**Comment by steve6375** [comment]
I removed hotkey file and I still get the problem, so hotkey is not the problem.
Previous grldr was OK with same files, so must be a problem with the new grldr.

**Comment by 2012yaya2007** [comment]
I have no problem here.

**Comment by steve6375** [comment]
Difficult for me to reproduce with simple menu. I will try to find best test case tomorrow and send you files.

**Comment by steve6375** [comment]
To reproduce problem - very simple but must use two menus
\menu.lst

```
title  MENU1
configfile /menu1.lst
```

\menu1.lst

```
graphicsmode -1 800
font --font-high=24 /sft.f24
pause HERE
configfile /menu.lst
```

![image](https://cloud.githubusercontent.com/assets/1469350/13631137/f886fdf8-e5da-11e5-90cb-542ac5a5d2c2.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13631153/06276fec-e5db-11e5-82d6-fab2b51f141c.png)

**Comment by 2012yaya2007** [comment]
test
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/167202/grldr.rar.txt)

**Comment by steve6375** [comment]
Not fixed!
I now get small fonts in menu, but it should be large font

**Comment by 2012yaya2007** [comment]
"Menu.lst" is not installed font, should use the BIOS internal font.

**Comment by steve6375** [comment]
menu1.lst has installed the font, so when load menu.lst it should keep large fonts.
This works OK on 2016-03-07 version but not on later versions.
menu.lst + menu1.lst
20160307 - OK
20160310 - BAD
20160311 - BAD

configile should not reset font height. This is major problem!

**Comment by steve6375** [comment]
ISSUES95-104_DEMO.zip - see ISSUE 104
Please try attached DEMO for issues
95 - exit command
96 - no large font after configfile command
101 - no animation at start of set /p
102 - goto n after errorcheck
103 - font command does not set high=16 + BIOS font
104 - bad font filespec causes bad display

**Comment by 2012yaya2007** [comment]
No "--font-high=",The default character is high =16.
therefore:
20160307 -  BAD
 20160310 - OK
 20160311 - OK

**Comment by steve6375** [comment]
We need function as in 20160307.
e.g.
I load fonts, set graphics mode, etc, in menu.lst, then make a menu in (md)xxxxx, then run configfile (md)xxxxxx to display menu. So graphicsmode and font mode must be preserved when using configfile. Also if load new menu, then must preserve graphicsmode and background and fonts.

You force us to to reload the fonts for each menu which is slow and not needed. 
PLEASE - configfile should not change font mode.

Why does configfile reset font mode? This is a **BIG PROBLEM**.

**\menu.lst**
title  MENU1
configfile /menu1.lst

**\menu1.lst**
graphicsmode -1 800
font --font-high=24 /sft.f24
pause HERE - when load menu.lst it should stay in 24 high font
configfile /menu.lst

**Comment by 2012yaya2007** [comment]
I agree with you.
This leads to a problem,When loading the 16*16 font, you must use the --font-high=16.(First boot exception)

**Comment by steve6375** [comment]
??? This is issue 96 - **configfile** command changes font from 24 high to 16 high

**Comment by 2012yaya2007** [comment]
20160307
font --font-high=16 /unifont.hex.gz  ok
font /unifont.hex.gz  bad

**Comment by steve6375** [comment]
font /_ISO/e2b/grub/unifont.hex.gz OK on YaYa's  20160311

This bug 96 is now about configfile issue and font-high=24

**Comment by 2012yaya2007** [comment]
20160310 - BAD
20160311 - BAD
The cause is: The new version is still in use "font /unifont.hex.gz",
Instead of "font --font-high=16 /unifont.hex.gz "

**Comment by steve6375** [comment]
..

**Comment by steve6375** [comment]
Sorry, I do not understand?? This issue is about sft.f24 font and configfile. This issue does not involve unifont. unifont is never loaded or used???

ISSUES95-104_DEMO.zip

**/menu.lst**
splashimage /_ISO/e2b/grub/background.bmp.gz
/_ISO/e2b/grub/hotkey -A
pager off
title ISSUE 96 24-high font reset by configfile
configfile /menu1.lst

**/menu1.lst**
font --font-high=24 /_ISO/e2b/grub/sft.f24
pause HERE - now load menu.lst - large font should stay...
configfile /menu.lst

![image](https://cloud.githubusercontent.com/assets/1469350/13727829/2e132128-e8fa-11e5-8bff-84c2a812daa3.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13727830/432357ea-e8fa-11e5-878b-006327dd2e90.png)
![image](https://cloud.githubusercontent.com/assets/1469350/13727835/6dd10640-e8fa-11e5-8af5-ef19c074c4bc.png)

**Comment by 2012yaya2007** [comment]
Has finally turned to a solution, I do not know whether it is perfect or not.
Not yet merged with “exit” patch.
[grldr.rar.txt](https://github.com/chenall/grub4dos/files/170931/grldr.rar.txt)

**Comment by steve6375** [comment]
Looks good! Works :+1: 
![image](https://cloud.githubusercontent.com/assets/1469350/13728419/b7ebdf1a-e90f-11e5-82ae-a412e53b8890.png)

![image](https://cloud.githubusercontent.com/assets/1469350/13728420/c2e8b8c0-e90f-11e5-827c-d32e3a5f61f8.png)

**Comment by steve6375** [comment]
2016-03-15 fixed :+1:
