### ISSUE TITLE
text not wrapping correctly on 24x24 font

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#97]
```
graphicsmode -1 800
font --font-high=24 /_ISO/e2b/grub/yxt

title test
echo 0123456789aaaaaaaaa0123456789bbbbbbbbbb0123456789cccccccccc0123456789dddddddddd0123456789eeeeeeeeee0123456789ffffffffff
pause
boot
```

not wrapping correctly...
![image](https://cloud.githubusercontent.com/assets/1469350/13465489/d67912e8-e08d-11e5-967b-d196e4b73b7e.png)

1024x768 also does not wrap properly
![image](https://cloud.githubusercontent.com/assets/1469350/13465544/16e0981a-e08e-11e5-8ab0-554eaa8236a2.png)

**Comment by steve6375** [comment]
[yxt.zip](https://github.com/chenall/grub4dos/files/156773/yxt.zip)

Seems to be fixed in 2016-03-03 ??
but a few characters short maybe?
1024x768, font 24 high, help command
![image](https://cloud.githubusercontent.com/assets/1469350/13495031/1bb656ec-e140-11e5-963e-4cd5a4847727.png)

**Comment by 2012yaya2007** [comment]
Find the problem,Word wrap

**Comment by 2012yaya2007** [comment]
How to upload files in this?

**Comment by steve6375** [comment]
I don't understand?

yxt.zip in previous page ^

**Comment by 2012yaya2007** [comment]
How to upload the "grldr" here?

**Comment by steve6375** [comment]
Reproduce
1. Boot to menu
2. Run Test 1 - in console type **help** -  cursor goes below screen
3. Press **ESC** to return to menu
4. Press **c** for console
5. type **help** - now screen pages and is OK (but pager is on!)
[font24console.zip](https://github.com/chenall/grub4dos/files/159809/font24console.zip)

```
graphicsmode -1 1024
font --font-high=24 /yxt
pager off

title Test 1 - type help in command console\n Type help in command console\n Then press ESC
commandline
errorcheck off
boot
```

![image](https://cloud.githubusercontent.com/assets/1469350/13547046/0ef1377c-e2b9-11e5-901d-feb6649513e7.png)

**Comment by 2012yaya2007** [comment]
English is not good, did not say clearly.
"font24console.zip" is how to upload to issue #97?

**Comment by steve6375** [comment]
font24console.zip  will show problem.
cursor moves below screen. help can be used to show problem or can type in console.
when more than 33 lines then cursor disappears below screen.
console mode problem with number of rows, but it fixes itself if go back to menu!
Follow instructions carefully to see issue.

**Comment by steve6375** [comment]
new 2016-03-04 fixes. Thanks!
