### ISSUE TITLE
0.4.6a splashimage in 2016-03-01 not setting graphicsmode and hanging?

### ISSUE THREAD

**Issue by steve6375** [chenall/grub4dos#98]
```
# load 800x600 bmp
splashimage /_ISO/e2b/grub/background.bmp.gz

title test
reboot
```

![image](https://cloud.githubusercontent.com/assets/1469350/13469017/6f1cd7a0-e09d-11e5-93f4-3f0eff88bc6c.png)

The same menu works using 2015-12-31

**Comment by yaya2007** [comment]
issues#90
"which causes the monitor to lose sync, on an HDMI monitor, the monitor takes several seconds to re-sync between each picture"
"Splashimage seems to change graphicsmode twice and this causes the monitor to lose sync for about 2 seconds!"
Due to the above reasons,splashimage not setting graphicsmode .

**Comment by steve6375** [comment]
For compatibility

splashimage [FILE] should set graphicsmode - otherwise will not work with older menus.

splashimage --offset, --fill-color  and splashimage --animated  should not set graphicsmode
also if no graphicsmode set then should not hang but print error: not in graphicsmode?

**Comment by steve6375** [comment]
Can you solve please? Should be compatible with previous versions.

**Comment by 2012yaya2007** [comment]
have already been solved

**Comment by steve6375** [comment]
20160307 

```
splashimage /mybitmap800_600.bmp

title test
reboot
```

not work???

**Comment by 2012yaya2007** [comment]
0.4.5c Can display mybitmap800_600.bmp?

**Comment by steve6375** [comment]
yes - e.g. from 0.4.5c console

```
graphicsmode 3        (if not in text mode) - optional
splashimage /mybitmap800_600.bmp
```

> > > > Graphics mode number set to 0x143
> > > > grub>
> 
> Loading splashimage...

**Comment by 2012yaya2007** [comment]
0.4.5c Show Only "Loading splashimage",But the image failed to load,Return command line.

**Comment by steve6375** [comment]
Press ESC to get menu and it will be there. Graphicsmode has been changed.

**Comment by steve6375** [comment]
P.S. bitmap must be exactly 800x600 pixels.

**Comment by 2012yaya2007** [comment]
menu  ->  Press "c"   ->  .command line  ->  "graphicsmode 3"  ->  "splashimage /mybitmap800_600.bmp"  ->  Press ESC   -> ok

boot ->   Press "c"   ->  .command line  ->   "splashimage /mybitmap800_600.bmp"  ->  Press ESC   -> fail

**Comment by steve6375** [comment]
menu.lst

```
splashimage /mybitmap800_600.bmp
title test
reboot
```

please test - with 0.4.5c  you get 800x600 + image. With latest 0.4.6a it is still in text mode.

**Comment by steve6375** [comment]
[Background.bmp.gz.zip](https://github.com/chenall/grub4dos/files/161276/Background.bmp.gz.zip)
Here is file I use - exactly 800x600 (compressed lzma)

**Comment by steve6375** [comment]
![image](https://cloud.githubusercontent.com/assets/1469350/13569737/aa0bbaa8-e461-11e5-9740-f61505b0a5ee.png)

#graphicsmode -1 1024
#font --font-high=24 /_ISO/e2b/grub/yxt
splashimage /_ISO/e2b/grub/background.bmp.gz
#font --font-high=16 /_ISO/e2b/grub/unifont.hex.gz
#pager off
#/_ISO/e2b/grub/hotkey -A
#cat /menu.lst > (md)0xa000+0x50

#graphicsmode -1 1024
debug 3
debug msg=3

title font ltb24  OK
font --font-high=24 /ltb24
pause 111
errorcheck off
boot

etc

**Comment by steve6375** [comment]
See Diddy tutorials on grub4dos -  see Submenus section
http://diddy.boot-land.net/grub4dos/files/menu.htm
![image](https://cloud.githubusercontent.com/assets/1469350/13570723/e5173ebe-e467-11e5-8138-021952026739.png)

**Comment by steve6375** [comment]
2016-03-10 fixed :+1:
